.travis.yml, bufio.ts, file_server.ts, file_server_test.ts, http.ts, test.ts
Closes #14 
Now file_server would serve directory!
Also fix a small bug with `bufio.ts` BufWriter that failed to await on flush (which would cause server to stuck forever on files larger than buf size)
=> Serve directory for file server & Fix bufio flush bug

file_server.ts
Simple logging for file server, built on top of #15 
```
HTTP server listening on http://0.0.0.0:4500/
[2018-12-11 22:48:59] "GET /buffer.ts HTTP/1.1" 200
[2018-12-11 22:48:59] "GET /buffer.ts HTTP/1.1" 200
[2018-12-11 22:49:05] "GET / HTTP/1.1" 200
[2018-12-11 22:49:13] "GET /foobar HTTP/1.1" 404
```
=> File server logging

file_server.ts
=> Fix file server crash

buffer_test.ts, bufio_test.ts, file_server.ts, http.ts, http_test.ts, test.ts
Bare minimum streaming response. I want to continue on top of work in #15
=> [WIP] streaming http response

README.md, colors/README.md, colors/main.ts, colors/main_test.ts, colors/styles.ts, net/README.md, test.ts
This PR adds the `colors` module collection and updates the READMEs so each collection contains a README along with a central one.
=> Add colors module collection

README.md, logging/README.md, logging/handler.ts, logging/handlers/console.ts, logging/index.ts, logging/levels.ts, logging/logger.ts, logging/test.ts, test.ts
This PR migrates [bartlomieju/deno-logging](https://github.com/bartlomieju/deno-logging) to `deno_std` as `logging` module.
The module is **very much work in progress**, but I'm really glad to have community discuss direction it should take.
=> Add logging module

colors/example.ts, colors/main_test.ts
=> colors example

net/file_server.ts, net/file_server_test.ts, test.ts
=> Add CORS option to file_server

.travis.yml, azure-pipelines.yml
=> Upgrade CI to v0.2.4

.travis.yml, README.md, azure-pipelines.yml, mkdirp/mkdirp.ts, mkdirp/readme.md, mkdirp/test.ts, net/file_server.ts, test.ts
=> adds mkdirp

README.md, logging/test.ts
=> Make README readable on mobile

README.md, colors/README.md
@kitsonk, I just took a jab at this since it was on my mind. Please review.
=> First pass on style guide

http/mod.ts
=> Use export from for re-exports in http

README.md, flags/README.md, log/README.md
Fix wrong links on READMEs and usages.
=> Fix wrong links

format.ts, http/README.md
Change README title, as module name changed
=> Change README title

colors/test.ts
Just adding a few test cases to the colors module.
=> colors: add test cases

datetime/test.ts, format.ts, log/handlers.ts, log/test.ts
now can format files in the deep dir
=> fix format

.editorconfig
Set `root` option in `.editorconfig` file to `true`
=> Make .editorconfig root

log/handlers_test.ts, log/logger_test.ts, log/mod.ts, log/test.ts, test.ts
here's some tests for the log module.
had to refactor it slightly to allow the default to be exposed, a thorough review of those changes would be worthwhile.
=> log: add tests

README.md
=> Add API design guidelines

log/README.md
Not yet done, I'll request review when I'm happy with it.
=> Update log docs

ws/mod.ts, ws/test.ts
`enum` is better for this usage case. If something else relies on these exports, I can restore them:
```ts
export const OpCodeContinue = 0x0;
export const OpCodeTextFrame = 0x1;
export const OpCodeBinaryFrame = 0x2;
export const OpCodeClose = 0x8;
export const OpcodePing = 0x9;
export const OpcodePong = 0xa;
```
=> Move WebSocket op codes to enum

azure-pipelines.yml
Bump deno version to v0.2.10 in CI
=> Bump deno to v0.2.10

benching/example.ts, benching/mod.ts, benching/readme.md, benching/test.ts, test.ts
API follows `testing`
Would be cool to enhance this by a high resolution timer from Rust.
=> Add benching

examples/test.ts
Checking if still causes problem with newest release.
Closes #150.
=> Reenable cat.ts test

azure-pipelines.yml
=> Bump CI to v0.3

testing/mod.ts
fixing: https://github.com/denoland/deno_std/issues/222
but this line: https://github.com/denoland/deno_std/blob/master/testing/mod.ts#L3
Is maybe not revelant anymore? You thought @ry ?
=> Testing add ansi color support from color module

README.md
Updated link and version in the Readme.md
Fixing: https://github.com/denoland/deno_std/issues/212
=> fixing readme link + version

benching/mod.ts
Fixing : https://github.com/denoland/deno_std/issues/228
=> Fixing default parameters of runBenchmarks

fs/glob.ts, fs/glob_test.ts, fs/globrex.ts
As requested, added JsDoc + examples.
Also added some more explicit UTs.
Changed the exposition of GlobOptions
=> Glob refactor

testing/mod.ts, testing/pretty.ts, testing/test.ts
=> Switching from assert equal to pretty assert equal

benching/example.ts, benching/readme.md, colors/README.md, examples/README.md, examples/gist.ts, examples/ws.ts, flags/README.md, fs/path/README.md, http/README.md, log/README.md, media_types/README.md, prettier/README.md, testing/README.md
xlink https://github.com/denoland/registry/issues/70
=> Replace deno.land/x/ with deno.land/std/

testing/asserts.ts, testing/asserts_test.ts
Added:
- assertNotEquals
- assertArrayContains
=> Assert improvement

testing/asserts.ts, testing/asserts_test.ts
=> testing/asserts: Add unimplemented

testing/asserts.ts, testing/asserts_test.ts, testing/test.ts
Fixing https://github.com/denoland/deno_std/issues/249
=> Assertion error instead of Error in testing

.eslintignore, http/server.ts
Fix eslint errors in http directory
* removed /http/ in .eslintrc.json
* removed 3 unused vars.
* rearranged functions to not use them before defined
=> Eslint Fix http folder 

datetime/mod.ts, datetime/test.ts
Added more consistent/flexible code for datetime module and improved tests
=> Datetime module improvement

fs/move.ts, fs/move_test.ts, test.ts
=> feat: add move/moveSync for fs modules

datetime/mod.ts, fs/empty_dir.ts, fs/ensure_dir.ts, fs/ensure_file.ts, fs/exists.ts, fs/globrex.ts, fs/move.ts, fs/read_json.ts
As discussed here: https://github.com/denoland/deno_std/pull/271#discussion_r265366006
Cleaning the jsDoc.
Also ref: https://github.com/denoland/deno_std/issues/274
=> jsdoc format

prettier/main.ts, prettier/main_test.ts
=> Fix prettier check in empty files

fs/glob.ts, strings/pad.ts
Wrong indentation on padding example.
ref: https://github.com/denoland/deno_std/issues/321
=> Fixing tsdoc example padding

fs/glob.ts, strings/pad.ts, toml/README.md, toml/parser.ts, toml/parser_test.ts, toml/testdata/inlineTable.toml
Added the dump feature for the toml. Corrected an optionnal parameter for `string pad` too.
=> [TOML] add Stringify feature

azure-pipelines.yml, examples/README.md, http/README.md
The flag handling seems changed in https://github.com/denoland/deno/pull/2025 and some of commands won't work in the next version of deno. This PR prepares for that change.
=> Prepare for the change of flag handling in the next version

http/server_test.ts
=> fix ts warning for http/server_test.ts

fs/mod.ts
This PR is a part of #268.
This PR should not appear in the changelog.
=> expose ensureSymlink in fs/mod.ts

testing/asserts.ts, testing/asserts_test.ts
Fixes #349.
Co-authored-by: @johnsonjo4531
=> Add assertSetEquals and assertNotSetEquals

azure-pipelines.yml, fs/ensure_link.ts, fs/ensure_link_test.ts, fs/test.ts
=> fix ensureLink broken. close #358

azure-pipelines.yml
=> Update TS version on pipeline

http/cookie.ts, http/cookie_test.ts
Fixing @motss remark on : https://github.com/denoland/deno_std/pull/359
=> [http] : fixing equal character split

fs/README.md
=> docs(fs): fix async iterator

fs/ensure_symlink.ts
https://github.com/denoland/deno/issues/2169 have been resolve.
=> remove completed todo item

tsconfig.json
- fixed: #407 
- This resolved IDE symbol errors
=> fix: add exnext lib to tsconfig.json

README.md, ws/README.md
This PR is for #401 
Please review.
=> chore(readme): add README.md for ws

azure-pipelines.yml
=> ci: bump version to v0.9.0

installer/README.md
=> fix installer readme

http/file_server.ts
=> file server display files order by filename

http/server_test.ts
This PR enables the test of aborted connection handling on windows.
=> Enable test of aborted connection on windows

examples/README.md
=> Fix URLs in examples/README

colors/test.ts
test all the text functions inside the colors module
=> test all text functions in colors module

README.md
via https://github.com/denoland/deno_std/pull/571
=> link colors to fmt/colors.ts

testing/main.ts
@bartlomieju Needs your approval.
See https://gitter.im/denolife/Lobby?at=5d82b4625ab936169417838e.
=> Remove //testing/main.ts

media_types/db_c50e0d1.json, media_types/deps.ts
Updated mime-db JSON file to commit `c50e0d1`. If it's required I can change version to latest stable.
=> Update mime-db to commit c50e0d1

ws/example_client.ts
It didn't compile due to `Promise` type issue
=> Fix types in example_client for ws module

azure-pipelines.yml, http/racing_server_test.ts, http/server.ts, http/server_test.ts, ws/mod.ts
=> Bump v0.19.0

ws/mod.ts
=> fix: [ws] mask must not be set by default for server

examples/echo_server.ts
=> fix: Update echo_server to new listen API

README.md
Ref https://github.com/denoland/deno_std/issues/603
=> Update README about move to deno repo

fmt/colors_test.ts
This adds a testcase for reset in fmt/colors which has zero coverage.
=> test(fmt/colors): add reset testcase

uuid/_common.ts, uuid/test.ts, uuid/v1.ts, uuid/v1_test.ts, uuid/v4.ts, uuid/v4_test.ts, uuid/v5.ts, uuid/v5_test.ts
=> UUID cleanup

README.md
This pr fixes a typo at https://github.com/denoland/deno_std/blob/main/README.md#opening-a-pull-request
=> chore: fix typo in contributing section

io/streams.ts, io/streams_test.ts
=> BREAKING feat(io/streams): Strengthen iterator to readable stream conversion

node/process.ts, node/process_test.ts
This PR adds `process.hrtime` function to node.js compatibility library.
=> feat(node/process): add hrtime function

http/_io.ts, io/writers.ts, textproto/mod.ts
https://github.com/denoland/deno_std/issues/788
=> fix: encoder/decoder one instance

node/util.ts, node/util_test.ts
this is PR [9935 in deno](https://github.com/denoland/deno/pull/9335) redone here
=> feat(node/util): add format and improve deprecate

io/bufio.ts
With this change we can use bufio.ts in Deno Deploy environment
tested with the following script
https://gist.githubusercontent.com/kt3k/58e8b429ce85b46acbb8e9e106c27fb2/raw/952d38fb57152ae2964d320189700fdf7e743496/bufio-test.ts
=> feat: make bufio compatible with Deploy

encoding/README.md
Add `base64` encoding example.
=> docs(encoding): Add `base64` encoding example

io/buffer.ts
=> ref(io/buffer): use std/bytes copy

path/glob.ts
=> fix: circular dependency on path

io/streams.ts
=> fix(io/streams): don't use a byte ReadableStream

.github/workflows/ci.yml, archive/tar.ts, io/buffer.ts, log/handlers.ts, node/os.ts
This will require canary once denoland/deno#9960 is merged until Deno 1.11 is released.
=> chore: update std for TypeScript 4.3 changes

node/util.ts, node/util_test.ts
Port inherits from https://github.com/nodejs/node/blob/master/lib/util.js#L231
=> feat(node/util): add inherits

io/streams.ts, io/streams_test.ts
For consistent auto-close behavior between `readableStreamFromReader` and `writableStreamFromWriter` (https://github.com/denoland/deno_std/issues/963).
=> feat(io/streams): writableStreamFromWriter autoClose (#963)

path/glob.ts, path/glob_test.ts
=> fix(path): Add question mark as a glob indicator

encoding/testdata/keys.toml, encoding/toml.ts, encoding/toml_test.ts
Fix #1018
Fix all cases shown at #1018 description.
=> fix(encoding/toml): parse keys correctly

collections/README.md
Add `std/collections` usage for 
- **chunked**
- **distinctBy**
- **distinct**
- **filterEntries**
- **filterKeys**
- **filterValues**
- **findLast**
- **groupBy**
- **intersect**
- **mapEntries**
- **mapValues**
- **partition**
- **permutations**
=> docs(collection): Add `std/collections`  API documentation

http/file_server_test.ts
Issue: https://github.com/denoland/deno_std/issues/1058
=> fix(http): 'file_server sets Date header correctly' test case is flaky

collections/README.md
Add `findLastIndex` documentation.
=> docs(collections): Add `findLastIndex` documentation

node/assert/strict.ts, node/assert_strict.ts
Aliases Node.js `import('assert/strict')` with the same interface.
=> feat: assert/strict alias

http/file_server_test.ts
=> fix(http/file_server): Fix flaky 'file_server sets Date header correctly' test case

collections/sort_by.ts, collections/sort_by_test.ts
please see https://github.com/denoland/deno_std/issues/1096
=> feat(collections/sortBy): make the `sortBy()` of Date a stable sort

node/module.ts, node/module_test.ts
=> fix(node): assert/strict, fs/promises, and perf_hooks modules could not be required

collections/permutations.ts
Remove function closure since it doesn't improve readability.
=> refactor(collections): permutations optimisation

collections/README.md, collections/mod.ts
@kt3k  Sorry 😬 , I forgot to Export `withoutAll` and add documention section.
Related Pr https://github.com/denoland/deno_std/pull/1100.
=> fix(collections): Export withoutAll function & add missing documentation

encoding/README.md, encoding/_yaml/example/sample_document.yml, encoding/_yaml/parse_test.ts, encoding/_yaml/stringify_test.ts
=> fix(tests/yaml): expect !!js/function parse/stringify to throw

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
The current issue templates look a little verbose. This PR cleans them up.
=> chore: clean up issue templates

node/buffer.ts, node/buffer_test.ts
Related https://github.com/denoland/deno_std/issues/1312
=> feat(node): Support `Buffer.readUIntBE`

node/README.md
Add information
- Setup command
- How to run the tests you have set up
- Troubleshooting for https://github.com/denoland/deno_std/issues/1319#issuecomment-929073301
=> docs(node): Add information for setting up the test runner

node/crypto.ts, node/crypto_test.ts
This PR adds a function `crypto.randomUUID` from Web Crypto API to `std/node/crypto.ts`
=> feat(std/node/crypto): Add `crypto.randomUUID`

node/child_process_test.ts
=> test: maybe fix flaky "[node/child_process spawn] Verify that stdin and stdout work" test

node/async_hooks.ts, node/cluster.ts, node/dgram.ts, node/dns.ts, node/domain.ts, node/http.ts, node/https.ts, node/net.ts, node/readline.ts, node/tls.ts, node/v8.ts, node/vm.ts, node/zlib.ts
Ref https://github.com/denoland/deno/pull/12293
=> feat: add missing node modules

node/_tools/suites/parallel/test-querystring.js, node/querystring.ts
ref: https://github.com/nodejs/node/blob/d4842e64bb1dc4113acdca2a012c74fbcfc71571/lib/querystring.js#L228-L270
=> fix(node/querystring): Improve `querystring.stringify`

testing/fast_check_example.ts
This PR enhances examples that use the fast-check property-based testing library in Deno tests. It supercedes PR #1484 that had commit authorship issues 😳.
=> doc(testing): update fast-check examples

node/_tools/suites/parallel/test-querystring.js, node/querystring.ts
=> fix(node/querystring/stringify): Remove initialValue

node/_tools/suites/parallel/test-querystring.js, node/querystring.ts
=> fix(node/querystring/stringify): Invalid surrogate pair throws URIError

node/README.md, node/_tools/setup.ts
Nice quality of live improvement so the test setup doesn't have to prompt us everytime time (:upside_down_face:) whether to use cache or not
=> feat(node/_tools): Add cache and no cache flags for test setup

node/_tools/suites/parallel/test-querystring.js, node/querystring.ts
ref: https://github.com/nodejs/node/blob/2e2a6fecd9b1aaffcb932fcc415439f359c84fdd/lib/querystring.js#L85
=> feat(node/querystring): Implement `qs.unescapeBuffer`

node/_util/_debuglog.ts
fixes #1518
see: 
https://dash.deno.com/playground/loud-sheep-97
=> fix(node/util): Deno.permissions is no longer called unless it exists.

collections/find_last.ts, collections/find_last_index.ts
=> chore(collections): deprecate findLast

fmt/printf_test.ts
Closes https://github.com/denoland/deno_std/issues/832
=> chore: reenable printf tests

node/process.ts, node/process_test.ts, node/testdata/process_worker.ts
Closes https://github.com/denoland/deno_std/issues/1485
=> fix(node/process): don't use window.addEventListener

http/README.md
Update README with changes from #1506
=> fix(http): update README

fmt/README.md, fmt/bytes.ts, fmt/bytes_test.ts
I'm not sure what to do with the copyright notice at the top of the files.
Left them there for now.
closes #1535
=> feat: add "fmt/bytes" module

node/_tools/suites/parallel/test-util.js, node/util.ts
=> feat(node/util): Add `util.isBuffer` and  `util._extend`

_tools/format.js, _tools/lint.js, node/_events.d.ts
=> ci: fix lint and format scripts

.github/workflows/ci.yml, README.md
=> ci: split running tests into steps

.github/workflows/ci.yml
=> ci: disable doctests for node/ directory

node/_fs/_fs_read.ts, node/_fs/_fs_read_test.ts
Related https://github.com/denoland/deno_std/issues/1496
=> feat(node/_fs): Add `fs.read` API

node/_errors.ts, node/_tools/suites/parallel/test-util.js, node/util.ts
=> fix(node/test-util): Improve coverage

node/process.ts, node/process_test.ts
Closes https://github.com/denoland/deno_std/issues/1594
=> feat(node): process.config, process.exitCode, process._exiting

node/http.ts, node/http_test.ts
Test fails like this:
```
running 2 tests from file:///home/bnoordhuis/src/std/node/http_test.ts
test [node/http listen] ... ok (9ms)
test [node/http chunked response ... FAILED (12ms)
failures:
[node/http chunked response
AssertionError: Test case is leaking async ops.
Before:
- dispatched: 9
- completed: 9
After:
- dispatched: 18
- completed: 17
Ops:
op_http_accept:
Before:
- dispatched: 0
- completed: 0
After:
- dispatched: 2
- completed: 1
Make sure to await all promises returned from Deno APIs before
finishing test case.
at assert (deno:runtime/js/06_util.js:41:13)
at asyncOpSanitizer (deno:runtime/js/40_testing.js:96:7)
at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:144:9)
at async runTest …
```
=> fix(node/http): improve http.Server#close() compat

node/_fs/_fs_read.ts, node/_fs/_fs_read_test.ts, node/fs.ts
Related https://github.com/denoland/deno_std/issues/1496
=> feat(node/_fs): Add `fs.readSync`

node/_stream/writable.ts, node/http.ts, node/http_test.ts
=> fix(node/http): fix no body chunked response

node/_tools/suites/parallel/test-util-inspect.js, node/internal/util/inspect.js
=> fix(node/util/inspect): Fix some bugs

deno.json
=> chore: ignore cov in lint & fmt

io/buffer.ts
See #1649 [please wait for CI]
=> chore(node/buffer): convert to js private variables

node/dgram.ts, node/dgram_test.ts, node/module_all.ts
Codes without implementation for 'node/dgram' like #1501
=> chore(node/dgram):mock 'dgram' module

http/server.ts, http/server_test.ts
=> feat(http): introduce onError option on ServerInit

http/server.ts, http/server_test.ts
=> feat(http): added onError option to serveListener and serveTls

node/_core.ts, node/_next_tick.ts, node/http.ts, node/module.ts
Closes https://github.com/denoland/deno_std/issues/1685
=> node: add node/_core.ts module

node/url.ts
Ref https://github.com/denoland/deno_std/pull/1667
=> feat(node): Support resolveObject

examples/colors_test.ts, fmt/colors_test.ts
This reverts commit 2f584bcbfea3482d85fd6ebe069abe1b184c8b13.
=> Revert "chore: skip fmt/colors test (#1700)"

node/dns.ts, node/internal/net.ts, node/internal_binding/cares_wrap.ts, node/internal_binding/tcp_wrap.ts, node/net.ts
Ref https://github.com/denoland/deno_std/issues/1707
=> ref(node): Move `net.ts` into `internal`

node/_tools/common.ts, node/_tools/config.json, node/_tools/test.ts
Node.js compatibility tests were not running on windows CI..
=> ci: run node tests on windows

uuid/mod.ts, uuid/test.ts
Ref https://github.com/denoland/deno_std/issues/1715
=> feat(uuid): Add `validate` function to check UUID

node/_tools/suites/parallel/test-util-format.js, node/internal/util/comparisons.ts, node/internal/util/inspect.js, node/internal_binding/util.ts, node/util_test.ts
this pr will fix https://github.com/denoland/deno_std/issues/1215. 
I also add a deno test at https://github.com/denoland/deno_std/blob/a6026ec3820f3ae0d2e3ab7319bf2f48c313d75c/node/util_test.ts#L12-L17
=> feat(node/util): implement `getOwnNonIndexProperties`

node/cluster.ts, node/http2.ts, node/https.ts, node/module_all.ts, node/repl.ts, node/tls.ts, node/v8.ts, node/worker_threads.ts
This PR adds stub implementations of missing node modules.
closes #1734
=> chore(node): add stub modules

node/stream/consumers.js
Ref https://github.com/denoland/deno/pull/13173
=> fix(node): typedef imports

uuid/mod.ts, uuid/test.ts
refs:
https://github.com/uuidjs/uuid/blob/main/src/version.js
https://github.com/uuidjs/uuid/blob/main/test/unit/version.test.js
=> feat(uuid): add version function to detect RFC version of a UUID

crypto/README.md
=> docs(crypto): Add supported algorithms

crypto/README.md
=> doc(crypto): change example from print array to uint8Array

testing/asserts.ts, testing/asserts_test.ts
=> fix(testing/assert): unequal of -0 and  0

http/file_server.ts
=> feat(http/file_server): add 'quiet' flag

node/_process/process.ts, node/process_test.ts
Closes https://github.com/denoland/deno_std/issues/1794
=> fix(node): process.env getOwnPropertyDescriptor

node/module.ts
Closes https://github.com/denoland/deno_std/issues/1796
=> fix(node): set prototype for Module

http/file_server.ts, http/file_server_test.ts
=> feat(http): add eyecandy to file_server

node/_process/streams.ts, node/internal/streams/readable.js
Closes https://github.com/denoland/deno_std/issues/1825
=> fix(node): make stdio streams optional if not present on Deno namespace

_tools/format.js, _tools/lint.js
=> chore: deprecate _tools scripts

http/file_server.ts
Minor peformance optimization.
=> chore(http/file_server): only seek if necessary

testing/asserts.ts, testing/asserts_test.ts
=> fix(testing): `assertObjectMatch` matches ArrayBuffer views correctly

node/_tools/setup.ts
You can now run the setup script like the below:
```
./node/_tools/setup.ts
```
=> chore(node): make node/_tools/setup.ts executable script

node/https.ts, node/https_test.ts
closes #1861 
part of yarn blocker issues denoland/deno#13420
=> chore(node): do not throw with new https.Agent

deno.json, node/integrationtest/test.ts, node/tty.ts
This PR adds integration test for checking the following compat features:
- `yarn add <mod>`
- `npm install <mod>`
- Run hello world example of express
=> test(node): add integration test

http/_mock_conn.ts
Update for changes in https://github.com/denoland/deno/pull/13615
=> fix: http/_mock_conn.ts

.gitattributes
Closes https://github.com/denoland/deno_std/issues/1924
=> chore: exclude node/suites/ from language statistics

log/handlers.ts, node/_fs/_fs_appendFile_test.ts, node/_fs/_fs_close_test.ts, node/_fs/_fs_writeFile.ts, node/_fs/_fs_writeFile_test.ts, node/fs/_fs_writeFile_test.ts, streams/conversion.ts
=> chore: don't use deprecated Deno.File API

testing/README.md, testing/asserts.ts, testing/asserts_test.ts
Closes #1894
I went with `assertAlmostEquals` but open to change the name but the first one proposed in #1894 sounded good
=> feat(testing): add `assertAlmostEquals`

dotenv/load.ts, dotenv/load_test.ts, dotenv/mod.ts, dotenv/mod_test.ts, dotenv/testdata/app_load_child.ts, dotenv/testdata/app_load_parent.ts
=> fix(dotenv): avoid top-level-await in load.ts

node/_crypto/crypto_browserify/bn.js/bn.js, node/_crypto/crypto_browserify/bn.js/constructor_test.js, node/_crypto/crypto_browserify/bn.js/reduction_test.js
This PR adds bn.js under `std/node/_crypto/crypto_browserify/`. `bn.js` is a utility which is heavily used in crypto-browserify organization modules.
part of #1962
=> chore(node): add bn.js

.editorconfig, node/_crypto/crypto_browserify/asn1.js/base/buffer.js, node/_crypto/crypto_browserify/asn1.js/base/node.js, node/_crypto/crypto_browserify/asn1.js/base/reporter.js, node/_crypto/crypto_browserify/asn1.js/constants/der.js, node/_crypto/crypto_browserify/asn1.js/decoders/der.js, node/_crypto/crypto_browserify/asn1.js/decoders/pem.js, node/_crypto/crypto_browserify/asn1.js/encoders/der.js, node/_crypto/crypto_browserify/asn1.js/encoders/pem.js, node/_crypto/crypto_browserify/asn1.js/mod.js, node/_crypto/crypto_browserify/asn1.js/test/der_decode_test.js, node/_crypto/crypto_browserify/asn1.js/test/der_encode_test.js, node/_crypto/crypto_browserify/asn1.js/test/error_test.js, node/_crypto/crypto_browserify/asn1.js/test/pem_test.js, node/_crypto/crypto_browserify/asn1.js/test/ping_pong_test.js, node/_crypto/crypto_browserify/asn1.js/test/tracking_test.js, node/_crypto/crypto_browserify/asn1.js/test/use_test.js, node/_crypto/crypto_browserify/asn1.js/test/util.js, node/_crypto/crypto_browserify/bn.js/bn.js
This PR adds [asn1.js](https://github.com/indutny/asn1.js) to `std/node`
part of #1962
=> chore(node): add asn1.js

node/http.ts
By closing the body's ReadableStream controller on _final
=> fix(node): http client reqs with bodies

testing/README.md, testing/asserts.ts, testing/asserts_test.ts
=> feat(testing): add `assertInstanceOf`

async/README.md, async/abortable.ts
=> feat(async): expose asyncPromise and asyncAsyncIterable

README.md
I think this is not changed by mistake.
=> chore: Fix test task on README

uuid/mod.ts, uuid/v4.ts
Cont. of https://github.com/denoland/deno_std/pull/1972
Tracking ref: https://github.com/denoland/deno_std/issues/1973
=> refactor: mark modules as browser compatible

node/_dns/_utils.ts, node/internal/options.ts, node/process.ts
=> refactor(node): move _options.ts to node/internal

testing/README.md
=> docs(testing): Fix typo

testing/README.md, testing/asserts.ts, testing/bench.ts
=> BREAKING(testing/bench): deprecate testing/bench module

mime/multipart.ts, testing/asserts.ts
=> BREAKING(mime/multipart): deprecate mime/multipart module

http/server.ts, http/server_test.ts
Fixes https://github.com/denoland/deno_std/issues/2123 .
=> fix(http): Use the `addEventListener` method instead of `onabort` properties

node/_buffer.mjs, testing/_diff.ts
Due to that regression in 1.20.6
=> chore: deno fmt with 1.21.0

http/file_server_test.ts, node/_buffer.mjs, testing/_diff.ts
Merge once https://github.com/denoland/deno/pull/14345 is in canary
=> chore(http): update file_server tests w.r.t. stream compression

testing/asserts.ts, testing/asserts_test.ts
=> feat(testing): assertFalse

crypto/_benches/bench.ts
Because testing/bench is now deprecated
https://github.com/denoland/deno_std/tree/main/testing#benching
> These APIs are deprecated. Use Deno.bench() instead.
Docs:
https://deno.land/manual/tools/benchmarker#benchmarking-tool
https://doc.deno.land/deno/unstable/~/Deno.bench
I didn't find the `runs` property equivalent, maybe I could just iterate, but doesn't seem idiomatic.
=> :recycle: Move from testing/bench to Deno.bench

testing/README.md
=> :memo: Add note about assertFalse

http/server_test.ts
Ref https://github.com/denoland/deno/issues/14449#issuecomment-1114322139
=> test(http): add catch handler to server promise

node/README.md
The path was updated.
Now is https://github.com/denoland/deno_std/tree/main/node/_tools/test
=> :memo: Update path on docs

.github/workflows/ci.yml, node/internal/errors.ts, testing/__snapshots__/options_tests/custom_path.snap, testing/__snapshots__/options_tests/snapshot_test.ts.snap, testing/__snapshots__/snapshot_test.ts.snap, testing/snapshot.ts, testing/snapshot_test.ts
Closes #2135 
Closes #2128 
Closes #2129
=> feat(testing/snapshot): Add "assertSnapshot" options overload

testing/_test_suite.ts, testing/bdd.ts
This should make it work on Node when using dnt (edit: yes, just tested it)
=> fix(testing/bdd): support using bdd tests with dnt

node/_fs/_fs_streams.ts, node/fs.ts
=> fix(node/fs): require('fs').ReadStream is undefined

http/file_server.ts, http/util.ts, http/util_test.ts
=> feat(http/util): add compareEtag

encoding/_yaml/loader/loader.ts, hash/sha1.ts, hash/sha256.ts, hash/sha512.ts, node/_buffer.mjs, node/_pako.mjs, node/internal/process/per_thread.mjs
`deno fmt` is updated in https://github.com/denoland/deno/pull/14725
This PR updates the format of code following the above change
=> chore: update code format

flags/README.md
=> Fixed Typo

flags/README.md, flags/mod.ts, flags/test.ts, http/file_server.ts
=> BREAKING(flags): introduce negatable option

deno.json, node/global_test.ts, node/perf_hooks_test.ts
=> fix: update ci script and fix type errors

node/child_process_test.ts
Use something else that works on Windows.
=> chore: fix child_process_test that uses echo on Windows

node/module_all.ts
This PR reorders items in lexical order
=> chore(node): reorder imports and exports

node/_utils.ts
Temporary, ref https://github.com/denoland/deno/pull/14919#issuecomment-1161670859
=> chore: Don't use Deno.spawn() in node utils

_wasm_crypto/README.md
I want to link to this in a blog post and having an overview would help.
=> chore: add overview paragraph to _wasm_crypto README.md

collections/mod.ts, fs/mod.ts
This will improve the index view of the documentation.
=> docs: improve module JSDoc for collections, fs

node/_pako.mjs, node/_zlib.mjs, node/_zlib_binding.mjs
Fix #2386 
@jonnydgreen Thanks for the great intel!
=> fix(node/zlib) zlib codes contains undefined values and keys

testing/README.md
=> docs(testing): add note about powershell usage

node/README.md
node now uses main instead of master
=> fix: change master to main in node github link

archive/tar.ts, archive/tar_test.ts
=> Bugfix/2425 export TarEntry class

testing/README.md, testing/asserts.ts, testing/asserts_test.ts
=> add support for `PromiseLike` in `assertRejects`

node/_stream.d.ts, node/assert.ts, node/child_process_test.ts, node/internal/child_process.ts, node/internal/crypto/pbkdf2.ts, node/internal/streams/readable.mjs, node/internal/streams/writable.mjs
Prerequisite for https://github.com/denoland/deno_std/pull/2395
=> node: Use "Deno.spawnChild" API for "child_process" polyfill

dotenv/README.md
Removed duplicated "Stringify" section.
=> docs(dotenv): remove duplicated section

node/_process/process.ts, node/process_test.ts
process.env.hasOwnProperty
process.env.valueOf
process.env.toString
process.env.toLocaleString
Fixes #2463
=> fix(node/process.env) Handle some function in process.env

node/internal/streams/duplexify.mjs, node/internal/streams/lazy_transform.mjs, node/module_all.ts
=> fix(node): correct import specifiers

testing/_test_utils.ts, testing/mock.ts, testing/mock_test.ts
=> feat(testing): allow for stubbing non existent instance methods

node/module_esm.ts
This import seems suspicious, just trying to remove it
=> node: remove import to global.ts from module_esm.ts

testing/_format.ts, testing/_format_test.ts, testing/asserts.ts
=> fix: assertEqual "diffi better for object getters"

node/_events.d.ts, node/_events.mjs, node/_tools/test/parallel/test-event-emitter-method-names.js, node/events.ts
the fix #2402 by export the static function
=> fix(node): events no export static function

http/file_server.ts, http/file_server_test.ts
=> feat(http/file-server) return 404 response if file not found

deno.json, encoding/yaml.ts, testing/time.ts
This PR fixes the type checking of browser compatible modules in CI.
=> ci: fix browser type checking

.github/workflows/ci.yml
=> chore(CI): upgrade actions/checkout to v3

.github/workflows/ci.yml, .github/workflows/version_bump.yml
=> chore(CI): upgrade denoland/setup-deno to v1

.github/workflows/ci.yml, README.md, _tools/check_circular_deps.ts, _tools/check_licence.ts, deno.json
=> feat(CI): move lint scripts to Deno task runner

testing/_diff.ts
=> fix(testing/asserts): temporarily disable background colors in diff

node/http.ts
Fixes #2478 and partially fixes #2159. This PR:
1. Makes the function more readable
2. Adds some defaults
3. Adds stricter `RequestOptions` argument type
=> fix(node/http): `_createUrlStrFromOptions` optimizations

collections/deep_merge.ts, flags/mod.ts, node/assertion_error.ts, node/dns.ts, node/internal/dns/promises.ts, node/url.ts
The latest `deno fmt` now makes these changes.
=> chore: update format

uuid/mod.ts
=> chore(uuid): add missing new identifier

node/stream.ts
Fixes: https://github.com/denoland/deno_std/issues/2651
=> fix(node): set proper default streams export

node/_tools/test/common/index.js
=> test(node): add caches to knownGlobals

node/_fs/_fs_dir.ts, node/_tools/test/parallel/test-fs-opendir.js
ref: https://github.com/microsoft/TypeScript/blob/b0795e9c94757a8ee78077d160cde8819a9801ea/lib/lib.es2015.iterable.d.ts#L31-L48
=> refactor(node/fs): use `done` field of `IteratorResult`

node/_tls_wrap.ts, node/tls_test.ts
=> fix(node/tls): fix TLSSocket constructor

node/child_process_test.ts
=> chore: maybe fix flaky `[node/child_process] child_process.fork` test

node/_tools/config.json
Fixes: https://github.com/denoland/deno_std/issues/2807
=> test: ignore two failing tests on windows

node/_process/streams.mjs, node/process_test.ts
Need it to land https://github.com/denoland/deno/pull/15933
=> chore: add ts-ignores for Deno.consoleSize() API

flags/mod.ts, flags/test.ts
=> fix(flags): set boolean aliases to false by default

log/README.md
Related: https://github.com/denoland/deno_std/issues/2506
=> docs(log): add note for module authors

http/file_server.ts, http/file_server_test.ts
When I use File Server again after a long time, I often want to know which version I'm on.
=> feat(file_server): Print version

node/http.ts
This is a blocker for `astro`.
=> node: mock ClientRequest.setTimeout

node/http.ts, node/http_test.ts
=> fix(node/http): allow setting statusMessage

node/console.ts
These console methods are added in https://github.com/denoland/deno/pull/16724
This PR updates the export items in `node/console` to fix the CI.
These methods are also available in node.js https://nodejs.org/api/console.html#inspector-only-methods
=> fix(node/console): update export members of console

node/process.ts, node/process_test.ts
=> feat(node): export `process.argv`

path/posix.ts
=> docs(path): clarify the meaning of resolve for normalize

node/_core.ts
Working on https://github.com/denoland/deno/pull/16881 I noticed some APIs
are not listed here.
=> refactor: add more functions to node/_core.ts

bytes/equals.ts, bytes/last_index_of_needle_test.ts, bytes/repeat.ts
This PR applies a few adjustments to the bytes module to be more correct and fully covered by tests.
=> fix(bytes): minor tweaks and fixes for full cov.

encoding/front_matter/mod.ts
The page https://deno.land/std@0.167.0/encoding/front_matter/mod.ts is wrong.
fix this https://github.com/denoland/dotland/issues/2616
=> docs(encoding/front_matter): fix doc error when render page

encoding/base58.ts
Ref:
https://github.com/denoland/deno_std/issues/2493
https://github.com/denoland/deno_std/pull/2515
=> docs: removed types from jsdoc directives

.github/workflows/ci.yml, encoding/_toml/parser_test.ts, media_types/_util_test.ts, node/_crypto/crypto_browserify/browserify_aes/test/test.js, node/_crypto/crypto_browserify/cipher_base_test.js, node/_fs/_fs_rmdir.ts
This PR updates the code format, following CLI's change https://github.com/denoland/deno/pull/16982
Also fixes one type error which was (probably) caused by TS 4.9.3 update. https://github.com/denoland/deno/pull/16973
=> chore: update for CLI canary

streams/mod.ts
Cleanup of work in #2957. See https://github.com/denoland/deno_std/pull/2957#issuecomment-1351366178
=> refactor(streams): clean up `mod.ts`

node/process.ts
=> fix(node): add missing exports to `process`

node/_core.ts
Required for https://github.com/denoland/deno/pull/16881
=> refactor: handle Deno[Deno.internal].core

flags/mod.ts, flags/test.ts
=> fix(flags): parse method looses types in certain cases with collect option

flags/mod.ts, flags/test.ts
=> fix(flags): types for aliases defined as array are ignored

node/internal_binding/connection_wrap.ts, node/internal_binding/stream_wrap.ts, node/internal_binding/tcp_wrap.ts, node/net_test.ts
closes https://github.com/denoland/deno/issues/16710
remaining:
=> fix(node): support ref & unref of TCP handle

_tools/check_deploy.ts
If the branch name contains capital letters, then the current `check_deploy.ts` fails to check it. This PR fixes it by replacing the usage of `fetch` by `Deno.connectTls`
closes #3104
=> chore(_tools): check deploy name with capital letters

fmt/printf.ts, fmt/printf_test.ts
Added a formatter that uses Deno.inspect.
=> Added formatter i I (w/ Deno.inspect)

_tools/release/02_create_pr.ts
Update the script so that the command to run tests is in a code fence, which has a copy button. Yes, I'm lazy to select and copy it.
=> ci: update 02_create_pr script

testing/asserts_test.ts
Fix the currently failing CI. (ref: https://github.com/denoland/deno_std/pull/3184#issuecomment-1426354288)
CI failure is related to swc upgrade. 
- https://github.com/denoland/deno/pull/17692
- https://github.com/denoland/deno_ast/pull/131
This PR updates the test cases and also resolves one TODO comment.
=> fix: update test cases according to swc updates

http/file_server_test.ts
'Access is denied' error is sometimes thrown at `child.kill("SIGKILL")` call only on windows. This PR tries to reduce the probability of flaky test failure caused by it.
closes #3195
=> test(http): make file_server_test less flaky

fs/ensure_symlink.ts, fs/ensure_symlink_test.ts
=> fix(fs/ensure_symlink): lstat relative symlink properly

fs/ensure_dir.ts
close #3233
This PR builds on top of #3240.
Note: I tried to add a test for this, but I couldn't reproduce it locally so I didn't.
=> fix(fs/ensureDir): Fix racy ensureDir

encoding/json/stream.ts, json/concatenated_json_parse_stream.ts, json/json_parse_stream.ts
=> fix(json): correct examples

front_matter/_test_utils.ts, front_matter/mod.ts, front_matter/testdata/toml2.md, front_matter/toml_test.ts
Closes https://github.com/denoland/deno_std/issues/3094
Supersedes https://github.com/denoland/deno_std/pull/3095
Huge thanks to @jpcaruana for the initial work!
=> feat(front_matter): Add +++ as valid TOML encoding

streams/_test_common.ts, streams/delimiter_stream_test.ts, streams/text_delimiter_stream.ts, streams/text_delimiter_stream_test.ts
closes https://github.com/denoland/deno_std/issues/3199
=> feat: disposition on TextDelimiterStream

http/file_server.ts
close #3318 
If the file server returns a 304 Not Modified, calls `Deno.open()` and `contentType()` are unnecessary. Change those functions to be called on a later line.
This change seems to make the 304 response generation slightly (100µs) faster. (446µs -> 340µs)
before:
```
benchmark                      time (avg)             (min … max)       p75       p99      p995
----------------------------------------------------------------- -----------------------------
fileServer_200OK           551.74 µs/iter(388.4 µs … 1.58 ms) 621.5 µs 1.01 ms 1.24 ms
fileServer_304NotModified  446.54 µs/iter(350.7 µs … 1.23 ms) 486.3 µs 883.2 µs 996.6 µs
```
after:
```
benchmark                      time (avg)             (min … max)       p75       p99      p995 …
```
=> perf(http/file_server): Avoid calculating Content-Type when 304 Not Modified response

async/pool.ts, async/pool_test.ts
=> feat(async/pool): use browser compatible APIs

path/mod.ts
=> BREAKING(path): deprecate path.sep

http/server_sent_event.ts, http/server_sent_event_test.ts
=> fix(http/server_sent_event): fix Uncaught TypeError if created without optional EventInit

flags/mod.ts
Fix CI that have failed since https://github.com/denoland/deno/pull/19050.
(for example: https://github.com/denoland/deno_std/actions/runs/4929689188/jobs/8809635130?pr=3368)
=> chore(ci): fix format

http/file_server.ts
=> chore(http/file_server): add module documentation

semver/cmp.ts, semver/comparator.ts, semver/comparator_min.ts, semver/sort.ts
First PR to check this is what you're after. Please do not merge. I'll mark this PR as ready to merge once everything's done.
=> move to single-export files

http/etag_test.ts
=> chore: remove ts-ignores

.github/workflows/typos.toml, http/file_server_test.ts, http/server_sent_event.ts
Some type errors started appearing because of TS upgrade in canary (See https://github.com/denoland/deno_std/actions/runs/5450255896/jobs/9915333243 for details). This PR fixes those type errors.
=> chore: fix type errors caused by canary

deno.json, test_import_map.json
This change cleans up the Deno configuration file.
=> chore: cleanup `deno.json`

http/server.ts, http/server_test.ts
Addressed https://github.com/denoland/deno/issues/10064#issuecomment-1637427260
=> fix(http): fix handling of string port number

json/concatenated_json_parse_stream_test.ts
Fails due to rusty_v8 downgrade -- will revert at a later date.
=> chore: revert test fix temporarily

collections/mod.ts
Closes https://github.com/denoland/deno_std/issues/3412
=> chore(collections): remove warning from mod.ts

encoding/binary.ts
=> BREAKING(encoding): deprecate encoding/binary

semver/cmp.ts, semver/compare.ts, semver/compare_build.ts, semver/difference.ts, semver/eq.ts, semver/gt.ts, semver/gte.ts, semver/gtr.ts, semver/increment.ts, semver/lt.ts, semver/lte.ts, semver/ltr.ts, semver/max_satisfying.ts, semver/min_satisfying.ts, semver/mod.ts, semver/neq.ts, semver/outside.ts, semver/parse.ts, semver/range_intersects.ts, semver/rcompare.ts, semver/rsort.ts, semver/sort.ts
This PR removes the deprecated APIs in #3385
=> BREAKING(semver): remove deprecated APIs

fmt/printf.ts
=> fix(fmt): make printf respect NO_COLOR

http/server_test.ts
=> test(http): reduce http test flakiness

testing/__snapshots__/snapshot_test.ts.snap, testing/snapshot.ts
Fix 1 snapshot**s** to 1 snapshot
=> style(testing/snapshot): distinguish between singular and plural forms

media_types/type_by_extension.ts
=> BREAKING(media_types): deprecate typeByExtension

path/_os.ts
Noticed these things while poking around the path module.
=> chore(path): update _os.ts

_tools/check_circular_submodule_dependencies.ts
This PR updates the status of sub modules towards the stabilization.
=> chore(_tools): update status towards stabilization

encoding/_util.ts, encoding/_util_test.ts, encoding/ascii85.ts, encoding/base32.ts, encoding/base58.ts, encoding/base64.ts, encoding/hex.ts
This PR adds the validation of the input type for encoding APIs.
=> fix(encoding): add validation of the input types

dotenv/load_test.ts
=> test: make dotenv/load_test.ts less flaky

README.md
These changes aim to make the README more concise, thorough, and friendlier to newcomers. I'm not strongly opinionated on most changes, so other opinions are welcome.
Further improvements on the README will come in the following PRs.
=> docs: re-write README

Releases.md
=> docs: fix README typo

README.md
This list will change often enough that I'm uncertain whether we should have this here or in a pinned tracking issue. Either way, here it is.
=> docs: add "Stability" README section

console/unicode_width_test.ts
=> refactor(console): format test names

archive/tar_test.ts, async/abortable_test.ts, async/mux_async_iterator_test.ts, async/pool_test.ts, async/tee_test.ts, csv/csv_parse_stream_test.ts, csv/csv_stringify_stream_test.ts, fs/empty_dir.ts, fs/expand_glob_test.ts, fs/walk_test.ts, http/unstable_cookie_map_test.ts, json/_test_common.ts, json/concatenated_json_parse_stream_test.ts, json/json_parse_stream_test.ts, json/json_stringify_stream_test.ts, streams/byte_slice_stream_test.ts, streams/early_zip_readable_streams_test.ts, streams/iterate_reader_test.ts, streams/limited_bytes_transform_stream_test.ts, streams/limited_transform_stream_test.ts, streams/merge_readable_streams_test.ts, streams/readable_stream_from_reader_test.ts, streams/to_transform_stream_test.ts, streams/zip_readable_streams_test.ts
=> chore: use `Array.fromAsync()` where possible

_tools/check_circular_submodule_dependencies.ts, _tools/check_deprecation.ts, _tools/check_doc_imports.ts, _tools/release/deps.ts, deno.json
=> chore: centralise dev dependencies in `deno.json`

http/method.ts, http/unstable_method.ts
=> BREAKING: deprecate `std/http/method`

fmt/printf.ts
Refers to this [issue](https://github.com/denoland/deno_std/issues/3782)
This change is only internal.
=> refactor(fmt): replaced enums with const objects

console/_tools/generate_data.ts
Refers to this [issue](https://github.com/denoland/deno_std/issues/3782).
This change is internal only.
=> refactor(console): replace enums with const objects

dotenv/mod.ts, dotenv/mod_test.ts, dotenv/stringify.ts, dotenv/stringify_test.ts
=> refactor(dotenv): move `stringify()` to own file

collections/deep_merge.ts, collections/drop_last_while.ts, collections/group_by.ts, collections/join_to_string.ts, collections/mod.ts, collections/sample.ts, collections/sort_by.ts, collections/union.ts
=> chore(collections): complete documentation

console/unicode_width.ts
=> chore(console): complete documentation

crypto/unstable_keystack.ts
Hi, PR enhances performance by leveraging `Promise.all` for concurrent execution of asynchronous functions. This brings improved parallelism, maximizing resource utilization and potentially optimizing overall efficiency.
=> perf(crypto): use `Promise.all()` for `KeyStack` data comparisons

.github/workflows/ci.yml
See https://github.com/denoland/deno_std/pull/3119#issuecomment-1850139738
=> chore(ci): temporarily disable Deno stable in CI

front_matter/_test_utils.ts, front_matter/any.ts, front_matter/any_test.ts, front_matter/create_extractor_test.ts, front_matter/json_test.ts, front_matter/mod.ts, front_matter/test.ts, front_matter/test_test.ts, front_matter/toml.ts, front_matter/toml_test.ts, front_matter/yaml.ts, front_matter/yaml_test.ts
These changes should not be breaking.
=> chore(front_matter): cleanup deprecation-related code

semver/_shared.ts
replaces regex strings with template strings.
=> chore(semver): regex template strings

semver/_shared.ts
rename some internal constants for more readability.
=> chore(semver): rename internal constants for better readability

semver/rcompare.ts
add deprecation notice to `rcompare`
=> deprecation(semver): deprecate `rcompare()`

.github/CONTRIBUTING.md
=> docs: add test name convention

.gitignore, deno.json
See https://deno.com/blog/v1.39#new-deno-coverage-reporters
=> chore: update coverage tasks

testing/mock.ts
This aims to make things a little more readable.
=> refactor(testing): minor cleanups

http/unstable_signed_cookie.ts, http/unstable_signed_cookie_test.ts
=> fix(http): account for period in signed cookie name

regexp/escape_test.ts
=> refactor(regexp): format test names

async/_util_test.ts, async/abortable_test.ts, async/deadline_test.ts, async/debounce_test.ts, async/delay_test.ts, async/mux_async_iterator_test.ts, async/pool_test.ts, async/retry_test.ts, async/tee_test.ts
=> refactor(async): format test names

datetime/constants_test.ts, datetime/day_of_year_test.ts, datetime/difference_test.ts, datetime/format_test.ts, datetime/is_leap_test.ts, datetime/parse_test.ts, datetime/week_of_year_test.ts
@iuioiua do we really need the `constants_test.ts` file to check constants?
=> refactor(datetime): format test names

cli/parse_args_test.ts
=> refactor(cli): format test names

cli/spinner.ts
Addresses https://github.com/denoland/deno_std/pull/3968#discussion_r1434345937
CC @jsejcksn
=> fix(cli): document milliseconds unit for `Spinner.interval`

fmt/bytes_test.ts, fmt/colors_test.ts, fmt/duration_test.ts, fmt/printf_test.ts
=> refactor(fmt): format test names

encoding/_util_test.ts, encoding/ascii85_test.ts, encoding/base32_test.ts, encoding/base58_test.ts, encoding/base64_test.ts, encoding/base64url_test.ts, encoding/hex_test.ts, encoding/varint_test.ts
=> refactor(encoding): format test names

semver/_shared.ts, semver/is_comparator.ts, semver/is_valid_operator_test.ts, semver/types.ts
- adds array of operators and derives type from array
- renames `isValidOperator` to `isOperator`
- replace switch statement with `includes` in `isOperator`
=> refactor(semver): add operators array

ulid/test.ts
=> refactor(ulid): format test names

url/basename_test.ts, url/dirname_test.ts, url/extname_test.ts, url/join_test.ts, url/normalize_test.ts
=> refactor(url): format test names

toml/parse_test.ts, toml/test.ts
=> refactor(toml): format test names

yaml/parse_test.ts, yaml/stringify_test.ts
=> refactor(yaml): format test names

html/entities_test.ts
=> refactor(html): format test names

toml/test.ts, toml/testdata/string.toml
Fixes https://github.com/denoland/deno_std/actions/runs/7393477091/job/20113460606?pr=4072
=> fix(toml): testdata typo

ulid/test.ts
Fixes https://github.com/denoland/deno_std/pull/4063/files#r1440055029
=> chore(ulid): fix `monotonicUlid()` test name

fs/expand_glob_test.ts
Should fix https://github.com/denoland/deno_std/actions/runs/7402850608/job/20141568466
=> fix(fs): fix `expandGlob()` test race condition

html/entities.ts, html/mod.ts
=> docs(html): complete documentation

semver/range_max.ts, semver/range_min.ts
- replaces .sort, .filter and .map with loops while making the code more readable.
- reduces overhead
=> refactor(semver): make `rangeMin()` and `rangeMax()` more readable

cli/spinner.ts
- makes `Spinner.color` prop public.
=> refactor(cli): make `Spinner.color` public

.github/SECURITY.md
To align with the changes in https://github.com/denoland/deno/pull/21766.
=> chore: update security policy

log/levels.ts, log/logger.ts
=> BREAKING(log): remove deprecated APIs

text/mod.ts
To align with the rest of the Standard Library.
=> refactor(text): use star exports in `mod.ts`

url/dirname_test.ts, url/extname_test.ts, url/normalize_test.ts
Handling all noUncheckedIndexedAccess issues for the url module, tracked in https://github.com/denoland/deno_std/issues/4040
=> refactor(url): prepare for `noUncheckedIndexedAccess`

csv/_io.ts
Handling all noUncheckedIndexedAccess issues for the csv module, tracked in https://github.com/denoland/deno_std/issues/4040
=> refactor(csv): prepare for `noUncheckedIndexedAccess`

front_matter/create_extractor.ts
Handling all noUncheckedIndexedAccess issues for the front_matter module, tracked in https://github.com/denoland/deno_std/issues/4040
=> refactor(front_matter): prepare for `noUncheckedIndexedAccess`

webgpu/texture_with_data.ts
Handling all noUncheckedIndexedAccess issues for the webgpu module, tracked in https://github.com/denoland/deno_std/issues/4040
=> refactor(webgpu): prepare for `noUncheckedIndexedAccess`

dotenv/mod.ts, dotenv/parse.ts, dotenv/stringify.ts
=> docs(dotenv): complete documentation

net/get_available_port.ts, net/get_available_port_test.ts
Closes https://github.com/denoland/deno_std/issues/4080.
=> feat(net): add `preferredPort` option to `getAvailablePort()`

front_matter/create_extractor.ts
=> docs(front_matter): complete documentation

datetime/difference.ts, datetime/mod.ts, datetime/parse.ts
=> docs(datetime): complete documentation

log/levels.ts
Related #4117
PTAL @timreichen
=> deprecation(log): deprecate `LogLevels.WARNING`

io/buffer.ts
See https://github.com/denoland/deno_std/issues/4120#issuecomment-1888570028
=> feat(io): un-deprecate `Buffer`

http/cookie.ts, http/etag.ts, http/negotiation.ts, http/server.ts, http/server_sent_event_stream.ts, http/status.ts, http/user_agent.ts
=> docs(http): complete documentation

log/formatters.ts
Closes #4175
Technically, this is a breaking change. However, I doubt anyone would be using this function.
=> fix(log): make `flattenArgs()` private

media_types/content_type.ts, media_types/extension.ts, media_types/format_media_type.ts, media_types/get_charset.ts, media_types/parse_media_type.ts, media_types/type_by_extension.ts
=> docs(media_types): complete documentation

msgpack/encode.ts
=> docs(msgpack): complete documentation

console/_run_length.ts, console/unicode_width.ts
=> refactor(console): prepare for `noUncheckedIndexedAccess`

expect/_assert_not_equals_test.ts, expect/_diff_test.ts, expect/_equal_test.ts, expect/_to_be_instance_of_test.ts, expect/_to_be_less_than_or_equal_test.ts, expect/_to_equal_test.ts, expect/_to_have_been_nth_called_with_test.ts
=> refactor(expect): format test names

html/entities.ts
=> refactor(html): prepare for `noUncheckedIndexedAccess`

ini/ini_map.ts
=> refactor(ini): prepare for `noUncheckedIndexedAccess`

semver/types.ts
This PR aligns the removal version of Comparator.semver to the other items in semver.
related https://github.com/denoland/deno_std/pull/4334
=> chore(semver): align removal version

streams/_common.ts, streams/delimiter_stream.ts, streams/merge_readable_streams.ts, streams/text_delimiter_stream.ts
Ref: https://github.com/denoland/deno_std/issues/4040
=> refactor(streams): prepare for `noUncheckedIndexedAccess`

msgpack/decode_test.ts, msgpack/encode_test.ts
=> chore(msgpack): format test names

media_types/_util_test.ts, media_types/content_type_test.ts, media_types/extension_test.ts, media_types/extensions_by_type_test.ts, media_types/format_media_type_test.ts, media_types/get_charset_test.ts, media_types/parse_media_type_test.ts, media_types/type_by_extension_test.ts
=> chore(media_types): format test names

jsonc/parse_test.ts
=> chore(jsonc): format test names

front_matter/any_test.ts, front_matter/create_extractor_test.ts, front_matter/json_test.ts, front_matter/test_test.ts, front_matter/toml_test.ts, front_matter/yaml_test.ts
=> chore(front_matter): format test names

deno.json, log/base_handler.ts
Some upcoming work should prevent this from happening again.
Fixes https://github.com/denoland/deno_std/actions/runs/8054065477/job/21997810452
=> fix(log): add missing return types

streams/buffer_test.ts, streams/byte_slice_stream_test.ts, streams/delimiter_stream_test.ts, streams/early_zip_readable_streams_test.ts, streams/iterate_reader_test.ts, streams/limited_bytes_transform_stream_test.ts, streams/limited_transform_stream_test.ts, streams/merge_readable_streams_test.ts, streams/readable_stream_from_reader_test.ts, streams/reader_from_iterable_test.ts, streams/reader_from_stream_reader_test.ts, streams/text_delimiter_stream_test.ts, streams/text_line_stream_test.ts, streams/to_array_buffer_test.ts, streams/to_blob_test.ts, streams/to_json_test.ts, streams/to_text_test.ts, streams/to_transform_stream_test.ts, streams/writable_stream_from_writer_test.ts, streams/writer_from_stream_writer_test.ts, streams/zip_readable_streams_test.ts
=> chore(streams): format test names

json/concatenated_json_parse_stream_test.ts, json/json_parse_stream_test.ts, json/json_stringify_stream_test.ts
=> chore(json): format test names

semver/_comparator_intersects_test.ts, semver/_is_comparator.ts, semver/_is_comparator_test.ts, semver/can_parse_test.ts, semver/comparator_test.ts, semver/compare_test.ts, semver/difference_test.ts, semver/equals_test.ts, semver/format_range_test.ts, semver/format_test.ts, semver/greater_or_equal_test.ts, semver/greater_than_test.ts, semver/gtr_test.ts, semver/increment_test.ts, semver/is_range_test.ts, semver/is_semver_test.ts, semver/less_or_equal_test.ts, semver/less_than_test.ts, semver/ltr_test.ts, semver/max_satisfying_test.ts, semver/min_satisfying_test.ts, semver/not_equals_test.ts, semver/parse_range_test.ts, semver/parse_test.ts, semver/range_min_test.ts
=> chore(semver): format test names

async/deadline.ts, async/debounce.ts, async/retry.ts
Having these tags enables syntax highlighting in documentation.
=> chore(async): add missing code snippet tags

assert/mod.ts
=> docs(assert): add module example

cli/parse_args.ts
Ref: https://github.com/denoland/deno_std/issues/4040
=> chore(cli): prepare for `noUncheckedIndexedAccess`

expect/_asymmetric_matchers.ts
=> refactor(expect): use `===` instead of `==`

http/unstable_signed_cookie.ts
=> docs(http): prepare for `noUncheckedIndexedAccess`

README.md
Link to JSR version of std in README
=> add JSR link

bytes/mod.ts
=> docs(bytes): module docs

async/mod.ts
=> docs(async): add module example

expect/expect.ts
=> refactor(expect): prepare for `noUncheckedIndexedAccess`

deno.json, fs/ensure_link_test.ts, http/file_server_test.ts, http/server.ts
=> chore: enable `no-sync-fn-in-async-fn` lint rule

io/buf_reader.ts, io/buf_writer_test.ts, io/read_delim.ts, io/string_writer_test.ts
ref https://github.com/denoland/deno_std/issues/4040
=> refactor(io): prepare for `noUncheckedIndexedAccess`

collections/_utils.ts, collections/mod.ts
=> docs(collections): add module example

crypto/mod.ts
=> docs(crypto): add module example

data_structures/mod.ts
=> docs(data_structures): add module example

http/server.ts
Towards addressing https://github.com/denoland/deno/pull/22868#issuecomment-1992564734
=> refactor(http): use `cert` and `key` for `Deno.listenTls()`

log/logger_test.ts, log/test.ts
=> refactor(log): prepare for `noUncheckedIndexedAccess`

deno.json
Closes #4040.
Thank you to those that helped get this done! CC @syhol, @gabelluardo, @javihernant and @eryue0220
=> chore: enable `noUncheckedIndexedAccess`

assert/_diff.ts, bytes/ends_with.ts, bytes/starts_with.ts, csv/stringify.ts, deno.json, encoding/ascii85.ts, encoding/base64.ts, encoding/varint.ts, expect/_diff.ts, path/_common/normalize_string.ts, path/posix/join.ts, testing/mock.ts, yaml/_dumper/dumper.ts, yaml/_loader/loader.ts, yaml/_mark.ts
=> chore: enable `single-var-declarator` lint rule

.github/CONTRIBUTING.md
So contributors are clear on how to write test names for classes.
=> docs: account for classes in test guideline

datetime/mod.ts
=> docs(datetime): add module doc

media_types/mod.ts
=> docs(media_types): module doc

console/mod.ts, console/unicode_width.ts
Towards a 100% JSR score. This also aims to adhere to MDN Web Doc's writing style guide, by providing more complete and thorough details, including context behind a particular API's existence.
=> docs(console): improve documentation

datetime/constants.ts, datetime/day_of_year.ts, datetime/difference.ts, datetime/format.ts, datetime/is_leap.ts, datetime/mod.ts, datetime/parse.ts, datetime/week_of_year.ts
Focuses on clarity, concision, and coherence. This module should act as the north star for the documentation of other modules. Towards v1.
=> docs(datetime): polish documentation

fs/test.ts
=> chore(fs): remove `test.ts`

.github/ARCHITECTURE.md, .github/CONTRIBUTING.md, README.md
=> docs: `ARCHITECTURE.md`

.github/CONTRIBUTING.md
=> docs: update public symbol and module documentation style

.github/workflows/workspace_publish.yml
=> chore: use canary in publish workflow

bytes/concat.ts, bytes/copy.ts, bytes/ends_with.ts, bytes/equals.ts, bytes/includes_needle.ts, bytes/index_of_needle.ts, bytes/last_index_of_needle.ts, bytes/mod.ts, bytes/repeat.ts, bytes/starts_with.ts
In preparation for stablisation.
Towards #3764
=> docs(bytes): polish documentation

internal/diff.ts
Fixes https://github.com/denoland/deno_std/actions/runs/8701409332/job/23863356620
=> chore: add missing return type

url/basename.ts, url/dirname.ts, url/extname.ts, url/join.ts, url/mod.ts, url/normalize.ts
=> docs(url): polish documentation

bytes/concat.ts, bytes/copy.ts, bytes/ends_with.ts, bytes/index_of_needle.ts, bytes/last_index_of_needle.ts, bytes/repeat.ts
These are non-breaking but either improve implementation logic and/or readability.
=> refactor(bytes): minor cleanups

http/server_test.ts
Fixes https://github.com/denoland/deno_std/actions/runs/8770879912/job/24067947040
=> test(http): update `Deno.listenTls()` options

collections/mod.ts
Prerequisite for #4697
Towards #4647
=> docs(collections): finalize module documentation

cli/spinner_test.ts
ref https://github.com/denoland/deno_std/actions/runs/9058079848/job/24883108851
=> test(cli): reduce flakiness of spinner test

.github/ARCHITECTURE.md
Updates `_tools` section and adds `<package>/deno.json` section.
=> docs: update `ARCHITECTURE.md`

.github/CONTRIBUTING.md
=> docs: instructions on how to add package title to title checker

.gitignore, .vscode/settings.json
This enables automatic formatting in vscode.
=> chore: add vscode settings

.github/CONTRIBUTING.md
In preparation for the upcoming documentation hackathon.
=> docs: improve documentation on how to write documentation

README.md
=> docs: update Releases section

_tools/check_docs.ts, async/abortable.ts, async/deadline.ts, async/debounce.ts, async/delay.ts, async/mux_async_iterator.ts, async/pool.ts, async/retry.ts, async/tee.ts, datetime/day_of_year.ts, media_types/extensions_by_type.ts, webgpu/create_capture.ts, webgpu/describe_texture_format.ts, webgpu/row_padding.ts, webgpu/texture_with_data.ts
=> chore: add `@example` title check to doc checker

http/server.ts
=> docs(http): don't run some examples in doc checker

cli/spinner_test.ts, cli/testdata/spinner_cases/change_message.ts, cli/testdata/spinner_cases/set_color.ts
=> test(cli): reduce the flakiness of `Spinner` test cases

_tools/check_docs.ts, data_structures/binary_heap.ts, data_structures/binary_search_tree.ts, data_structures/red_black_tree.ts
=> docs(data-structures): enables doc lint of data-structures

path/normalize_test.ts, path/windows/normalize.ts
This PR improves the test coverage of `normalize` function.
part of #3713 #4600
=> test(path): improve `normalize()` coverage

path/normalize_glob_test.ts
=> test(path): improve `normalizeGlob()` test coverage

cli/parse_args.ts, encoding/ascii85.ts, encoding/base32.ts, encoding/base58.ts, encoding/base64.ts, encoding/base64url.ts, encoding/hex.ts, encoding/mod.ts, fmt/bytes.ts, fmt/colors.ts, jsonc/mod.ts, jsonc/parse.ts, path/mod.ts, path/posix/mod.ts, path/windows/mod.ts, semver/mod.ts, testing/mock.ts, text/mod.ts, toml/mod.ts, url/mod.ts
This is already stated in JSR.
=> docs(cli,encoding,fmt,jsonc,path,semver,testing,text,toml,url): remove "This module is browser compatible" note

data_structures/_binary_search_node.ts
=> refactor(data-structures): remove use of `public` keyword

_tools/check_docs.ts, net/get_available_port.ts, net/get_network_address.ts, net/mod.ts
=> docs(net): complete documentation

assert/assert_almost_equals.ts, assert/assert_almost_equals_test.ts
=> fix(assert): fix tolerance calculation when comparing negative values

text/compare_similarity.ts, text/levenshtein_distance.ts, text/mod.ts, text/word_similarity_sort.ts, text/word_similarity_sort_test.ts
Mostly adding options interfaces, improving documentation and tests.
=> refactor(text): minor cleanups and improvements

yaml/_schema.ts, yaml/_utils.ts
This PR removes the dead code in yaml package.
=> refactor(yaml): remove dead code

yaml/_schema.ts
- removes inferred Schema type
=> refactor(yaml): remove inferred `Schema` type

yaml/parse_test.ts
=> test(yaml): add test for `ParseOptions.json` option

deno.json
This is causing an issue in #4931.
=> chore: update `@std/encoding` version

yaml/_chars.ts, yaml/_dumper.ts, yaml/_loader.ts
- moves char check functions into `_chars.ts`
=> refactor(yaml): move char check functions

yaml/_dumper.ts
- replaces usedDuplicates array with a Set
=> refactor(yaml): replace `usedDuplicates()` array with `Set`

yaml/_dumper.ts
Note: The if statement conditions seemed very odd. I am not sure, if the new conditions reflect the original. Please check.
=> refactor(yaml): cleanup `detectType()`

toml/_parser.ts, toml/parse.ts, toml/parse_test.ts
- renames functions to camel case
- replace nested functions with arrow functions
=> refactor(toml): rename functions to camel case

yaml/_error.ts
Pre-requisite work for exposing `YamlError` in the public API.
=> refactor(yaml): simplify `YamlError`

toml/_parser.ts
- replaces Pattern object with regexp constants
=> refactor(toml): remove `Patterns` object

ini/_ini_map.ts, ini/parse.ts, ini/stringify.ts
=> docs(ini): link options interfaces to functions that use them

fmt/README.md, fmt/bytes.ts, fmt/colors.ts
=> docs(fmt): improve documentation

front_matter/types.ts
addresses https://github.com/denoland/deno_std/pull/5376#issuecomment-2220056006
=> docs(front-matter): fix description of `Extract`

log/file_handler_test.ts, log/rotating_file_handler_test.ts
Spotted while looking at #5384.
=> test(log): cleaunp `TextDecoder` use

yaml/_dumper.ts
- rearranges constants at the top, utility functions next and then exports
=> refactor(yaml): rearrange constants and functions

.github/FAQ.md
Addresses https://github.com/denoland/deno_std/issues/3757#issuecomment-2223547790
=> chore: document how to find changed API

yaml/parse.ts, yaml/stringify.ts
=> docs(yaml): list `extended` schema

collections/intersect.ts
- reduces code by using `Set.prototype.intersection()`.
=> refactor(collections): use `Set.prototype.intersection()` method in `intersect()`

text/levenshtein_distance.ts
=> docs(text): state complexity of `levenshteinDistance()`

path/_os.ts
=> fix(path): support use in dnt

streams/limited_bytes_transform_stream.ts, streams/limited_transform_stream.ts
Addresses https://github.com/denoland/std/pull/5213#pullrequestreview-2185612266
=> docs(streams): address documentation issues

.github/CONTRIBUTING.md
=> chore: document how to document unstable APIs

deno.json, streams/deno.json
This PR extends RC of `streams` to discuss #5079 further
=> chore: `streams@1.0.0-rc.4` (extending RC phase)

cli/spinner.ts
=> chore(cli): remove redundant constructor example

csv/parse_stream.ts, csv/stringify_stream.ts
=> chore(csv): remove redundant constructor examples

data_structures/binary_heap.ts, data_structures/binary_search_tree.ts, data_structures/red_black_tree.ts
=> chore(data-structures): remove redundant constructor examples

fs/move.ts, fs/walk.ts
=> chore(fs): remove redundant constructor examples

http/user_agent.ts
=> chore(http): remove redundant constructor example

json/concatenated_json_parse_stream.ts, json/parse_stream.ts, json/stringify_stream.ts
=> chore(json): remove redundant constructor examples

testing/mock.ts, testing/time.ts
=> chore(testing): remove redundant constructor examples

text/levenshtein_distance_test.ts
https://github.com/denoland/std/pull/5527#pullrequestreview-2193725090.
=> test(text): add more testcases for `levenshteinDistance`

yaml/stringify_test.ts
This PR adds test cases that check `lineWidth` option behavior of `stringify`
=> test(yaml): check `lineWidth` option behavior

testing/time.ts, testing/time_test.ts
Corrects casing and improves consistency
=> refactor(testing): improve `FakeTime` error messaging

yaml/_type/float.ts
=> refactor(yaml): cleanup dead sexagesimal regexp code in float type

text/levenshtein_distance.ts
I included a link to the paper and added explanatory comments where the implementation differs from that described in the paper. I hope this addresses the understandability problem.
<details><summary>Benchmark code and results</summary>
```text
cpu: Apple M1
runtime: deno 1.45.2+f4b9d85 (aarch64-apple-darwin)
benchmark      time (avg)        iter/s             (min … max)       p75       p99      p995
--------------------------------------------------------------- -----------------------------
group short strings
main          210.58 µs/iter       4,748.9    (195.12 µs … 396 µs) 208.92 µs 264.54 µs 280.29 µs
this PR         6.36 µs/iter     157,287.5     (6.29 µs … 6.46 µs) 6.41 µs 6.46 µs 6.46 µs
summary
this PR
33.12x faster than main
group long strings
main              1.8 s/iter …
```
=> perf(text): make `levenshteinDistance()` up to 147x faster

.github/workflows/ci.yml, http/file_server_test.ts
Fixes https://github.com/denoland/std/actions/runs/10136063768/job/28024339317?pr=5561
=> fix(http): update localhost strings in tests

testing/mock.ts, testing/mock_test.ts
Addresses https://github.com/denoland/std/pull/5570#discussion_r1696174755
=> fix(testing): correct `stub()` error message

ini/parse_test.ts, ini/stringify_test.ts
=> test(ini): copy tests from `ini/_ini_map_test.ts`

cli/parse_args.ts
Addresses https://github.com/denoland/std/pull/5599#discussion_r1701269351
=> refactor(cli): use non-null assertion in `parseArgs()` logic

.github/workflows/title.yml
=> chore: add random scope in title ci check

front_matter/_formats.ts, front_matter/json_test.ts, front_matter/toml_test.ts, front_matter/yaml_test.ts
=> fix(front-matter): allow whitespaces after the header

yaml/_type/bool.ts
**Changes**
This PR refactors `resolveYamlBoolean()` and `constructYamlBoolean()` by using constants containing boolean strings.
=> refactor(yaml): boolean constants

yaml/_loader_state.ts, yaml/_schema.ts
**Changes**
This PR changes the `TypeMap` type so it uses `Map`.
=> refactor(yaml): use `Map`s for `TypeMap`

datetime/mod.ts
Addresses https://github.com/denoland/std/issues/5695#issuecomment-2296582737
=> docs(datetime): add constants to module docs

csv/_io.ts, csv/stringify.ts, csv/stringify_test.ts
=> fix(csv): accept readonly cell/header data (#5734)

yaml/_dumper_state.ts
**Changes**
This PR moves options to an options object in all `DumperState`.
**Reasoning**
All methods are now structured the same, taking a value as first argument and options as the second argument.
=> refactor(yaml): move options to options object

yaml/_loader_state.ts
=> refactor(yaml): inline `yamlDirectiveHandler()`

_tools/check_docs.ts
This should fix concurrency issues with the `lint:docs` task. See https://github.com/denoland/std/actions/runs/10484008177/job/29037626131
=> chore: fix `lint:docs` task concurrency

yaml/_loader_state.ts
=> refactor(yaml): inline `tagDirectiveHandler()`

yaml/_loader_state.ts
=> refactor(yaml): inline `captureSegment()`

http/route.ts, http/route_test.ts
I realise we didn't match on the request method 😅
=> fix(http/unstable): match request method

yaml/_loader_state.ts
=> refactor(yaml): inline `mergeMappings()`

yaml/_loader_state.ts
**Changes**
This PR removes the null type of `result` in `storeMappingPair()`.
**Reasoning**
This should improve the codecov score.
=> refactor(yaml): remove `storeMappingPair()` result `null` type 

yaml/_loader_state.ts
=> refactor(yaml): inline `storeMappingPair()`

cache/lru_cache.ts
=> docs(cache): tweak `LruCache` docs

yaml/_loader_state.ts
=> refactor(yaml): inline `skipSeparationSpace()`

front_matter/any_test.ts, front_matter/json_test.ts, front_matter/toml_test.ts, front_matter/yaml_test.ts
**Changes**
This PR removes duplicate tests. All removed tests already exists in `front_matter/test_test.ts`
=> test(front-matter): remove duplicate tests

yaml/stringify_test.ts
Catches https://app.codecov.io/gh/denoland/std/pull/5836?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=denoland
=> test(yaml): add duplicate binary references test

yaml/_loader_state.ts
=> refactor(yaml): inline `readFlowCollection()`

yaml/_loader_state.ts
=> refactor(yaml): inline `readBlockScalar()`

yaml/_loader_state.ts
=> refactor(yaml): inline `readBlockMapping()`

yaml/_type/pairs.ts
**Changes**
This PR simplifies the `resolve()` function for pairs.
=> refactor(yaml): simplify `resolve()` for pairs

yaml/_loader_state.ts
=> refactor(yaml): inline `composeNode()`

.github/labeler.yml, .github/workflows/title.yml
=> chore: prepare for `@std/tar` package

.github/labeler.yml, .github/workflows/title.yml
=> chore: add settings for new `@std/cbor` package

dotenv/mod_test.ts, fs/ensure_dir_test.ts, fs/ensure_file_test.ts, fs/ensure_symlink_test.ts, fs/expand_glob_test.ts, internal/_is_deno_2.ts
As a result of https://github.com/denoland/deno/pull/25431
=> test: use `Deno.errors.NotCapable` where appropriate

expect/_equal.ts, expect/_equal_test.ts
Same as https://github.com/denoland/std/pull/5913/ (and https://github.com/denoland/std/pull/5921) but for `expect`
=> perf(expect): add fast path for primitive keyed collections in `equal()`

_tools/check_docs.ts, cli/deno.json, cli/mod.ts, cli/testdata/spinner_cases/change_message.ts, cli/testdata/spinner_cases/custom_color_black.ts, cli/testdata/spinner_cases/custom_color_blue.ts, cli/testdata/spinner_cases/custom_color_cyan.ts, cli/testdata/spinner_cases/custom_color_gray.ts, cli/testdata/spinner_cases/custom_color_green.ts, cli/testdata/spinner_cases/custom_color_magenta.ts, cli/testdata/spinner_cases/custom_color_red.ts, cli/testdata/spinner_cases/custom_color_white.ts, cli/testdata/spinner_cases/custom_color_yellow.ts, cli/testdata/spinner_cases/custom_interval_10.ts, cli/testdata/spinner_cases/custom_interval_750.ts, cli/testdata/spinner_cases/custom_message.ts, cli/testdata/spinner_cases/custom_spinner.ts, cli/testdata/spinner_cases/set_color.ts, cli/testdata/spinner_cases/start.ts, cli/testdata/spinner_cases/stop.ts, cli/unstable_spinner.ts, cli/unstable_spinner_test.ts
=> BREAKING(cli/unstable): move `spinner` module to `unstable-spinner`

path/join.ts, path/posix/join.ts, path/windows/join.ts
=> docs(path): add note about `unstable-join`

cache/lru_cache.ts, data_structures/unstable_bidirectional_map.ts
=> fix(cache,data-structures): add missing non-null assertion and `override` keyword

io/buf_writer.ts
=> deprecation(io): deprecate `BufWriter`

deno.json
Thanks to https://github.com/denoland/deno/pull/25848
=> chore: revert `deno fmt --check` workaround

_tools/check_docs.ts, log/formatters.ts
=> docs(log): document `formatters` module

_tools/check_docs.ts, log/console_handler.ts, log/debug.ts
=> docs(log): document `ConsoleHandler`

log/logger.ts
=> fix(log): remove leaky `Logger.prototype.asString()` method

async/unstable_mux_async_iterator.ts
followup to https://github.com/denoland/std/pull/6087#discussion_r1791989531
=> chore(async/unstable): fix typo

.github/workflows/title.yml
=> chore: add kv to scopes of title check

testing/snapshot.ts
Fixes: https://github.com/denoland/std/actions/runs/11641113112/job/32419220160#step:6:1
=> fix(testing): typo in snapshot.ts

cli/prompt_secret.ts, cli/prompt_secret_test.ts
Seems like `promptSecret()` is stable but not covered by any tests. I think that should be avoided in the future.
=> test(cli): add tests for `promptSecret()`

_tools/check_docs.ts, _tools/node_test_runner/run_test.mjs, deno.json, fs/_utils.ts, fs/deno.json, fs/unstable_umask.ts, fs/unstable_umask_test.ts
This PR is part of the #6255 and adds the `umask` to the API
=> feat(fs/unstable): add umask

toml/_parser.ts
=> refactor(toml): improve `integer()` function

http/file_server.ts, http/file_server_test.ts
=> fix(http): use relative urls in file server dirlisting

_tools/lint_plugin.ts, _tools/lint_plugin_test.ts, deno.json, testing/types_test.ts
To get the ball rolling on #6551. Inspired by #6548.
=> chore: Deno Style Guide lint plugin

data_structures/unstable_bidirectional_map.ts, data_structures/unstable_bidirectional_map_test.ts
Fixes https://github.com/denoland/std/issues/6599
=> fix(data-structures/unstable): BidirectionalMap differentiate extant `undefined` from missing values

README.md
This'll do until https://github.com/denoland/deno/issues/23671 is implemented.
=> docs: link to test coverage explorer

toml/_parser.ts, toml/parse_test.ts
This PR fixes https://github.com/denoland/std/issues/6568
=> fix(toml): fix empty inline table bug

_tools/check_docs.ts
Towards https://github.com/denoland/fresh/issues/2876 and towards making this tool available for other codebases to use.
=> chore: export doc checker

html/unstable_is_valid_custom_element_name.ts, html/unstable_is_valid_custom_element_name_test.ts
=> fix(html/unstable): add missing range (`unstable_is_valid_custom_element_name`)

_tools/node_test_runner/run_test.mjs, _tools/node_test_runner/tsconfig_for_bun.json, internal/assertion_state.ts, internal/assertion_state_test.ts
=> fix(internal): support AssertionState cleanup in node and bun

cli/unstable_progress_bar.ts, cli/unstable_progress_bar_test.ts
This fixes the resource leak of ProgressBar on windows. This fixes the main CI.
=> fix(cli/unstable): fix resource leak of ProgressBar

uuid/mod.ts
Add v7 to list of supported versions.
=> docs(uuid): update module docs to mention UUIDv7

random/_pcg32.ts, random/seeded_test.ts
Fixes https://github.com/denoland/std/issues/6688
=> fix(random/unstable): fixed results for some seeds

toml/_parser.ts
https://github.com/denoland/std/pull/6704#discussion_r2120340492
=> refactor(toml): use RegExp groups for month validation

text/deno.json, text/unstable_longest_common_prefix.ts, text/unstable_longest_common_prefix_test.ts
Closes https://github.com/denoland/std/issues/6731
=> feat(text/unstable): add `longestCommonPrefix`

cli/unstable_prompt_multiple_select.ts, cli/unstable_prompt_multiple_select_test.ts, cli/unstable_prompt_select.ts, cli/unstable_prompt_select_test.ts
https://github.com/denoland/std/pull/6742#discussion_r2173145069
=> refactor(cli/unstable): rename `title` to `label` for valued prompt items

streams/unstable_to_byte_stream.ts
I don't know when the `autoAllocateChunkSize` property became a thing on readable streams, but it does make the logic for supporting BYOB streams easier.
This pull request makes use of the property to simplify the code.
=> refactor(streams/unstable): toByteStream to make use of autoAllocateChunkSize

internal/truncate_build_message.ts
This fixes the JSR publish of `@std/internal`
=> fix(internal): fix error in module reference
