- encoding/README.md
`ColumnDetails["fn"]` was removed in #2611, but it remains in the docs. Therefore, it has been removed.
> docs(encoding): remove `ColumnDetails["fn"]`

- fs/walk.ts
It doesn't actually visit files in any particular order
> Remove misleading docs from fs.walk

- _tools/check_deprecation.ts
- semver/README.md
- semver/diff_test.ts
- semver/increment_test.ts
- semver/mod.ts
- semver/tooLong_test.ts
- rename abbreviations: `inc` to `increment` and `diff` to `difference`.
This is more in alignment to the js naming convention.
> chore(semver): rename inc and diff

- bytes/equals.ts
- bytes/equals_bench.ts
This reverts commit e86f7cdbba49a973afd17e0205b68ff8f9e74fa4.
We haven't discussed enough about the performance implication of this change in #2852 
(merge on approval)
cc @iuioiua
> Revert "refactor(bytes): remove `equalsNaive` (#2852)"

- node/http.ts
- node/http_test.ts
This PR fixes binary (non-text) response of flash-backed node/http server.
fixes #2862
> fix(node/http): fix non-string buffer response

- node/_fs/_fs_appendFile_test.ts
- node/_fs/_fs_chmod_test.ts
- node/_fs/_fs_chown_test.ts
- node/_fs/_fs_close_test.ts
- node/_fs/_fs_copy_test.ts
- node/_fs/_fs_dir_test.ts
- node/_fs/_fs_link_test.ts
- node/_fs/_fs_lstat_test.ts
- node/_fs/_fs_mkdir_test.ts
- node/_fs/_fs_open_test.ts
- node/_fs/_fs_opendir_test.ts
- node/_fs/_fs_readFile_test.ts
- node/_fs/_fs_readdir_test.ts
- node/_fs/_fs_readlink_test.ts
- node/_fs/_fs_realpath_test.ts
- node/_fs/_fs_rename_test.ts
- node/_fs/_fs_rmdir_test.ts
- node/_fs/_fs_stat_test.ts
- node/_fs/_fs_unlink_test.ts
- node/_test_utils.ts
- node/_utils.ts
- node/internal/crypto/_randomBytes_test.ts
- node/internal/crypto/pbkdf2_test.ts
This PR creates `node/_test_utils.ts` and moves `assertCallbackErrorUncaught` from `node/_utils.ts` to there.
`assertCallbackErrorUncaught` is a testing utility, and it shouldn't be in the dependencies of non-test code.
> refactor(node): create _test_utils.ts

- node/_tools/test/common/internet.js
- node/_tools/test/internet/test-dns-any.js
This PR updates the domain name `_jabber._tcp.google.com` to `_caldav._tcp.google.com` in test-dns-any.js (in node compat testing). `_jabber._tcp.google.com` seems to have stopped working recently. `_caldav._tcp.google.com` seems still working.
> test(node): update domain names in dns test

- node/_fs/_fs_read.ts
- node/_fs/_fs_read_test.ts
Currently `fs.read` calls the callback synchronously. That partially caused https://github.com/denoland/deno_std/issues/2851. This PR makes `fs.read` call the callback asynchronously.
> fix(node/fs): improve fs.read compatibility

- node/http.ts
- node/http_test.ts
Congrats on launching the NPM compatibility, this is huge!
I'm trying to get an express app running on Netlify Edge Functions, and using https://github.com/dougmoscrop/serverless-http to do so. That library is [creating a `http.IncomingMessage`](https://github.com/dougmoscrop/serverless-http/blob/80bfb3e940057d694874a8b0bc12ad96d2abe7ab/lib/request.js#LL7) without `url` being specified, and sets it [in a second step](https://github.com/dougmoscrop/serverless-http/blob/80bfb3e940057d694874a8b0bc12ad96d2abe7ab/lib/request.js#LL29) (reproduced in the test).
That currently results in an uncaught exception with Deno's polyfill. This PR fixes that.
> fix: allow creating http.IncomingRequest without url being set

- fmt/bytes_test.ts
Fix tests with `decimal` and `group` symbols on unspecified `locale: true`.
This test failed before when run on default german system.
> fix(fmt/bytes): default local decimal and group symbols

- node/http.ts
- node/http_test.ts
This PR makes `http.request()` with the `headers` option actually send the headers.
> fix(node/http): request with headers

- node/module_test.ts
> test(node): ignore Node API test on aarch64 darwin

- node/fs.ts
- node/internal/fs/streams.d.ts
- node/internal/fs/streams.mjs
- node/internal/fs/streams_test.ts
Fixes #2891
References:
https://github.com/nodejs/node/blob/main/lib/internal/fs/streams.js
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/fs.d.ts
> fix(node/fs): enable type narrowing with instanceof for ReadStream and WriteStream

- node/string_decoder.ts
- node/string_decoder_test.ts
Issues: https://github.com/denoland/deno_std/issues/2859
I found out there are 4 problems when checking on this:
1) decoder needs `Buffer` while what received was `TypedArray`. Even though those two are similar, there are some fundamental difference between the pair. Most notably the `copy` method and how the `Buffer View` works.
2) With the current code in the issue, if you add specific encoding `utf8` it would also not work
3) The current `string_decoder` has different encoding normalisation logic from `node` code. Can reference here - https://github.com/nodejs/string_decoder .By default, if not specified, all encoding should be `utf8`, `GenericDecoder` is for unrecognised `encoding` only. 
4) Current `deno` `string_decoder` is using old `string_decoder` logic from nodes, the current …
> fix(node/string_decoder) proper buffer type casting and fix default logic

- http/cookie.ts
- http/cookie_test.ts
Before, when setting a cookie with a value that contained a space (like `United Kingdom`), the error message implied that the value was `" "`. This can be confusing, because what it really means is that the value *contained* `" "`! This PR updates that error message, so it's more descriptive of the error.
> fix: wording for cookie value validation error

- _tools/check_doc_imports_test.ts
Currently the last assertion of `_tools/check_doc_imports_test.ts` is ~~failing~~ flaky on main on ubuntu. This PR disables that assertion on ubuntu.
> chore(_tools): disable some tests of doc import check tool

- http/cookie.ts
- http/cookie_test.ts
This PR allows number type for expires param of setCookie API. This is better aligned to how [CookieStore](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore/set) API handles `expires` param.
closes #2928
> feat(http/cookie): allow number type for expires param

- http/cookie.ts
There isn't an issue specifically for this, but I figured it would be helpful to clarify some of these properties and provide examples for `Expires` since it now supports two types. Prompted by #2928 and the changes in #2932.
> docs(cookie): clarify properties and their usage

- dotenv/mod.ts
- dotenv/mod_test.ts
> feat(dotenv): support type inference based on `restrictEnvAccessTo` option

- node/http.ts
This PR tries to fix https://github.com/denoland/deno_std/issues/2944
> test(node/http): modify writable of ClientRequest

- README.md
One needs to first click in "View Documentation" before we can choose a module whose docs to view.
> Reorder steps to view documentation

- node/http.ts
This reverts commit 5f5413df9ae7bf27819f2a112250a00822e811bb.
This change was made in response to https://github.com/denoland/deno/pull/16616. However, that change was reverted in https://github.com/denoland/deno/pull/16839 due to it breaking Vite. Let's revert it here as well.
> Revert "test(node/http): modify writable of ClientRequest (#2945)"

- node/_core.ts
We dropped `core.decode` dependency in https://github.com/denoland/deno_std/pull/2897. This PR removes it as it's no longer used.
> chore(node): remove core.decode

- fs/copy_test.ts
https://github.com/denoland/deno/issues/2411 was resolved two years ago. Creating this PR to see if we can enable this test. 
Edit: We can.
> chore(fs): enable timestamp tests with copy

- node/_tools/test/parallel/test-os.js
- node/os.ts
This PR implements `os.version`. The returned value is not identical to Node.js version, but it's sufficient for passing `test-os.js` and enabling `deno run npm:next info` command.
related: https://github.com/denoland/deno/issues/16679
> feat(node): add os.version

- node/_core.ts
- node/_tools/test/parallel/test-util-types.js
- node/internal/util/types.ts
- node/internal_binding/types.ts
This PR adds `util.types.isProxy`. Currently this depends on `Deno.core` namespace, but the dependency should be removed when https://github.com/denoland/deno/pull/16872 landed
Note: util.types.isProxy is used in undici https://github.com/nodejs/undici/blob/232905f476913da9c73df03bac41a0a96d48b128/lib/fetch/webidl.js#L262
ref https://github.com/denoland/deno/issues/16710 https://github.com/denoland/deno/issues/15427#issuecomment-1329945670
> feat(node): add util.types.isProxy

- bytes/concat.ts
- bytes/copy.ts
- bytes/ends_with.ts
- bytes/includes_needle.ts
- bytes/index_of_needle.ts
- bytes/last_index_of_needle.ts
- bytes/repeat.ts
- bytes/starts_with.ts
> fix(bytes): JSDoc examples match new structure

- node/_core.ts
`std/node` is now not possible to load in Deploy. It started from https://github.com/denoland/deno_std/pull/2965
`node/_next_tick.ts` branches based on the condition `typeof core.setNextTickCallback !== "undefined"`. So `setNextTickCallback` should be `undefined` in Deploy.
The fix is manually checked as the deployment https://node-fix-next-tick.deno.dev/
> fix(node): fix nextTick shim in deploy

- encoding/_yaml/type/binary.ts
`isBinary` is called for every object that is encoded in yaml. Currently, it works by attempting to read from every object inside a generic `try {} catch {}` block, but that incurs allocation of a Buffer object and at least two Uint8Arrays in buf.readFromSync before the exception is thrown. In workloads that are heavy in yaml serialization this adds up. 
Over at https://quarto.org, the PR I'm submitting by itself improves our total running time by 10% by simply checking the types more conservatively ahead of attempting to read from the buffer.
> perf(encoding/yaml) Don't allocate buffers unnecessarily

- node/internal/buffer.mjs
Microbenchmarks show 29x improvement of decoding uint8array
```
cpu: Apple M1 Max
runtime: deno 1.28.3 (aarch64-apple-darwin)
benchmark               time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------- -----------------------------
• bench
---------------------------------------------------------- -----------------------------
buf.toString         55.06 µs/iter  (52.58 µs … 240.75 µs)  53.46 µs 105.67 µs 109.08 µs
textdecoder length     1.9 µs/iter     (1.88 µs … 2.02 µs)   1.91 µs   2.02 µs   2.02 µs
summary for bench
textdecoder length
28.92x faster than buf.toString
```
<details>
<summary>Benchmark implementation</summary>
```javascript
const buf = Buffer.from(large)
const decoder = new TextDecoder()
group({ name: …
```
> perf(node/buffer): improve utf8 decoding performance

- node/http.ts
- node/http_test.ts
This PR updates http ServerResponse class.
Currently the first chunk of server responses are buffered in the private field `#firstChunk` to add `content-type: text/plain;charset=UTF-8` automatically when the only chunk is string (only on non flash-backed implementation). This behavior is not tested anywhere and it seems only causing the issue (https://github.com/denoland/deno/issues/16929). This PR removes this buffering behavior, and now the server always responds the first chunk immediately.
closes https://github.com/denoland/deno/issues/16929
> fix(node): do not buffer first chunk

- encoding/base58.ts
- encoding/base58_test.ts
Fix base58 encoding logic
The following was filtering filter `0`s and `undefined`s because `0` is falsy in `.filter`
```
const validOutput = output.filter((item) => item ?? false);
```
> fix(encoding): base58 encoding

- _tools/check_licence.ts
Current implementation of `deno task fmt:licence-headers` adds a secondary header if the year is not correct. This PR extends the tool to update the year instead if there is a header already. 
This will be handy to create a "happy new year 🥳" PR soon.
Related: #2981
> feat(tools): auto-update copyright headers

- media_types/mod.ts
This information is just wrong. I assume that at one point this used to be `application/javascript` but it is no longer the case and should be updated.
> fix(media_types): incorrect documentation

- deno.json
- http/server.ts
- http/server_test.ts
Stream errors does not warrant closing the downstream connection. This PR prevents that.
I've added a non-regression test for the errors thrown within new `ReadableStream`s. I've tried to write one for fetch upstream streams but have failed. Any suggestion on how to write such test would be appreciated!
> fix(http): prevent downstream connections from getting closed when the response stream throws an error

- node/http.ts
- node/http_test.ts
This reverts commit eca4dbfab0a8f5ab5e80daa255c4024e76c042ce.
This commit caused performance regression in `express` server from
25k rps to 20k rps.
CC @kt3k
> Revert "fix(node/http): do not buffer first chunk (#2989)"

- http/server_test.ts
This PR fixes the test case `Server should not close the http2 downstream connection when the response stream throws` in `http/server_test.ts` for canary
After the change https://github.com/denoland/deno/pull/17126, the 3rd fetch call throws immediately (Looks like it's more ideal behavior according to the comment in the test case)
> test(http): fix test case of http2 stream error

- node/_http_outgoing.ts
- node/internal/fs/streams.mjs
- node/internal/fs/utils.mjs
- node/internal/util.mjs
- node/process.ts
- node/util.ts
- node/util_test.ts
Current implementation of `util.deprecate` depends on global `process` object and it doesn't work with `npm:` feature. (For example, `connect` from `npm:mongoose` doesn't work. See https://github.com/denoland/examples/pull/12 )
This PR fixes the above issue.
As a side effect of the fix, this PR moves the implementation of `deprecate` from `node/internal/utils.mjs` to `node/util.ts`. This was necessary for avoiding circular dependencies. (See also https://github.com/denoland/deno_std/pull/1697#discussion_r767247360
> fix(node/util): reference error of 'process'

- node/_tools/TODO.md
- node/_tools/check_circular_deps.ts
- node/_tools/list_remaining_tests.ts
- node/_tools/test/parallel/test-path-dirname.js
- node/_tools/test/parallel/test-zlib-truncated.js
This change:
- updates the `deno_graph` dep
- adds proper instructions to `TODO.md` on how to update
- runs `deno task node:setup` again causing the rest of these changes
In https://github.com/denoland/deno_std/pull/2993, `.substr` was replaced by `.slice`, even in the vendored node test code which I think probably wasn't the best idea. Running `node:setup` reverts this change incidentally.
It looks like the changes to `TODO.md` were caused by people updating it by hand instead of changing the config and just running `node:setup` (I am one of those guilty of doing this). I have added a line in `TODO.md` to remedy this.
> chore: update node tests

- flags/mod.ts
This makes the typings more readable and was also requested by @dsherret in this PR https://github.com/denoland/deno_std/pull/2180#discussion_r886863723 but I did not have the time to do this in the original PR.
> refactor(flags): use meaningful names instead of single chars for generic params

- encoding/_yaml/loader/loader.ts
- encoding/testdata/jsonc/test262/assert.js
- fmt/printf.ts
- fs/empty_dir.ts
- fs/move.ts
- node/assert.ts
Noticed a few of these while looking at codebase, and I thought it could use a refactor.
LMK if there is a reason for these but to me these just look like dubious code.
> refactor: remove unnecessary returns

- testing/_diff.ts
- testing/_diff_test.ts
Input:
```ts
import { assertEquals } from "https://deno.land/std@0.166.0/testing/asserts.ts";
assertEquals(`foo bar`, `fooo baz`);
```
Before:
```diff
-   foo bar
+   fooobaz
```
After:
```diff
-   foo bar
+   fooo baz
```
---
Input:
```ts
import { assertEquals } from "https://deno.land/std@0.166.0/testing/asserts.ts";
assertEquals(`foo bar`, `foo baz`);
```
Before/after:
```diff
-   foo bar
+   foo baz
```
> fix: Do not mutate tokens when creating details

- io/buffer.ts
- io/files.ts
- io/readers.ts
- io/util.ts
- io/writers.ts
This change simplifies how functions and types are re-exported while maintaining deprecation warnings introduced in #2975. This also fixes an issue blocking https://github.com/denoland/deno/pull/16881.
CC @bartlomieju
> refactor(io): rework single-export files

- archive/_common.ts
- archive/tar.ts
- encoding/csv/stream_test.ts
- examples/echo_server_test.ts
This change simplifies how functions and types are re-exported while maintaining deprecation warnings introduced in #2958. It also cleans up a couple of little remaining bits for single-export files in `io`.
> refactor(archive): rework single-export files

- streams/buffer.ts
- streams/conversion.ts
- streams/delimiter.ts
- streams/merge.ts
This change simplifies how functions and types are re-exported while maintaining deprecation warnings introduced in #2957.
> refactor(streams): rework single-export files

- node/http.ts
- node/http_test.ts
This solves a part of astro issues https://github.com/denoland/deno/issues/16659
Currently flash seems having an issue in handling empty chunks in ReadableStream response body (https://github.com/denoland/deno/issues/17194). This PR tries to avoid that issue by skipping enqueuing empty chunks.
> fix(node/http): avoid empty chunk issue of flash

- node/_tools/test/parallel/test-os.js
- node/os.ts
- node/os_test.ts
Dependent on https://github.com/denoland/deno/pull/17179
A part of https://github.com/denoland/deno_std/issues/1436
This will also allow for out-of-the-box support for `npm:@sentry/node`, ref: https://github.com/getsentry/sentry-javascript/issues/3009#issuecomment-1364503874
> feat(node): Add support for os.uptime

- node/http.ts
- node/http_test.ts
Currently the http server of `std/node` can't respond when the status code is one of 101, 204, 205, 304 and response body is specified. `Response` constructor throws in those cases.
(This problem seems causing the issue https://github.com/denoland/deno/issues/17142 )
This PR ignores specified body and makes body null when the status code is one of those.
closes https://github.com/denoland/deno/issues/17142
> fix(node/http): ignore body when status code is one of 101, 204, 205, 304

- path/basename_test.ts
- path/posix.ts
- path/win32.ts
The only "real" change here is marking `end = firstNonSlashEnd` when we first encounter the non-slash character. This way, if we don't match the whole suffix (which happens when using input like `a/bb`, as it contains a slash, and can never be matched), it will still trim all trailing slashes.
Fixes https://github.com/denoland/deno_std/issues/3063
> fix(path): Correctly handle trailing slashes for posix basename

- collections/binary_heap.ts
fixes https://github.com/denoland/deno_std/issues/3076
Returns the underlying cloned array in arbitrary order without sorting
> Add method toArray to Heap

- streams/text_line_stream.ts
- streams/text_line_stream_test.ts
Resolves #3075. (Alternative to #3096)
For details, see: https://github.com/denoland/deno_std/issues/3075#issue-1515492150 — quick summary:
`TextLineStream` is for breaking streams of text content into chunks of _lines_. My understanding of the conventional definition of _variable length lines_ is:
> each line is an EOL character sequence of 1+ bytes (e.g. `\n`), preceded by a character sequence of 0+ bytes containing no EOL character sequences
It seems that the class was written to expect the exception to this definition (the stream does not terminate with an EOL character sequence), and this PR updates the class to handle both cases.
> fix(streams): prevent artificial terminal newline in `TextLineStream`

- fs/expand_glob.ts
- fs/expand_glob_test.ts
https://deno.land/std@0.172.0/fs/expand_glob.ts?s=ExpandGlobOptions extends https://deno.land/std@0.172.0/path/mod.ts?s=GlobOptions which states that `globstar: boolean = true`.
Fixes https://github.com/denoland/deno_std/issues/3099
> fix(fs): Change globstar default to true for expandGlob and expandGlobSync

- collections/binary_search_tree.ts
- collections/red_black_tree.ts
Fixes #3055
Changes `removeNode` to take in a node as a parameter, without exposing the functions as public. This should allow for extending these functions for further use.
@KyleJune These are more or less what you've suggested so would appreciate your thoughts.
> feat(collections): refactored binary search tree and red black tree to remove by node

- node/module_all_test.ts
This test case detects the error like https://github.com/denoland/deno/issues/17414, and prevents similar errors
This PR will pass the CI when the current env permission error is fixed in CLI (needs another release) and STD ( https://github.com/denoland/deno_std/pull/3111 ) repos.
> test(node): prevent leak of permission requirement

- encoding/csv.ts
- encoding/csv_test.ts
Escapes CSV cells containing newlines, so that they can be displayed correctly when opened in MS Excel.
**Old behavior:**
```js
stringify([['(1)\n(2)', '(3)']], { headers: false })
// => (1)\n(2),(3)\r\n
```
**New behavior:**
```js
stringify([['(1)\n(2)', '(3)']], { headers: false })
// => "(1)\n(2)",(3)\r\n
```
Note that this PR does _not_ normalize newlines within cells, so this results in a file with plain LFs within a cell but CRLFs delimiting rows. I'd argue that this doesn't constitute inconsistent line endings, as only the end-of-row ones are really "line endings" within the context of the file. In any case, the user can normalize the text within cells however they wish, if necessary.
Note also that this doesn't resolve all MS Excel compatibility issues — for files containing …
> fix(encoding/csv): Escape cells containing newlines

- semver/format_test.ts
- semver/increment_test.ts
- semver/mod.ts
Currently the build metadata is parsed but is not printed out in any form. A semver which is parsed will not be identical to 
the printed output:
```ts
console.log(semver.parse("1.2.3+4").format()) // 1.2.3
```
Additionally, once set, there is no way to alter the metadata on the SemVer instance without formatting into a new string and re-parsing:
```ts
const build = "5";
const v0 = semver.parse("1.2.3+4").increment("pre");
const v1 = semver.parse(`${v0}+${build}`);
```
Therefore this PR attempts to address these two issues with the following APIs:
1. Add a new, optional, options object parameter onto the `.format()` function which contains a single field `style`. The style will dictate the format of the _output_ of the function, it will not affect the format internal mutated fields …
> feat(semver): Add support for build metadata

- node/internal_binding/pipe_wrap.ts
- node/internal_binding/tcp_wrap.ts
- node/internal_binding/udp_wrap.ts
- node/net_test.ts
Closes https://github.com/denoland/deno_std/issues/1396
> fix(node): throw permisison error instead of unknown error

- node/_core.ts
This change allows to only a part of `Deno.core` namespace to be available,
while still missing some APIs. This is needed for `AsyncLocalStorage` polyfill
in Deno Deploy.
> refactor(node): allow partial availability of Deno.core

- node/internal/crypto/keys.ts
- node/internal/util/comparisons.ts
- node/internal/util/types.ts
- node/internal_binding/types.ts
In accordance with the ECMAScript specification, internal slots are used for runtime type checking whenever possible.
> fix(node/util): Stricter runtime type checking

- node/worker_threads.ts
- node/worker_threads_test.ts
This is a blocker for embedding `std/node` in the Deno binary: https://github.com/denoland/deno/pull/16748
When trying to get rid of Top-Level Await we found out that this module is buggy, because it behaves differently
depending if user import `worker_threads` module inside the worker or not. Disabling it temporarily to enable 
embedding std/node in the binary. We'll revisit it after that PR lands.
> fix(node): disable worker_threads

- encoding/front_matter/mod.ts
This safely access the Deno namespace so encoding/front_matter can be used in a browser (like an interactive island in Fresh).
> fix: make encoding/front_matter work in a browser

- async/deadline.ts
> NOTE: Prefer to use `AbortSignal.timeout` instead for the APIs accept `AbortSignal`.
FYI (japanese text):
https://twitter.com/petamoriken/status/1619887604161470466
> update(async): add note to deadline

- encoding/csv/stream_test.ts
This PR re-enables the test case `[encoding/csv/stream] cancel CsvStream during iteration does not leak file` on non-windows platforms.
> test(encoding): re-enable csv stream leak test on non-windows

- encoding/csv.ts
- encoding/csv/_parser.ts
- encoding/csv_test.ts
* Adds a `bom` option to CSV `StringifyOptions`, which prepends `U+FEFF` ([BOM/byte-order mark](https://en.wikipedia.org/wiki/Byte_order_mark)) to the output
* Automatically strips leading BOM when parsing CSVs, even if `trimLeadingSpace` option is not set
This is largely for compatibility with MS Excel's handling of CSV files containing Unicode text:
* When opening a CSV file with no BOM, Excel assumes the encoding is some ANSI encoding (Windows-1252?), rather than anything sensible like UTF-8. As a result, a UTF-8 file containing `文,字\r\n` is displayed as `æ–‡ å­—`, rather than the expected `文 字`.
* When opening a CSV file with a UTF-8 BOM, Excel correctly treats it as UTF-8.
* When using "Save As", you're given multiple CSV options:
- The first is "CSV UTF-8", which adds a BOM.
- The …
> feat(encoding/csv): handle CSV byte-order marks

- node/_fs/_fs_chmod.ts
- node/_fs/_fs_chmod_test.ts
Fixes: #2916
Part of: #3149
This PR fixes an error that occurs when an invalid value is unintentionally passed to the `mode` parameter of the `chmod` and `chmodSync` functions on Windows.
This change will make `npm:fs-extra.copy()` work on Windows.
___NOTE: This change must be reverted if `Deno.chmod` and `Deno.chmodSync` were supported on Windows.___
> fix(node/fs): chmod function throws unnecessary TypeError on Windows

- node/_util/strip_color.ts
- node/assertion_error.ts
- node/internal/util/debuglog.ts
This PR replaces `std/fmt` usages in `std/node`.
part of #3171
> refactor(node): replace std/fmt usages in std/node

- node/_process/process.ts
- node/process_test.ts
This PR changes the behavior of `process.env`. Now the property access doesn't ask env permission, but works as if the env var is not set.
This reduces the number of env permission prompts when using npm modules
> fix(node): do not ask env permission from process.env access

- node/_crypto/crypto_browserify/browserify_aes/test/test.js
- node/_fs/_fs_chmod.ts
- node/_fs/_fs_chown.ts
- node/_module/cjs/test_cjs_import.js
- node/module.ts
- node/process.ts
- node/testdata/child_process_unref.js
- node/worker_threads.ts
This PR replaces `std/path` references from `std/node` with `node/path` references
part of #3171 
(Note: This reduces outside reference count from 70 to 63)
> refactor(node): replace std/path references from std/node

- node/_crypto/crypto_browserify/asn1.js/base/node.js
- node/_fs/_fs_dir.ts
- node/_fs/_fs_writeFile.ts
- node/_process/process.ts
- node/_util/asserts.ts
- node/_util/os.ts
- node/internal/child_process.ts
- node/internal/errors.ts
- node/internal/fs/utils.mjs
- node/internal_binding/cares_wrap.ts
- node/internal_binding/handle_wrap.ts
- node/internal_binding/node_file.ts
- node/internal_binding/pipe_wrap.ts
- node/internal_binding/tcp_wrap.ts
- node/internal_binding/udp_wrap.ts
- node/internal_binding/uv.ts
- node/module.ts
- node/net.ts
- node/os.ts
- node/path/glob.ts
- node/path/mod.ts
- node/path/separator.ts
- node/path/win32.ts
- node/process.ts
- node/url.ts
part of #3171 
This PR moves the references to `std/_util` to `node/_util` (by creating copies of `_util/asserts.ts` and `_util/os.ts` in `node/_util`)
(Note: this reduces the number of outside imports from `std/node` to `std` from 70 to 40.)
> refactor(node): move std/_util usages to node/_util

- encoding/_yaml/loader/loader.ts
- encoding/_yaml/parse_test.ts
Similar to #3077, try to avoid prototype pollution of the Yaml parser when running in browsers and Node.js.
Related link: Changes when preventing prototype pollution in js-yaml -> https://github.com/nodeca/js-yaml/commit/a00312147f287a1703bf6b7e104d27c8a0caacee
> fix(encoding/yaml): avoid prototype pollution in Node.js and Browser

- encoding/varint/mod.ts
- node/_fs/_fs_stat.ts
- node/internal_binding/types.ts
- node/process.ts
Fix the currently failing CI. (ref: https://github.com/denoland/deno_std/pull/3184#issuecomment-1426354288)
The cause of CI failures is that BigInt types are now reported as lint errors.(https://github.com/denoland/deno_lint/pull/1124)
This PR fixes CI by replacing BigInt with bigint.
> fix: change `BigInt` type to `bigint` type

- streams/delimiter_stream.ts
- streams/delimiter_stream_test.ts
Adds the option to include the delimiter in the output chunks, either as a suffix in the found chunk or as a prefix to the subsequent chunk. The default behavior is preserved, but can be explicitly enabled by passing `{ disposition: "discard" }`.
Let me know what you think!
> feat(streams/delimiter_stream): add disposition option

- http/file_server.ts
- http/file_server_test.ts
close #3182 
some questions:
- Now always fallback to `DENO_DEPLOYMENT_ID`. Should this be optionally configurable?
```ts
interface ServeDirOptions {
etagFallbackToDenoDeploymentId?: boolean; // default is true
}
// or
interface ServeDirOptions {
defaultEtag?: string; // default value is Deno.env.get("DENO_DEPLOYMENT_ID")
}
````
Note: This PR is not necessary if https://github.com/denoland/deploy_feedback/issues/334 is expected to be resolved soon. If so, feel free to close this.
> feat(http/file_server): etag value falls back to `DENO_DEPLOYMENT_ID` if `fileInfo.mtime` is not available

- testing/snapshot.ts
Updating snapshots works on Powershell nowadays using `-- --update` rather than `"--" --update`, so maybe this note can be cleaned up now.
I am on `deno` 1.30.3, `std` 0.177.0 and `pwsh` 7.3.2.
> chore: remove powershell note in snapshot docs

- crypto/timing_safe_equal.ts
- crypto/timing_safe_equal_test.ts
The example presented in https://github.com/denoland/deno_std/issues/3207 uses `argontwo`, which under the hood returns `Uint8Array` which memory buffer is taken directly from a WASM instance, making original `b.getUint8(i)` access out of bounds for 2nd argument to `timingSafeEqual`.
ref: https://deno.land/x/argontwo@0.1.1/wasm/mod.ts?source#L14
ref: https://deno.land/x/argontwo@0.1.1/mod.ts?source#L126
Fixes https://github.com/denoland/deno_std/issues/3207
Note#1: I use `SharedArrayBuffer` for cleaner assertions.
Note#2: changed names of 2 tests, because VS Code integration deduplicates tests with the same name.
> fix: Create DataView with correct byteLength in timingSafeEqual

- encoding/varint.ts
- encoding/varint/mod.ts
- encoding/varint_test.ts
This change replaces the Wasm implementation of `encoding/varint` with a native-TypeScript implementation ported from the [x/varint module](https://deno.land/x/varint@v2.0.0) by @keithamus.
My benchmarks show that this implementation is 2x slower than its Wasm predecessor. However, the benefit is the implementation is simpler, and a step in CI is removed.
This PR supersedes #3213.
Ref:
* https://github.com/denoland/deno_std/issues/3123#issuecomment-1437857122
* https://github.com/denoland/deno_std/pull/3213#discussion_r1115252163
> refactor(encoding/varint): deprecate Wasm implementation in favour of native TypeScript

- http/file_server.ts
- http/file_server_test.ts
When `showIndex` is true and `directory/index.html` exists, loading `http://example.com/directory` (without a final slash) can cause relative URLs in the index file to resolve against the wrong directory. This change redirects such URLs to the version ending with a slash to avoid this.
Fixes #3219.
> fix(http/file_server): Redirect directory URLs that don't end with a slash

- .github/workflows/ci.yml
Uploading coverage from Ubuntu was disabled in denoland/deno#10420 due to a panic caused by `readAll()` within `std/streams`. This change is an experiment that re-enables coverage upload.
> refactor(CI): enable ubuntu to upload coverage

- fs/ensure_dir_test.ts
- fs/ensure_file_test.ts
When I was investigating #3233, these test cases seemed incorrect, so I changed some.
The following three points have been updated.
- Changed `assertThrows()` that looks like nothing ([comment](https://github.com/denoland/deno_std/pull/3240#discussion_r1128484467))
- Use try-finally to make the directory clean up correctly
- A small test case that is useful for debugging when implementing [#3233](https://github.com/denoland/deno_std/issues/3233) has been added. (`ensureDirShouldNotSwallowErrors` and `ensureDirSyncShouldNotSwallowErrors`)
> chore(fs): Refactor the test of ensureFile and ensureDir

- encoding/_yaml/parse.ts
YAMLException doesn't exist, changed documentation to actual name.
This is a single-line change that does not substantially effect how the script runs.
> Update _yaml/parse.ts: YAMLException doesn't exist

- _tools/release/02_create_pr.ts
This fixes the release PR description which is created by create_pr script
BEFORE
AFTER
> chore(_tools): fix create_pr script

- .github/workflows/ci.yml
For the same reason that Ubuntu and Windows runner versions are pinned.
> refactor(CI): pin runner to macOS-12

- testing/asserts.ts
- testing/asserts_test.ts
- testing/mock_test.ts
Rework assertion functions to always include custom `msg` text in the failure message when `msg` is provided.
Since this change touches almost all assertion functions, I used the opportunity to improve the assertion error messages to be more consistent.
This commit also fixes `assertObjectMatch` to propagate the `msg` argument to the underlying `assertEquals()` call. (It was always ignored before this change.)
**BREAKING CHANGE:**
Assertion error messages have slightly different content now. This may break downstream consumers that depend on the exact error message strings.
Resolve https://github.com/denoland/deno_std/issues/2461
_Note: the changes are best viewed with whitespace-only changes ignored._
> feat!: include `msg` in assertion errors

- csv/_io.ts
- csv/mod.ts
- csv/stream.ts
- csv/stringify.ts
- json/mod.ts
I noticed a couple modules are missing [a summary line](https://deno.land/std@0.180.0?doc) so I added some for csv and json. I also added more docs for csv, largely based on go's encoding/csv.
> docs: add JSDoc to csv and json modules

- encoding/base58.ts
- encoding/base58_test.ts
> fix(encoding/base58): fix base58 decoding missing the first byte

- _tools/check_deprecation.ts
Update `deno_doc@0.48.0` to `deno_doc@0.59.0` so that `deno task lint:deprecations` works. Also updated to work on Windows.
> chore: update deprecation checker

- fmt/bytes.ts
Attribution to the contributor of original source was missing. ref. https://github.com/kt3k/pretty_bytes/commit/2cc05376ff87c0d374ef7073754740b6f1530a16
> chore(fmt): attribute contributor of original source

- csv/csv_stringify_stream.ts
- csv/csv_stringify_stream_test.ts
- csv/mod.ts
Closes #3258
This PR adds `CsvStringifyStream` (`std/csv/csv_stringify_stream`) to support streaming CSV records
> feat(csv): add `CsvStringifyStream`

- signal/test.ts
SIGINT is now used for special purpose in `deno test` (ref. https://github.com/denoland/deno/pull/18246 ), and we can't use it for testing of `std/signal` module. This PR removes the usages of SIGINT in testing to fix the CI status.
> test(signal): avoid using SIGINT in signal testing

- _tools/check_doc_imports.ts
This PR updates the TypeScript version in the doc import checker. Now, it matches the current TypeScript version of the CLI, v5.0.2.
> chore(_tools): update TypeScript version in doc import check

- encoding/ascii85.ts
- encoding/ascii85_test.ts
> fix(encoding/ascii85): fix `encode()` returns a wrong result with a 4-byte subarray

- testing/bdd.ts
- testing/bdd_test.ts
This PR adds `.skip()` as an alias of `.ignore()`. That alias is much more common than `.ignore()` in popular bdd-style testing APIs in other test runners.
| Test runner | Skipping APIs | 
|---|---|
| [mocha](https://github.com/mochajs/mocha) | `describe.skip()`, `it.skip()` |
| [jasmine](https://github.com/jasmine/jasmine) | `xdescribe()`, `xit()` |
| [jest](https://github.com/facebook/jest) | `describe.skip()`, `it.skip()` or `xdescribe()`, `xit()` |
| [vitest](https://vitest.dev/guide/filtering.html#skipping-suites-and-tests) | `describe.skip()`, `it.skip()` |
> feat(testing): add .skip alias to bdd test API

- http/file_server.ts
Since #3245, the default etag hash algorithm is `SHA-256` instead of `fnv1a` (because `http/etag` only supports digest algorithms available for `crypto.subtle.digest`).
This PR fixes the doc for it. Also removes the reference to `DigestAlgorithm` type from `std/crypto`.
Because of the removal of the dependency to `std/crypto` this PR reduces the file_server size from 646.44KB to 389.77KB.
> docs(http): fix default etag algorithm

- http/file_server.ts
- http/file_server_test.ts
fix #3198
Note: As commented by https://github.com/denoland/deno_std/issues/3198#issuecomment-1510884991, the problem is already fixed for most users using file_server.ts. However, users who wanted to use serveFile() by itself were still getting the wrong response. This PR fixes it.
> fix(http/file_server.ts): Respond to Range requests with correct byte length

- http/etag.ts
- http/file_server.ts
Move logic related to `DENO_DEPLOYMENT_ID` in `etag.ts` to `file_server.ts`.
This logic was originally in `file_server.ts` but was moved to etag.ts at #3245. But since this logic is mainly for file servers, wouldn't it be better to put it in `file_server.ts` rather than `etag.ts`?
> fix(http): Move deno deploy specific logic from `etag.ts` to `file_server.ts`

- csv/stream.ts
This change states when these deprecated APIs can be removed.
> chore(csv): add removal version to deprecated APIs

- dotenv/mod.ts
- dotenv/mod_test.ts
This PR improves security/privacy by allowing the user to read env data from `.env` files without granting actual environment permissions.
Continuation of [#3221 (comment)](https://github.com/denoland/deno_std/pull/3221#issuecomment-1444784865):
> Note to self and for a potential follow up PR: After refactoring the new test to be stricter, I realized that there doesn't seem to be a way to load environment variables purely from a file: without granting access to at least some actual environment variables. In my view, this seems like an oversight and could be fixed rather easily by:
> 
> * not using an empty array `[]` as the default parameter for `restrictEnvAccessTo` in most of the functions in this module, and
> * refactoring `readEnv` to interpret the case of an empty array as "allow …
> feat(dotenv): allow reading from `.env` files without granting env access

- jsonc/parse.ts
Previously, return type annotations were missing and the type `JsonValue` was duplicated.
> feat(jsonc): annotate return types

- http/server.ts
Resolves #3320 
When server.addrs[0].port is assigned to a variable, it sometimes fails because the call to `server.listenAndServe` has not finished yet, resulting in a rather unhelpful error being thrown.
Awaiting the call to `server.listenAndServe` fixes the bug.
> fix(http/server): flaky 'address in use' error

- examples/xeval_test.ts
- fmt/printf_test.ts
- testing/__snapshots__/snapshot_test.ts.snap
- testing/_format_test.ts
- testing/mock_test.ts
This PR updates the assertion of various outputs which was affected by `Deno.inspect` change in https://github.com/denoland/deno/pull/18691
> chore: update assertions following Deno.inspect change

- http/file_server.ts
Documents the default values for the `fsRoot`, `urlRoot` and `showIndex` options of `file_server`'s `serveDir` function which are currently missing in the [documentation](https://deno.land/std@0.185.0/http/file_server.ts?s=ServeDirOptions).
> docs(http): add missing default values for `ServeDir` options of `file_server`

- async/deadline.ts
- async/deadline_test.ts
As the subject suggests, I have added support for the signal parameter in the `deadline()` function. This change is useful to clean up dangling promises for tests like:
```ts
Deno.test("...", async () => {
const controller = new AbortController();
const { signal } = controller;
assertEquals(await Promise.race([
deadline(new Promise(() => {}), 100, { signal }),
Promise.resolve("Hello"),
], "Hello");
controller.abort();
});
```
Without the signal parameter, the above test fails with the following error:
```
error: Leaking async ops:
- 1 async operation to sleep for a duration was started in this test, but never completed. This is often caus
ed by not cancelling a `setTimeout` or `setInterval` call.
To get more details where ops were leaked, run again with --trace-ops flag.
```
Note that the …
> feat(async): support `signal` on `deadline()` like `delay()`

- uuid/constants.ts
- uuid/constants_test.ts
- uuid/mod.ts
- uuid/test.ts
These namespaces are useful for generating uuid v3 or v5.
Ref: https://www.ietf.org/rfc/rfc4122.html#appendix-C
> feat(uuid): add pre-defined namespace UUIDs

- .github/workflows/ci.yml
- _tools/check_doc_imports.ts
This PR uses `npm:typescript@5.0.2` instead of `https://esm.sh/typescript@5.0.2`. This change removes the dependency to `Deno.core` (`Deno.core.runMicrotasks` are used in `std@0.177.0/node` and it's in dependnecy of `https://esm.sh/typescript@5.0.2`)
closes #3337
> refactor(_tools): update check_doc_imports.ts

- http/method.ts
- http/method_test.ts
- http/mod.ts
This provides a couple of utilities to be able to safely handle common HTTP methods.
This comes from oak/oak_commons.
> feat(http): add HTTP_METHODS, HttpMethods, and isHttpMethod

- http/file_server.ts
- http/file_server_test.ts
close #3353
Current file servers' handling of the Range header is different from typical server's handling.
After verifying with google cloud storage, cloudflare, AWS cloudfront, githubusercontent.com, express lib, etc., it seems that Range requests are handled roughly in the manner shown in the table below.
These differences are causing problems like https://github.com/denoland/deploy_feedback/issues/377.
In this PR, I rewrote the handling of the Range header to behave as per spec and behave the same as a typical server.
request header | std's implementation before this PR | typical server<br>(e.g. cloud storage, cloudfront, github...) 
-- | -- | --
`range: bytes=0-10` | `🟡206 Partial Content`<br>(`content-range: bytes 0-10/100`) | `🟡206 Partial Content`<br>(`content-range: bytes …
> fix(http/file_server): fix `Range` header handling

- http/file_server.ts
- http/file_server_test.ts
part of #3361
This PR changes the `serveDir()`'s behavior so that URLs are canonicalized.
The current behavior and the behavior after the change are as follows.
request|before|after
|--|--|--|
`/path/to/directory`|`🟢200 OK`|`🟡301` redirect to `/path/to/directory/`
`/path/////to/////directory///////`|`🟢200 OK`|`🟡301` redirect to `/path/to/directory/`
`/path/////to/////file.txt`|`🟢200 OK`|`🟡301` redirect to `/path/to/file.txt`
`/path/to/file.txt/`|`🔴500 Internal Server Error`|`🟡301` redirect to `/path/to/file.txt`
`/path/////to/////file.txt/`|`🔴500 Internal Server Error`|`🟡301` redirect to `/path/to/file.txt`
`/path/////to/////file.txt/////`|`🔴500 Internal Server Error`|`🟡301` redirect to `/path/to/file.txt`
Also `serveDir()` currently has 7 nestings (`function-try-if-if-try-if-if`). I cut …
> fix(http/file_server): Redirect non-canonical URL to canonical URL

- http/file_server.ts
part of #3361
Previously, fileInfo was read serially when generating directory listing pages. Change this to read in parallel.
After this PR, the display of the directory listing (page below) is tens of milliseconds faster.
```
// When there are 100 files in the directory:
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
before     29.6 ms/iter (20.56 ms … 34.89 ms) 31.05 ms 34.89 ms 34.89 ms
after      4.27 ms/iter   (3.51 ms … 6.63 ms)  4.44 ms  5.27 ms  6.63 ms
// When there are 1000 files in the directory:
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
before …
```
> perf(http/file_server): read fileinfo in parallel

- http/file_server.ts
part of #3361
As far as I know, when this code was first introduced we had to manually set the Date header. The CLI now automatically sets the Date header, so we no longer need to manually set the Date header.
There is one more place to set the Date header ([link](https://github.com/denoland/deno_std/blob/699ba98572f28e6dfb423abe959502ba6a96c551/http/file_server.ts#L157)), but I left it that way because it seemed meaningful.
Also renamed `setBaseHeader` to `createBaseHeader` as I thought it would be more appropriate.
---
I apologize for submitting the PR all at once. Feel free to close these PRs if you don't think you need them.
> chore(http/file_server): remove unnecessary Date header generation

- http/file_server.ts
This PR refactors `http/file_server` by using `format` util from `std/fmt/bytes` and `isRedirectStatus` from `http/http_status`. Also removes a few redundant `await` keywords.
> refactor(http/file_server): use utils from std

- collections/mod.ts
- collections/partition_entries.ts
- collections/partition_entries_test.ts
The collection functions for arrays and objects are mostly in parity, such as `filter{keys,values,entries}`. However, [partition][partition] is available only for arrays.
[partition]: https://github.com/denoland/deno_std/blob/9dd2253e591d4bf2f66a4d38d75a7e60b1cb7c74/collections/partition.ts
bulk of the [code][code] and [test][test] are modified from `filterEntries`, as the only difference was not discarding entries that does not match given predicate.
[code]: https://github.com/denoland/deno_std/blob/9dd2253e591d4bf2f66a4d38d75a7e60b1cb7c74/collections/filter_entries.ts
[test]: https://github.com/denoland/deno_std/blob/9dd2253e591d4bf2f66a4d38d75a7e60b1cb7c74/collections/filter_entries_test.ts
<details><summary>Example usages</summary>
```ts
const args = {
"armor_bullet": 30,
"id": …
```
> feat(collections): add `partitionEntries`

- datetime/difference.ts
- datetime/difference_test.ts
`difference` will currently return negative months, quarters, and years, when `to` < `from`, while all other units are always non-negative.
I know [we're not doing more work on `difference`](#3086), but this is just a simple bugfix, so please consider it.
```
{
days: 730,
hours: 17520,
milliseconds: 63072000000,
minutes: 1051200,
-     months: -24,
-     quarters: -8,
+     months: 23,
+     quarters: 7,
seconds: 63072000,
weeks: 104,
-     years: -2,
+     years: 1,
}
```
> fix(datetime): negative months, quarters, and years

- http/file_server.ts
- http/file_server_test.ts
close #3141
When I launch a file server in the Windows root directory and access http://localhost:4507/, I get a 500 Internal Server Error.
It seems that the following error occurs internally. These are Windows system files that reject `Deno.stat` calls.
```
The process cannot access the file because it is being used by another process. (os error 32): stat 'C:\/DumpStack.log.tmp'
The process cannot access the file because it is being used by another process. (os error 32): stat 'C:\/hiberfil.sys'
The process cannot access the file because it is being used by another process. (os error 32): stat 'C:\/pagefile.sys'
Access is Denied. (os error 5): stat 'C:\/PerfLogs'
Access is Denied. (os error 5): stat 'C:\/Recovery'
The process cannot access the file because it is being used by another …
```
> fix(http/file_server): dealing with dir listing view that contain system files

- csv/_io.ts
- csv/csv_parse_stream.ts
I removed the `readRecord()` in `csv/_io.ts` as it is not used anywhere.
> chore(csv): remove internal dead code

- flags/mod.ts
- flags/test.ts
Fixes https://github.com/denoland/deno_std/issues/3376
> fix(flags): Correctly collect default value

- http/server_test.ts
This PR fixes the CI on main.
The cert error message of http client seems a bit changed by this change ( https://github.com/denoland/deno/pull/18499 ) in CLI repo.
> test(http): update cert error assertions

- collections/group_by.ts
- collections/group_by_test.ts
Follow up to [#1880](https://github.com/denoland/deno_std/pull/1880)
- Accept iterable inputs
- Add index param to callback
See recent changes in [tc39/proposal-array-grouping](https://github.com/tc39/proposal-array-grouping) — prototype methods have now been changed to static factory methods. This PR aims to align the `groupBy` function to the new (non-breaking) API.
> feat(collections/group_by): align to proposal

- streams/merge_readable_streams.ts
- streams/merge_readable_streams_test.ts
'try catch' must be wrapping the inner body of the async function in order to be effective. In this way not unhandle errors will be thrown
> fix(streams/mergeReadableStreams): better error handling

- collections/associate_by.ts
- collections/associate_with.ts
- collections/distinct.ts
- collections/distinct_by.ts
- collections/find_single.ts
- collections/first_not_nullish_of.ts
- collections/join_to_string.ts
- collections/map_not_nullish.ts
- collections/max_by.ts
- collections/max_of.ts
- collections/max_with.ts
- collections/min_by.ts
- collections/min_of.ts
- collections/min_with.ts
- collections/partition.ts
- collections/permutations.ts
- collections/sum_of.ts
- collections/union.ts
- collections/unzip.ts
Many functions in the standard library already work with all iterables, so the argument types should be updated to reflect that. I also made small changes with negligible performance implications to `joinToString` and `permutations` to make them support iterables.
Unrelated to the rest of the PR, I also changed `unzip` to use the `Array` length constructor instead of `Array.from` since `Array.from` is for some reason much, much slower.
> feat(collections): switch functions to take iterables when possible

- toml/stringify.ts
- toml/test.ts
Fixes the `stringify` errors in #3402
> Various edge case fixes for `toml.stringify`

- collections/sort_by.ts
- collections/sort_by_test.ts
> feat(collections/sort_by): descending order can be specified in options

- archive/tar.ts
According to this line https://github.com/denoland/deno_std/blob/0783b5a32243262cd56dcb82db6e2a546448636c/archive/tar.ts#L72 and this line https://github.com/denoland/deno_std/blob/0783b5a32243262cd56dcb82db6e2a546448636c/archive/tar.ts#L77, I find there exists a bug.
Firstly, the third argument (end index) of Uint8Array.fill is not included. See more information on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill.
Secondly, when calling Uint8Array constructor function with length argument, the contents of Uint8Array are initialized to 0.
> fix(archive/tar): implement clean function correctly

- async/retry.ts
Attempts is always one more than retries, so it is confusing talking about retries, when we have `maxAttempts` as an option.
Updated docs and error message.
Resolves #3433
> docs(async/retry): consistently talk about attempts

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
- testing/snapshot_test.ts
close https://github.com/denoland/deno_std/issues/2143
> feat(testing): report the number of removed snapshots

- testing/time.ts
- testing/time_test.ts
Using a real Date objects means that structured cloning works correctly.
Now, only the constructor is replaced, not the actual created object.
Fixes #3413
> fix(testing/time): use real Date in FakeTime

- http/file_server.ts
- http/file_server_test.ts
One goal of this commit is to avoid tripping over the 'current directory read permission' prompt from deno.
The prompt should not happen in the case when we already specified a path to the `--allow-read` argument.
This prompt can be seen when navigating to a subdir in a browser while running a deno server from Windows. This is because file_server mixed different path separators when building paths and then pass it to `Deno.stat()`. However `Deno.stat()` doesn't seem to handle it well and therefore generated the prompt.
> fix(http/file_server): resolve empty subdir correctly on Windows

- yaml/_loader/loader.ts
- yaml/parse_test.ts
In issue #3426 there's differences with how YAML parse is treating empty YAML files. Sometimes they're undefined, but if you have extra lines, you can get back null. I don't really care what value we want to put in (null, undefined, ""), but the null was already being triggered when adding a yaml file with `\n`, so that's the value I rolled with. It also makes sense to me if loadDocuments returns something, either a parsed document, empty string or null - `undefined` gives the vibe that sometimes this function returns something and sometimes nothing. At least null or "" looks intentional.
> fix(yaml): parse always return null when file is empty, whitespace or only comments

- .github/workflows/ci.yml
- .github/workflows/typos.toml
- README.md
- deno.json
This is the followup PR for #3458 to prevent accidental typos from ending up in the codebase.
>  ci: add spell-checking with typos

- json/concatenated_json_parse_stream.ts
- json/concatenated_json_parse_stream_test.ts
Hello,
I am consuming an API that uses concatenated JSON when streaming.
I came across the issue this API sent `nullnull` in the stream.
I can't really blame the API because they are clearly saying they have no separator between JSON values and null is valid for their API.
I updated the transformer to allow for `null`, `true` and `false` at top level without any separation at all.
Best regards,
Michel
> feat(json): Primitives at top level without separator

- http/file_server_test.ts
> test(http): re-enable 'serveDirIndex TLS' test on mac

- collections/deep_merge.ts
- testing/asserts.ts
- testing/asserts_test.ts
Having issues when null and undefined are passed in the 'actual' argument for `assertObjectMatch`. Typeof null is 'object', so in recursion null kept being sent as a weakmap, but should have been assigned as `filtered[key] = value`.
Primitive types also could be passed in as the 'actual' value in JS, and they gave a cryptic weakmap error, but it's just a typeerror.
I slightly disagree with the AssertionError instead of the TypeError in issue #3451, but I'm open to suggestions.
> fix: Added catches for primitive/null values passed as "actual" in assertObjectMatch

- http/mod.ts
- http/testdata/user_agent/browser-all.json
- http/testdata/user_agent/cpu-all.json
- http/testdata/user_agent/device-all.json
- http/testdata/user_agent/engine-all.json
- http/testdata/user_agent/os-all.json
- http/user_agent.ts
- http/user_agent_test.ts
This feature adds user agent parsing to `std/http`. It is heavily inspired by [ua-parser-js](https://www.npmjs.com/package/ua-parser-js) and is able to break down a user agent string into browser, OS, CPU, device, and browser engine.
For example to respond with a request with some information extracted from the user agent:
```ts
import { UserAgent } from "https://deno.land/std@$STD_VERSION/http/user_agent.ts";
import { serve } from "https://deno.land/std@$STD_VERSION/http/server.ts";
serve((req) => {
const userAgent = new UserAgent(req.headers.get("user-agent") ?? "");
return new Response(`Hello, ${userAgent.browser.name}
on ${userAgent.os.name} ${userAgent.os.version}!`);
});
```
> feat: add http/user_agent

- .github/dependabot.yml
This change automates keeping GitHub action dependencies up-to-date.
> chore(ci): add Dependabot

- .github/labeler.yml
- .github/workflows/labeler.yml
Add a GitHub action that automatically labels the PR with the names of the modules changed. Currently, it seems that PRs don't always follow the conventional commit naming convention, resulting in PR names that are not directly associated with the changed modules/code.
The action used is maintained in GitHub's actions repository and is used by ~47k repositories. The action takes ~14s and automatically sets the configured labels. You can see that it needs [`pull-requests: write`](https://github.com/actions/labeler/#permissions) permissions. There is also an option to include dot directories like `.github` if desired.
Information about other options and configurations can be found [here](https://github.com/actions/labeler/#match-object).
Recent:
- Added the labels of the `std` library …
> feat: add Pull Request auto labeler action

- msgpack/decode.ts
- msgpack/decode_test.ts
- msgpack/encode.ts
- msgpack/encode_test.ts
- msgpack/mod.ts
- msgpack/testdata/1.json
- msgpack/testdata/2.json
- msgpack/testdata/3.json
- msgpack/testdata/4.json
- msgpack/testdata/5.json
> feat: msgpack encoding

- fmt/colors.ts
Allowed for programmatic override of enable color.
When Deno is not available in global this, and we want to use the colors library in e.g. browsers without shiming (dnt), it is not possible to view colors in the console, or set it to enabled. This pr changes this behavior so that it is possible to programmatically override the enable variable.
> feat(fmt): enable `setColorEnabled` in browsers

- testing/asserts.ts
`std/testing/asserts.ts` was moved to `std/assert` not `std/asserts`.
> Fix typo in std/testing/asserts.ts deprecation message

- fs/walk_test.ts
A unix socket file is not cleaned up after testing, and it causes test failure after the 2nd run of the same test case (The issue seems introduced in #3446)
This PR adds the clean up of it, and fixes the issue.
> test(fs/walk): clean up socket file after testing

- dotenv/mod.ts
Closes #3492 
Add documentation about default .env values
> docs(dotenv): Add documentation about default .env values

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
- testing/snapshot_test.ts
Example test
```ts
Deno.test("Snapshot Test - Default serializer", async (t) => {
await assertSnapshot(t, "a\nb\tc");
});
```
Before
```
snapshot[`Snapshot Test - Default serializer 1`] = `
"a
b\\tc"
`;
```
After
```
snapshot[`Snapshot Test - Default serializer 1`] = `
"a
b	c"
`;
```
> BREAKING(testing/snapshot): change tab char serialization

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
Now the snapshots of long strings are split into additions of smaller string, and those are very hard to read as pointed in #3404. This behavior is unintentionally introduced by the merge of `Deno.inspect` and `util.inspect` (Node compat). ref: https://github.com/denoland/deno/pull/18691
This PR uses `breakLength: Infinity` option of `Deno.inspect` (which was added in https://github.com/denoland/deno/pull/19337), and restores the original behavior.
fixes #3404 
cc @oscarotero
> BREAKING(testing/snapshot): fix regression of serialization of long strings

- toml/_parser.ts
- toml/test.ts
- toml/testdata/arrays.toml
- toml/testdata/inlineTable.toml
This PR fixes the two remaining cases described in #3402.
Specifically:
`toml.parse("a = [0.1]")`:
Previously:
`Uncaught Error: Parse error on line 1, column 6: Array is not closed`
Now:
`{"a":[0.1]}`
And...
`toml.parse("a = {}")`:
Previously:
`Uncaught Error: Parse error on line 1, column 5: Invalid token after "{"`
Expected:
`{"a": {}}`
Tests have been added for both fixes.
Closes #3402.
> fix(toml/parse): Fix edge cases

- media_types/parse_media_type.ts
In the `parseMediaType` example from `std/media_types/parse_media_type.ts`, the example code asserts (erroneously) that an input of `text/html; charset=utf-8` will return `["application/json", { charset: "utf-8" }]`. 
This has been corrected to `["text/html", { charset: "utf-8" }]`.
Thanks!
> fix: typo in parse_media_type.ts example

- assert/assert_object_match.ts
Seems like a new version of canary caught this. I'm a fan of the change.
> chore: fix fmt error

- collections/mod.ts
> fix(collections): redblack tree and bst not being exported from mod

- http/cookie_map.ts
- http/cookie_map_test.ts
Adds `maxAge` to the `CookieMapSetDeleteOptions` and `SecureCookieMapSetDeleteOptions`, so the interface matches the implementation. Closes #3523.
I added a test to make sure `maxAge` keeps working, since there wasn't one. The option gets converted to `expires`, so I needed to mock the time with `FakeTime`.
> fix(http/cookie_map): Add maxAge to set/delete options

- dotenv/mod_test.ts
- fs/copy.ts
- fs/empty_dir.ts
- fs/ensure_file.ts
- fs/ensure_link.ts
- fs/ensure_symlink.ts
- fs/expand_glob.ts
- fs/walk.ts
- http/file_server.ts
- http/server.ts
- json/concatenated_json_parse_stream_test.ts
- testing/mock.ts
- testing/snapshot.ts
- testing/time.ts
- wasi/snapshot_preview1.ts
This PR changes a few internal imports to point to single-export files instead of their corresponding `mod.ts` files. As a result, the total size of `http/file_server.ts` and its dependencies is reduced by about 12%.
```shellsession
$ deno info https://deno.land/std@0.198.0/http/file_server.ts
…
dependencies: 57 unique
size: 367.76KB
…
$ deno info ./http/file_server.ts
…
dependencies: 34 unique
size: 323.66KB
…
```
> chore: repoint internal imports to single-export files

- fs/walk.ts
When I looked at the [WalkOptions](https://deno.land/std@0.198.0/fs/walk.ts?s=WalkOptions) documentation, I noticed that there is no description of each property. So, this PR adds JSDoc comments to each property of `WalkOptions`.
> docs(fs/walk): add descriptions to `WalkOptions`'s properties

- testing/time.ts
- testing/time_test.ts
Fixed `FakeTime.restoreFor` to atomically restore and re-override `globalThis.setTimeout` etc.
This also fixes `FakeTime.prototype.delay` and `FakeTime.prototype.runMicrotasks` and others.
Of course, we don't get atomicity when an async function is specified to `restoreFor`.
However, `FakeTime.prototype.delay` that uses an non-async function will be fixed.
Example of `runMicrotasks` (that calls `delay` that calls `restoreFor`):
```ts
import { FakeTime } from "./testing/time.ts";
const testTarget = async() => {
console.log(1, setTimeout);
await Promise.resolve();
console.log(2, setTimeout);
await Promise.resolve();
console.log(3, setTimeout);
};
const time = new FakeTime();
const promise = testTarget(); // no await, microtask is queued
time.runMicrotasks();
await promise; // already …
```
> fix(testing/time): fix FakeTime.restoreFor accuracy for sync callbacks

- examples/xeval_test.ts
> test(examples/xeval): re-enable `xevalCliSyntaxError` test case

- log/logger.ts
- log/logger_test.ts
Another approach to fix #3547
While my brief implementation in original issue and #3548 represent bigint value as quoted string, this PR serializes value without quotes.
Since this is my first PR submitting to deno, I hope I'm doing right to follow community guidelines😅
> fix(log): fix serializing BigInt value in object

- dotenv/mod.ts
While looking at #3492 it was clear that the documentation for dotenv module was incomplete.  This PR attempts to address this by including all options, capabilities and files associated with the dotenv module.
Note, for `restrictEnvAccessTo`, I was very unclear as to the purpose of this.  No matter what I tried, this option did nothing.  Either this is a bug or I'm using it incorrectly.  I've copied the docs for this option verbatim but they are not clear and should be revisited.
> doc: add complete docs for all dotenv functionality

- dotenv/mod.ts
The current description of the `restrictEnvAccessTo` is confusing and potentially misleading.  This PR attempts to simplify the description.
Example of behaviour:
```sh
#.env
HELLO=world
SOME=${A}
THING=${B}
```
```ts
//main.ts
import {load} from https://deno.land/std@0.199.0/dotenv/mod.ts
const env1 = await load({ restrictEnvAccessTo: ['A'] });  //.env only has access to A
console.log(env1);
const env2 = await load(); //.env has access to both A and B
console.log(env2);
```
and invoke with:
```sh
A=1 B=2 deno run -A main.ts
```
the output is:
```sh
{ HELLO: "world", SOME: "1", THING: "undefined" }
{ HELLO: "world", SOME: "1", THING: "2" }
```
> doc: improve dotenv config option description

- permissions/mod.ts
> BREAKING(permissions): deprecate permissions module

- signal/mod.ts
> BREAKING(signal): deprecate signal module

- .github/workflows/ci.yml
- _tools/check_circular_submodule_dependencies.ts
- deno.json
This PR adds a tool for checking circular dependencies between std sub-modules.
```
$ deno task lint:circular
Task lint:circular deno run --allow-env --allow-read ./_tools/check_circular_submodule_dependencies.ts
34 submodules checked.
No circular dependencies found.
```
Optionally (with `--graph` option) the tool can output graphviz graph source code. Which can be rendered like the below with graphviz cli
> chore(_tools): check dependencies between submodules

- assert/assert_is_error.ts
- assert/assert_is_error_test.ts
Currently messages will look like
- `expected X but got "["howdy", 2]"` instead of
- `expected X but got "[\"howdy\", 2]"`
Its misleading, but also inconvenient since often its nice to copy out the `instead got` and use it to fix the test case.
> Properly quote/escape strings in assertIsError

- yaml/_type/binary.ts
- yaml/parse_test.ts
- yaml/stringify_test.ts
Currently `yaml` module parses `!!binary "..BASE64.."` notation to `Buffer` class, and serializes `Buffer` (or any object with `readSync` method) to `!!binary "..BASE64.."` notation.
This PR replaces `Buffer` in the above usage with `Uint8Array`. I think this makes more sense in JavaScript.
Also this change is necessary to remove the dependency to `std/io` from `std/yaml`. We're going to deprecate `std/io` soon. This change is necessary for stabilizing `yaml` in the future.
closes #3585
> BREAKING(yaml): change binary handling

- fmt/colors.ts
> BREAKING(fmt): rename stripColor to stripAnsiCode

- archive/_common.ts
- archive/mod.ts
- archive/tar.ts
- archive/untar.ts
std/archive needs some TLC.  This is the first in a series of improvements to this module.  Specifically, this PR adds or improves documentation and makes cosmetic code changes primarily for readability.
> [std/archive] Improve docs and general code cleanup

- bytes/bytes_list.ts
- msgpack/encode.ts
- streams/_common.ts
- streams/delimiter_stream.ts
- streams/delimiter_stream_test.ts
As part of std cleanup, this PR deprecates the `BytesList` class and suggests plain `Uint8Array[]` usage instead. The two non-deprecated users of this class are also transformed to use a plain `Uint8Array[]`.
These are:
1. msgpack: Here the transformation is trivial and the `bytes/concat` function can be utilized directly.
2. DelimiterStream: Here the transformation is very much nontrivial.
Switching to a plain Array based approach made quite a few optimisations more directly "visible" in the stream implementation. These are in no particular order:
1. The generally expected case is that a chunk will include a delimiter. It's generally thus the case that the list of previous chunks is relatively short, and that at the end of a chunk's iteration all previous chunks will usually have been …
> feat(bytes): Deprecate BytesList class

- json/concatenated_json_parse_stream_test.ts
This PR fixes the expectation of the error message from `ConcatenatedJsonParseStream`. This is affected by V8 upgrade in canary https://github.com/denoland/deno/pull/20333
> test(json): fix expectation of ConcatenatedJsonParseStream test

- msgpack/decode_test.ts
- msgpack/encode_test.ts
Not sure how these slipped through the last removal PR. Maybe `msgpack` was originally written before deprecation and merged right after these were removed from the rest of std?
> chore(msgpack): get rid of testing/asserts usage

- crypto/crypto.ts
- crypto/timing_safe_equal.ts
> BREAKING(crypto): deprecate crypto.subtle.timingSafeEqual()

- fmt/colors.ts
I run into this while debugging a windows terminal app
A quick search on github shows that it seems to be the erase character sequence https://github.com/search?q=ESC%5B%23X&type=code
> feat(stripAnsiCode): escape erase character

- csv/parse.ts
These items are part of error messages, and are not useful for the users. Also these are not documented, and the users don't know how to use them.
part of #3489
> BREAKING(csv): deprecate error message exports

- streams/delimiter_stream.ts
- streams/delimiter_stream_test.ts
Two regressions appeared in the recent DelimiterStream refactoring:
1. #3609 The pushing of chunk remnants was off by one, which would mean that if an incoming chunk's last byte was the first byte to be pushed out into an outgoing chunk then that byte would accidentally be left out.
2. Unreported issue but related to the first that appeared once it was fixed was that if an incoming chunk started with a separator then the chunk starting pointer was not properly moved forward.
A regression test was added testing for these two errors.
closes #3609
> Fix(streams): DelimiterStream regression

- _tools/check_circular_submodule_dependencies.ts
This PR updates dependency graph generator tool. Now `deno task lint:circular --graph` generates the below graph (rendered by graphviz):
white/double-circle - ready (for stabilization)
yellow/circle - needs clean up
pink/box - not ready
gray/polygon - deprecated
> chore(_tools): update dependency graph output

- assert/assert_false.ts
That JSDoc should belong to `function assertFalse` but not `type Falsy`.
> fix(assert/assert_false): Fix incorrect JSDoc placement

- http/server_test.ts
This PR updates `http/server_test.ts`. Now we use different port number for each test case.
This should reduce the possibility of rare test failure in linux with the error message `AddrInUse: Address already in use (os error 98)` (ex https://github.com/denoland/deno_std/actions/runs/6067720722/job/16459754435 )
> test(http): reduce http server test flakiness

- datetime/to_imf.ts
I know we're planning on deprecating the whole module but this one is especially not useful.
> BREAKING(datetime): deprecate to_imf.ts

- .github/workflows/ci.yml
- _tools/check_deprecation.ts
- _tools/check_doc_imports.ts
- deno.json
This PR fixes the below type errors in `_tools`. Currently scripts in `_tools` are not type-checked because they are not imported from any test cases. This PR also adds the type check task for them and run it in CI.
- `semver.increment(ver: string)` is now type error since #3591 (`_tools/check_deprecation.ts`)
- There are type errors in `_tools/check_doc_imports.ts` introduced in https://github.com/denoland/deno_std/pull/3351
> chore(_tools): fix type errors in `_tools`

- testing/time.ts
- testing/time_test.ts
Fix `FakeTime.next()` and `nextAsync()` to return `false` if all timers are cleared.
The document for `FakeTime.next()` says:
```
Advances time to when the next scheduled timer is due.
If there are no pending timers, time will not be changed.
Returns true when there is a scheduled timer and false when there is not.
```
However, if the timer is cleared before calling `next()`, it will return true even if there is no scheduled timer.
```typescript
import { FakeTime } from "https://deno.land/std@0.201.0/testing/time.ts";
const time = new FakeTime();
const start = time.now;
const id = setTimeout(() => {}, 1000);
clearTimeout(id);
const hasNext = time.next();
console.log(hasNext); // true, but expected false
console.log(time.now - start); // 1000, but expected 0
```
> fix(testing/time): fix FakeTime.next to return false if all timers are cleared

- streams/copy.ts
- streams/iterate_reader.ts
- streams/read_all.ts
- streams/readable_stream_from_reader.ts
- streams/reader_from_iterable.ts
- streams/reader_from_stream_reader.ts
- streams/writable_stream_from_writer.ts
- streams/write_all.ts
- streams/writer_from_stream_writer.ts
This PR deprecates the APIs which are based on legacy Reader and Writer interfaces. closes #3551 
part of #3489
> BREAKING(streams): deprecate APIs based on legacy Reader/Writer interfaces

- encoding/hex.ts
- encoding/hex_test.ts
`encode`, `decode` of `hex` has inconvenient signatures (and also inconsistent with other `encode` `decode`).
This PR adds `encodeHex` and `decodeHex` APIs which are more aligned to other `encode`/`decode` APIs and also ergonomic for most usages.
This PR also prepares for the deprecation of `toHashString` of `std/crypto` in #3630 
closes #3605
> feat(encoding): add encodeHex, decodeHex

- front_matter/any.ts
- front_matter/json.ts
- front_matter/toml.ts
- front_matter/yaml.ts
This PR deprecates default export items from `front_matter`. In deno std, we usually don't use default exports except these 4 (and also `wasi/snapshot_preview1.ts`).
This aligns `front_matter` design to other modules.
part of #3601 #3489
> BREAKING(front_matter): deprecate default exports

- testing/bdd_examples/user_flat_test.ts
- testing/bdd_examples/user_mixed_test.ts
- testing/bdd_examples/user_nested_test.ts
- testing/bdd_examples/user_test.ts
- testing/bdd_test.ts
- testing/mock_examples/internals_injection_test.ts
- testing/mock_examples/parameter_injection_test.ts
- testing/mock_examples/random_test.ts
- testing/mock_test.ts
- testing/snapshot_test.ts
- testing/time_test.ts
The test files under `testing/` still use deprecated `testing/asserts.ts`. This PR fixes it.
> test(testing): use assert/mod.ts instead of testing/asserts.ts

- collections/aggregate_groups.ts
- collections/aggregate_groups_test.ts
- collections/reduce_groups.ts
- collections/reduce_groups_test.ts
- collections/zip.ts
- collections/zip_test.ts
Most methods in std/collections accept readonly arrays (as none of the methods mutate the input), but these 3 were the exception. Updated types to allow readonly arrays as input.
Additionally added docs for the generic types, since the single letter names can be difficult to read.
> Accept readonly arrays in aggregateGroups, reduceGroups, zip

- http/file_server_test.ts
- streams/merge_readable_streams.ts
- streams/zip_readable_streams.ts
Small change to avoid using numbers that are converted to strings then converted back to numbers.
`mergeReadableStreams` and `zipReadableStreams` both used `Object.entries(array)`, which turned the array indexes into strings. Using `array.entries()` instead lets us stick with numbers the whole time. `zipReadableStreams` can additionally just use a set instead of working with indexes at all.
file_server_test used `port?: string` as its config type instead of `port?: number`, which also required coersion.
> Avoid internally using strings for numbers

- datetime/_common.ts
- datetime/format_test.ts
I found that a Date object in the midnight hour will be formatted as `0:xx` in a `hmm` date time format.
Deno's [datetime.format documentation](https://deno.land/std@0.202.0/datetime/mod.ts) for `h`/`hh` says this should be from 1-12, as does the underlying [Unicode specification](https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-hour).
> fix(datetime): Correctly format midnight in 12-hour time

- fmt/duration.ts
Fix spelling error in `millisecondsToDurationObject()` function JSDoc.
> chore(fmt): fix spelling of 'milliseconds'

- encoding/hex.ts
I realized that these were not deprecated in the last PR. Maybe an oversight? Might have missed something.
> BREAKING(encoding): deprecate old encode/decode in hex.ts

- .github/workflows/ci.yml
- datetime/day_of_year.ts
`dayOfYear` result looks wrong when the timezone has the daylight saving time, and the start of year and the given date have different timezone offsets.
This PR fixes the issue by adjusting the diff calculation using timezone offset values.
closes #3659 
closes #3571
> fix(datetime): fix dayOfYear when the timezone has DST

- encoding/base64url.ts
Reasons for potential speed improvement:
- Fewer String Parses: In the original function, the string is parsed three times due to three replace calls. In the new function, the string is parsed at most twice using replace, and even this is optimized using quick endsWith checks.
- Optimized Checks for '=': The new function uses the endsWith method, which is optimized for checking the end of a string and is faster than scanning the entire string as in the replace method.
- Slice Over Replace: The new function uses slice to remove trailing '=' characters. slice is generally faster for such operations since it simply involves adjusting a pointer/reference to the string start/end, whereas replace would have to parse through the string.
also, this operation is safe because is a base64 where `=` …
> perf base64url

- assert/_diff.ts
- assert/_diff_test.ts
This PR fixes the bug of multiline str diff when there are more diff lines in `actual` than `expected`.
The multiline diff algorithm ([`diffstr`](https://github.com/denoland/deno_std/blob/4fe9fd6d3910589a6fbae2f5063981d3510c965a/assert/_diff.ts#L250)) performs diffing in 2 different ways: First it takes diff of the entire multiple string, comparing each line. Then it takes diff of words for each line over the combination of added (`expected`) lines and removed (`actual`) lines.
When computing word diffs for each line combination, the code swaps [the main array](https://github.com/denoland/deno_std/blob/4fe9fd6d3910589a6fbae2f5063981d3510c965a/assert/_diff.ts#L345) to use for the loop (probably for optimization), but it forgot to swap [diffing …
> fix(assert): fix swapping of multiline str diff

- front_matter/any.ts
- front_matter/json.ts
- front_matter/toml.ts
- front_matter/yaml.ts
This PR deprecates language specific `test` functions. This PR makes front_matter module aligned to single-export pattern together with #3653 #3641 
part of #3601 #3489
> BREAKING(front_matter): deprecate language-specific `test` functions

- crypto/crypto_test.ts
@iuioiua proposed a change in #3687 that looked sensible, but would have broken our re-exporting of native WebCrypto methods in the `crypto` module. Unfortunately, that this regression was not caught by our existing tests, because they only cover methods where we added new logic, not cases where we were just re-exporting native methods. I explained in more detail at https://github.com/denoland/deno_std/pull/3687#issuecomment-1752240642.
This PR just adds a one-line test to ensure that we can call one such method successfully. I'm not sure whether more thorough tests for those methods would be warranted or not, but this a small addition that would have caught the regression, so it's probably worth having this at least.
> test(crypto): add regression test for re-export of native crypto.getRandomValues()

- csv/csv_parse_stream_test.ts
This reduces the possibility of flakiness of the test case `[csv/csv_parse_stream] cancel CsvParseStream during iteration does not leak file`.
closes #3694 
closes #3160
> test(csv): add workaround delay to reduce flakiness

- crypto/crypto.ts
> docs(crypto): remove use of deprecated `toHashString()`

- csv/csv_parse_stream_test.ts
Removed the use of `readableStreamFromReader` and `StringReader` in csv stream parse tests since they are deprecated.
See #3718
> chore: remove `readableStreamFromReader()` & `StringReader()` in CSV stream test

- http/file_server_test.ts
> chore(http): remove `iterateReader()` from `file_server_test.ts`

- io/read_delim.ts
Removed use of deprecated `BytesList` in `readDelim` in favour of  `Uint8Array`.
See #3718
> chore: remove deprecated `BytesList()` in `readDelim()`

- media_types/content_type.ts
Replaced call to deprecated `typeByExtension` in `content_type.ts` in favour of private `typeByExtension` function.
See #3718 
Not sure if this is what you were looking for. Seems odd to deprecate typeByExtension when it is needed by content type and would need to be reimplemented for content type when removed.
> chore: replace deprecated `typeByExtension()` in `content_type.ts`

- .github/workflows/ci.yml
- .gitignore
- deno.json
This will make analysing test coverage locally easier and align local coverage-related processes with CI. I'll elaborate on how they work in a follow-up PR that improves the CONTRIBUTING.md file.
> chore: add `cov:*` tasks

- wasi/snapshot_preview1.ts
After a discussion with @kt3k, there appears to be nearly no interest or development in this module. Best it be removed.
> BREAKING: deprecate `std/wasi`

- path/basename_test.ts
- path/common_test.ts
- path/dirname_test.ts
- path/extname_test.ts
- path/from_file_url_test.ts
- path/glob_test.ts
- path/is_absolute_test.ts
- path/join_test.ts
- path/parse_format_test.ts
- path/relative_test.ts
- path/resolve_test.ts
- path/to_file_url_test.ts
- path/zero_length_strings_test.ts
I added `posix` and `win32` as prefixes to the function name (for example ` posix.toFileUrl()`).
Question: lots of tests do not have a description. Most of these would repeat the information in the function name. Do all tests need a description?
> refactor(path): format  test names

- http/server_test.ts
This should fix the current CI issue.
> fix: add `[Symbol.dispose]()` to `MockListener()`

- fs/copy_test.ts
- fs/empty_dir_test.ts
- fs/ensure_link_test.ts
- fs/move_test.ts
- http/file_server_test.ts
While looking at the failing HTTP tests, I realised these should be cleaned up.
> chore: use `Deno.readTextFile()` and `Deno.writeTextFile()` in tests

- testing/mock.ts
- testing/mock_test.ts
I encounter a situation where I have to create a wrapper class for `Deno.Command` to spy/mock its constructor, but it is not consistent with the mocking API provided by `std/testing/mock.ts`, which is awkward to me.
So this PR proposes enabling `spy` function to accept a class constructor as an argument, so that we can create a spy instance for a class constructor in the same manner as for a regular function.
This shouldn't be a breaking change, but does include some internal API changes. I didn't find a clean way to incorporate two types of spies in a single interface `Spy`, so I created a new `ConstructorSpy` interface, which is returned when you call `spy` on a constructor.
It is the first time for me to create a PR to this repository, so please kindly notice me if I miss something.
> feat(testing/mock): enable `spy` to accept a class constructor

- http/file_server_test.ts
This will make the diff easier to follow when transitioning to using `serveDir()` directly.
Towards #3770 and #3754
> chore(http): fix file server test names

- fmt/duration.ts
- fmt/duration_test.ts
this works-around rounding errors in `millisecondsToDurationObject()` of `std/fmt/duration.ts` by converting values in milliseconds or less into as string and use `String.slice()`. 
use-case: I get durations like `16.342` millis when I round my values to microseconds.
`main`:
```ts
> import { format } from "https://deno.land/std@0.204.0/fmt/duration.ts";
> format(16.342, { ignoreZero: true })
"16ms 341µs 999ns"
```
`hastebrot/fix-duration-format-rounding-error`:
```ts
Deno.test({
name: "format duration rounding error",
fn() {
assertEquals(format(16.342, { ignoreZero: true }), "16ms 342µs");
},
});
```
TODO:
related to #3672
> fix(fmt): format duration rounding error.

- http/file_server_test.ts
This change fixes HTTP file server flakiness by using `serveDir()` directly instead of starting a new process and making `fetch()` requests. This increases the ergonomics, simplicity and stability of these tests. Other cleanups were also included. These tests also complete faster, as a bonus.
Closes #3770
Towards #3718
> fix: rework file server tests

- async/abortable.ts
- async/abortable_test.ts
- async/mux_async_iterator.ts
- http/server_test.ts
- signal/mod.ts
- streams/merge_readable_streams.ts
`deferred()` from `std/async` is now deprecated.
Towards #3718
> refactor: remove use of `deferred()`

- http/server_sent_event.ts
- http/unstable_server_sent_event.ts
In favour of `ServerSentEventStream()` introduced in #3751.
> BREAKING(http): deprecate `ServerSentEvent()`

- path/glob.ts
This PR fixes a `@deprecated` comment so that `isGlob` is imported from [`std/path/is_glob.ts`](https://deno.land/std@0.206.0/path/is_glob.ts) instead of [`std/path/windows/is_glob.ts`](https://deno.land/std@0.206.0/path/windows/is_glob.ts).
> docs(path): fix `@deprecated` note for `isGlob()`

- http/file_server_test.ts
The main CI looks failing because of the op leak in `serveDir() traverses path` test case with canary Deno CLI. This PR fixes it.
> test(http): fix op leak in file_server_test

- fs/eol.ts
The `EOL` enum will be replaced by an OS-dependent constant in 0.209.0.
Closes #3583
Towards #3782
> BREAKING(fs): deprecate `EOL` enum

- .github/labeler.yml
- .github/workflows/typos.toml
- README.md
This cleans up some remnants of the `std/wasi` deprecation and removal, some of which had to happen after the actual removal.
> chore: cleanup after removal of `std/wasi`

- collections/binary_heap.ts
- collections/binary_search_node.ts
- collections/binary_search_tree.ts
- collections/red_black_node.ts
- collections/red_black_tree.ts
This updates the deprecation notices within `std/collections` with links to new documentation and aligns the removal versions to all be 0.209.0. Previously, some were to be removed in 0.207.0 and others in 0.209.0.
> chore(collections): improve deprecation notices

- collections/max_by.ts
- collections/max_of.ts
- collections/min_by.ts
- collections/min_of.ts
- collections/partition.ts
- collections/sort_by.ts
- collections/zip.ts
This refactor combines multiple function overloads within `std/collections`. The functions are now easier to understand, and the documentation required for this module has been reduced.
More functions can be cleaned up in follow-up PRs.
Towards #3764
> refactor(collections): unify function overloads

- collections/max_by.ts
- collections/max_of.ts
- collections/min_by.ts
- collections/min_of.ts
- collections/partition.ts
- collections/sort_by.ts
- collections/zip.ts
#3818 removed overloads from several functions, but they seemed useful. Now these functions accept selectors of mixed return types such as `maxBy(arr, (item) => item === null ? 10 : "foo")` and what happens with these calls are not obvious (also not documented). I think we shouldn't allow these calls.
This PR instead documents all overloads of these functions towards #3764
> docs(collection): document overloads (revert #3818)

- .github/dependabot.yml
This aims to automate keeping Rust dependencies for `std/crypto/_wasm` up-to-date.
> chore: configure dependabot for `std/crypto`

- .gitignore
- datetime/week_of_year.ts
This PR replaces the used typescript enum in the `datetime` module with a 
as `const object` as requested [here](https://github.com/denoland/deno_std/issues/3782)
As this enum is only used internally, merging this change wouldn't constitute a
breaking change.
History:
- chore(root): ignore .tool-versions
- feat(datetime): replace enum with const object
> refactor(datetime): replace enum with object

- jsonc/parse.ts
This PR replaces the used typescript enum in the `jsonc` module with a
`const object` as requested  [here](https://github.com/denoland/deno_std/issues/3782).
As this enum is only used internally, merging this change wouldn't constitute a
breaking change.
This change seems a little bit clunky but does the trick.
> refactor(jsonc): replace `enum` with string union type

- console/_rle_test.ts
Related issue https://github.com/denoland/deno_std/issues/3713
- add `runLengthEncode()` test
- add `runLengthDecode()` test
https://app.codecov.io/gh/denoland/deno_std/commit/145c81a3c648f8c0d108f1517536cdfc0f487522/indirect-changes
> chore(console): improve console test coverage

- assert/_diff.ts
Refers to this [issue](https://github.com/denoland/deno_std/issues/3782)
This change is internal only. The changed `DiffType` was solely exported to facilitate tests in `_diff_test.ts`.
> refactor(assert): replace DiffTypeEnum with const object

- fs/eol.ts
- fs/eol_test.ts
This was deprecated in favour of a plain JS object.
> BREAKIING(fs): remove `EOL` enum, add OS-dependent `EOL`

- http/status.ts
This moves the removal version of the `Status` enum back to match the deletion of the `http/http_status.ts` file. Otherwise, the `Status` enum will get removed before the `http_status.ts` file is deleted.
> docs(http): fix `Status` enum deprecation notice

- log/handlers_test.ts
- log/levels.ts
- log/logger.ts
- log/mod.ts
- log/test.ts
References this [issue](https://github.com/denoland/deno_std/issues/3782) and is the successor of this [PR](https://github.com/denoland/deno_std/pull/3838)
- feat(log): replaced LogLevels enum with object and enforced stricter types
- feat(log): updated types
- chore(log): updated types in tests
- chore(log): retain bimap for const object and add deprecation notices
- refactor(log): added deprecation notices and hardened level setter
- feat(log): added LogLevel to module API
- chore(log): removed unnecessary type casts in tests
> deprecate(log): remove enums and add deprecation notices

- .github/dependabot.yml
Currently, Dependabot opens a new PR for each dependency update available. This change makes Dependabot open only one PR for any available updates, reducing maintenance.
Reference https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#example-2
> chore: group Dependabot PRs

- media_types/content_type.ts
- media_types/mod.ts
- media_types/type_by_extension.ts
- media_types/type_by_extension_test.ts
And undoes the deprecation.
Reverts denoland/deno_std#3848
See https://github.com/denoland/deno_std/issues/3616#issuecomment-1830404615
> Revert "BREAKING(media_types): remove `typeByExtension()`"

- cli/prompt_secret.ts
The function is similar to `prompt`, but it prints the user's input as `*` to prevent the password from being shown.
Sometimes, I find the need for this type of function when creating CLI applications, so I decided to implement it. I'm not certain whether it should be included in the standard library, as it's somewhat challenging to test since it hooks into stdin. Therefore, I couldn't provide tests (or please let me know if there is a way).
Please inform me if this function shouldn't be included in the standard library, and I'll develop it as a third-party module. :+1:
> feat(cli): `promptSecret()`

- async/abortable.ts
- async/deadline.ts
- async/delay.ts
- async/mux_async_iterator.ts
- async/pool.ts
- async/retry.ts
- async/tee.ts
I'm a little unsure of some of the wording I chose, particularly with `MuxAsyncIterator`. Minor cleanups and inconsistency fixes have also been included.
Towards #3880
Towards #3764
> chore(async): complete documentation

- ulid/_util.ts
- ulid/mod.ts
> chore(ulid): complete documentation

- async/_util.ts
- async/_util_test.ts
- async/retry.ts
- async/retry_test.ts
The function comes from an internal file, so the underscore prefix in the function name isn't needed. I've also moved the test to `_util_test.ts` to be more direct.
> chore(async): `exponentialBackoffWithJitter()` tweaks

- .gitignore
- http/file_server_test.ts
See https://github.com/denoland/deno_std/pull/3882#pullrequestreview-1758729944
> chore(http): add test for file containing space in name

- streams/buffer.ts
- streams/byte_slice_stream.ts
- streams/copy.ts
- streams/delimiter_stream.ts
- streams/early_zip_readable_streams.ts
- streams/iterate_reader.ts
- streams/limited_bytes_transform_stream.ts
- streams/limited_transform_stream.ts
- streams/merge_readable_streams.ts
- streams/read_all.ts
- streams/readable_stream_from_reader.ts
- streams/reader_from_iterable.ts
- streams/reader_from_stream_reader.ts
- streams/text_delimiter_stream.ts
- streams/text_line_stream.ts
- streams/to_array_buffer.ts
- streams/to_blob.ts
- streams/to_json.ts
- streams/to_text.ts
- streams/to_transform_stream.ts
- streams/writable_stream_from_writer.ts
- streams/write_all.ts
- streams/writer_from_stream_writer.ts
- streams/zip_readable_streams.ts
Do note that a couple of changes for deprecated APIs were made just to make the linter happy.
Towards #3878
Towards #3764
> chore(streams): complete documentation

- fs/_util.ts
- fs/copy.ts
- fs/ensure_file.ts
- fs/eol.ts
- fs/exists.ts
- fs/expand_glob.ts
- fs/move.ts
- fs/walk.ts
- path/_common/glob_to_reg_exp.ts
Note: some `void` and `Promise<void>` return types have been declared. This is a bug in the `deno_doc` version in the stable version of the runtime. It was fixed in https://github.com/denoland/deno_doc/pull/405 which will be included in the next release of the runtime.
Towards #3764 and #3878.
> chore(fs): complete documentation

- io/types.d.ts
- types.d.ts
To be clear, `/types.d.ts` is being deprecated in favour of `/io/types.d.ts` with a removal version of 0.211.0. `/io/types.d.ts` is being deprecated in favour of the Web Streams API. It's being done this way to minimise breaking changes and allow code to still use `/io/types.d.ts` until its removal in 1.0.0.
This change assumes that `Deno.*` IO interfaces and methods will be removed in Deno v2 and Std. Lib. v1, at the same time.
See https://github.com/denoland/deno/pull/21465
> deprecation(io): IO types in favour of Web Streams API

- assert/_format_test.ts
- assert/assert_equals_test.ts
- assert/assert_is_error.ts
- console/unicode_width.ts
- expect/_format_test.ts
- fmt/colors_test.ts
- testing/snapshot.ts
- testing/snapshot_test.ts
`stripColor()` is now deprecated in favour of `stripAnsiCode()`.
> chore(fmt): replace `stripColor()` use with `stripAnsiCode()`

- assert/assert.ts
- assert/assert_almost_equals.ts
- assert/assert_array_includes.ts
- assert/assert_equals.ts
- assert/assert_exists.ts
- assert/assert_false.ts
- assert/assert_greater.ts
- assert/assert_greater_or_equal.ts
- assert/assert_instance_of.ts
- assert/assert_is_error.ts
- assert/assert_less.ts
- assert/assert_less_or_equal.ts
- assert/assert_match.ts
- assert/assert_not_equals.ts
- assert/assert_not_instance_of.ts
- assert/assert_not_match.ts
- assert/assert_not_strict_equals.ts
- assert/assert_object_match.ts
- assert/assert_rejects.ts
- assert/assert_strict_equals.ts
- assert/assert_string_includes.ts
- assert/assert_throws.ts
- assert/assertion_error.ts
- assert/equal.ts
- assert/fail.ts
- assert/unimplemented.ts
- assert/unreachable.ts
> chore(assert): complete documentation

- fs/expand_glob_test.ts
Fixes the failures we're seeing here: https://github.com/denoland/deno_std/actions/runs/7122896293/job/19394638369?pr=3905
> test(fs): fix `expandGlob()` test assertion

- assert/assert_array_includes.ts
- assert/assert_array_includes_test.ts
Fixes https://github.com/denoland/deno_std/issues/3372
> fix(assert): disallow scalar string args in `assertArrayIncludes()`

- assert/assert_array_includes.ts
Resolves https://github.com/denoland/deno_std/pull/3910#discussion_r1420087019
/cc @kt3k
> fix(assert): export parameter type alias for `assertArrayIncludes()`

- fs/_util.ts
Towards fixing #3915. We could also split internal utilities into one file per function. But if we do that here, we'd have to do that in other sub-modules too. WDYT, @kt3k?
> refactor(fs): trim internal dependencies

- toml/_parser.ts
- toml/parse_test.ts
> fix(toml): handle CRLF as newline in parsing multiline string

- front_matter/_formats.ts
Removing in v1 seems like overkill. The deprecation shouldn't be too disruptive, and removing it earlier allows the `front_matter` to be cleaned up sooner alongside the cleanups in #3930.
> deprecation(front_matter): move `Format` enum deprecation forward

- text/closest_string.ts
- text/closest_string_test.ts
Currently `closestString` always returns the first element of the given `possibleWords`. This PR fixes it to choose closest string using levenshtein distance.
```js
import { closestString } from "https://deno.land/std@0.208.0/text/mod.ts";
console.log(closestString("a", ["b", "a"])); // this currently prints b
```
> fix(text): fix closestString

- assert/assert_is_error.ts
- assert/assert_is_error_test.ts
- expect/_matchers.ts
- expect/_to_throw_test.ts
- expect/expect.ts
I'm attempting to support deno testing in valibot: https://github.com/fabian-hiller/valibot/pull/179 and currently trying to swap out the vitest expect for the new deno_std expect, but I came across an unsupported feature.
Currently the parameter for toThrow only supports an Error constructor, this PR also lets you pass a string, RegExp, or Error instance.
Excerpt from the Jest Expect documentation https://jestjs.io/docs/expect#tothrowerror
> You can provide an optional argument to test that a specific error is thrown:
> 
> - regular expression: error message matches the pattern
> - string: error message includes the substring
> - error object: error message is equal to the message property of the object
> - error class: error object is instance of class
> 
> For example, let's say that …
> feat(expect): support message checks in expect().toThrow

- encoding/ascii85.ts
- encoding/base32.ts
- encoding/base58.ts
- encoding/base64.ts
- encoding/base64url.ts
- encoding/hex.ts
> docs(encoding): complete documentation

- cli/mod.ts
This PR adds re-export of `promptSecret` from mod.ts
ref https://github.com/denoland/deno_std/pull/3777
> fix(cli): re-export promptSecret from mod.ts

- http/cookie_map.ts
- http/unstable_cookie_map.ts
Closes #3942
Prerequisite #3905
> chore(http): deprecate `CookieMap()`

- semver/_shared.ts
- semver/parse.ts
- semver/parse_comparator.ts
- semver/parse_range.ts
removes unnecessary regexp array storage in favour of direct regexp exports.
> chore(semver): remove regexp array

- semver/can_parse.ts
- semver/format_test.ts
- semver/parse.ts
- semver/range_min_test.ts
deprecates SemVer as argument type for `parse` and `canParse`.
> deprecation(semver): deprecate `SemVer` argument for `parse()` and `canParse()`

- streams/to_blob.ts
It's faster just to use `Response.blob()`. This also makes the argument more stricter by only allowing `Uint8Array`s, which the previous implementation implied. Inspired by talks in #3894.
Benchmark source code:
```ts
import { toBlob } from "https://deno.land/std@0.208.0/streams/mod.ts";
Deno.bench("toBlob()", { group: "blob" }, async () => {
const stream = ReadableStream.from([
new Uint8Array([1, 2, 3, 4, 5]),
new Uint8Array([6, 7]),
new Uint8Array([8, 9]),
]);
await toBlob(stream);
});
Deno.bench("Response.blob()", { group: "blob", baseline: true }, async () => {
const stream = ReadableStream.from([
new Uint8Array([1, 2, 3, 4, 5]),
new Uint8Array([6, 7]),
new Uint8Array([8, 9]),
]);
await new Response(stream).blob();
});
```
Benchmark results:
```
cpu: Apple M2
runtime: deno 1.38.5 …
```
> perf(streams): make `toBlob()` 20-30% faster

- README.md
Correct compatibility of different versions of the Deno Standard Library and the Deno CLI
> docs: update `versions.json` URL in `README.md`

- encoding/_util_test.ts
- encoding/ascii85_test.ts
- encoding/base32_test.ts
- encoding/base64url_test.ts
- encoding/varint_test.ts
Related: #3713
`_util.ts`
- For object with empty prototype.
`ascii85.ts`
- When decoding with default `standard` option.
`base32.ts`
- For `byteLength` function.
- When encoding a very long text.
`base64url.ts`
- When decoding illegal base64url strings.
`varint.ts`
- When encoding overflow uint64.
See: https://app.codecov.io/gh/denoland/deno_std/pull/3971/indirect-changes
> chore(encoding): improve test coverage

- path/extname.ts
`windowsExtname` should import from `./windows/extname.ts` but not `./posix/extname.ts`.
> fix(path/extname): Fix incorrect import

- semver/parse_range.ts
Renames `isX()` to `isWildcard()` for more clarity, because a wildcard can also be "" or "*".
> refactor(semver): rename isX to isWildcard

- log/formatters.ts
- log/formatters_test.ts
- log/handlers.ts
- log/mod.ts
Implementing a solution for this issue: https://github.com/denoland/deno_std/issues/3394
**What is it?**
Lets you configure the logger to emit structured json logs that will play nicely with log aggregators
**Why do it?**
People like structured json logs:
- https://stackify.com/what-is-structured-logging-and-why-developers-need-it/
- https://sematext.com/glossary/structured-logging/
- https://www.loggly.com/use-cases/what-is-structured-logging-and-how-to-use-it/
TLDR; Easier parsing makes it more reliable, cheap, and fast to gain insight into your logs, whether thats for monitoring, root cause analysis, or business intelligence.
**What does it look like?**
```ts
import * as log from "https://deno.land/std@$STD_VERSION/log/mod.ts";
log.setup({
handlers: {
default: new …
```
> feat(log): Added support for structured JSON logging

- archive/tar_test.ts
- archive/untar_test.ts
> refactor(archive): format test names

- crypto/_fnv/util_test.ts
- crypto/crypto_test.ts
- crypto/timing_safe_equal_test.ts
- crypto/unstable_keystack_test.ts
> refactor(crypto): format test names

- semver/_shared.ts
- semver/parse_range.ts
Replaces `replace()` functions with `match()` and uses groups for more readability.
> chore(semver): replace `replace()` with `match()` capturing groups 

- encoding/base32.ts
> deprecation(encoding): deprecate `base32.byteLength()`

- dotenv/load_test.ts
- dotenv/mod_test.ts
- dotenv/parse_test.ts
- dotenv/stringify_test.ts
> refactor(dotenv): format test names

- uuid/constants_test.ts
- uuid/test.ts
- uuid/v1_test.ts
- uuid/v3_test.ts
- uuid/v4_test.ts
- uuid/v5_test.ts
Ref: #3713, #3754
This PR updates the test names as well as improving the test coverage in `uuid`.
See: https://app.codecov.io/gh/denoland/deno_std/pull/4002/tree/uuid
> refactor(uuid): format test names and improve test coverage 

- deno.json
Previously, everything in `coverage/` was going through the formatter, linter, etc. Now, it doesn't.
> chore: ignore `coverage/` for formatting, linting, etc.

- signal/mod.ts
This change moves the removal version of `std/signal` from v1 to v0.212.0.
This is being done as there's little usage of the sub-module and most likely not to be too impacting.
This will help clean up technical debt sooner.
> deprecation(signal): move deprecation forward

- cli/spinner.ts
Ref: https://github.com/denoland/deno_std/pull/3968
I saw this new feature in the [release notes for 0.210.0](https://github.com/denoland/deno_std/releases/tag/0.210.0) and noticed that there's no way to access the `Color` type alias which is used by the public options property at `SpinnerOptions.color`. This exports that union and one of its members which was also still private.
https://github.com/denoland/deno_std/blob/5ddf32a1eaeb04ce55d2680e32cac19e4dd8a8ca/cli/spinner.ts#L41-L58
https://github.com/denoland/deno_std/blob/5ddf32a1eaeb04ce55d2680e32cac19e4dd8a8ca/cli/spinner.ts#L13-L27
> fix(cli/spinner): export private type aliases used in public API

- bytes/last_index_of_needle.ts
- http/unstable_cookie_map.ts
- io/slice_long_to_bytes.ts
- log/handlers.ts
- log/mod.ts
- path/common.ts
- path/posix/common.ts
- path/windows/common.ts
- streams/byte_slice_stream.ts
- yaml/schema/core.ts
- yaml/schema/default.ts
- yaml/schema/extended.ts
- yaml/schema/failsafe.ts
- yaml/schema/json.ts
This will further help with deno doc output.
> chore: add more explicit types

- jsonc/parse_test.ts
This PR tries to fix flaky test failure of `[jsonc] use Object.defineProperty when setting object property` case.
The test case sometimes fails with the below error message:
```
------- output -------
error: Unable to parse contents of lockfile. /home/runner/work/deno_std/deno_std/deno.lock
./jsonc/parse_test.ts => [jsonc] use Object.defineProperty when setting object property ...----- output end -----
./jsonc/parse_test.ts => [jsonc] use Object.defineProperty when setting object property ... FAILED (7ms)
```
https://github.com/denoland/deno_std/actions/runs/7292878535/job/19874783040
The command doesn't need to use lock file. So we can avoid the above flaky failure by passing `--no-lock` flag.
closes #4015
> test(jsonc): do not use deno.lock in subcommand

- fs/empty_dir_test.ts
The test case sometimes fails at line 237, but the root cause of the test failure is not shown in the log. This PR prints more info about the error to enable further debugging.
> chore(fs): log more information about test failure

- log/handlers.ts
Attempting to solve https://github.com/denoland/deno_std/issues/3907
> std/log is the last of the sub-modules that uses the deprecated Writer (i.e. Deno.Writer) interface. It should use WritableStream instead.
Previous attempt of https://github.com/denoland/deno_std/pull/3969 was trying to use `std/streams/buffer.ts` and the streams API, but moving to async flushes resulted in potentially lost logs.
Now just solving with a `Uint8Array` and a `ArrayBuffer` and a number pointer.
> chore(log): rework `std/log` to work without deprecated `Deno.Writer`

- semver/reverse_sort.ts
- semver/reverse_sort_test.ts
- semver/rsort.ts
renames `rsort` to `reverseSort`.
> deprecation(semver): rename rsort to reverseSort

- semver/cmp.ts
deprecates `cmp`, because one can achieve the same with `compare` and operators or `eq`, `neq` etc. `cmp` even uses them internally.
> deprecation(semver): deprecate cmp

- expect/_matchers.ts
- expect/_to_strict_equal_test.ts
This PR changes the behavior of `expect().toStrictEqual()` to make it aligned to jest's. This has been pointed in https://github.com/denoland/deno_std/issues/3947#issuecomment-1870858120
> fix(expect): align toStrictEqual behavior to jest

- semver/test_comparator.ts
deprecates `testComparator` in favour of using `compare`.
> deprecation(semver): deprecate `testComparator()`

- expect/_matchers.ts
- expect/_to_equal_test.ts
This PR updates `expect().toEqual()` behavior. Now the difference of `undefined`-valued keys are ignored in objects.
closes #3947
> fix(expect): align toEqual to jest

- log/mod.ts
Handling all noUncheckedIndexedAccess issues for the log module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(log): prepare for `noUncheckedIndexedAccess`

- media_types/_util.ts
- media_types/format_media_type.ts
- media_types/parse_media_type.ts
Handling all noUncheckedIndexedAccess issues for the media_types module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(media_types): prepare for `noUncheckedIndexedAccess`

- uuid/mod.ts
- uuid/v1.ts
- uuid/v3.ts
> docs(uuid): complete documentation

- semver/_shared.ts
- semver/parse_range.ts
- updates comments in `_shared` and add examples in jsdoc
- renames `MAIN_VERSION` to `VERSION_CORE` (according to semver bnf)
- renames `FULL_PLAIN` to `FULL_VERSION` (according to semver bnf)
- renames `XRANGE_PLAIN` to `XRANGE`
> refactor(semver): update internal variables and comments

- semver/format.ts
- semver/types.ts
ref: https://github.com/denoland/deno_std/pull/3962#issuecomment-1864389806
- deprecates `format()` `style` argument as it is obsolete due to optional `SemVer` properties
> deprecation(semver): deprecate `format()` `style` argument

- crypto/keystack.ts
`KeyStack()` is available in `crypto/unstable_keystack.ts`.
> BREAKING(crypto): remove stable `KeyStack()`

- semver/range_max.ts
- removes obsolete `undefined` from `rangeMax()` return type
> fix(semver): remove `undefined` return type from `rangeMax()`

- testing/bdd_test.ts
- testing/mock.ts
- testing/mock_test.ts
- testing/time_test.ts
Handling all noUncheckedIndexedAccess issues for the testing module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(testing): prepare for `noUncheckedIndexedAccess`

- log/logger.ts
- removes obsolete `Log.handler` property getter and setter and make `#handler` property public.
> refactor(log): remove obsolete `Log.handler` property getter and setter

- semver/sort.ts
- deprecates `sort()`, which just calls `.sort(compare)` on the array. 
**Note**: This is not discussed but seemed obvious. The User should rather import `compare()` and call sort directly on the array.
> deprecation(semver): deprecate `sort()`

- .gitignore
- _tools/check_deprecation.ts
- deno.json
This change ensures the `/docs` directory is ignored in appropriate checks, etc. This is so nothing is ever accidentally committed when working with `deno doc --html`.
> chore: ignore `/docs` folder

- async/mux_async_iterator.ts
- data_structures/binary_search_tree.ts
Handling all noUncheckedIndexedAccess issues for the async module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(async): prepare for `noUncheckedIndexedAccess`

- bytes/equals_test.ts
Handling all noUncheckedIndexedAccess issues for the bytes module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(bytes): prepare for `noUncheckedIndexedAccess`

- testing/asserts.ts
This seems to be the best way to make the linter and type checker happy and have deprecated symbols highlighted in the editor.
Fixes #4027
Fixes #4116
> docs(testing): fix assertion deprecation notices

- assert/assert_almost_equals.ts
- assert/assert_array_includes.ts
- assert/assert_equals.ts
- assert/assert_greater.ts
- assert/assert_greater_or_equal.ts
- assert/assert_less.ts
- assert/assert_less_or_equal.ts
- assert/assert_not_equals.ts
- assert/assert_not_strict_equals.ts
- assert/assert_object_match.ts
Deno sees `void` return types are unncessary boilerplate.
> refactor(assert): remove `void` return types

- http/unstable_cookie_map.ts
This is so `cookie_map.ts` and `unstable_cookie_map.ts` can be removed at the same time. This should prevent any confusion that would otherwise arise from both files being removed at different times.
> fix(http): punt removal version of `unstable_cookie_map.ts`

- async/retry.ts
Resolves #4129
1. Run `deno doc --html --name=std/async async/mod.ts`
2. Open `docs/index.html`
I confirmed that the rendering issue reported in #4129 has been resolved.
> docs(async): fix doc of `retry.ts` #4129

- fs/ensure_dir.ts
- fs/ensure_file_test.ts
Another attempt to solve #3339. (ref. #4008)
This PR updates `ensureDir` behavior. It now first checks the lstat of the path, then tries `mkdir`, then catches `AlreadyExists` error and checks the lstat of the path again. This reduces the permission requirement to the given dir to only `read` permission when the path already exists (currently `write` is always required), and also doesn't fail with concurrent calls (doesn't re-introduce #3233).
closes #3339 
closes #3233
> fix(fs): reduce perm requirement of `ensureDir()`

- semver/comparator_format.ts
- semver/comparator_intersects.ts
- semver/comparator_max.ts
- semver/comparator_min.ts
- semver/is_comparator.ts
- semver/parse_comparator.ts
- semver/test_comparator.ts
- semver/try_parse_comparator.ts
ref: https://github.com/denoland/deno_std/issues/4047
This PR deprecates all public `Comparator` functions.
**Note**: Some of these functions are used in range functions, which means they should be made private (for example `is_comparator.ts` -> `_is_comparator.ts`) after the deprecation deadline or combined into one `_comparator.ts` file.
> deprecation(semver): deprecate `Comparator` functions

- console/unicode_width.ts
- html/_tools/generate_data.ts
- html/entities.ts
- html/entities_test.ts
- http/user_agent_test.ts
Fixes lint errors on canary: https://github.com/denoland/deno_std/actions/runs/7472961212/job/20336165920?pr=4121
See https://github.com/denoland/deno_lint/pull/1209
> fix: use `with` keyword for import attributes

- README.md
It looks like the formatting applied in
33c09251bee9cb78fd2896f1c8160140df2436c8 introduced a typo. This commit removes it.
> docs: fix typo in versions link

- data_structures/binary_heap.ts
- data_structures/binary_heap_test.ts
- data_structures/binary_search_tree.ts
- data_structures/binary_search_tree_test.ts
- data_structures/red_black_tree_test.ts
Handling all noUncheckedIndexedAccess issues for the data_structures module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(data_structures): prepare for `noUncheckedIndexedAccess`

- ulid/_util.ts
Handling all noUncheckedIndexedAccess issues for the ulid module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(ulid): prepare for `noUncheckedIndexedAccess`

- text/_util.ts
- text/closest_string.ts
- text/levenshtein_distance.ts
Handling all noUncheckedIndexedAccess issues for the text module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(text): prepare for `noUncheckedIndexedAccess`

- jsonc/parse.ts
Handling all noUncheckedIndexedAccess issues for the jsonc module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(jsonc): prepare for `noUncheckedIndexedAccess`

- json/concatenated_json_parse_stream.ts
Handling all noUncheckedIndexedAccess issues for the json module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(json): prepare for `noUncheckedIndexedAccess`

- expect/_matchers.ts
- expect/_to_have_been_nth_called_with_test.ts
Handling all noUncheckedIndexedAccess issues for the expect module, tracked in https://github.com/denoland/deno_std/issues/4040
Looks like toHaveBeenNthCalledWith failure case was checking with the wrong variable, I'll call out where I've updated it to now check the correct variable.
> refactor(expect): prepare for `noUncheckedIndexedAccess`

- csv/_io.ts
- csv/csv_parse_stream.ts
- csv/csv_stringify_stream.ts
- csv/mod.ts
- csv/parse.ts
- csv/stringify.ts
> docs(csv): complete documentation

- fmt/bytes.ts
- fmt/colors.ts
- fmt/duration.ts
Towards #3764 and #3878
`fmt/colors.ts` could probably do with further polish in the future. But the current state is good enough to make the doc linter happy.
> docs(fmt): complete documentation

- _tools/check_browser_compat.ts
- crypto/crypto_test.ts
- dotenv/load_test.ts
- dotenv/mod_test.ts
- fs/empty_dir_test.ts
- fs/ensure_file_test.ts
- http/file_server_test.ts
- http/server_test.ts
- ini/parse_test.ts
- testing/snapshot_test.ts
- yaml/parse_test.ts
I noticed that tests containing spawned processes that use the Deno binary tend to be flaky. There have been a few instances in the past that these processes fail because the runtime is unable to parse the contents of the lockfile. I.e. race condition.
This fix adds the `--no-lock` CLI flag to all such instances. Hopefully, we'll see a noticable reduction in test flakiness in CI.
> fix: add `--no-lock` to spawned process args in tests

- jsonc/parse.ts
> docs(jsonc): complete documentation

- semver/parse.ts
- semver/range_min_test.ts
> BREAKING(semver): remove `parse(semver: string)` overload

- semver/format.ts
- semver/format_test.ts
- semver/types.ts
> BREAKING(semver): remove `FormatStyle`

- log/base_handler.ts
- log/handlers_test.ts
This change makes all `std/log` handlers disposable.
See https://github.com/tc39/proposal-explicit-resource-management
> feat(log): make handlers disposable

- archive/tar.ts
- archive/tar_test.ts
- archive/untar.ts
- archive/untar_test.ts
- io/limited_reader_test.ts
- io/multi_reader_test.ts
- io/string_writer.ts
- io/string_writer_test.ts
- streams/iterate_reader.ts
- streams/read_all.ts
- streams/reader_from_iterable.ts
- streams/reader_from_stream_reader.ts
- streams/reader_from_stream_reader_test.ts
- streams/writable_stream_from_writer.ts
- streams/write_all.ts
- streams/writer_from_stream_writer.ts
Various cleanups that we previously missed.
> refactor: cleanup deprecated-related APIs in `std/io` and `std/streams`

- expect/_matchers.ts
- expect/_to_match_object_test.ts
- expect/expect.ts
Fix https://github.com/denoland/deno_std/issues/4190
> fix(expect): fix the function signature of `toMatchObject()`

- README.md
Previously, we referred to this as the "single-export files" pattern. I think it makes more sense to use the term "minimal-export files".
See https://github.com/denoland/deno_std/issues/4174#issuecomment-1888435091
> docs: add "Minimal Exports" explainer

- flags/mod.ts
Fixes #4203
Normally, we'd call `parseArgs()` within `parse()`. However, `parseArgs()` is so complex with all its type arguments, one cannot simply do so. I figured the next best thing to do is copy the entire `std/cli/parse_args.ts` implementation. I did this instead of reverting to the old `std/flags` code, as the new code has minor tweaks that enable the `noUncheckedIndexedAccess` compiler option.
> fix(flags): correct deprecation notices

- fmt/colors.ts
This change fixes how `stripColor()`'s signature is documented by calling `stripAnsiCode()` within it.
Before:
After:
> fix(fmt): correct `stripColor()` deprecation notice

- toml/_parser.ts
- toml/parse_test.ts
- toml/test.ts
- toml/testdata/string.toml
> test(toml): improve test coverage

- streams/reader_from_iterable.ts
As `Deno.metrics()` is deprecated.
Towards #4216
> docs(streams): remove `Deno.metrics()` use in example

- toml/stringify.ts
towards https://github.com/denoland/deno_std/issues/3764
> docs(toml): complete documentation

- internal/warn_on_deprecated_api.ts
- internal/warn_on_deprecated_api_test.ts
To align it with the runtime. See https://github.com/denoland/deno/pull/21939#discussion_r1462640212
> refactor: remove environment variable functionality notice in `warnOnDeprecatedApi()`

- collections/map_values.ts
- collections/map_values_test.ts
Pass `key` parameter to `mapValues()` transformer to support transformed values that depends on `key`.
> feat(collections): pass `key` to `mapValues()` transformer

- cli/prompt_secret.ts
~~This will fail in stable until Deno 1.40 is released.~~
Oh yeah. We don't test this function.
Towards #4216
> refactor: use `Deno.stdin.isTerminal()`

- webgpu/_test_util.ts
> refactor(webgpu): use internal `Deno.close()` for cleanup of WebGPU resources

- collections/mod.ts
- crypto/crypto.ts
- encoding/ascii85.ts
- encoding/base32.ts
- encoding/base58.ts
- encoding/base64.ts
- encoding/base64url.ts
- encoding/hex.ts
- io/buf_reader.ts
- io/buf_writer.ts
- io/copy_n.ts
- io/limited_reader.ts
- io/multi_reader.ts
- io/read_delim.ts
- io/read_int.ts
- io/read_lines.ts
- io/read_long.ts
- io/read_range.ts
- io/read_short.ts
- io/read_string_delim.ts
- io/slice_long_to_bytes.ts
- io/string_reader.ts
- io/string_writer.ts
- permissions/mod.ts
- ulid/mod.ts
- webgpu/mod.ts
I have changed `{@link}` syntax from `[text]{@link namepathOrURL}` to `{@link namepathOrURL | text}` to fix broken hyperlinks.
Inspired by #4167, #4169, #4209,...
> docs: fix broken `{@link}` hyperlinks

- assert/equal.ts
- assert/equal_test.ts
- expect/_assert_equals.ts
- expect/_assert_equals_test.ts
- expect/_assert_not_equals.ts
- expect/_assert_not_equals_test.ts
- expect/_constants.ts
- expect/_diff.ts
- expect/_diff_test.ts
- expect/_equal.ts
- expect/_equal_test.ts
- expect/_matchers.ts
- expect/_to_be_test.ts
- expect/_to_equal_test.ts
- expect/_to_strict_equal_test.ts
- expect/_types.ts
> fix(expect): align `toEqual` to jest

- expect/_equal.ts
- expect/_to_equal_test.ts
This pr is to solved #4221, which is missed from the previous PR.
> fix(expect): add Error object equal check.

- io/buf_reader.ts
I think this deprecation notice is unnecessary because all APIs in `buf_reader.ts` have already been marked deprecated.
Fix: #4249
Ref: #3556
> docs(io): fix `io` module is marked deprecated

- cli/parse_args.ts
- crypto/mod.ts
- crypto/timing_safe_equal.ts
- crypto/unstable_keystack.ts
- csv/stringify.ts
- dotenv/mod.ts
- expect/mod.ts
- flags/mod.ts
- front_matter/mod.ts
- fs/walk.ts
- http/cookie.ts
- http/mod.ts
- ini/mod.ts
- io/buffer.ts
- json/json_parse_stream.ts
- json/json_stringify_stream.ts
- media_types/mod.ts
- semver/mod.ts
- streams/buffer.ts
- streams/mod.ts
- testing/bdd.ts
- toml/mod.ts
- yaml/mod.ts
> docs: replace markdown hyperlink syntax with `{@link}` tag where necessary.

- semver/comparator_format.ts
- semver/comparator_intersects.ts
- semver/comparator_max.ts
- semver/comparator_min.ts
- semver/eq.ts
- semver/gt.ts
- semver/gte.ts
- semver/is_comparator.ts
- semver/lt.ts
- semver/lte.ts
- semver/neq.ts
- semver/parse_comparator.ts
- semver/range_format.ts
- semver/sort.ts
- semver/test_comparator.ts
- semver/try_parse_comparator.ts
This change postpones `std/semver` deprecations to 0.215.0. This allows all the removals to happen simultaneously, making the removals easier to apply, and allows a little more time for those needing to make changes to their code.
This also unblocks the 0.214.0 release.
> deprecation(semver): postpone removals to 0.215.0

- dotenv/mod.ts
- dotenv/parse.ts
- dotenv/parse_test.ts
> refactcor(dotenv): prepare for `noUncheckedIndexedAccess`

- log/base_handler_test.ts
- log/console_handler.ts
- log/file_handler_test.ts
- log/levels.ts
- log/logger.ts
- log/logger_test.ts
- log/mod.ts
- log/mod_test.ts
- log/rotating_file_handler_test.ts
- log/test.ts
- log/warn.ts
Users should use the `WARN` log level and `warn()` instead.
Deprecations were made in #4170 and #4117.
Original proposal in #4099.
CC @timreichen
> BREAKING(log): remove `WARNING` log level

- semver/eq.ts
- semver/gt.ts
- semver/gte.ts
- semver/is_semver_range.ts
- semver/lt.ts
- semver/lte.ts
- semver/neq.ts
- semver/outside.ts
- semver/types.ts
This change postpones the removal version of the following APIs from 0.215.0 to 0.216.0: `eq()`, `gt()`, `gte()`, `neq()`, `lt()`, `lte()`, `SemVerRange` and `isSemVerRange()`.
A removal version of 0.215.0 is too early, considering they were deprecated in 0.213.0.
CC @timreichen
> chore(semver): postpone removal versions of some APIs

- semver/comparator_intersects.ts
- semver/comparator_min.ts
- semver/constants.ts
- semver/gtr.ts
- semver/ltr.ts
- semver/max_satisfying.ts
- semver/min_satisfying.ts
- semver/outside.ts
- semver/range_max.ts
- semver/range_min.ts
- semver/range_min_test.ts
- semver/test_comparator.ts
- semver/test_range.ts
This change removes the internal use of the deprecated `eq()`, `lt()`, `lte()`, `neq()`, `gt()` and `gte()` functions.
This will make the future removal PR cleaner.
> refactor(semver): cleanup comparison functions

- collections/drop_last_while.ts
- collections/drop_while.ts
- collections/filter_keys.ts
- collections/map_keys.ts
- collections/map_keys_test.ts
- collections/permutations.ts
- collections/sort_by.ts
- collections/take_last_while.ts
- collections/take_while.ts
> refactor(collections): prepare for `noUncheckedIndexedAccess`

- .github/workflows/workspace_publish.yml
This updates `workspace publish` workflow. Now the workflow is triggered by the push of tags, which should trigger `Publish (real)` step in it
> chore: publish workspace on tag push

- async/debounce.ts
> docs(async): use `Array.fromAsync()` in `debounce()` example

- semver/reverse_sort.ts
Deprecates `reverseSort()` function
This function seems like a really special user case and trivial by using `compare()`.
ref: https://github.com/denoland/deno_std/issues/3948
> deprecation(semver): deprecate `reverseSort()`

- datetime/_common.ts
- datetime/format.ts
- datetime/format_test.ts
> feat(datetime): `format()` options

- fmt/colors.ts
> docs(fmt/colors): warn that `dim` is incompatible accross terminals

- semver/_comparator_intersects.ts
- semver/_comparator_max.ts
- semver/_comparator_min.ts
- semver/range_max.ts
- semver/range_min.ts
- semver/test_range.ts
This refactors `comparatorMin()` and `comparatorMax()` args so they take a `Comparator` instead of two separate args.
> refactor(semver): simplify args for `comparatorMin()` and `comparatorMax()`

- semver/mod.ts
This PR removes the outdated document about `includePrerelease` option which was deprecated in #3385 and removed in #3591.
> docs(semver): remove obsolete docs

- semver/compare.ts
This PR fixes the arg names in jsdoc of `compare`. Currently the jsdoc and the function signature use different names for arguments, and they look confusing.
This change makes the following change in VS Code overlay view.
BEFORE
AFTER
> docs(semver): fix arg names in jsdoc

- http/_negotiation/encoding.ts
- http/_negotiation/language.ts
- http/_negotiation/media_type.ts
- http/cookie.ts
- http/file_server.ts
- http/server_test.ts
- http/user_agent.ts
> refactor(http): prepare for `noUncheckedIndexedAccess`

- path/mod.ts
Just the "path/" missing in the link...
> doc: fix `std/path/posix` link

- semver/reverse_sort.ts
This PR suggests to move the removal version of `reverseSort` to `after 0.217.0` to align it to other items (By this change, the users are exposed to the breaking changes less often. That will cause less frictions to the existing users of semver)
> chore(semver): align removal version of reverseSort to others

- _tools/convert_to_workspace.ts
Fixes https://github.com/denoland/deno/issues/22434
Fixes #4341
> fix(http): `version` from `deno.json` import

- media_types/extensions_by_type.ts
The function `extensionsByType` has conflicting information in its JSDoc comment on whether or not the returned extensions have a leading `.` in their names. They do not, in fact, have a leading dot. This PR updates the docs to accurately reflect that.
> docs(media_types): fix erroneous docs in extensions_by_type.ts

- io/mod.ts
- io/reader_from_stream_reader.ts
- io/reader_from_stream_reader_test.ts
- streams/reader_from_stream_reader.ts
This change un-deprecates `readerFromStreamReader()` and moves it from `std/streams` to `std/io`.
Closes #4336
> feat(io): un-deprecate `readerFromStreamReader()`

- media_types/extensions_by_type.ts
- media_types/extensions_by_type_test.ts
`extensionsByTypes` always returns `undefined` when imported from `media_types/extensions_by_type_test.ts`.
This PR fixes it by importing `_db.ts` (`_db.ts` sets values in `extensions` Map object when imported).
> fix(media_types): load extensions when directly importing `extensionsByTypes()`

- semver/_parse_comparator.ts
- semver/parse.ts
- semver/parse_range.ts
- semver/range_intersects.ts
> refactor(semver): prepare for `noUncheckedIndexedAccess`

- .github/workflows/workspace_publish.yml
Also avoids an unnecessary warning being printed in the terminal.
> chore(_tools): remove unneeded `--unstable` flag

- crypto/crypto_test.ts
- crypto/testdata/digest_large_inputs.ts
- crypto/testdata/digest_many_calls.ts
Fixes test cases in #4346 for `crypto/crypto_test.ts`. I can confirm that these tests pass after running the migration script.
These tests were previously failing because the migration script didn't factor in the inline code.
> chore(crypto): move test scripts to own files

- http/file_server_test.ts
Adding `--config deno.json` seems to be needed for these tests to complete successfully after running the workspaces migration script. Shouldn't `deno.json` be automatically detected and loaded? This appears to be a bug.
I can confirm that these tests now pass after running the migration script.
Towards #4346
> chore(http): fix spawned tests after migration script

- .github/workflows/workspace_publish.yml
This updates `workspace publish` workflow.
This workflow wasn't triggered for the latest 2 tags for some reason (It was triggered for [0.215.0](https://github.com/denoland/deno_std/actions/runs/7827572342) though).
(This might be caused by the behavior described in [this page](https://stackoverflow.com/questions/57963374/github-actions-tag-filter-with-branch-filter), or by the misconfig of PAT)
This change uses `release` event (triggered when the github release is published) to avoid the above issue.
> chore: use 'release' event for triggering jsr publish

- semver/_format_comparator.ts
- semver/comparator_test.ts
- semver/format_range.ts
**Changes**
- renames `comparatorFormat()` to `formatComparator()`
**Reasons**
- javascript generally has a verb-first convention
- this aligns with `parseComparator()`
- this function and file are private, so no breaking changes
> refactor(semver): rename `comparatorFormat()` to `formatComparator()`

- semver/gtr.ts
- semver/ltr.ts
- semver/reverse_sort.ts
- semver/types.ts
Move the breaking versions of `gtr`, `ltr`, `reverseSort`, and `Comparator.semver` forward to align them to the breaking version of obsolete operators (https://github.com/denoland/deno_std/pull/4271)
Note: We might move these further if we decide to accept #4365
> chore(semver): move breaking versions

- semver/format_range.ts
- semver/parse_range.ts
This was missed after the removal of `SemVerRange`.
Ref: https://github.com/denoland/deno_std/pull/4161
> chore(semver): remove legacy `Range.ranges` object definition

- .editorconfig
fix .editorconfig to make .js/.ts settings take effect.
Previously those settings were being ignored
> chore: fix .editorconfig syntax

- collections/mod.ts
- collections/omit.ts
- collections/omit_test.ts
- collections/pick.ts
- collections/pick_test.ts
This is like Lodash's [pick](https://lodash.com/docs/#pick) and [omit](https://lodash.com/docs/#omit), but it's a bit more restrictive. Specifically, it only accepts an array of strings (`string[]`) rather than just a single string.
> feat(collections): Add `pick` and `omit`

- README.md
These snippets are deliberately bad and should be ignored.
Fixes https://github.com/denoland/deno_std/actions/runs/8041176789/job/21960124528
> docs: ignore bad snippet examples

- log/base_handler.ts
**Changes**
- makes `levelName` a getter and setter so it stays in sync with `level`.
- small cleanup with `options` in `constructor()`.
**Reasons**
- makes `levelName` and `level` should never get out of sync.
- avoids `||` operator by setting default formatter value.
> chore(log): sync `level` and `levelName` in BaseHandler

- assert/assert_rejects.ts
- assert/assert_throws.ts
See https://github.com/denoland/deno_std/pull/4384#issuecomment-1962857090
> docs: link to `assertThrows()` and `assertRejects()`

- http/cookie_test.ts
- http/etag_test.ts
- http/negotiation_test.ts
- http/server_sent_event_stream_test.ts
- http/server_test.ts
- http/status_test.ts
> chore(http): format test names

- log/base_handler_test.ts
- log/file_handler_test.ts
- log/formatters_test.ts
- log/logger_test.ts
- log/mod_test.ts
- log/rotating_file_handler_test.ts
- log/test.ts
**Note**
`mod_test.ts` seems to be more or less tests for `setup()`. Maybe it should be renamed to `setup_test.ts`.
There is one test called `"default loggers work as expected"` which checks `debug()`, `info()`, `warn()`, `error()`, `critical()` at the same time and would probably make more sense to split them in individual tests and maybe put them into separate test files as well.
> chore(log): format test names

- fs/ensure_symlink.ts
- fs/ensure_symlink_test.ts
fix: #4363
> So the API doc seems correct, and I think we should check the symlink is actually pointing the given target file if `Deno.errors.AlreadyExists` is thrown
I implemented it.
> fix(fs/ensure_symlink): check symlink is pointing the given target

- expect/_any_test.ts
- expect/_anything_test.ts
- expect/_array_containing_test.ts
- expect/_asymmetric_matchers.ts
- expect/_equal.ts
- expect/expect.ts
> feat(expect): add asymmetric matchers (#3964)

- assert/unreachable.ts
- assert/unreachable_test.ts
Fixes https://github.com/denoland/deno_std/issues/4404
> feat(assert): optional `reason` param for `unreachable` (#4404)

- uuid/v4.ts
I added this so that one could use `validate` to actually narrow down a value for further usage at places where a v4 UUID is expected, like for example:
```ts
import { validate } from "std/uuid/v4";
const getUserByName = (name: string) => { /* ... */ };
const getUserById1 = (id: ReturnType<typeof crypto.randomUUID>) => { /* ... */ };
const getUserById2 = (id: `${string}-${string}-${string}-${string}-${string}`) => { /* ... */ };
// stupid unrealistic function but I hope you get the point
const getUser = (idOrName: string) => {
if (validate(idOrName)) {
// Without the change in this PR, TS/Deno will complain here with
// "Argument of type 'string' is not assignable to parameter of type
// '`${string}-${string}-${string}-${string}-${string}`'",
// because the `validate` check above doesn't …
```
> feat(uuid): add type predicate return type to validate (v4)

- .github/workflows/ci.yml
- testing/__snapshots__/snapshot_test.ts.snap
The string patterns for indicating output during test executions have been changed in https://github.com/denoland/deno/pull/22611, and snapshot test cases are affected by that change. This PR updates the expectations of these test cases to pass CI with Deno canary.
This PR also disables CI for v1.x because it can't pass with those versions.
> chore(testing): update snapshot testing expectations

- archive/tar.ts
- csv/parse.ts
- semver/_is_comparator_test.ts
- semver/is_range_test.ts
Going to do a release in a few minutes, so here's the latest fixes for verbatim-module-syntax (we'll have this landed as a lint rule in deno std in a bit)
> chore: latest verbatim-module-syntax fixes

- log/file_handler.ts
- log/file_handler_test.ts
- log/rotating_file_handler_test.ts
Fixes the bug https://github.com/denoland/deno_std/issues/4411
Bug introduced in https://github.com/denoland/deno_std/pull/4021
TLDR; Attempting to log 4096 or more bytes in a single call to the logger would throw an error and the log would not be written.
Note this PR appears to introduce a new dependency between std/log and std/io. If this is not acceptable then we can find a workaround but the solution will be more verbose.
> fix(log): don't discard bytes >4096 in `FileHandler`

- _tools/check_circular_submodule_dependencies.ts
This PR adds `--all-imports` option to `_tools/check_circular_submodule_dependencies.ts` to output the scripts like the below:
```js
import "std/archive/mod.ts";
import "std/assert/mod.ts";
import "std/async/mod.ts";
import "std/bytes/mod.ts";
import "std/cli/mod.ts";
import "std/collections/mod.ts";
import "std/console/mod.ts";
import "std/crypto/mod.ts";
import "std/csv/mod.ts";
import "std/data_structures/mod.ts";
import "std/datetime/mod.ts";
import "std/dotenv/mod.ts";
import "std/encoding/ascii85.ts";
import "std/encoding/base32.ts";
import "std/encoding/base58.ts";
import "std/encoding/base64.ts";
import "std/encoding/base64url.ts";
import "std/encoding/hex.ts";
import "std/encoding/varint.ts";
import "std/expect/mod.ts";
import "std/flags/mod.ts";
import "std/fmt/bytes.ts";
import …
```
> chore: add `--all-imports` option to deps check tool

- fs/expand_glob_test.ts
> fix(fs): `expandGlob()` test after workspace conversion

- fs/empty_dir_test.ts
- fs/testdata/empty_dir.ts
- fs/testdata/empty_dir_sync.ts
> fix(fs): `emptyDir()` test after workspace conversion

- _tools/convert_to_workspace.ts
This change prevents many unnecessary files from being published and reduces the number of warnings from `deno publish --dry-run`.
> chore: exclude test files from being published to JSR

- _tools/check_circular_submodule_dependencies.ts
- deno.json
- dotenv/parse.ts
- encoding/base58.ts
- url/basename_test.ts
- url/dirname_test.ts
- url/extname_test.ts
- url/join_test.ts
- url/normalize_test.ts
IMO, this should be enabled by default.
Closes #4322
> chore: enable `camelcase` lint rule

- path/_common/common.ts
- path/common_test.ts
This pull request addresses (and adds tests for) cases where [`common()`](https://deno.land/std@0.217.0/path/mod.ts?s=common) returns different values depending on the order and/or number of the input paths, when different results may not be intended.
For example in this case it's probably expected that both cases return an empty string:
```ts
> common(["/", ""], "/")
'/'
> common(["", "/"], "/")
''
```
In the next case the result depends on the number of paths, even if the paths are all equal. The expected result in both cases is likely `'/foo/bar'`:
```ts
> common(["/foo/bar"], "/")
'/foo/'      // missing 'bar'
> common(["/foo/bar", "/foo/bar"], "/")
'/foo/bar/'  // extra slash at the end
```
This pull request adds a variable (`append`) to track whether a separator should be appended …
> fix(path): fix common() results that depend on the order and/or number of input paths

- deno.json
This change aims to improve the debugability of runtime errors.
Related https://github.com/denoland/deno/issues/22719
> chore: add `RUST_BACKTRACE=1` to `test` task

- _tools/check_circular_submodule_dependencies.ts
- _tools/check_doc_imports.ts
- _tools/check_licence.ts
- _tools/convert_to_workspace.ts
> chore(_tools): prepare for `noUncheckedIndexedAccess`

- semver/_constants.ts
- semver/constants.ts
- semver/parse_range_test.ts
- semver/range_intersects.ts
- semver/range_max.ts
- semver/range_min.ts
- semver/test_range.ts
- semver/types.ts
This change removes deprecated operators `""`, `==`, `===` and `!==` in favor of `undefined`, `=` and `!=`, respectively.
> [unstable] BREAKING(semver): remove deprecated operators

- .github/workflows/ci.yml
Found this while checking the Github Actions workflows and thought about doing this quick fix. Since Deno is now available in 1.41.1 this might be usable now.
> chore: run on Deno v1.x

- path/posix/basename.ts
- path/posix/dirname.ts
- path/posix/extname.ts
Hi
This documentation PR adds JSDoc `@example` for : 
- https://deno.land/std/path/posix/basename.ts?s=basename
- https://deno.land/std/path/posix/dirname.ts?s=dirname
- https://deno.land/std/path/posix/extname.ts?s=extname
> docs(path): add examples for posix basename, dirname and extname

- uuid/mod.ts
- uuid/v1.ts
- uuid/v1_test.ts
- uuid/v3.ts
- uuid/v5.ts
Handling all noUncheckedIndexedAccess issues for the uuid module, tracked in https://github.com/denoland/deno_std/issues/4040
> refactor(uuid): prepare for `noUncheckedIndexedAccess`

- yaml/_dumper/dumper.ts
- yaml/_dumper/dumper_state.ts
- yaml/_loader/loader.ts
- yaml/_type/binary.ts
- yaml/_type/float.ts
- yaml/_type/pairs.ts
- yaml/_type/timestamp.ts
- yaml/schema.ts
Ref: https://github.com/denoland/deno_std/issues/4040
> refactor(yaml): prepare for `noUncheckedIndexedAccess`

- cli/mod.ts
- cli/prompt_secret.ts
- cli/spinner.ts
- example.ts
Towards a 100% JSR score, #3878, #4299 and #3764
> docs(cli): add missing documentation

- archive/_common.ts
- archive/tar.ts
- archive/untar.ts
This PR cleans up some logic in `std/archive`. However, there's probably still more room for improvement.
> refactor(archive): various cleanups

- .github/workflows/ci.yml
- crypto/crypto.ts
Nit: the correct abbreviation is "Wasm", not "WASM".
> chore: fix "Wasm" casing

- archive/_common.ts
- archive/mod.ts
- archive/tar.ts
- archive/untar.ts
This fills in several holes in the documentation of `std/archive` and improves its JSR score.
> docs(archive): further documentation

- path/basename_test.ts
- path/dirname_test.ts
- path/extname_test.ts
- path/relative_test.ts
> refactor(path): prepare for `noUncheckedIndexedAccess`

- cli/parse_args.ts
This reverts commit 8c022c4f6488accaca1f0ccea93d982ba0c503dc.
fixes #4481
> Revert "refactor(cli): cleanup `parse_args.ts` (#4189)"

- archive/tar_test.ts
> fix(tar): leak in `Tar() checks directory entry type` test

- .github/workflows/workspace_publish.yml
This is needed as CI needs to publish with uncommitted changes. This fixes JSR publishing. See https://github.com/denoland/deno_std/actions/runs/8285101246/job/22672084929
> chore(CI): use `--allow-dirty` for publish action

- front_matter/_formats.ts
- front_matter/create_extractor.ts
- front_matter/test.ts
**Changes**
- renames constants in `_formats.ts`, uses conventional name format.
- removes `Array` destructuring.
- renames `createRegExp()` to `createRegExps()` as it returns multiple regexps.
- removes `createRegExps()` spread arguments in favour of an array.
> refactor(front_matter): cleanup `_formats.ts`

- crypto/crypto.ts
- front_matter/any.ts
- front_matter/json.ts
- front_matter/mod.ts
- front_matter/test.ts
- front_matter/toml.ts
- front_matter/yaml.ts
Towards a 100% score, #4299, #3764 and #3878.
> docs(front_matter): cleanup and improve docs

- archive/untar.ts
Future versions of Deno don't require an ignore comment around empty `interfaces` that extend another type. Previous Deno versions required that.
```ts
// Deno <=1.41.3
// deno-lint-ignore no-empty-interface
export interface TarEntry extends TarMetaWithLinkName {}
```
Canary + Future Deno versions don't need that comment.
```ts
export interface TarEntry extends TarMetaWithLinkName {}
```
This change to the linter in Deno was done in https://github.com/denoland/deno_lint/pull/1250
> chore: fix lint error in canary

- expect/_equal.ts
- expect/_equal_test.ts
We didn't do any `constructor` checks when not in strict mode which is wrong.
Fixes https://github.com/denoland/deno_std/issues/4511
> fix(expect/assert): missing constructor equality check

- yaml/stringify.ts
- yaml/stringify_test.ts
> fix(yaml): speciously restrictive type for `stringify()`

- http/etag.ts
The default algorithm for etag is not FNV32A, but SHA-256. This PR fixes the doc for it.
> docs(http): fix default algorithm for etag in docs

- _tools/check_deprecation.ts
- _tools/check_mod_exports.ts
PR #4503 updated the `lint` action to run on all platforms, not just Linux, and updated the path-exclusion logic in `_tools/check_mod_exports.ts` to use a regex that matches both Linux and Windows directory separators. However, `_tools/check_deprecation.ts` was not updated and the path exclusion logic is not working correctly on Windows. This doesn't break anything that's currently on `main`, but it breaks my PR #4515 which was relying on one of those path exclusions to avoid crashing on an `node:` import in my benchmark script which is unsupported by `/x/deno_doc`. (The exclusion does **not** apply to any actual library code, so I think it's reasonable to use it and skip the check, since the benchmark is only used manually by developers working on this repository.)
This PR attempts to …
> fix(_tools): update `check_deprecation` path exclusion to recognize Windows directory separators

- .github/workflows/ci.yml
It seems enough to check lint in linux (posix) and windows. I'd suggest drop lint ci in macos.
> chore: drop lint in macos

- datetime/_date_time_formatter.ts
- datetime/format.ts
- datetime/parse.ts
This change is purely for development purposes. The filename more clearly describes its purpose.
> chore(datetime): rename `_common.ts` to `_date_time_formatter.ts`

- fs/move.ts
- fs/walk.ts
The name of a custom error should have the same name as its constructor name. This ensures that for `SubdirectoryMoveError` and `WalkError`.
> fix(fs): `SubdirectoryMoveError` extends `Error` correctly

- .github/workflows/workspace_publish.yml
Now `--allow-dirty` flag seems necessary even with dry run.
> chore: add `--allow-dirty` flag to publish dry run

- crypto/_benches/bench.ts
- crypto/crypto.ts
- crypto/crypto_test.ts
(Originally part of #4515, broken into separate PR as [suggested by iuioiua](https://github.com/denoland/deno_std/pull/4515#pullrequestreview-1956667727).) 
This PR renames `crypto.ts`'s exported `const` `wasmDigestAlgorithms` to `DIGEST_ALGORITHM_NAMES`, to match Deno's style guide and reflect the fact that it includes all algorithm names supported by the digest function, not just a subset. The old name is maintained as a deprecated alias for now. The exported `WasmDigestAlgorithm` type is deprecated, as it's redundant with the existing `DigestAlgorithmName` export (all algorithms are available in Wasm, and if that changes in the future it should probably just be an internal implementation detail, not part of the public interface). The `FNVAlgorithms` export is similarly deprecated (they …
> deprecation(crypto): rename an export to match style guide, deprecating original and two other obsolete imports

- testing/bdd.ts
Mocha and `node:test` use `after` and `before` instead of `afterAll` and `beforeEach`. This PR adds some aliased exports to make switching to Deno easier.
> feat(testing): add `after`, `before`, `test` aliases

- .github/CONTRIBUTING.md
Module documentation guidelines are to come in a follow-up PR after discussions.
CC @timreichen
> chore: add "Documentation" to contributing guidelines

- fmt/duration_test.ts
This should up the [code coverage of `fmt/duration`](https://app.codecov.io/gh/denoland/deno_std/blob/main/fmt%2Fduration.ts) up to 100%. Not 100% about the second test's name so I'm open to suggestions since we're testing here the default `switch` case.
This referes to #3713
> tests(fmt): add `duration()` tests

- encoding/varint.ts
This PR deprecates:
1. `encode()` in favor of `encodeVarint()`
2. `decode()` in favor of `decodeVarint()`
3. `decode32()` in favor of `decodeVarint32()`
> deprecation(encoding): make exported function names consistent with `std/encoding`

- media_types/_util.ts
- media_types/_util_test.ts
- media_types/content_type_test.ts
- media_types/extensions_by_type_test.ts
- media_types/format_media_type_test.ts
- media_types/get_charset_test.ts
- media_types/parse_media_type_test.ts
working towards https://github.com/denoland/deno_std/issues/3713.
pushes code coverage of the `media_types` sub-module to 100%.
> test(media_types): improve test coverage

- .github/workflows/ci.yml
- webgpu/_test_util.ts
As expected, this currently fails because [`cleanup()`](https://github.com/denoland/deno_std/blob/main/webgpu/_test_util.ts#L33) calls `Deno.resources()`, which will be removed in Deno 2.
Closes #4517
> chore: enable simulated tests for Deno 2

- log/mod.ts
update the documentation according to this pull request: https://github.com/denoland/deno_std/pull/4239
> docs(log): remove string formatter description

- testing/bdd_test.ts
This PR cleans up `testing/bdd_test.ts` by removing the unnecessary wrapping `global` test.
> test(testing): cleanup bdd tests

- yaml/schema/core.ts
- yaml/schema/default.ts
- yaml/schema/extended.ts
- yaml/schema/failsafe.ts
- yaml/schema/json.ts
- yaml/schema/mod.ts
Previously, `core`, `def`, `extended`, `json` and `failsafe` constants were exported from their source files. However, the same symbols were exported as `CORE_SCHEMA`, `DEFAULT_SCHEMA`, `EXTENDED_SCHEMA`, `JSON_SCHEMA`, and `FAILSAFE_SCHEMA` were exported elsewhere, which were the same symbols, respectively. See https://jsr.io/@std/yaml/doc. This change uses the uppercase snake case names, which is the appropriate casing for constants.
> deprecation(yaml): cleanup schema exports

- semver/range_max.ts
- semver/range_min.ts
> deprecation(semver): deprecate `rangeMax()` and `rangeMin()`

- log/base_handler.ts
- log/console_handler.ts
- log/file_handler.ts
- log/logger.ts
- log/rotating_file_handler.ts
This reverts commit 42df58a2331f6c028d71a2082809583793ee2442.
closes #4571
> fix(log): Revert "deprecate(log): deprecate internal utility methods" (#4436)

- datetime/day_of_year.ts
- datetime/difference.ts
- datetime/format.ts
- datetime/is_leap.ts
- datetime/mod.ts
- datetime/parse.ts
- datetime/week_of_year.ts
Puts #4570 into effect, making `std/datetime` the Northstar for other documentation in the codebase.
> docs(datetime): polish module documentation

- .github/codecov.yml
This change enables Codecov comments. I find myself having to manually look up test coverage changes on commits in the Codecov UI. Having this presented within PR feeds would help a lot. We can re-evaluate if it becomes too noisy.
> chore: enable Codecov comments in PRs

- expect/expect.ts
This PR renames `expect.addSnapshotSerializers` to `expect.addSnapshotSerializer` to match [Jest's naming](https://github.com/jestjs/jest/blob/v29.7.0/docs/ExpectAPI.md#expectaddsnapshotserializerserializer).
> deprecation(expect): rename `addSnapshotSerializers` to `addSnapshotSerializer`

- net/get_available_port.ts
Thanks to https://github.com/denoland/deno/pull/23228
> refactor(net): remove use of `as Deno.NetAddr`

- .github/workflows/ci.yml
- .github/workflows/workspace_publish.yml
- url/basename.ts
This allows us to catch issues with dry-run publishes before cutting a release.
> chore(CI): perform dry-run publish to be done in PRs

- csv/parse.ts
This was made according to the issue #4545 inside the file deno_std/csv/parse.ts
> fix(csv): remove unused `opt` parameter

- bytes/repeat.ts
- bytes/repeat_test.ts
This change simplifies the error logic and message in `repeat()` when the `count` parameter is negative or not an integer.
> fix(bytes): improve invalid count error message for `repeat()`

- _tools/check_deprecation.ts
- permissions/mod.ts
This PR updates the removal version of `std/permissions` to be when `std` migrates to JSR, as `std/permissions` will never reach v1.
> deprecation(permissions): update removal time for `std/permissions`

- .github/workflows/ci.yml
- csv/parse_test.ts
- deno.json
This PR fixes the type error in `csv/parse_test.ts`. This also adds workaround in tasks. Now `deno task test` type check the codebase correctly, and we check the doc types with a separate task `deno task doc-test`.
closes #4606
> test(csv): fix type error in `csv/parse_test.ts`

- csv/stringify.ts
- csv/stringify_test.ts
> fix(csv): do not print empty header line when no columns are given in `stringify()`

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/version_bump.yml
- .github/workflows/workspace_publish.yml
This codebase no longer contains any git submodules since the Node compatibility layer moved to the runtime repo.
> chore: cleanup old git submodule settings

- http/file_server.ts
- http/file_server_test.ts
closes #4597
This PR updates `onListen` hook of file_server to show the local network IP address. The scripts shows 2 urls like the below (Updated):
```shellsession
$ deno run -A http/file_server.ts 
Listening on:
- Local: http://localhost:4507
- Network: http://192.168.79.163:4507
```
Suggestions to the output format are welcome
---
Note: `npm:serve` chooses non internal IPv4 address as the network address. This implementation follows it. ref. https://github.com/vercel/serve/blob/1ea55b1b5004f468159b54775e4fb3090fedbb2b/source/utilities/http.ts#L40
Note: Deno's [NetworkInterfaceInfo](https://deno.land/api@v1.42.4?s=Deno.NetworkInterfaceInfo) object doesn't have `internal` field, but it's polyfilled as `address.startsWith("127")` in the node compat layer …
> feat(http): file server prints local network address

- _tools/release/repo.ts
- cli/_tools/generate_data.ts
- crypto/testdata/digest_large_inputs.ts
- crypto/testdata/digest_many_calls.ts
- csv/parse_test.ts
Found by running `deno check **/*.ts`. Continues or supersedes the type-checking fixes in #4609.
> chore: fix types

- bytes/equals.ts
- bytes/equals_test.ts
> fix(bytes): `equals()` works with subarray

- _tools/convert_to_workspace.ts
This bit is not needed anymore since https://github.com/denoland/deno/pull/23492 landed.
> chore: update convert_to_workspace.ts script

- bytes/equals.ts
- bytes/equals_test.ts
See https://github.com/denoland/deno_std/pull/4630 for prior history
cc @iuioiua @0f-0b
The `THRESHOLD_32_BIT` value was based off of the following benchmark:
```ts
import { equals32Bit, equalsNaive } from "./equals.ts";
let n = 0;
for(let l = 0; l < 300; l += 10) {
const len = l;
const a = crypto.getRandomValues(new Uint8Array(len));
const b = new Uint8Array(a);
Deno.bench(`naive ${len}`, () => {
n += +equalsNaive(a, b)
})
Deno.bench(`32-bit ${len}`, () => {
n += +equals32Bit(a, b)
})
}
```
```
benchmark       time (avg)        iter/s             (min … max)       p75       p99      p995
---------------------------------------------------------------- -----------------------------
naive 0          3.94 ns/iter 253,808,039.2     (3.75 ns … 9.02 ns)   4.07 ns   4.83 ns   5.12 ns
32-bit 0 …
```
> perf(bytes): improve performance of `equals()` 

- http/test.ts
This was added in https://github.com/denoland/deno/pull/7264 but it's premise is no longer true.
> chore(http): remove `http/test.ts`

- crypto/crypto.ts
- crypto/crypto_test.ts
This PR bumps test coverage of `crypto/crypto.ts` to 100% and aims to improve logic and readability.
This might interest you, @mbhrznr.
> refactor(crypto): cleanup `crypto.subtle.digest[Sync]()` logic

- path/parse.ts
- path/posix/parse.ts
- path/windows/parse.ts
The `ParsedPath` type is used as the return type for the function [`parse`](https://github.com/denoland/deno_std/blob/0.223.0/path/parse.ts#L25), which is part of the public API… yet it is only exported from the "private" module [`_interface.ts`](https://github.com/denoland/deno_std/blob/0.223.0/path/_interface.ts#L19). Item number 4 in the [Recommended Usage](https://github.com/denoland/deno_std/tree/0.223.0#recommended-usage) states this…
> Do not import modules with a directory or filename prefixed by an underscore (they're not intended for public use).
…which means that it's currently impossible to import the type in a recommended way. This PR re-exports the type from the `parse` modules which use it so that the `parse` function and the `ParsedPath` type can now be imported together: …
> fix(path): export private types used in public API

- README.md
This change trims some of the README, by relying more on JSR's usage instructions built-in to package pages. 
My thinking is that JSR already does a fine job at instructing the reader on how to use the package and further usage instructions simply aren't needed elsewhere. This should also act as more of a forcing function to improve our documentation.
I'd like to complete remove the packages table once https://github.com/jsr-io/jsr/issues/421 is merged, so there's no need to maintain such a list. We can instead have a note on each package's module documentation like so:
```
/**
* This module does this and that.
*
* Note: this module is unstable and may change in the future.
* @module
*/
```
and
```
/**
* This module does this and that.
*
* Note: this module is settled and is unlikely to …
```
> docs: update README for JSR

- _tools/check_circular_package_dependencies.ts
- deno.json
`_tools/check_circular_package_dependencies.ts` was disabled in #4650 
This PR re-enables it.
related #4544 #4600
> chore: update `check_circular_package_dependencies.ts` for workspaces

- _tools/check_circular_package_dependencies.ts
- _tools/check_deprecation.ts
- _tools/check_docs.ts
- _tools/utils.ts
- deno.json
We disabled `check_deprecation.ts` in #4650. This PR re-enables it by providing appropriate resolver to `@deno/doc`. Also shares the same resolver with `check_circular_package_dependencies.ts`.
> chore: update `check_deprecation.ts`

- assert/deno.json
- fmt/deno.json
- fs/deno.json
- internal/deno.json
- path/deno.json
These versions are used & yanked in JSR by accident. Let's move forward the versions to skip them in the next release.
> chore: skip yanked versions

- bytes/last_index_of_needle.ts
- Clarifies the description of the default value of `start` param (`lastIndexOfNeedle`)
- Fixes an example return value
> docs(bytes): update API doc of lastIndexOfNeedle

- _tools/check_docs.ts
This change adds the ability for the doc checker to ensure that all functions have a `@template` JSDoc tag for each type argument.
> chore: add `@template` JSDoc tag check

- bytes/concat.ts
> docs(bytes): fix return type description for `concat()`

- cli/spinner.ts
This may change `fmt/colors` in the future, but please support this first.
> fix(cli): spinner support NO_COLOR

- _tools/check_docs.ts
- bytes/repeat.ts
This ensures that our code snippets are correct. Once this is merged, we'll have to rewrite some documents to take advantage of assertions.
> chore: run `@example` JSDoc code snippets

- .github/workflows/ci.yml
- deno.json
We added doc-test workaround in https://github.com/denoland/deno_std/issues/4606 because of the issue https://github.com/denoland/deno/issues/23430
This PR removes that workaround because the issue https://github.com/denoland/deno/issues/23430 is now resolved in main.
> chore: remove doc test workaround

- log/file_handler.ts
> feat(log): make `FileHandler` and `RotatingFileHandler` buffer size configurable

- collections/chunk.ts
- collections/chunk_test.ts
This is a more fitting error class for when `size` is incorrectly defined.
> fix(collections): correct error class when `chunk()` throws

- .editorconfig
This PR updates .editorconfig. Now it enforces `charset = utf-8` `end_of_line = lf` `insert_final_newline = true` to `.yml` files, which should reduce the whitespace diffs in PRs.
> chore: update `.editorconfig`

- .github/workflows/title.yml
- assert/deno.json
- fmt/deno.json
- fs/deno.json
- internal/deno.json
- path/deno.json
I updated [the tool](https://jsr.io/@deno/bump-workspaces) for upgrading the versions of packages ([ref](https://github.com/denoland/bump-workspaces/pull/13)), and now the tool always respect the versions which are manually modified (This change was made for supporting manual upgrade of `std/bytes` from `0.224.0` to `1.0.0-rc.1`). Because of this tool update, we need to skip these yanked versions manually.
This unblocks the next release of std packages.
> chore(assert,fmt,fs,internal,path): skip yanked versions manually

- .github/workflows/version_bump.yml
This PR sets up new version upgrade flow to the repo using [jsr:@deno/bump-workspaces](https://jsr.io/@deno/bump-workspaces) tool
The new release steps:
- A maintainer trigger `version_bump` action
- @denobot creates a PR like [this](https://github.com/kt3k/deno_std/pull/34)
- the tool automatically calculates the necessary version upgrades.
- A maintainer review PR, and update it if necessary
- A maintainer land the PR.
- A maintainer tag it with something like `release-YYY-MM-DD` (can be automated in the future)
- A maintainer publish the tag from github UI
- `workspace publish` action is triggered by the above and new versions will be published
- That's all
> chore: update version_bump.yml

- .github/workflows/version_bump.yml
The workflow run failed with missing permission for denobot token. https://github.com/denoland/deno_std/actions/runs/8982982654/job/24671741490
This change could solve the issue (`permissions` was there before the change https://github.com/denoland/deno_std/pull/4687)
> chore: fix permissions for version_bump.yml

- .github/workflows/version_bump.yml
This PR updates the dependency version of `@deno/bump-workspaces` to `^0.1` to automatically include the fixes in the upstream.
#4689 revealed a few bugs in the tool and they are fixed in v0.1.14: https://github.com/denoland/bump-workspaces/releases/tag/v0.1.14
> chore: update `jsr:@deno/bump-workspaces`

- _tools/check_docs.ts
- bytes/concat.ts
- bytes/copy.ts
- bytes/ends_with.ts
- bytes/equals.ts
- bytes/includes_needle.ts
- bytes/index_of_needle.ts
- bytes/last_index_of_needle.ts
- bytes/repeat.ts
- bytes/starts_with.ts
- collections/drop_last_while.ts
- collections/reduce_groups.ts
- collections/running_reduce.ts
- collections/sample.ts
I previously added a modification that ensured function overload signatures were checked instead of implementation signatures, but this also prevented functions without overloads from being skipped. This PR fixes that and applies documentation fixes where spotted.
> docs(bytes,collections): fix doc checker and documentation

- expect/_build_message.ts
- expect/_constants.ts
This change removes lines that seem unreachable. This also eliminates a dependency on `fmt/colors.ts`.
Towards #4699
> fix(expect): don't swallow the original error while creating assertion error

- assert/_constants.ts
- assert/assert_equals.ts
- assert/assert_equals_test.ts
- assert/assert_not_equals.ts
- assert/assert_not_equals_test.ts
- assert/assert_strict_equals.ts
- assert/assert_strict_equals_test.ts
This change removes lines that seem unreachable and reduces the dependency on `fmt/colors.ts`. The exact reasons for the changes are the same as in #4700.
Towards #4699
> fix(assert): don't swallow the original error while creating assertion error

- internal/diff.ts
- internal/diff_str.ts
This is no longer needed, thanks to #4700 and #4701.
Related #4699
> refactor(internal): cleanup `_internals`

- internal/diff_str.ts
This change moves functions out of `diffstr()` and applies simple cleanups.
> refactor(internal): cleanup and restructure `diffstr()`

- webgpu/_test_util.ts
- webgpu/create_capture_test.ts
- webgpu/texture_with_data_test.ts
Possible due to https://github.com/denoland/deno/pull/23752
> test(webgpu): remove `Deno.resources()` usage

- internal/_types.ts
- internal/diff.ts
To improve maintainability. I wasn't able to make `snake()` top-level. Oh well. That can be done some other time.
> refactor(internal): cleanup `diff()`

- internal/build_message.ts
> refactor(internal): cleanup `buildMessage()`

- net/get_available_port_test.ts
working towards https://github.com/denoland/deno_std/issues/3713.
pushes code coverage of the `net` sub-module to 100%.
> test(net): improve test coverage

- expect/expect.ts
- testing/bdd.ts
Fast check will be getting a bit smarter at analyzing expando properties.
```
error[missing-explicit-return-type]: missing explicit return type in the public API
--> V:\deno_std\testing\bdd.ts:582:11
|
582 | it.only = function itOnly<T>(...args: ItArgs<T>) {
|           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
583 |   const options = itDefinition(...args);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
584 |   return it({
| ^^^^^^^^^^^^^
585 |     ...options,
| ^^^^^^^^^^^^^^^
586 |     only: true,
| ^^^^^^^^^^^^^^^
587 |   });
| ^^^^^
588 | };
| ^ this function is missing an explicit return type
= hint: add an explicit return type to the function
info: all functions in the public API must have an explicit return type
docs: https://jsr.io/go/slow-type-missing-explicit-return-type …
```
> chore(expect): fix future `no-slow-type` lint errors with expando properties

- assert/assert_strict_equals.ts
- assert/assert_strict_equals_test.ts
> fix(assert): handle `assertStrictEquals(-0, +0)` correctly

- _tools/check_licence.ts
- cli/spinner_test.ts
- cli/testdata/spinner_cases/change_message.ts
- cli/testdata/spinner_cases/custom_color_black.ts
- cli/testdata/spinner_cases/custom_color_blue.ts
- cli/testdata/spinner_cases/custom_color_cyan.ts
- cli/testdata/spinner_cases/custom_color_gray.ts
- cli/testdata/spinner_cases/custom_color_green.ts
- cli/testdata/spinner_cases/custom_color_magenta.ts
- cli/testdata/spinner_cases/custom_color_red.ts
- cli/testdata/spinner_cases/custom_color_white.ts
- cli/testdata/spinner_cases/custom_color_yellow.ts
- cli/testdata/spinner_cases/custom_interval_10.ts
- cli/testdata/spinner_cases/custom_interval_750.ts
- cli/testdata/spinner_cases/custom_loading_text.ts
- cli/testdata/spinner_cases/custom_message.ts
- cli/testdata/spinner_cases/custom_spinner.ts
- cli/testdata/spinner_cases/set_color.ts
- cli/testdata/spinner_cases/start.ts
- cli/testdata/spinner_cases/stop.ts
Adding tests for @std/cli/spinner per #4672 . Open to feedback.
> test(cli): `Spinner` tests

- assert/assert_strict_equals.ts
- assert/assert_strict_equals_test.ts
See https://github.com/denoland/deno_std/issues/4714#issuecomment-2106423300
> chore(assert): revert "handle `assertStrictEquals(-0, +0)` correctly"

- .github/FAQ.md
- README.md
First pass. Other questions that should be answered:
1. Why is the Standard Library versioned differently to the Deno runtime?
2. What are the compatibility guarantees for the Standard Library?
@kt3k, are you able to handle these?
> docs: "Frequently Asked Questions" page

- assert/assert_strict_equals.ts
> docs(assert): document `assertStrictEquals()` equality comparison behavior

- .github/workflows/title.yml
- Changed snake_case names to kebab-case for scope names. [The version upgrade tool](https://github.com/denoland/bump-workspaces) assumes these match with JSR package name.
- Removed `_tools` scope as it's not jsr package. I think we should use non-scoped `chore:` for tool updates.
- Added `cache` to make #4725 CI green.
> chore: update `title.yml`

- _tools/check_docs.ts
- deno.json
- media_types/content_type.ts
- media_types/extension.ts
- media_types/extensions_by_type.ts
- media_types/format_media_type.ts
- media_types/get_charset.ts
- media_types/mod.ts
- media_types/parse_media_type.ts
- media_types/type_by_extension.ts
> docs(media-types): polish documentation

- cli/spinner_test.ts
- cli/testdata/spinner_cases/set_color.ts
Updates spinner test. Now the test case waits longer time (350ms) to make sure green text appearing
closes #4734
> test(cli): reduce flakiness of spinner test

- encoding/base32_test.ts
- encoding/base58_test.ts
The `encoding` sub-module is now fully covered.
Towards: #3713
> test(encoding): improve test coverage

- media_types/_db.ts
- media_types/_util.ts
- media_types/extension.ts
- media_types/format_media_type.ts
- media_types/get_charset.ts
- media_types/parse_media_type.ts
- media_types/type_by_extension.ts
Minor cleanups and logic improvements. Overall, this was already quite a well-writtten and thorough package.
Towards #4730
> refactor(media-types): minor cleanups

- README.md
> docs: update stabilization section

- README.md
This section is typically at the end of a page.
> docs: move FAQ section

- assert/assert_equals.ts
- assert/assert_strict_equals.ts
- expect/_build_message.ts
- internal/build_message.ts
- internal/diff_str.ts
- internal/diff_str_test.ts
- internal/mod.ts
There's no reason for this function to not adhere to the function naming convention.
Prerequisite #4757
> refactor(assert,internal): rename `diffstr()` to `diffStr()`

- expect/_matchers.ts
- expect/_to_contain_equal_test.ts
- expect/_to_contain_test.ts
See issue: #4659 
Updated error message `toContain` to include the values from the failed test.
~~Should we also add this to `toContainEqual`?~~
For `toContainEqual` we need to come to an agreement for how to format that.
> fix(expect): updated error message for toContain

- internal/deno.json
related #4739 
Retry of #4741. We reverted #4741 in #4753 to fix internal dependency issue.
> chore: release `@std/internal@1.0.0`

- bytes/ends_with.ts
- bytes/index_of_needle.ts
- bytes/starts_with.ts
Not sure if this is worth it (or if I have introduced some bugs with this change), but I think we can avoid doing some work here.
> perf(bytes): skip doing extra work in some scenarios

- media_types/deno.json
Currently [vendor/mime-db.v1.52.0](https://jsr.io/@std/media-types/doc/vendor/mime-db.v1.52.0/~/) is exposed as a public API, but I believe this is an error.
related https://github.com/denoland/deno_std/pull/4744/ https://github.com/denoland/deno_std/issues/4730
> fix(media-types): do not expose vendored json file as public API

- csv/csv_parse_stream.ts
- csv/mod.ts
- encoding/ascii85.ts
- encoding/base32.ts
- encoding/base64.ts
- encoding/base64url.ts
- http/cookie.ts
- json/json_parse_stream.ts
- json/json_stringify_stream.ts
- media_types/format_media_type.ts
- media_types/parse_media_type.ts
- uuid/mod.ts
`www.rfc-editor.org` seems the most official place for hosting RFCs. I think we should always use `www.rfc-editor.org` urls for the references of RFCs
ref:
- https://en.wikipedia.org/wiki/Request_for_Comments#Obtaining_RFCs
- github discussion discussing various RFC urls https://github.com/ietf-tools/datatracker/discussions/7259
> docs(csv,encoding,http,json,media-types,uuid): use `rfc-editor.org` for RFC links

- bytes/index_of_needle_test.ts
Addresses https://github.com/denoland/deno_std/pull/4746#discussion_r1605477633
> test(bytes): add test for negative `start` index for `indexOfNeedle()`

- cli/spinner.ts
This todo comment is out-of-date as the test cases of Spinner were added in this PR https://github.com/denoland/deno_std/pull/4713
> chore(cli): remove outdated todo comment

- _tools/check_docs.ts
- deno.json
- media_types/extensions_by_type.ts
This PR:
1. Swaps the command order in the `lint:docs` task so `document.jsDoc` is known to be defined in the doc checker.
2. Simplifies some of the functions in the doc checker by just passing in `document`.
3. Adds the ability for the doc checker to check if the JSDocs for exported variables contain at least one example.
> chore: improve doc checker

- encoding/README.md
- encoding/deno.json
- encoding/mod.ts
Currently the `@std/encoding` package is one of the few without a root module that re-exports the public symbols.
This PR adds a `mod.ts` file that re-exports the submodules in `encoding`. I diverged a bit from convention by not re-exporting _all_ public symbols, leaving out the `encode` and `decode` functions from `@std/encoding/varint`. Those functions are deprecated, and it seemed confusing to have them exported from the root.
> chore: Add a root module (`mod.ts`) to `@std/encoding`

- msgpack/decode.ts
- msgpack/decode_test.ts
Previously data that was too short would not cause the `decode()` function to throw.
Now decoding a partial chunk will result in the `decode()` function throwing.
> fix(msgpack): error on early end of data

- data_structures/_binary_search_tree_internals.ts
- data_structures/binary_heap.ts
- data_structures/binary_heap_test.ts
- data_structures/binary_search_tree.ts
- data_structures/binary_search_tree_test.ts
- data_structures/comparators.ts
- data_structures/red_black_tree.ts
- data_structures/red_black_tree_test.ts
This commit makes the internals of
`BinarySearchTree` is properly private so that
`BinarySearchNode` is not leaked in public types anymore.
Relands #4794
Towards #4826
> BREAKING(data-structures): hide private internals

- cli/spinner.ts
- cli/spinner_test.ts
This makes the `Spinner` in `@std/cli` expose a `message` property to be consistent with the existing `color` property. It also adds doc comments and an examples for both `message` and `color `
_NOTE: I noticed another issue while making this change. The `Color` type also includes `Ansi` which is defined as a string. However, the actual code in the set `color` property will never let you set this to anything other then a valid `COLORS` value._
> docs(cli): improve spinner.message document

- ini/ini_map.ts
> fix(ini): remove unused `ParseOptions.assignment` property

- ini/ini_map.ts
- ini/ini_map_test.ts
Seems like we should just use `FormattingOptions` here?
> BREAKING(ini): remove internal `Formatting` type

- yaml/_utils.ts
These utils don't seem used from anywhere
This improves the test coverage. Related: #3713
> refactor(yaml): remove dead code

- yaml/parse_test.ts
- yaml/stringify_test.ts
part of #3764 
This improves the test coverage of `std/yaml`. Added test cases which exercise the handling of floats.
> test(yaml): test float handling

- _tools/check_docs.ts
- streams/buffer.ts
- streams/byte_slice_stream.ts
- streams/concat_readable_streams.ts
- streams/delimiter_stream.ts
- streams/early_zip_readable_streams.ts
- streams/early_zip_readable_streams_test.ts
- streams/iterate_reader.ts
- streams/limited_bytes_transform_stream.ts
- streams/limited_bytes_transform_stream_test.ts
- streams/limited_transform_stream.ts
- streams/limited_transform_stream_test.ts
- streams/merge_readable_streams.ts
- streams/readable_stream_from_reader.ts
- streams/reader_from_iterable.ts
- streams/reader_from_stream_reader.ts
- streams/text_delimiter_stream.ts
- streams/text_delimiter_stream_test.ts
- streams/text_line_stream.ts
- streams/to_array_buffer.ts
- streams/to_blob.ts
- streams/to_json.ts
- streams/to_text.ts
- streams/to_transform_stream.ts
- streams/writable_stream_from_writer.ts
- streams/writer_from_stream_writer.ts
- streams/zip_readable_streams.ts
This commit improves docs of the streams module.
Towards #3764
> docs(streams): improve docs for stabilization

- _tools/check_docs.ts
Previously, inter-package module imports broke the Super Linter. This change fixes that.
Pre-requisite for #4790
> chore: implement custom resolver for Super Linter

- _tools/check_docs.ts
When the return type of a function is type assertion like `asserts expr`, the actual return value is undefined. We should skip requiring `@returns` doc in that case.
Example:
https://github.com/denoland/deno_std/blob/0b95598ec109a35f679b78cd92eb9573aa34ad27/assert/assert.ts#L16
> chore: don't require `@returns` tag when return type is type assertion

- uuid/v1.ts
The convention in this codebase is for options interfaces to be named `XOptions`, where `X` is the name of the symbol that the options interface belongs to.
> deprecation(uuid): rename `V1Options` to `GenerateOptions`

- uuid/v3_test.ts
- uuid/v5_test.ts
Notice: These `generate()` functions only check the length of the namespace UUID and not its format. This behavior will be improved in #4874.
> test(uuid): add tests for invalid namespace UUID

- uuid/v1.ts
This PR deprecates the `v1.generate()` signature with the optional `buf` and `offset` arguments and `number[]` return type. These settings are unneeded in almost all cases and gave the function a shape that differed from the other `generate()` functions within `@std/uuid`. The function also went against Deno's Style Guide, which required functions to have only one optional argument (see https://docs.deno.com/runtime/manual/references/contributing/style_guide#exported-functions-max-2-args-put-the-rest-into-an-options-object).
Pre-requisite for #4877
> deprecation(uuid): deprecate `v1.generate()` signature with `buf` and `offset` parameters

- uuid/_common.ts
- uuid/v3.ts
- uuid/v3_test.ts
- uuid/v5.ts
- uuid/v5_test.ts
Previously, these `generate()` functions only checked if the namespace UUIDs were the correct length and nothing more. In other words, providing a string with the proper length but incorrect UUID format would go uncaught. It also threw an `AssertionError`, meaning that handling that error, if using these functions, would require importing `AssertionError` from `@std/assert.`
These functions now check that the namespace UUID is a valid UUID and throw a `TypeError` if it is not, making error handling a little easier, as it's a native JS error.
This is a breaking fix, as the class and message of the thrown error have changed.
Related #4865
> fix(uuid): validate namespace UUIDs in `v3.generate()` and `v5.generate()`

- _tools/check_docs.ts
- html/entities.ts
> docs(html): improve API docs

- http/mod.ts
With this new [change](https://github.com/denoland/deno_std/pull/4604), running the following script asks the user to approve Deno.networkInterfaces.
`deno run --allow-net --allow-read jsr:@std/http/file-server`
Certainly they are required so not having access ends the application:
Having --allow-sys fixes the prompt
> docs(http): added `--allow-sys` to file server example

- net/get_network_address.ts
- net/get_network_address_test.ts
According to https://github.com/mafintosh/network-address/pull/3 the scopeid needs to be 0 for the address to be reachable if the family is `IPv6`.
(This is a PR targeting the feature branch, not main)
> fix(net): check `scopeid === 0` in `getNetworkAddress()`

- crypto/unstable_keystack_test.ts
This PR updates the test case of Node.js custom inspection.
Deno uses Deno's custom inspection if `Symbol.for("Deno.customInspect")` is defined. We need to overwrite it with undefined to invoke the custom Node.js inspection. ( https://github.com/denoland/deno/blob/4f9b23b3664578c2bf48415db246fb21e49abddb/ext/console/01_console.js#L451-L465 )
This improves the code coverage of `crypto` package.
> test(crypto): test node.js custom inspection of `KeyStack`

- _tools/check_docs.ts
- assert/assert.ts
- assert/assert_almost_equals.ts
- assert/assert_array_includes.ts
- assert/assert_equals.ts
- assert/assert_exists.ts
- assert/assert_false.ts
- assert/assert_greater.ts
- assert/assert_greater_or_equal.ts
- assert/assert_instance_of.ts
- assert/assert_is_error.ts
- assert/assert_less.ts
- assert/assert_less_or_equal.ts
- assert/assert_match.ts
- assert/assert_not_equals.ts
- assert/assert_not_instance_of.ts
- assert/assert_not_match.ts
- assert/assert_not_strict_equals.ts
- assert/assert_object_match.ts
- assert/assert_rejects.ts
- assert/assert_strict_equals.ts
- assert/assert_string_includes.ts
- assert/assert_throws.ts
- assert/assertion_error.ts
- assert/equal.ts
- assert/fail.ts
- assert/unimplemented.ts
- assert/unreachable.ts
This PR improves the API docs of `assert` package. Now the `@param` `@returns` `@typeParam` are fully documented. It passes doc-linter check.
part of #4600 #3764
> docs(assert): improve docs

- path/to_namespaced_path_test.ts
> test(path): test `toNamespacedPath()`

- encoding/mod.ts
- encoding/varint.ts
- encoding/varint_test.ts
> BREAKING(encoding): rename `MaxUInt64` to `MaxUint64`

- encoding/mod.ts
- encoding/varint.ts
- encoding/varint_test.ts
> BREAKING(encoding): rename `MaxVarInt` to `MaxVarint`

- path/common_test.ts
- path/is_absolute_test.ts
- path/join_globs_test.ts
- path/posix/join_globs.ts
- path/windows/join_globs.ts
part of #3713
This improves the test coverage of `isAboslute`, `joinGlobs`, and `common` in `path` package.
> test(path): add test cases of `isAbsolute()`, `joinGlobs()`, and `common()`

- deno.json
I realise this actually makes troubleshooting harder because diagnostics are difficult to understand. We can instead temporarily enable this environment variable when needed.
> chore: remove `RUST_BACKTRACE=1` from `test` task

- _tools/check_docs.ts
The conflicts while writing to lockfile seem causing flaky CI failures. This PR prevents it.
See https://github.com/denoland/deno_std/actions/runs/9312185249/job/25632575577?pr=4912
> chore: use `--no-lock` in doc snippet eval

- crypto/crypto.ts
These APIs are scheduled to be removed for 1.0.0.
> BREAKING(crypto): remove deprecated APIs

- testing/snapshot.ts
Dependency to `assertEquals` from `testing/snapshot` was introduced in https://github.com/denoland/deno_std/pull/3563 to avoid using non public API of `assert` from `testing` (That was necessary for a part of JSR migration).
Now those internal APIs `diff`, `diffStr`, and `buildMessage` are available from `std/internal`. This PR (partially) reverts #3563 and make `testing/snapshot` directly use those APIs from `std/internal`.
This unblocks #4893
> refactor(testing): do not use assertEquals in snapshot.ts

- csv/_io.ts
- csv/csv_parse_stream.ts
- csv/csv_stringify_stream.ts
- csv/mod.ts
- csv/stringify.ts
> docs(csv): use assertions in example code snippets

- assert/assert_equals.ts
The option doesn't exist anymore.
related #4893
> docs(assert): remove outdated API docs

- path/_common/common.ts
- path/common.ts
- path/common_test.ts
- path/posix/common.ts
- path/windows/common.ts
This change removes the separator argument, `sep`, from `posix.common()`, `windows.common()` and `common()`.
This change was made so these functions are made to be consistent with other APIs within `@std/path`, which don't have the ability to set the path separator via an argument. Instead, the user should use the OS-specific variant of `common()` if OS-specific behavior is required and the OS-agnostic `common()` so behavior is oriented for the current machine's OS.
To migrate, either use the OS-specific or OS-agnostic variant of `common()`, for your use case:
For the current machine's OS (automatically detected):
```ts
import { common } from "@std/path/common";
// No need to define a second argument
common(["C:\\foo\\bar", "C:\\foo\\baz"]);
```
For Windows systems:
```diff
- import { …
```
> BREAKING(path): remove separator argument from `common()`
