denoland/std

- http.ts
- http_test.ts
Closes #1 .
Resolve the immediate cause for blocking, by making new conn accept and readRequest of same level and async, ~~with `Promise.race`~~. Now `http_test.ts` should work properly.
~~(Currently there will be warnings of `Promise resolved after resolved`. The warning would go away after denoland/deno#1273)~~
~~Socket is closed for now once responding. Will need to change this behavior later.~~ Sockets are left open now until EOF.
I'm not quite sure if this fix is proper, and whether I should keep `serveConn` (since it is exported)
I will work more on http based on feedback for this change.
> Unblock server on multiple HTTP requests

- file_server.ts
- http.ts
If you request path ending with slash (`localhost:4500/foo/bar`) it looks for `index.html` file in that dir.
Ideas for improvement:
- addr option (`-a/--addr 127.0.0.1:4500`)
- serve HTML page with directory structure if `index.html` missing
Closes #9
> Simple file server

- net/bufio_test.ts
- net/http.ts
- net/http_test.ts
Allow reading request body & streaming request.
Added 2 methods to `ServerRequest`: `bodyStream` (returns an async iterator for chunks) and `body` (returns a collected Uint8Array of body)
Added 1 method to `BufReader`: `readFull` (corresponding to [`io.ReadFull`](https://golang.org/pkg/io/#ReadFull) of Golang. We don't have `io` implemented so this is placed directly at `BufReader` for now)
e.g. Echo http server
```typescript
import * as deno from "deno";
import { serve } from "./http.ts";
const addr = deno.args[1] || "127.0.0.1:4500";
const server = serve(addr);
async function main(): Promise<void> {
for await (const request of server) {
const body = await request.body();
await request.respond({ status: 200, body });
}
}
main();
```
> Request body & Streaming

- examples/gist.ts
- flags/README.md
- flags/example.ts
- flags/index.ts
- flags/tests/all_bool.ts
- flags/tests/bool.ts
- flags/tests/dash.ts
- flags/tests/default_bool.ts
- flags/tests/dotted.ts
- flags/tests/kv_short.ts
- flags/tests/long.ts
- flags/tests/num.ts
- flags/tests/parse.ts
- flags/tests/short.ts
- flags/tests/stop_early.ts
- flags/tests/unknown.ts
- flags/tests/whitespace.ts
This PR removes default export from `flags` module and replaces it with `parse` named export.
> Remove default export from flags module

- net/textproto.ts
- net/textproto_test.ts
This avoids crashing on suddenly terminated connections.
Before:
```
$ deno net/http_bench.ts --allow-net &
[2] 40718
$ telnet 127.0.0.1 4500
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> ^C
TypeError: Cannot read property 'byteLength' of null
at readMIMEHeader (file:///Users/kevinqian/Desktop/Programming/Deno/deno_std/net/textproto.ts:75:14)
[2]-  Exit 1                  deno net/http_bench.ts --allow-net
```
After:
```
$ deno net/http_bench.ts --allow-net &
[1] 41093
$ telnet 127.0.0.1 4500
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^]
telnet> ^C
$ pkill deno # this means deno server is still up and running just fine
[1]+  Terminated: 15          deno net/http_bench.ts --allow-net
```
> Avoid textproto crashing on empty reader

- path/index.ts
- path/parse_format_test.ts
Otherwise I'm getting this with latest native ES module refactoring PR:
```
/Users/kevinqian/.deno/deps/https/deno.land/x/std/path/index.ts:1425:1 - error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.
1425 export = module;
~~~~~~~~~~~~~~~~
```
(Probably because we are changing TS compiler target from AMD to ESNext?)
> Remove export = module 

- testing/mod.ts
As discussed in https://github.com/denoland/deno/pull/1355 and https://github.com/denoland/deno/pull/1363, this PR uses `groupCollapsed` method for printing the status of a test in the same line as its name.
The output looks like the below:
When it has an error:
> Print test status on the same line as test name

- azure-pipelines.yml
- media_types/deps.ts
Fixes the importing of JSON.  Requires a build of Deno that includes denoland/deno#1514 (e.g. current `master`).
Upgrading to a version of Deno that includes ESM will "break" `media_types` and the other patch and this one will "fix" it.
> Fix media_types running under Deno with ESM

- testing/README.md
- testing/mod.ts
- testing/test.ts
This PR improves `assert` in the `testing` module.
It decorates the `assert` function with three additional functions for assertion:
* `assert.equal()` - This is the same as `assertEqual()` already present.
* `assert.strictEqual()` - This checks that `actual` and `expected` are strictly equal.
* `assert.throws()` - This takes a function which is expected to throw.  If it does not, then the assertion will throw.  It can also take optional error class, where the class of the thrown error is checked, and a string which should be included in the thrown error message.
> Improve assert

- test.ts
- testing/main.ts
- testing/mod.ts
> Do not automatically run tests

- testing/mod.ts
- testing/test.ts
Introduces these two:
```ts
fail('some message'); // equivalent to assert(false, msg)
assert(throws(fn), true);
```
For now, `throws` returns a boolean and is expected to be used with `assert` just like `equal`.
If we want node compatibility, see #122 (`throws` does the assertion and throws the assertion error in node rather than returning a bool).
> testing: introduce `fail` function

- format.ts
- log/handlers_test.ts
- log/logger_test.ts
- log/mod.ts
- log/test.ts
This is a fix for the @hayd's [comment](https://github.com/denoland/deno_std/pull/156#discussion_r251283970). When a file is deleted and not staged, the formatter crashes when try to format that deleted file. This change skips formatting those files. (The diffs under //log directory are just the result of formatting, not relevant)
> Skip formatting of deleted files

- colors/README.md
- colors/mod.ts
Ref denoland/deno#1716 and #175 
This PR support `deno.noColor` disabling any coloring. It'd be good to test it, but currently there is no way to override `noColor` in tests. Any ideas?
Depends on: #181
> support NO_COLOR in colors module

- http/server.ts
- http/server_test.ts
- ws/mod.ts
- ws/test.ts
- made `acceptWebSocket`, `acceptable` independent from `ServerRequest`
- These are still compatible with existing code
- made `ServerRequest` more stateless
- add tests for `acceptable`
- reformated
>  refactor: make acceptWebSocket independent from ServerRequest

- log/handlers.ts
Add different colors to log messages by levels
> Add colors to log module

- http/server.ts
- http/server_test.ts
- Use only pathname for matching instead of full url
- Fixed url match logic for regular expression
Currently, both `"/foo"` and `"/bar/foo"` are matched to `/\/foo/` and the later is used because it is longer than the former. This is correct but strange behavior for url routing. I changed logic of evaluation for priority of matches:
- Matches with the earliest index (RegexMatchArray.index) is prior to others.
- The longest match is picked from them.
With this logic,
- `"/foo"` is prior to `"/bar/foo"` because the former matched to `/\/foo/` at index 0.
- `"/foo/bar"` is prior to `"/foo"` because the former has longer match than the later.
> fix: url match logic of http server

- testing/mod.ts
This PR adds `runIfMain` method to `testing` module. 
Ref #152.
Usage: 
```ts
// test.ts
import { test, runIfMain, assertEqual } from "https://deno.land/x/testing/mod.ts";
test(function simple() {
const a = 1;
assertEqual(a, 1);
});
runIfMain(import.meta);
```
Then if you do:
```
$ deno test.ts
Compiling file://dev/test.ts
Compiling file://dev/deno_std/testing/mod.ts
running 1 tests
test simple ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
> Add runIfMain method

- testing/mod.ts
Specifically, don't throw an exception when the tests fail,
instead return with exit status 1.
Before:
After:
> Clean up the test failure output

- fs/walk.ts
In fs.walk there is 2 loops with `for of` which is known to be slower than the classic `for` loop.
https://github.com/denoland/deno_std/blob/master/fs/walk.ts#L34
https://github.com/denoland/deno_std/blob/master/fs/walk.ts#L74
For example this snippet:
```javascript
const NS_PER_SEC = 1e9;
var t = [];
for (var i = 0; i < 5000; i++) {
t.push(Math.floor(Math.random() * Math.floor(666)))
}
var start = process.hrtime();
for (let f of t) {
if (true) {
continue;
}
}
var diff = process.hrtime(start);
console.log(`Benchmark took ${diff[0] * NS_PER_SEC + diff[1]} nanoseconds`);
var start2 = process.hrtime();
for (var i = 0; i < t.length; i++) {
var f = t[i];
if (true) {
continue;
}
}
var diff2 = process.hrtime(start2);
console.log(`Benchmark took ${diff2[0] * NS_PER_SEC + diff2[1]} nanoseconds`); …
```
> fs.walk performance improvement

- colors/test.ts
While testing for the color module the colors are disabled and not re-enabled. So unit tests of the deno_std are done without colors.
Just fixed it.
> Re-enabling colors after color testing

- testing/bench.ts
- testing/format_test.ts
- testing/mod.ts
- testing/test.ts
Defaults to serial execution.
Test parallel with `runTests({ parallel: true })`.
Run `deno ./testing/bench.ts` for a simple comparison.
> feat: parallel testing

- media_types/db_1.38.0.json
- media_types/deps.ts
mime-db@1.38.0 [was released on 2019-02-04](https://github.com/jshttp/mime-db/blob/master/HISTORY.md). This updates the JSON file.
> Update mime-db to 1.38.0

- azure-pipelines.yml
- fs/globrex.ts
- fs/globrex_test.ts
- fs/path/constants.ts
- fs/walk_test.ts
- prettier/util.ts
This PR replaces Deno.platform.os usages with Deno.build.os. It is renamed in https://github.com/denoland/deno/pull/1879 and included in [v0.3.2](https://github.com/denoland/deno/blob/master/Releases.md#v032--20190306)
> fix: replace Deno.platform with Deno.build

- examples/cat.ts
- fs/glob.ts
- fs/glob_test.ts
- fs/walk.ts
- fs/walk_test.ts
- http/file_server.ts
- http/http_bench.ts
- http/server.ts
- io/bufio.ts
- io/bufio_test.ts
- io/iotest.ts
- io/ioutil.ts
- io/ioutil_test.ts
- io/readers.ts
- io/util.ts
- io/writers.ts
- log/handlers.ts
- multipart/multipart.ts
- ws/mod.ts
'deno' builtin module is going to be removed soon ( https://github.com/denoland/deno/pull/1895 ). This PR replace those usages with Deno global variable.
> Replace remaining "deno" module usages with Deno global var

- fs/ensure_dir.ts
- fs/ensure_dir_test.ts
- fs/ensure_file.ts
- fs/ensure_file_test.ts
- test.ts
part of #261
Because `ensureFile` depends on `ensureDir`
so. put them in one PR
> feat: add ensureDir/ensureFile for fs modules

- fs/write_json.ts
- fs/write_json_test.ts
- test.ts
> feat: add writeJson/writeJsonSync for fs modules

- strings/pad.ts
- strings/pad_test.ts
- test.ts
Added string pad helper in strings. Shorthand for combination of str.padStart / str.padLeft / str.slice / str.substring.
Was needing this for a console reporter, so added it in deno_std. Maybe some opinions on the naming?
Usage:
```ts
pad("deno", 6, { char: "*", side: Side.Left }) // output : "**deno"
pad("deno", 6, { char: "*", side: Side.Right}) // output : "deno**"
pad("denosorusrex", 6 {
char: "*",
side: Side.Left,
strict: true,
strictSide: Side.Right,
strictChar: "..."
}) // output : "den..."
pad("denosorusrex", 6, {
char: "*",
side: Side.Left,
strict: true,
strictSide: Side.Left,
strictChar: "..."
}) // output : "...rex"
```
> Added string pad

- prettier/main.ts
- prettier/main_test.ts
- prettier/testdata/opts/0.ts
- prettier/testdata/opts/1.ts
- prettier/testdata/opts/2.ts
- prettier/testdata/opts/3.md
This PR adds 9 JS/TS styling options and 1 markdown styling option to `//prettier/main.ts`. These are at this moment all of the options prettier provides in relevant scope of deno. (JSX and html styling options are intentionally excluded.)
---
closes #236
> Add prettier styling options

- flags/all_bool_test.ts
- flags/bool_test.ts
- flags/dash_test.ts
- flags/default_bool_test.ts
- flags/dotted_test.ts
- flags/kv_short_test.ts
- flags/long_test.ts
- flags/num_test.ts
- flags/parse_test.ts
- flags/short_test.ts
- flags/stop_early_test.ts
- flags/test.ts
- flags/unknown_test.ts
- flags/whitespace_test.ts
Should follow the [style guide](https://deno.land/style_guide.html#unittestsshouldbeexplicit).
> Each module should come with its test as a sibling with the name modulename_test.ts. For example the module foo.ts should come with its sibling foo_test.ts.
> move test file out of tests dir in flags module

- datetime/test.ts
- testing/asserts.ts
- testing/asserts_test.ts
This fixes : https://github.com/denoland/deno_std/issues/304
Had to add a special case in `equal` for `RegExp` and `Date` objects. Also fixed assertion in the datetime module.
> assertEquals fix

- testing/README.md
- testing/mod.ts
Following : https://github.com/denoland/deno_std/issues/306
Add a parameter to handle `exitOnFail` in `runTests()` with default value: true to not change the API. Updated documentation also.
Also i think maybe a refactor of the test runtime to a Class in a further PR would be a good idea.
> Testing : exitOnFail

- testing/bench_test.ts
- testing/test.ts
This addresses https://github.com/denoland/deno_std/issues/316#ref-pullrequest-426836589
> fix: Benchmarks not returning on deno 0.3.4+

- toml/README.md
- toml/parser.ts
- toml/parser_test.ts
- toml/testdata/inlineTable.toml
this adds the full support of inline table (even nested see tests):
```toml
animal = { type = { name = "pug" } }
animal = { type.name = "pug" }
animal.as.leaders = "tosin"
"tosin.abasi" = "guitarist"
"tosin.abasi" : "guitarist"
```
> [TOML] Full support of inline table

- http/http_bench.ts
Just realized that we have been awaiting here all the time... Essentially blocking next accept of connection due to `await`ing writes... Removing this `await` more accurately reflect the actual possible performance, and notice the drop of tail latency.
Tested with `wrk -d 10 http://localhost:4500` on my machine:
Before:
```
Running 10s test @ http://localhost:4500
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    12.29ms   30.71ms 273.26ms   89.79%
Req/Sec    10.84k     3.41k   21.87k    73.00%
215872 requests in 10.01s, 10.29MB read
Requests/sec:  21573.06
Transfer/sec:      1.03MB
```
After
```
Running 10s test @ http://localhost:4500
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   363.19us  163.29us …
```
> Remove `await` from respond in http_bench.ts

- fs/ensure_dir.ts
- fs/ensure_dir_test.ts
- fs/ensure_file.ts
- fs/ensure_file_test.ts
- fs/utils.ts
- fs/utils_test.ts
eg.
when `filepath` is exists and not a file. e.g a folder. it will throw error
same as `ensureFile`
> fix: ensure exists file/dir must be the same type or it will throw error

- fs/eol.ts
- fs/eol_test.ts
- fs/test.ts
As files may be used in a Linux env but may come from a windows env, EOL is not the same. Added a FS helper for the detection / format. ATM it gets a string input, maybe coupled with readFileStr ( https://github.com/denoland/deno_std/pull/276 ) in the future?
> Added EOL detect / format

- testing/main.ts
> Remove second call to `runTests`

- http/racing_server.ts
- http/racing_server_test.ts
- http/server.ts
- http/server_test.ts
- http/test.ts
+ Using a `Map` to track pipelined requests and resolve only when the previous request is responded.
+ Added test (`racing_server_test.ts`). This test have been confirmed to fail before this patch.
Slight performance impact, yet tail latency is still about the same:
Before:
```
Running 10s test @ http://localhost:4500
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   382.03us  216.38us   6.15ms   94.04%
Req/Sec    13.63k     1.64k   15.48k    86.14%
274043 requests in 10.10s, 13.07MB read
Requests/sec:  27133.13
Transfer/sec:      1.29MB
```
After:
```
Running 10s test @ http://localhost:4500
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   388.00us  176.04us   2.82ms   93.29%
Req/Sec    13.18k   832.27 …
```
> Enforce HTTP/1.1 pipeline response order

- README.md
- fs/README.md
Added links to module documentation.
Added fs documentation.
Mention to @axetroy , could you provide an explanation for the options of `writeJson` module options please?
> doc: Add missing documentation

- flags/mod.ts
- fs/README.md
- prettier/main_test.ts
- testing/main.ts
- toml/parser.ts
Just cleaned the typing which will make eslint not warn anymore in addition to https://github.com/denoland/deno_std/pull/326 .
Fixed a typo in the documentation.
Because https://github.com/denoland/deno_std/pull/276 has landed, little refactor in the TOML module.
**EDIT**: for the `flags/mod.ts` i have tried to fix it but can't really find a way. I'm not sure to add `eslint ignore` tag is a good solution. For the moment keeping it like this and we'll see if we find a solution after.
> Typo/refactor : Eslint warnings + updates with PR

- fs/README.md
- fs/mod.ts
- fs/test.ts
- fs/write_file_str.ts
- fs/write_file_str_test.ts
refs: #261 , https://github.com/denoland/deno_std/pull/276#issuecomment-482920939
@zekth
> add writeFileStr and update documentation

- flags/README.md
In the flags module, there was a missing example of using the **options['--']**, even though there was a mention of having an example by stating '_Here's an example:_'. @ry
> Docs: Added missing example in flags module - README.md

- fs/ensure_link.ts
- fs/ensure_link_test.ts
- fs/mod.ts
> feat: add ensureLink/ensureLinkSync for fs

- toml/README.md
- toml/parser.ts
- toml/parser_test.ts
Feel free to close if this is not the right direction
> Remove parseFile from toml

- datetime/mod.ts
- datetime/test.ts
- http/README.md
- http/cookie.ts
- http/cookie_test.ts
Add `delCookie` and `setCookie`.
I have a concern about the multiple `Set-Cookie` header. It's common to use BUT `Headers` does not give us the possibility to do this. Do you think any workaround is possible? I think we can keep it like this for the moment and work on multiple `Set-Cookie` headers handling in a future PR.
Also Days / Months format are hardcoded in the module because ATM there is some discussions about embedding or not the ICU in Deno which may break this module. Ref: https://github.com/denoland/deno/issues/1968
> http: Cookie extend

- textproto/mod.ts
- textproto/reader_test.ts
- textproto/test.ts
Porting the test from https://github.com/golang/go/blob/master/src/net/textproto/reader_test.go as @ry suggested.
ref: https://github.com/denoland/deno_std/issues/363
Also there is 3 problems atm:
First one is the HTTP header line break. If we check in the RFC2616 ( https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.3 ) the standard line terminator is `CRLF`. It also says: 
```
The line terminator for message-header fields is the sequence CRLF. However, we recommend that applications, when parsing such headers, recognize a single LF as a line terminator and ignore the leading CR.
```
Problem is in `bufio` we `readLine` using charCode('\n') which is not standard for HTTP headers.
https://github.com/denoland/deno_std/blob/master/io/bufio.ts#L238
In the golang tests, as i read it …
> [textproto] test porting

- bytes/bytes.ts
- bytes/bytes_test.ts
`bytesFindIndex` and `bytesFindLastIndex` in `deno_std/bytes` cannot find the binary pattern when its occurrence has an overlap with a partly (but not completely) matching sequence.
- target: `001`
- pattern: `01`
- expected `bytesFindIndex` result: `1`
- current `bytesFindIndex` result: `-1`
Existing test cases are edited to reproduce the bug: https://github.com/arcatdmz/deno_std/commit/fe9d5b47ccb89c1244c54bf04dfbb941f65ac657
Two corresponding tests fail accordingly: https://gist.github.com/arcatdmz/08ae107dd5e29e2aaebf18e1d8b76d43
This pull request contains a commit that fixes the bug: https://github.com/arcatdmz/deno_std/commit/1251423f5b18bc12e2821862825f0a95a99edee7
- I am writing a web server that accepts `multipart/form-data` posted by a web browser client.
- The server crashes …
> [bytes] fix bytesFindIndex and bytesFindLastIndex

- testing/bench.ts
Due to inactivity of https://github.com/denoland/deno_std/pull/253
Pushing this as it's revelant to have it now.
> Bench: replace Date.now with Performance.now

- datetime/mod.ts
- datetime/test.ts
ToIMF was not using the UTCday.
Thanks @ry for finding it.
> [datetime] UTC date fix ToIMF

- fs/glob_test.ts
- fs/walk.ts
- fs/walk_test.ts
- prettier/main.ts
- prettier/main_test.ts
walk() made extensive use of `FileInfo.path` which will be removed in future versions. 
cc @kt3k 
Note: this is necessary to bump CI to v0.5 https://github.com/denoland/deno_std/pull/393
Necessary for https://github.com/denoland/deno/pull/2313 too
> walk() should not use deprecated FileInfo.path

- ws/mod.ts
- ws/test.ts
> ws: make acceptable() more robust

- textproto/mod.ts
- textproto/reader_test.ts
fix https://github.com/denoland/deno_std/issues/409
So the problem was in this http headers:
```
Host: localhost:8000
Connection: keep-alive
Content-Length: 136
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: a5b88a02-b7af-2296-42ba-a9c33ed4206f
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryimeZ2Le9LjohiUiG
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Content-Disposition: form-data; name="test"
<- There is a space character here
------WebKitFormBoundaryimeZ2Le9LjohiUiG--
```
So the reader was continuing to read or it was the end of the …
> Fix #409 handle multipart header in mime reader

- http/server.ts
- http/server_test.ts
fix: https://github.com/denoland/deno_std/issues/427
Also deleted `conn` property of `ServerRequest` because it's not used anymore and it's not in the request struct of golang:
https://github.com/golang/go/blob/1d1ba85d9986bb56226046c06dec4ce63ef9fe48/src/net/http/request.go#L107
> [http] delete conn parameter in readRequest

- http/file_server.ts
- http/file_server_test.ts
https://github.com/denoland/deno_std/issues/425
> fix(fileserver):wrong url href of displayed files

- http/server.ts
- http/server_test.ts
This is meant to fix : https://github.com/denoland/deno/issues/2346
It's not that pretty but ATM i haven't found any other way to do it.
So if, there is an issue in the request with malformed headers or encrypted due to HTTPS, an error is attached to the server request, if there is a respond of it the ServerResponse is automaticaly rewritten.
This fixes bad headers and wrong protocol (somehow). The problem with https is we got : `ssl3_get_record:wrong version number` because the client is trying to do the handshake.
**Note**: i've noticed we have multiple set of `new TextEncoder()`. Would it be better to have it as a const in the module?
> [http] add handling of bad request

- http/server.ts
- http/server_test.ts
- io/bufio.ts
> Set http response body as empty by default

- fs/glob.ts
- fs/glob_test.ts
> Added isGlob function

- http/server.ts
- http/server_test.ts
As mentionned in : https://github.com/denoland/deno_std/pull/419
Fixing readRequest for the content length chekcking.
Note: https://github.com/denoland/deno_std/compare/master...zekth:fix_readRq?expand=1#diff-58b0092e6441ae4b79fb3069e2ba21ddR359
This one is still not working because of the trimming of the `kv` in textproto:
https://github.com/denoland/deno_std/blob/master/textproto/mod.ts#L114
I think it can stay like this for the moment
> [http] fixing content-length checking

- http/README.md
Some cosmetic fixes to the provided examples in the http README:
- Ensure they're all actually runnable
- Use clear variable names
- Add usage of Cookie interface
> Fix http README examples

- bytes/bytes.ts
- bytes/bytes_test.ts
- bytes/test.ts
- test.ts
1. fix #445
2. add bytesRepeat for `bytes`
Because I need `bytesRepeat()` in the other modules, and it is also the Go module https://golang.org/pkg/bytes/#Repeat.
> add bytesRepeat

- prettier/main.ts
close #424
Thanks to @dshubhadeep for #433
support `specified files` mix with `glob`
```bash
> deno run prettier/main.ts script1.ts script2.ts **/**/test.ts
```
This allows to directly specify a file to be formatted.
```bash
> deno run prettier/main.ts test.ts
Formatting test.ts
Formatting fs/test.ts
Formatting fs/copy_test.ts
Formatting fs/empty_test.ts
...
```
> only format the `test.ts`
```bash
> deno run prettier/main.ts test.ts
Formatting test.ts
```
/cc @kt3k
> Prettier: support for specified files and glob mode

- http/server.ts
- http/server_test.ts
Add port of ParseHttpVersion: https://github.com/golang/go/blob/f5c43b9/src/net/http/request.go#L766-L792
> [http] add ParseHTTPVersion

- http/README.md
Hi 👋
I was just exploring deno and accidentally found a small mistake, this fixes a typo on the file server alias in README.
> add "run" to file server alias

- http/server.ts
- http/server_test.ts
Add handling of RFC 7230:
https://tools.ietf.org/html/rfc7230#section-3.3.2
```
A sender MUST NOT send a Content-Length header field in any message
that contains a Transfer-Encoding header field.
```
> [http] add rfc7230 handling

- fs/copy_test.ts
Deactivate flaky test on MacOs
refs:
https://github.com/denoland/deno/issues/2411
https://github.com/denoland/deno_std/issues/421
> [fs] deactivate copy assertion

- README.md
- encoding/README.md
- encoding/csv.ts
- encoding/csv_test.ts
- fs/copy_test.ts
Ported https://github.com/zekth/deno_easyCSV to encoding/csv.
Also added the possibility to use `BufReader` as input and not only `string`.
ref: https://github.com/denoland/deno_std/issues/455
> [encoding] add csv parse

- ws/mod.ts
I tried to communicate with deno_std WebSocket Client and a WebSocket Endpoint of Chrome DevTools, but handshake was rejected by Chrome.
I had to add a `sec-websocket-version` field to the request header to fix this.
According to the RFC, `sec-websocket-version` is required for the WebSocket Client implementation.
> The request MUST include a header field with the name |Sec-WebSocket-Version|.  The value of this header field MUST be 13.
https://tools.ietf.org/html/rfc6455#page-60
cc: @keroxp
> [WebSocket] Add sec-websocket-version to handshake header

- prettier/main_test.ts
- test.ts
This PR:
- Uses temp dirs in prettier/main testing.
- Checks file changes after the test run.
---
closes #408
> Check file changes during test

- testing/asserts.ts
I noticed the some assertions included logging to `console.error`.  This doesn't make any sense and generally didn't include any more information than what would be contained in the `AssertionError`, it also causes content to get logged to console which may not be intended, like when wrapping an assertion and providing a better error message/condition to the user.  We should avoid being opinionated about what gets logged to the console in `std`.  If there are critical data (like raw "expected" and "actual" or the type of assertion made) they should be added to `AssertionError` so that consumers have the ability to control how the error is handled.
> Remove console.error from asserts.

- fs/README.md
Property `path` does not exist on type `WalkInfo`. `filename` should be used instead in the example
> fix wrong field name

- installer/mod.ts
> installer: Print name of installed file

- testing/mod.ts
Following : https://github.com/denoland/deno_std/issues/306
Here is a proposal of pretty output for tests (for more readability):
Also added the option for `disableLogs` in the test. It is usefull for CI when there is still debug in the tests, then you directly have information of which tests is buggy and you're not flooded with all the debug logs. Currently it is set to `false` and only work for `serialTesting`. Do you think this is usefull and should i expand it to parallel? (needs a bit more refactor)
I've added the timers on each tests and on the whole runtime. See:
Added on Silent mode the display of the currently running TEST:
> [Testing] Pretty output + Silent mode

- bundle/test.ts
- bundle/utils.ts
> bundle/run handles Deno.args better.

- .ci/template.linux.yml
- .ci/template.mac.yml
- .ci/template.windows.yml
CI broke today, seems like problem is in unpinned version of eslint, [reference](https://github.com/typescript-eslint/typescript-eslint/issues/637)
This PR temporarly pins version of ESlint
> fix: pin eslint version for CI

- testing/README.md
Typo: `comparision` -> `comparison`
> Correct text, fix #519

- azure-pipelines.yml
> ci: bump deno to v0.10.0

- archive/tar.ts
- azure-pipelines.yml
- encoding/csv.ts
- fs/empty_dir_test.ts
- http/file_server_test.ts
- http/racing_server_test.ts
- http/server.ts
- http/server_test.ts
- installer/test.ts
- io/bufio.ts
- io/bufio_test.ts
- io/iotest.ts
- io/ioutil.ts
- io/ioutil_test.ts
- io/readers.ts
- io/readers_test.ts
- mime/multipart.ts
- mime/multipart_test.ts
- textproto/mod.ts
- textproto/reader_test.ts
- ws/mod.ts
This PR updates the Reader interface based on the change introduced by https://github.com/denoland/deno/pull/2591
> [WIP] io: update Reader interface

- fs/empty_dir.ts
- fs/empty_dir_test.ts
fixes: https://github.com/denoland/deno_std/issues/530
> fix emptydir on windows

- examples/catj.ts
- examples/gist.ts
- format.ts
- http/file_server.ts
- installer/mod.ts
- prettier/main.ts
- test.ts
- testing/test.ts
- uuid/test.ts
Fixes #544
This makes the shebangs work with GNU coreutils 8.30+ where /usr/bin/env supports the '-S' option.
It should still work with macOS based on the manual pages I've read but can I get verification on this?
> Make shebangs Linux compatible

- http/racing_server.ts
- http/racing_server_test.ts
- http/server.ts
- http/server_test.ts
- http/testdata/simple_server.ts
- http/util.ts
- util/async.ts
This PR fixes the case described in #442. The test case reproduces the case given by @MarkTiedemann in the comment ( https://github.com/denoland/deno_std/issues/442#issuecomment-495557424 ).
This change simply ignore the error when the writing failed.
I believe the corresponding part of go's std library is [here](https://github.com/golang/go/blob/1962dc88eb89cd37d3f9f85e8e4b7ad4915db089/src/net/http/server.go#L1858).
```go
fmt.Fprintf(c.rwc, "HTTP/1.1 "+publicErr+errorHeaders+publicErr)
```
This doesn't handle the error returned by `fmt.Fprintf`. So this patch follows the above.
closes #442
> Ignore error of writing responses to aborted requests

- examples/test.ts
- http/file_server_test.ts
- http/racing_server_test.ts
- installer/mod.ts
- installer/test.ts
This is convenient when you want to test deno_std with a special build of deno.
> Use Deno.execPath where possible

- testing/mod.ts
- testing/test.ts
> feat: add overloaded form of unit test declaration

- testing/runner.ts
Otherwise test runner is not working properly when requested from remote server:
```
// run in root of deno_std repo
$ deno -A https://deno.land/std/testing/runner.ts 
Download https://deno.land/Users/biwanczuk/dev/deno_std/strings/pad_test.ts
error: Uncaught TypeError: Import 'https://deno.land/Users/biwanczuk/dev/deno_std/strings/pad_test.ts' failed: 404 Not Found
```
It's caused because `base` for specifier is a remote script (`https://deno.land/std/testing/runner.ts`) and found test files are absolute paths (`/Users/biwanczuk/dev/deno_std/strings/pad_test.ts`).
I explicitly added `file://` prefix to import, that should resolve the problem.
> fix: add file:// prefix for imports in test runner

- http/file_server.ts
Closes #557.
Also some refactors:
- `path` utility functions are used where appropriate.
- I had some difficulty along the way with some variable names so I made them more consistent. A `filePath`/`dirPath`  is an absolute FS path to a file or directory, whereas `fileUrl`/`dirUrl` is a syntactically absolute path but relative to the served root, consistent with `req.url`. The latter were confusingly called `fileName`/`dirName` before.
> Accept absolute root directories in the file server

- testing/mod.ts
After adding `deno test` command a new problem appeared.
If you try running `deno test` inside this repo test runner will find 80 test files but won't run any tests! This is caused by fact that `deno test` uses tagged version of standard library which causes `test` function available inside to repo to be different function that `test` available in standard lib used by `deno test`.
```
~/src/deno_std> deno test -A
Found 79 matching test files.
Hello world!
running 0 tests
test result: OK. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (0.34ms)
```
A simple fix appears to be to add a global registry of all tests. It causes to register every test (even using `test` function from different version of standard lib) in the same global array that can be picked up by test runner. …
> fix: add global test registry

- testing/mod.ts
We have 575 tests and it is a problem to scroll up the terminal to see which tests failed.
So I added a summary of all the failed tests down under with a red label next to them.
These changes will only affect cases when we have failed tests (If all tests pass, it will look like before.) 
Also some refactoring to use existing `TestResult` model and populate it with the test results. We only initialized it before when going Serial testing and could not extract the details from each test afterwards.
proposed look :
> print out the failed tests after the summary

- testing/runner.ts
- testing/runner_test.ts
> fix: better paths handling in test runner

- multipart/formfile.ts
- multipart/formfile_test.ts
- util/has_own_property.ts
- ws/mod.ts
see https://github.com/denoland/deno/pull/2144
> Avoid prototype builtin `hasOwnProperty`

- ws/mod.ts
Refactor code to use `crypto.getRandomValues` and remove TODO
> Remove TODO in ws createMask

- flags/mod.ts
- flags/parse_test.ts
> flags: Parse builtin properties

- fs/copy_test.ts
- fs/ensure_symlink_test.ts
- http/file_server_test.ts
- installer/mod.ts
- installer/test.ts
Deno.platform was deprecated and it was reorganized into Deno.build at https://github.com/denoland/deno/pull/1879 . This PR replaces Deno.platform usages with Deno.build.
> Replace Deno.platform usages

- prettier/prettier.ts
- prettier/vendor/index.d.ts
- prettier/vendor/parser_babylon.d.ts
- prettier/vendor/parser_markdown.d.ts
- prettier/vendor/parser_typescript.d.ts
- prettier/vendor/standalone.d.ts
This PR adds types to `prettier`.
WARNING: types are for `1.18` version, while `prettier/` uses `1.17.1` version. I couldn't find types `1.18`, so it's a good idea to update prettier anyway.
This was suggested by @MarkTiedemann in denoland/deno#2490 and providing types significantly shortens time to compile prettier`
```
Before:
$ time deno --reload --no-prompt ../deno_std/prettier/main.ts
real	0m36.094s
user	0m43.474s
sys	0m1.148s
After:
$ time deno_dev --reload --no-prompt ../deno_std/prettier/main.ts
real	0m6.710s
user	0m10.205s
sys	0m0.232s
```
(Note that `after` is debug build, while `before` is `v0.17.0` release)
To get this to work we need to land denoland/deno#2910 first
> feat: Add types to prettier

- uuid/v4.ts
UUID v4 is not currently RFC4122 compliant, the `8` is hard-coded
https://github.com/denoland/deno_std/blob/d36bff3fbe22a3585d23213e3f4c9f58756c032b/uuid/v4.ts#L13
Loosely based of https://github.com/google/uuid/blob/master/uuid.go
Went with the cleanest approach to convert Uint8Array to string, I could unwrap looping since the array contains 16 elements, if needed.
Let me know if any changes are required I'll make them.
Related to and fixes #559
> Make uuid v4 rfc4122 compliant

- fs/walk.ts
- fs/walk_test.ts
Towards API improvements in the test runner (touched upon here https://github.com/denoland/deno/issues/2948#issuecomment-531471956).
Also just a useful feature.
Fixes outdated documentation. cc @bartlomieju.
> Add includeDirs to WalkOptions

- io/bufio.ts
- io/bufio_test.ts
> Implement readString

- encoding/toml.ts
- encoding/toml_test.ts
- Dumper is emitting invalid TOML format.
- Table names or keys should be wrapped with `""` if title contains characters except `A-Za-z0-9_-`
> fix: [toml] adapted to TOML's key encoding spec

- ws/mod.ts
- ws/test.ts
- feat: `wss` support with dialTLS
- fixed: Default port check by url.protocol was not working
> feat: [ws] wss support with dialTLS

- format.ts
- fs/README.md
- fs/glob.ts
- fs/glob_test.ts
- fs/globrex.ts
- fs/path/constants.ts
- fs/walk.ts
- fs/walk_test.ts
- prettier/main.ts
- testing/runner.ts
- testing/runner_test.ts
...properly. Fixes #576.
This had to be done from scratch unless we could utilise `globrex` somehow but I think it can be done by splitting paths and flat-mapping on each segment, applying `globrex` on individual segments. I also want to give it an `exclude` option so excluded directories won't be traversed - callers all want to exclude by path prefix anyway, this is currently done with a hacky `g` flag.
> Implement expandGlob()

- .github/workflows/ci.yml
This removes some dead branches in the lint job introduced in #681.
Lint doesn't actually run on matrix.os, only ubuntu-latest.
> build: remove matrix checks for lint job

- http/file_server.ts
- http/file_server_test.ts
- If the current dir is not root, show "../".
- Make dir end with "/"
- `Deno.stat()` no longer needs to catch errors. (The "mode" prop may not exist before, see https://github.com/denoland/deno_std/pull/15/files#diff-106086daad2313990285a9c61085eeb5995d479127db151e613f84ea709450c8R118
> feat(http/file_server): show .. if it makes sense & make dir end with /

- http/file_server.ts
- http/file_server_test.ts
- http/testdata/.dotfile
default:
with `--no-dotfiles`:
> feat(http/file_server): support do not show dotfiles

- node/process_test.ts
- node/testdata/process_exit.ts
The process exit test fixture is being run as a test, it uses console.log which adds to the noise produced by running deno test.
This moves it into testdata folder and drops the test suffix so that it doesn't run as a test.
> test(node): Prevent fixture from being run as a test

- io/ioutil.ts
I wasn't sure what to put for the `r` and `dest` parameters for `copyN` so i just put Reader and Writer.
Didn't add any description for `buf` parameters because it's very self explanatory.
> docs(io/ioutil.ts): add jsdoc

- hash/md5.ts
Use [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) is a good option for `a value is not of the expected type`
>  refactor(md5): throw `TypeError` for wrong type

- http/file_server.ts
If you use `file_server` to host a site with local svg files...
```html
```
...then the image does not show...
...because the browser assumes the XML media type, not the svg+xml type.
**This PR adds the correct `Content-Type` header to svg files, which fixes the problem.**
---
_(I also checked png and jpg, they work already because the browser can deduce the media type from the file headers)_
> fix(http/file_server): svg media type

- testing/asserts.ts
- testing/asserts_test.ts
From https://github.com/denoland/deno/pull/8063
Currently symbols equalities are not properly handled in `std/testing/asserts` because of the way objects are iterated in equality function (symbols are ignored):
https://github.com/denoland/deno_std/blob/b2c25026537afab2d1e29569f3b72c08cf947fd3/testing/asserts.ts#L153-L155
**Example**
```typescript
import { assertEquals } from "https://deno.land/std/testing/asserts.ts"
const foo = Symbol("foo")
Deno.test("symbol1", () => assertEquals({[foo]:"bar"}, {[foo]:"bar"}))             //Same symbol
Deno.test("symbol2", () => assertEquals({[foo]:"bar"}, {[Symbol("foo")]:"bar"}))   //Different symbols (should fail)
```
**Expected**
```
running 2 tests
test symbol1 ... ok (3ms)
test symbol2 ... FAILED (2ms)
test result: FAILED. 1 passed; 1 failed; 0 …
```
> fix(std/testing) : Handle Symbols correctly in deep equalities

- node/README.md
- node/module.ts
- node/module_test.ts
This PR adds `url` and `crypto` native module polyfills, and adds testing for checking native module polyfills. (url and crypto already exist but not polyfilled for `require`)
This PR also updates `node/README.md` to reflect the current state of std/node.
> feat(node): add url and crypto native module polyfills

- node/README.md
- node/module.ts
- node/module_test.ts
- node/tty.ts
- node/tty_test.ts
This PR implements `isatty` function of [tty](https://nodejs.org/api/tty.html) module of Node.js API.
A heavily dependent npm module [supports-color](https://www.npmjs.com/package/supports-color) uses this method. (ref: https://github.com/chalk/supports-color/blob/main/index.js#L150). This PR enables requiring `supports-color` in deno.
> feat(node): add tty module

- node/util.ts
`callbackify`, `promisify`, and `types` of `util` module wasn't exported as part of default export. This PR fixes it.
> fix(node/util): export promisify & callbackify

- hash/mod.ts
- node/crypto.ts
- node/crypto_test.ts
This PR adds crypto.createHash() method and related functions.
Many items are still missing, but this partial implementation covers the use case of [object-hash](https://www.npmjs.com/package/object-hash) npm module. object-hash is heavily depended by many modules, which include eslint-loader, nestjs, tailwindcss, [etc](https://www.npmjs.com/browse/depended/object-hash).
> feat(node): add crypto.createHash

- node/process.ts
- node/process_test.ts
This PR makes process.argv simply an array.
The current implementation simulates an array by using Proxy, but it doesn't support array methods and it causes problem in executing cli tools in npm.
In node.js, process.argv is just an array (ref 1: https://github.com/nodejs/node/blob/eed3c72/src/node_process_object.cc#L158, ref 2: https://github.com/nodejs/node/blob/eed3c72/src/env-inl.h#L601). So this PR change it to an array.
> fix(node/process): make process.argv an array

- node/_stream/readable.ts
- node/process.ts
This PR fixes type errors in canary test in main branch. TypeScript was updated in https://github.com/denoland/deno/pull/9341 yesterday, and probably that causes these errors.
> fix(node): fix type errors in canary test

- node/_stream/readable_internal.ts
- node/events.ts
- node/module.ts
- node/module_test.ts
In Node.js, EventEmitter is exported as both `require("events")` and `require("events").EventEmitter`, but latter is not exported in the current implementation. This PR fixes it.
> fix(node): fix export items of events

- encoding/_yaml/schema.ts
- examples/chat/server_test.ts
- fmt/printf.ts
- http/cookie_test.ts
- http/file_server.ts
- http/file_server_test.ts
- http/server.ts
- node/_crypto/pbkdf2_test.ts
- node/_crypto/randomBytes_test.ts
- node/_fs/_fs_access.ts
- node/_fs/_fs_dir_test.ts
- node/_fs/_fs_mkdtemp.ts
- node/_fs/_fs_readdir.ts
- node/_fs/_fs_watch_test.ts
- node/_stream/duplex_internal.ts
- node/_util/_util_callbackify_test.ts
- node/assert_test.ts
- node/assertion_error.ts
- node/crypto.ts
- node/events_test.ts
- node/os.ts
- testing/asserts.ts
- wasi/snapshot_preview1.ts
- wasi/snapshot_preview1_test.ts
- ws/mod.ts
The `no-unused-vars` rule is going to be enabled by default in deno_lint: https://github.com/denoland/deno_lint/pull/625
Once it's enabled, lots of errors will be flagged in deno_std. So in this PR, I address them beforehand.
> refactor: fix codes to pass `no-unused-vars` lint

- node/module.ts
- node/module_test.ts
This PR adds `require('module')` polyfill to our commonjs resolution logic.
fixes #771
> feat(node): add "module" polyfill

- node/assert.ts
This PR removes `msg` because this variable looks to be unused at all. 
This has been detected by `no-unused-vars` rule of deno_lint, which is going to be enabled soon.
ref: https://github.com/denoland/deno_lint/pull/625
> refactor(node): remove unused variable `msg`

- node/_fs/_fs_open.ts
- node/_fs/_fs_open_test.ts
- node/_fs/_fs_rename_test.ts
- node/_fs/_fs_rmdir_test.ts
- node/_fs/_fs_unlink_test.ts
this pr is to avoid the `node/fs` to import unnecessary fs modules.
> refactor(node/fs): update fs import

- node/_stream/duplex_test.ts
> chore: fix typo in duplex_test.ts

- node/cli.ts
This PR fixes an error of node/cli.ts. The first argument of createRequire needs to be a local path. In testing `import.meta.url` becomes a local file url, but when the user use [the released version](https://deno.land/std@0.90.0/node/cli.ts), that path becomes `https://...` url, and it doesn't work.
You can reproduce this error with the following command:
example.js
```
console.log(1);
```
```shellsession
$ deno run --unstable https://deno.land/std@0.90.0/node/cli.ts example.js
error: Uncaught InvalidData: invalid url scheme
throw new Deno.errors.InvalidData("invalid url scheme");
^
at fileURLToPath (https://deno.land/std@0.90.0/node/url.ts:53:11)
at createRequire (https://deno.land/std@0.90.0/node/module.ts:535:18)
at https://deno.land/std@0.90.0/node/cli.ts:62:17
```
> fix(node): fix node/cli.ts

- path/_util.ts
- path/from_file_url_test.ts
- path/posix.ts
- path/to_file_url_test.ts
- path/win32.ts
Previously part of denoland/deno#9276, std moved while it was open.
> fix(path): Enable and fix file URL tests

- encoding/README.md
- encoding/_yaml/example/sample_document.yml
- encoding/_yaml/parse_test.ts
- encoding/_yaml/schema.ts
- encoding/_yaml/schema/extended.ts
- encoding/_yaml/schema/mod.ts
- encoding/_yaml/stringify_test.ts
- encoding/_yaml/type/function.ts
- encoding/_yaml/type/mod.ts
- encoding/_yaml/type/regexp.ts
- encoding/_yaml/type/undefined.ts
- encoding/yaml.ts
This extends current YAML support with an `EXTENDED_SCHEMA` which supports `!!js/regexp`, `!!js/function` and `!!js/undefined` to remove current [Deno limitation](https://github.com/denoland/deno_std/tree/main/encoding#warning-limitations) (heavily based on [nodeca/js-yaml-js-types](https://github.com/nodeca/js-yaml-js-types) but reworked a bit to be more succint).
This also exposes the `Type` function (which is already implemented but not available to end-users) to allow the creation of custom types with `!tags` as defined in [YAML spec](https://yaml.org/spec/1.2/spec.html#tag/).
> feat(encoding/yaml): Add support for JS types and user types

- mime/multipart.ts
Broke as a result of https://github.com/denoland/deno/commit/c4709834b37640fd3c9d492123e6add904546573.
> fix(multipart): support useDefineForClassFields

- async/deferred.ts
Now typescript would infer type properly.
> property into method (converted type)

- .github/codecov.yml
- README.md
This PR configures codecov to ignore the coverage of `examples`. This PR also adds the badge of codecov in README.
ref: Ignoring Paths - https://docs.codecov.io/docs/ignoring-paths
> chore(codecov): ignore coverage of examples

- node/_fs/_fs_writeFile.ts
This code should violate `no-unsafe-finally`, but due to a bug of deno_lint, no lint error happens at the moment.
(This bug is fixed in https://github.com/denoland/deno_lint/pull/641)
In fact, if we run ESLint with `no-unsafe-finally` enabled, the following output is emitted:
```
111:16  error  Unsafe usage of ThrowStatement  no-unsafe-finally
✖ 1 problem (1 error, 0 warnings)
```
It looks like this `if (error) throw error;` could be moved out of the finally block. This patch did so to work around `no-unsafe-finally`.
> refactor(node): move `throw error` out of finally block to pass `no-unsafe-finally`

- archive/README.md
- archive/tar.ts
- archive/tar_test.ts
- encoding/_yaml/type/binary.ts
- encoding/binary_test.ts
- examples/catj.ts
- http/_io_test.ts
- http/file_server_test.ts
- http/server.ts
- http/server_test.ts
- io/buffer.ts
- io/buffer_test.ts
- io/bufio.ts
- io/bufio_test.ts
- io/ioutil_test.ts
- io/mod.ts
- io/readers.ts
- io/readers_test.ts
- io/streams.ts
- io/streams_test.ts
- io/util.ts
- io/util_test.ts
- mime/multipart.ts
- mime/multipart_test.ts
- node/_fs/_fs_exists_test.ts
- node/_fs/_fs_writeFile.ts
- node/_tools/setup.ts
- node/_utils.ts
- wasi/snapshot_preview1_test.ts
- ws/test.ts
This moves the `Deno.Buffer` and `Deno.readAll` / `Deno.readAllSync` /
`Deno.writeAll` / `Deno.writeAllSync` implementations to std, so we can
deprecate them in Deno 1.9, and remove them in Deno 2.0.
> feat: add io/buffer and io/util module

- encoding/csv_test.ts
We should strive for concise code. `void` and `Promoise<void>` return types are unnecessary boilerplate.
Discussion https://github.com/denoland/deno/issues/8832
> ref(encoding): Promise<void> return types are unnecessary boilerplate.

- fmt/printf_test.ts
Canary CI has been failing because of these test cases.
> fix(test): skip test cases which cause serde_v8 error

- node/buffer.ts
More aligned types in `TextEncoder` have required an update to `node/decode.ts` that should be backwards compatible.
> fix: handle upstream type changes

- encoding/_yaml/type/function.ts
- node/_fs/_fs_utimes_test.ts
deno_lint's `no-unused-vars` rule will be enabled (see https://github.com/denoland/deno_lint/pull/625). Before it comes, I've added underscore prefixes to unused variables.
> chore: add underscore prefix to unused variables

- testing/asserts.ts
- testing/asserts_test.ts
The type `Record<PropertyKey, unknown>` used in `assertObjectEquals()` does not accept interface types as an argument.
```ts
import { assertObjectMatch } from "https://deno.land/std@0.87.0/testing/asserts.ts";
interface NumberToken {
type: "number";
value: number;
}
const token: NumberToken = {
type: "number",
value: 15
};
assertObjectMatch(token, { type: "number" }); // doesn't work
type TNumberToken = {
type: "number";
value: number;
};
const typeToken: TNumberToken = {
type: "number",
value: 15
};
assertObjectMatch(typeToken, { type: "number" }); // works
```
The solution is to change `assertObjectMatch` first param from `unknown` to `any`.
> fix(testing): Function signature of assertObjectEquals() does not accept interfaces #741

- http/_io.ts
- http/file_server_test.ts
- io/util.ts
- io/util_test.ts
- node/_fs/_fs_futimes_test.ts
- node/crypto.ts
This moves the `Deno.iter` and `Deno.iterSync` implementations to std,
so we can deprecate them in Deno 1.9, and remove them in Deno 2.0.
> feat: add iter and iterSync to io/util

- testing/asserts.ts
- testing/asserts_test.ts
> fix(std/testing): equals does not differentiate undefined/absent keys

- io/streams.ts
- io/streams_test.ts
This adds `readableStreamFromReader` to `io/streams`.  This is quite useful when dealing with files and the new native HTTP bindings.  For example to "stream" a file from disk in a response you would do something like this:
```ts
import { readableStreamFromReader } from "https://deno.land/std/io/streams.ts";
for await (const conn of Deno.listen({ port: 8000 })) {
(async () => {
const httpConn = Deno.serveHttp(conn);
for await (const { request, respondWith } of httpConn) {
const file = await Deno.open("./big_file.zip", { read: true });
respondWith(new Response(readableStreamFromReader(file)));
}
})();
}
```
> feat(io/streams): add readableStreamFromReader

- fs/expand_glob.ts
- path/README.md
- path/glob.ts
- path/glob_test.ts
Closes #806
This add a `caseInsensitive` option to `globToRegExp`.
When `os` option (which defaults to current os) is set to `"windows"`, this option will be enabled by default as file system is case insensitive on it
> feat(path/glob): add caseInsensitive option

- node/fs.ts
There were a lot of `fs` apis which had been implemented, but not actually exported in the main `node/fs.ts`.
I also sorted everything, so it was easier to read the file tree and check everything was there.
> fix(node/fs): Actually export everything

- node/child_process_test.ts
Some tests for `node/child_process` fails at 7498d9da5505011e31c7eea00eeebf7266fd9927. :scream: This PR tries to fix those flaky tests.
> fix(node/child_process): Try to fix flaky tests

- .github/codecov.yml
codecov often reports failure status to the commit which has low coverage rate in diff, but we don't have such policy to reject such PRs. This PR disables that check from codecov.
ref: https://docs.codecov.io/docs/commit-status#disabling-a-status
> ci: disable codecov's patch status

- io/buffer.ts
- io/buffer_test.ts
- io/util.ts
- io/util_test.ts
I found I needed to read a range of a seekable file and felt that `readRange` and `readRangeSync` are good compliments to `readAll` and `realAllSync`, so I wanted to contribute them back to `std`.
This PR also cleans up the `Buffer()` init types to accept what is truly needed to init the buffer which eliminates the need for arbitrary type asserts.
> feat(io): add readRange, readRangeSync

- fs/walk.ts
- fs/walk_test.ts
This adds the root path to error object. I am not sure this is the way to go, maybe I should put it in the message?
Fix #863
> fix(fs): no root path in walk error

- node/README.md
- node/console.ts
- node/module.ts
This just exports the `console` object.
I tried enabling the Node console tests, but all of them either don't work or don't really apply.
Note that Deno's console doesn't have all the same methods as Node's, so this isn't a perfect polyfill. Node has these extra properties:
- `Console`
- `context`
- `profile`
- `profileEnd`
- `timeStamp`
I've marked it as partly implemented for now, although I don't know whether those APIs are worth polyfilling.
> feat(node): Add console module

- mime/multipart.ts
- mime/multipart_test.ts
Closes #672 
As mentioned in #672 there is current no way to where and how temporary files created by the reader are stored. In some cases storing temporary files in the current non-configurable location (the current working directory) is not possible or unacceptable for other reasons.
> feat(multipart): add options to readForm

- node/_stream/stream.ts
- node/stream.ts
- node/stream_test.ts
In Node, `require("stream")` returns `Stream` itself with all the other kinds of streams as properties. This maps to the default export for ESM, so I've changed the default export of `stream.ts` to be `Stream` and added all the other streams as properties.
> fix(node/stream): Make `Stream` the default export

- encoding/testdata/cargo.toml
- encoding/toml.ts
- encoding/toml_test.ts
Deleting double use of `string.replace` speeding up the parsing.
> encoding/TOML: delete useless replace

- http/_io.ts
- http/server.ts
- http/server_test.ts
Closes #664
As specified in the [rfc2616 spec](https://tools.ietf.org/html/rfc2616):
> HTTP status codes are extensible. HTTP applications are not required to understand the meaning of all registered status codes, though such understanding is obviously desirable. However, applications MUST understand the class of any status code, as indicated by the first digit, and treat any unrecognized response as being equivalent to the x00 status code of that class, with the exception that an unrecognized response MUST NOT be cached. For example, if an unrecognized status code of 431 is received by the client, it can safely assume that there was something wrong with its request and treat the response as if it had received a 400 status code. In such cases, user agents SHOULD present to the user the …
> feat(http): allow custom http codes along with custom response text

- testing/asserts.ts
- testing/asserts_test.ts
The filtered subset in `assertObjectMatch` is built with the following:
https://github.com/denoland/deno_std/blob/69183a05261b58870870b48e4191660b49212039/testing/asserts.ts#L502-L503
But because `typeof [] === "object"`, array values match this condition and we end up with the following:
```diff
{
-     foo: {
-       "0": 1,
-       "1": 2,
-       "2": 3,
-       length: 3,
-     },
+     foo: [
+       1,
+       2,
+       3,
+     ],
}
```
This add a skip for arrays to get the wanted behaviour
> fix(testing): support array values in assertObjectMatch

- .gitignore
After collecting coverage following directories are produced:
```
cov/
examples/cov/
fs/testdata/cov/
node/_tools/cov/
node/cov/
```
Added them to `.gitignore`
> chore: add coverage directories to gitignore

- io/bufio.ts
- io/bufio_test.ts
- This is bug from #867 
- @ry Sorry, would you see this?
> fix(io): readDelim returns wrong result if delim strides over chunks

- io/buffer.ts
- io/types.d.ts
This PR fixes type error of `io/buffer` in Deploy environment by inlining `Reader` / `ReaderSync` interafaces.
This enables deploy script using, for example, `encoding/yaml` module without type error with `deployctl run`. https://gist.github.com/kt3k/43e25efffc6e1c360fc64274ea0381eb
closes #907
> fix(io/buffer): make Buffer compatible with Deploy

- async/mux_async_iterator.ts
- async/mux_async_iterator_test.ts
Currently MuxAsyncIterator takes `AsyncIterableIterator<T>` as source of iterator, but `AsyncIterable<T>` is a more general form of async iterable data. This PR changes the signature of `add` method of MuxAsyncIterator from `add(iterator: AsyncIterableIterator<T>)` to `add(iterable: AsyncIterable<T>)` and makes it work with `AsyncIterable`s.
> feat(async/mux): takes AsyncIterable as source iterator

- async/README.md
- async/mod.ts
- async/tee.ts
- async/tee_test.ts
This PR adds the utility (`tee`) for branching the given async iterable into n copies.
This has been originally developed in https://github.com/kt3k/tee_async_iterable as part of file stream processing tool (which is not published yet).
> feat(async): add async/tee

- datetime/README.md
The README of `datetime` module has inconsistent format, like:
- single quotations and double quotations are mixed
- semicolon styles and non-semicolon styles are mixed
- in some code blocks, not `ts` but `js` is specified as a language. Moreover, some code blocks don't have a language specified, so they are not syntax highlighted
This PR fixes all of the above.
> docs(datetime): make README consistent in format

- encoding/binary.ts
- encoding/binary_test.ts
- Write `readExact` function for `encoding/binary`:
- Read from `reader` until the `Uint8Array` array is filled.
- If the reader reaches EOF, throws a `UnexpectedEof` error.
- Rewrite `getNBytes` to use `readExact`.
closes #651
> fix(encoding/binary): allow getNBytes to read until EOF

- encoding/binary.ts
- encoding/binary_test.ts
Okay, so found a potential bug in std:
```ts
import { varnum } from "https://deno.land/std@0.91.0/encoding/binary.ts";
const main = new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]);
const sub = main.subarray(4, 8);
console.log(varnum(sub, { dataType: "uint8" })); // logs 1
```
This PR should only affect varnum() and friends operating on Uint8Array subarrays where the offset is > 0.
I replaced all hardcoded 0 indices in the relevant functions with b.byteOffset to get the desired behavior of logging 5 in the above example.
I also added a test for my change (note that this only tests varnum, and not all the relevant functions).
> Bugfix / Inconsistency: Respect Uint8Array offsets

- node/_fs/_fs_watch.ts
This PR fixes the type error in fs.watch impl of std/node. This error is caused by the change of builtin API in https://github.com/denoland/deno/pull/10798
> fix(node/fs): fix type error in fs.watch impl

- node/perf_hooks.ts
- node/perf_hooks_test.ts
see https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_measurement_apis
> feat(perf_hooks): add basic node perf_hooks module

- path/README.md
First of all, thanks for the project and maintainers for this great system and libraries. I really love it.
I've copied the description of each method and add some example codes to complete the README of the `path` module while it's a bit difficult to find correct documentation of `path` module while it switches the implementation by running the platform. 
This is my first contribution and I could not find any style guide for README so let me know if there is something I should fix 👍
> docs(path): Rewrite README to fill examples

- testing/asserts.ts
- testing/asserts_test.ts
- `WeakMap` and `WeakSet` cannot be deeply compared (no `size`, `Symbol.iterator`, etc.)
- `WeakRef` can be dereferenced
Refs #949
> fix(equal): account for Weak* objects

- node/process.ts
- node/process_test.ts
This PR add `getOwnPropertyDescriptor()` to `process.env` in order to make it iterable.
> fix(node/process): make process.env iterable

- node/README.md
- node/_tools/config.json
- node/_tools/setup.ts
Currently the 'ignore' option in the configuration for the test runner is being ignored, causing edited test files to be regenerated when running the setup, deleting any manual changes and making it hard to track what files have been manually edited.
Additionally, the documentation about what this option actually did was not that clear, so that has been enhanced as well
> fix: Apply node test suite 'ignore' configuration when running tests

- mime/multipart.ts
It's good idea to specify custom headers: 
```ts
const buf = new Buffer();
const mw = new MultipartWriter(buf);
await mw.writeField("foo", "foo");
await mw.writeField("bar", "bar");
const f = await Deno.open(path.join(testdataDir, "sample.txt"), {
read: true,
});
const header = new Headers();
header.set("deno", "deno");
await mw.writeFile("file", "sample.txt", f, header);
await mw.close();
f.close();
```
> feat(mime): Add Custom content-type for MultipartWriter

- testing/asserts.ts
- testing/asserts_test.ts
This is an improvement which allows [using the function as a type guard](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) in addition to its runtime safety. See the following TS playground link for a comparison of before/after: [TS Playground](https://www.typescriptlang.org/play?target=99&strict=true#code/KYDwDg9gTgLgBAYwDYEMDOa4EEPFgSwgDsBRKKaOUGYIgE0zIqjgG8AoORYtGKAVwQxoACgC2wDCgDmwAFxxeUfEWkBKNpy6L+YPOMloZwNQG4tXGAAt8aAHREUEuAF44AIhxo8MQqXLQ7uZcAL7sYewA9ABU0ZzRcACyKADWwHAoRBm4BMRw1ijwKEL8KEhwtnBEEPBE-EjllPz0wABmKsB0dnAAkq1VNfH5VrTDFADuRHbxkeygkLBwrc1CftnesCQgtjBoAEJt0MAiWsUwpUgKzSnVkwA0WmJo0gD8Ckoq0g9qCgBuEPg6JouPh+iIzhdXC43M06G0OkCAD6IjIlMpQtx1BoaDjaCpggCET3UwLxcGJrgsZIABhCygp3AASVh0pAhdxUcDAISdfIQcmFBBWDJEACe1k+cAARvxavVGixYfCiJ1qcFtG …
> feat(testing/asserts): Use assertion signature for "assertExists"

- testing/_diff.ts
- testing/_diff_test.ts
- testing/asserts.ts
- testing/asserts_test.ts
This add a specialized tokenizer that is called when both operands are string before entering `diff()`, making changes in large strings assertions more visible.
A word diff has been implemented (similar to `git diff --word-diff`):
As the above is not practical when a lot of words have been changed, a multiline diff has also been implemented:
**Todo**
Closes #929
> feat(testing): improved strings diff

- .github/workflows/ci.yml
This PR cleans up CI settings by using the official `setup-deno` action.
> ci: use setup-deno gh-action

- path/glob.ts
**Description**
Hi!
This PR fixes the following error that I've been experiencing with [glob.ts](https://deno.land/std@0.99.0/path/glob.ts):
<details>
<summary>Error log</summary>
```bash
error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'never'.
groupStack.push("+");
~~~
at https://deno.land/std@0.99.0/path/glob.ts:219:25
TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'never'.
groupStack.push("@");
~~~
at https://deno.land/std@0.99.0/path/glob.ts:226:25
TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'never'.
groupStack.push("?");
~~~
at https://deno.land/std@0.99.0/path/glob.ts:234:27
TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'never'. …
```
> fix(path/glob): Fixed array type error in glob.ts

- http/cookie.ts
- http/cookie_test.ts
This PR changes the `toString` function for `Cookie` in order for `setCookie` to allow for `maxAge` with a value of `0`. This fixes #989
> fix: `setCookie` with `maxAge` of `0`

- io/bufio.ts
- io/bufio_test.ts
This PR changes the implementation of `readLines` to fix #986. It currently uses `readStringDelim` internally. This PR changes it to use `bufReader.readLine`, which already implements the correct handling of trailing new line.
closes #986
> fix(io/bufio): fix handling of trailing new line

- .github/workflows/ci.yml
- _util/os.ts
- browser-compat.tsconfig.json
- fmt/colors.ts
- path/glob.ts
- path/posix.ts
- path/win32.ts
- testing/asserts.ts
This PR fixes the current compiler errors emitted when using browser-compatible TypeScript modules without including the Deno namespace library in `compilerOptions.lib`.
---
There is a link to [contributing guidelines](https://github.com/denoland/deno/blob/de6e44794b7a95b6895a9aab907e01788820d18c/docs/contributing/style_guide.md#document-and-maintain-browser-compatibility) toward the end of the [Deno repo README](https://github.com/denoland/deno/tree/de6e44794b7a95b6895a9aab907e01788820d18c#contributing), which includes this:
> #### Document and maintain browser compatibility.
> 
> If a module is browser compatible, include the following in the JSDoc at the top of the module:
> 
> ```ts
> // This module is browser compatible.
> ```
> 
> Maintain browser compatibility for such a module by …
> fix: Improve type safety for browser-compatible modules

- node/internal_binding/README.md
- node/internal_binding/fs.ts
- node/internal_binding/fs_test.ts
This PR implements `writeBuffer` function (sync part) in node.js internal binding fs module (`internalBinding("fs").writeBuffer(...)`.
This function is used in the `net.Socket` implementation ([ref](https://github.com/nodejs/node/blob/0869b82/lib/internal/net.js#L53), related #694). `net.Socket` is the parent class of `tty.WriteStream` and process.stdout is an instance of `tty.WriteStream`.
> feat(std/node): add writeBuffer of internal binding fs module

- http/cookie.ts
- http/cookie_test.ts
Cookie domain should not start with `-` and end with `.` or `-`.
https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.3
> feat(http): Add Cookie domain validation

- uuid/README.md
- uuid/mod.ts
- uuid/v4.ts
- uuid/v5.ts
- uuid/v5_test.ts
This commit updates README, adds better JSDoc, and updates
implementations to use new `crypto` features.
> BREAKING std/uuid: rework v4 and v5 module

- async/README.md
- async/debounce.ts
- async/debounce_test.ts
- async/mod.ts
Resolves: #1008 
This is a proposal for adding a debounce function to the async module.
I always use this function together with the `Deno.watchFs` method and I have seen it in another project as well.
So i think this is a usefull function that could be added to the async module.
It is just a first version of how the module could look like. I'm open for any suggestions and changes.
Example:
```ts
import { debounce } from "https://deno.land/std/async/debounce.ts";
const log = debounce((param: string) => console.log(param), 200);
log("foo");
log("bar");
log("baz");
// wait 200ms ...
// output: baz
```
> feat(async): add debounce method to async module

- bytes/test.ts
This pr does 3 things to all tests for those:
- Adds tests to check that it fails when it should
- Adds tests to check that it also fails when array sizes are different
- Changes `assertEquals(v, true)` to `assert(v)`
> test(bytes): improve tests for equals, startsWith and endsWith

- async/README.md
- async/deadline.ts
- async/deadline_test.ts
- async/mod.ts
Hi, I'm not sure if you like the idea but I added a `timeout` function to the `async` module while simple code with `delay(100).then(() => new Error("Timeout"))` would cause the following error
```
AssertionError: Test case is leaking async ops.
Before:
- dispatched: 0
- completed: 0
After:
- dispatched: 4
- completed: 3
Make sure to await all promises returned from Deno APIs before
```
Added `timeout` function call `clearTimeout` to avoid such kind of error.
Please close this PR if it does not suit the std requirements.
> feat(async): add `timeout` to async module

- encoding/toml.ts
- encoding/toml_test.ts
fixes #983
Previously, arrays are assumed to be homogenous, but that is not the case (or it is changed recently?).
>arrays can contain values of the same data types as allowed in key/value pairs. Values of different types may be mixed.
https://github.com/toml-lang/toml/blob/master/toml.md#user-content-array
> fix(encoding/toml): serializes mixed array

- testing/_diff.ts
- testing/_diff_test.ts
Thanks to #948 by @lowlighter's great contribution, strings diff of assertion is now very readable.
But I found some edge case that strings diff displays like unwelcome.
It's a feature of merging word diffs if a in-between token is a space. Actually word diffs are merged even when the in-between token is not a space.
For example, this is as expected. Fine.
However, this is not as expected.
And this is also not as expected.
That's the issue. So this PR fixes it not to merge if the in-between token is not a space.
After fixed, above 2 bad examples will be improved as below.
> fix(testing/_diff) Don't merge diff when a token that is surrounded by word-diffs isn't a space

- node/process.ts
- node/util.ts
`Deno.customInspect` has been deprecated since Deno v1.12 https://github.com/denoland/deno/pull/10035 and the usage of it now causes lint errors. This PR fixes them.
> fix: fix lint errors in deno 1.12

- encoding/_yaml/parse.ts
- encoding/_yaml/parse_test.ts
fix #679
This fixes type definition of `parseAll` in yaml module.
Current:
```ts
// ok
parseAll(yaml)
// ok
parseAll(yaml, callback)
// ok
parseAll(yaml, callback, options)
// typing is ok, but options are ignored
parseAll(yaml, undefined, options)
// type error, but options are accepted
parseAll(yaml, options)
```
Modified:
```ts
// ok
parseAll(yaml)
// ok
parseAll(yaml, callback)
// ok
parseAll(yaml, callback, options)
// type error
parseAll(yaml, undefined, options)
// ok
parseAll(yaml, options)
```
> fix(encoding/yaml): fix `parseAll` type definition by using overloads

- .github/workflows/ci.yml
closes #1030 
This PR tries to restore coverage report of std.
The command excludes the following files/directories from the report:
- `.*test\.(ts|js)` - test files
- `wasm\.js` - wasm wrapper script (generated file)
- `testdata` - test fixture
- `node/_tools` - node.js test files
- `node/_module/cjs` - test fixture for node.js module testing
- `node_modules` - test fixture for node.js module testing
> chore: restore coverage reporting

- async/deferred.ts
- async/deferred_test.ts
This edits a bit `deferred<T>` in order to be able to track promise status, which is not exposed directly by default.
It's mostly useful to know whether the deferred promise is still `pending` or not (as they're manually resolved)
Personnaly I sometimes use it in unit testing so I figured out it may be useful for others too, though I could understand it may not be that revelant 🙂
> feat(async): add status to deferred promises

- async/deferred.ts
- async/deferred_test.ts
As pointed in https://github.com/denoland/deno_std/pull/1047#discussion_r674598436 by @kitsonk, ecma262 spec calls this property of promise [[PromiseState]] (ref: https://tc39.es/ecma262/#sec-fulfillpromise). This PR follows that convention to reduce confusions in the future, and renames the property to '.state'
This PR also makes the property 'readonly' (both in typings and runtime)
cc @lowlighter
> fix: rename deferred.status -> state

- .github/workflows/ci.yml
- async/debounce.ts
- async/tee_test.ts
- collections/chunked.ts
- collections/distinct.ts
- collections/distinct_by.ts
- collections/filter_entries.ts
- collections/filter_keys.ts
- collections/filter_values.ts
- collections/find_last.ts
- collections/group_by.ts
- collections/intersect.ts
- collections/map_entries.ts
- collections/map_keys.ts
- collections/map_values.ts
- collections/partition.ts
- collections/permutations.ts
- collections/union.ts
- collections/unzip.ts
- collections/zip.ts
- datetime/mod.ts
- flags/mod.ts
- http/cookie.ts
- io/streams.ts
- io/util.ts
- testing/asserts.ts
This PR enables the type checking of examples in jsdocs.
closes #1038
> chore: enable doc type checking

- testing/asserts.ts
- testing/asserts_test.ts
Closes #967
As `assertThrowsAsync` has an implementation drift from `assertThrows` which result in hiding the actual typing of errors in result messages when using custom errors:
```ts
class CustomError extends Error {}
Deno.test("test", async () => void await assertThrowsAsync(() => Promise.reject(new CustomError()), TypeError))
```
Before (making test harder to debug):
```
AssertionError: Expected error to be instance of "TypeError", but got "Error".
```
After:
```
AssertionError: Expected error to be instance of "TypeError", but got "CustomError ".
```
___
References:
AssertThrows:
https://github.com/denoland/deno_std/blob/e4c6419c466335eb697df38a387a2def06e6f3c5/testing/asserts.ts#L598
AssertThrowsAsync:
https://github.com/denoland/deno_std/blob/e4c6419c466335eb697df38a387a2def06e6f3c5 …
> fix(testing): `assertThrowsAsync` always reporting `Error` instead of actual error class

- collections/find_last_index.ts
- collections/find_last_index_test.ts
Please see https://github.com/denoland/deno_std/issues/1060
closes #1060
> feat(collections): Returns the index of the last element in the given array matching the given predicate

- async/pool_test.ts
- encoding/csv_test.ts
- testing/README.md
- testing/asserts.ts
This add a side note in documentation about `assertThrowsAsync` to mention that it is actually **required** to `await` them.
Examples are correct, but I feel like this should be highlighted as this is pretty hard to debug. 
Since it's the only assertion that is async it's not really intuitive.
Failing to do so can result in the whole runner to be interrupted... (see below where `test 3` is not even executed) 
```ts
import { assert, assertThrowsAsync } from "https://deno.land/std@0.102.0/testing/asserts.ts";
Deno.test("1", () => { throw new Error() });
Deno.test("2", () => void assertThrowsAsync(async () => {}, Error));
Deno.test("3", () => {});
```
```
running 3 tests from file:///deno_std/test.ts
test 1 ... FAILED (25ms)
test 2 ...
test result: FAILED. 1 passed; 0 failed; 0 ignored; 0 …
```
> fix(testing): change `assertThrows` and `assertThrowsAsync` return type to `void` and `Promise<void>`

- node/README.md
- node/sys.ts
This updates the Node.js builtin list assuming #1083, #1084, #1085 land.
It also aliases sys to util and extends the list to include the newest Node.js builtins.
> docs: update Node.js builtin list, alias sys to util

- http/file_server.ts
- http/file_server_test.ts
The If-Modified-Since request HTTP header makes the request conditional: the server will send back the requested resource, with a 200 status, only if it has been last modified after the given date. If the resource has not been modified since, the response will be a 304 without any body; the Last-Modified response header of a previous request will contain the date of last modification. Unlike If-Unmodified-Since, If-Modified-Since can only be used with a GET or HEAD.
When used in combination with If-None-Match, it is ignored, unless the server doesn't support If-None-Match.
The most common use case is to update a cached entity that has no associated ETag.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
> Return code 304 based on If-Modified-Since Header

- node/README.md
- node/perf_hooks.ts
- node/perf_hooks_test.ts
Just upstreaming the shims that we are trying to add into `jspm-core` 😄. Please let me know if there are any changes needed.
> Adding shim for perf_hooks in deno

- collections/sort_by.ts
- collections/sort_by_test.ts
This changeset updates the new `sort_by` function to be slightly more compact / idiomatic (imo). I also added tests for functions that return `bigint`s being provided for the `selector` parameter.
> chore(collections): Clean up sort_by code and add BigInt selector tests.

- collections/README.md
- collections/deep_merge.ts
- collections/deep_merge_test.ts
This implements `deepMerge`, which merges deeply two records together into the first one.
```ts
deepMerge({           // {
foo: {              //   foo: {
bar: true,        //     bar: true,
},                  //     baz: true,
}, {                  //     quux: {},
foo: {              //   },
baz: true,        //   qux: true,
quux: {},         // }
},
qux: true,
})
```
For convenience, a few options are proposed to handle edge cases:
- `arrays`, `sets` and `maps` can change their merging strategy from `"replace"` to `"concat"`. In the latter mode, values from both records will be kept
- `includeNonEnumerable` can be used to include properties and symbols which have an hidden visibility
Additional implementation notes:
- All `PropertyKey` types are supported (including `symbol`)
- …
> feat(collections): add `deepMerge`

- collections/sort_by.ts
- collections/sort_by_test.ts
This fixes `NaN` handling in `sortBy` as mentioned in #1092 by adding a simple explicit check. Also adds two tests for that behaviour.
> Fix `NaN` handling in `collections/sortBy` ( closes #1092 )

- async/deadline.ts
- async/deadline_test.ts
```ts
try {
await deadline(Promise.reject("booom"), 20);
} catch (error) {
console.log(`catch error: ${error}`);
}
```
will crash:
```plain
catch error: booom
error: Uncaught (in promise) booom
```
> fix(async): let async exception of `deadline` can be caught

- collections/mod.ts
This adds functions to `collection`s `mod.ts` which I have forgotten to add when implementing them :see_no_evil:
> fix (collections): Add missing functions to mod.ts

- collections/CONTRIBUTING.md
- collections/README.md
This adds a contribution guide with a checklist for common things I have been seeing in recent PRs to the module. It also
adds a small philosophy section that tries to summarize the current ideas behind the module and which might answer common
questions.
It also adds a bit of info to the README and updates missing functions.
> doc (collections): Add contribtution guide, some principles and extend README

- .github/workflows/ci.yml
- collections/README.md
- encoding/README.md
- encoding/yaml.ts
- flags/README.md
- fs/README.md
- http/README.md
- io/README.md
- log/README.md
- log/handlers.ts
- log/mod.ts
- node/README.md
- test_import_map.json
- testing/README.md
Fixes https://github.com/denoland/deno_std/issues/1120
> fix: type check examples in README files

- collections/associate_by.ts
- collections/chunked.ts
- collections/deep_merge.ts
- collections/distinct.ts
- collections/distinct_by.ts
- collections/filter_entries.ts
- collections/filter_keys.ts
- collections/filter_values.ts
- collections/find_last.ts
- collections/find_last_index.ts
- collections/group_by.ts
- collections/intersect.ts
- collections/map_entries.ts
- collections/map_keys.ts
- collections/map_not_nullish.ts
- collections/map_values.ts
- collections/partition.ts
- collections/permutations.ts
- collections/sort_by.ts
- collections/sum_of.ts
- collections/union.ts
- collections/unzip.ts
- collections/zip.ts
```ts
const arr = Object.freeze([1, 2, 3, 4, 5]);
const a = findLast(arr, (e) => e === 1);
^^^
// Argument of type 'readonly number[]' is not assignable to parameter of type 'number[]'.
//   The type 'readonly number[]' is 'readonly' and cannot be assigned to the mutable type 'number[]'.
```
```ts
const arr = Object.freeze([1, 2, 3, 4, 5]);
const a = findLast(arr, (e) => e === 1);
```
On top of that, the compiler will also help `std` maintainers to not mutate the parameters by mistake to a certain degree.
```ts
export function foo(array: readonly number[]) {
array.push(1);
^^^^
// Property 'push' does not exist on type 'readonly T[]'.
array[2] = 3;
^^^^^^^^
// Index signature in type 'readonly number[]' only permits reading.
...
}
```
> feat(collections): compile time guarantee on pure functions

- _util/os.ts
- fs/walk_test.ts
- http/file_server_test.ts
- node/_errors.ts
- node/_fs/_fs_chmod_test.ts
- node/_fs/_fs_chown_test.ts
- node/_fs/_fs_readlink_test.ts
- node/_fs/_fs_rmdir_test.ts
- node/_fs/_fs_writeFile.ts
- node/_fs/_fs_writeFile_test.ts
- node/child_process.ts
- node/child_process_test.ts
- node/fs/_fs_writeFile_test.ts
- node/internal_binding/fs_test.ts
- node/os.ts
- node/process.ts
- path/glob.ts
- signal/test.ts
- wasi/snapshot_preview1_test.ts
we had os util but in some where of code we didn't use it
> Use os util on entire of codebase

- collections/intersect.ts
- collections/intersect_test.ts
One would expect `intersection` to be commutative.
> fix(collections): intersect does not handle duplicate values in head properly

- bytes/README.md
- bytes/mod.ts
- bytes/test.ts
- Rename `contains` to `includes` as discussed in std-wg.
- Add optional argument `fromIndex` to `includes` since `Array.prototype.includes` has it.
> refactor(bytes): rename `contains` to `includes` with optional argument `fromIndex`

- async/delay.ts
- async/delay_test.ts
This is a non-breaking change which adds an optional `signal?: AbortSignal` to the delay function.
3 new tests were added which test that:
1. The abort stops the timeout and immediately resolves the delay promise
2. Not aborting the signal behaves as normal
3. Aborting after the delay has already completed does not result in an error
Fixes #1129
> feat(async): Add abort signal to delay

- testing/asserts.ts
- testing/asserts_test.ts
> fix(testing): `assertEquals` now considers constructors equal if one is nullable and the other is `Object`

- collections/README.md
- collections/max_of.ts
- collections/max_of_tests.ts
- collections/mod.ts
Suggestion how to implement a maxOf method
Related: #1065
> feat(collections): add maxOf

- collections/README.md
- collections/min_by.ts
- collections/min_by_test.ts
- collections/mod.ts
Implemented the `minBy` method in the collection module. ref: https://github.com/denoland/deno_std/issues/1065
Types are declare based on [this comment](https://github.com/denoland/deno_std/pull/978#issuecomment-866126420)
Let me know if I should add any specific test cases.
> feat(collections): add minBy

- .github/workflows/ci.yml
An oversight of #1128 was the introduction of `http/bench_legacy.ts` vs `http/bench.ts` which was missed from the canary test configuration's ignore list, resulting in the http bench server being run and hanging canary jobs in GH actions.
This PR adds the missing `http/bench_legacy.ts` entry.
Will be superseeded by #1195 if it lands first.
> fix(ci): ignore `http/bench_legacy.ts` in canary runs

- collections/deep_merge.ts
- collections/deep_merge_test.ts
The use of the `in` operator to check for the existence of properties is causing unexpected merging in objects with the same property names as `Object.prototype`. This PR fixes it by changing it to use `Object.prototype.hasOwnProperty`.
Expected behavior:
```ts
assertEquals(
deepMerge({
constructor: undefined,
}, {
foo: true,
}),
{
constructor: undefined,
foo: true,
}
);
```
Actual behavior:
```ts
assertEquals(
deepMerge({
constructor: undefined,
}, {
foo: true,
}),
{
constructor: Object.prototype.constructor,
foo: true,
}
);
```
> fix(collections): Prevent prototype merge in collections/deep_merge.ts

- http/README.md
- http/_io.ts
- http/_mock_conn.ts
- http/cookie.ts
- http/file_server.ts
- http/server.ts
- http/server_legacy.ts
- http/server_legacy_test.ts
Following https://github.com/denoland/deno_std/pull/1128, this PR corrects the JSDoc syntax previously implemented to match the [style guide](https://deno.land/manual/contributing/style_guide) (apologies for not getting right first time!) and the supported syntax of <https://doc.deno.land/>.
In addition to correcting the docs in the `http/server.ts` module, I have also corrected/formatted docs in the rest of the `http` module for consistency. I haven't done the whole of std to keep the scope of this PR small and easily reviewable.
Compare [docs from this PR](https://doc.deno.land/https/raw.githubusercontent.com%2Fdenoland%2Fdeno_std%2Fd929a3a%2Fhttp%2Fmod.ts) with [current docs](https://doc.deno.land/https/raw.githubusercontent.com%2Fdenoland%2Fdeno_std%2Fmain%2Fhttp%2Fmod.ts).
> docs(http): adhere to deno style guide in `std/http` module

- testing/README.md
This PR continues the work of #1139. Updates `testing/README.md` following the change of #1101
> docs(testing): document assertRejects in README

- examples/echo_server.ts
- examples/echo_server_test.ts
- http/README.md
- http/file_server.ts
- http/server.ts
- http/testdata/simple_https_server.ts
- http/testdata/simple_server.ts
- http/testdata/simple_server_legacy.ts
Fixes #1165
Attempt to reduce friction for windows users r.e. `0.0.0.0` by opting to use `localhost` in logged statements.
Related to https://github.com/denoland/deno/pull/11938. As noted by @kt3k:
> Listening this address works for all platforms, but the browsers on windows don't work with the address 0.0.0.0, and that's been causing the confusions to Windows users of several tools (ref: denoland/deno_std#1165, denoland/deployctl#63, kt3k/packup#10)
> docs(http): reduce friction for windows users r.e. `0.0.0.0`

- testing/asserts.ts
It is used as parameter for `assertThrows` and `assertRejects`.
> fix(testing/asserts): export Constructor type

- README.md
I talked with @ry and we decided to keep running canary CI because we want to know the breakage as soon as possible. But we don't require them passing for the PR to be accepted. This PR tries to clarify that for the contributors.
closes #870 
closes #1174
> docs(README): add note about ci checks

- README.md
This is good to document for modules such as `collections` who have a `README.md` with examples.
> doc: Adds an explanation about how to test markdown files

- collections/README.md
- collections/associate_with.ts
- collections/associate_with_test.ts
- collections/mod.ts
Builds a new Record using the given array as keys and choosing a value for each key using the given selector.
```ts
import { associateWith } from "https://deno.land/std@$STD_VERSION/collections/mod.ts";
import { assertEquals } from "https://deno.land/std@$STD_VERSION/testing/asserts.ts";
const names = ["Kim", "Lara", "Jonathan"];
const namesToLength = associateWith(names, (it) => it.length);
assertEquals(namesToLength, {
"Kim": 3,
"Lara": 4,
"Jonathan": 8,
});
```
Related https://github.com/denoland/deno_std/issues/1173
> feat(collections): Add `associatewith`

- async/deferred.ts
- async/tee.ts
- encoding/csv.ts
- flags/mod.ts
- fmt/colors.ts
- fs/expand_glob.ts
- fs/walk.ts
- io/streams.ts
- node/module.ts
- path/common.ts
- path/posix.ts
- path/win32.ts
- permissions/mod.ts
- signal/mod.ts
Wraps all examples in fenced code blocks so that they can be tested with `deno test --doc`.
> chore: wrap examples in fenced code blocks

- collections/includes_value.ts
- collections/includes_value_test.ts
Add an `Object.hasOwn()` check to the `for...in` loop to prevent enumeration of keys that exist in prototype.
before:
```ts
Object.prototype.a = "hello";
includesValue({}, "hello"); // => true
```
after fix:
```ts
Object.prototype.a = "hello";
includesValue({}, "hello"); // => false
```
> fix (collections/includesValue): prevent enumerable prototype check

- collections/README.md
- collections/mod.ts
- collections/running_reduce.ts
- collections/running_reduce_test.ts
> feat (collections): add `runningReduce`

- io/streams.ts
- io/streams_test.ts
Passes readable stream cancellations to the underlying iterator when applicable.
```ts
const readable = readableStreamFromIterable(async function* () {
try {
yield "foo";
} catch (error) {
console.log(error); // Error: Cancelled by consumer.
}
}());
const reader = readable.getReader();
console.log(await reader.read()); // { value: "foo", done: false }
await reader.cancel(new Error("Cancelled by consumer."));
```
> feat(io/streams): Propagate cancel in readableStreamFromIterable()

- encoding/_yaml/schema/extended.ts
Which could allow arbitrary code execution when parsing YAML files with the extended schema, e.g:
```js
import { parse, EXTENDED_SCHEMA } from "https://deno.land/std/encoding/yaml.ts";
const data = parse(`
fun: !!js/function >
console.log(Deno.core);
`, {schema: EXTENDED_SCHEMA});
console.log(data);
```
Will log `Deno.core`
```js
import { parse, EXTENDED_SCHEMA } from "https://raw.githubusercontent.com/denoland/deno_std/security/yaml-func-exec/encoding/yaml.ts";
const data = parse(`
fun: !!js/function >
console.log(Deno.core);
`, {schema: EXTENDED_SCHEMA});
console.log(data);
```
Will throw with `Uncaught YAMLError: unknown tag !<tag:yaml.org,2002:js/function> at line 4, column 1:`
- Reported by @ry0tak
- Impact: high (allows arbitrary JS execution)
- Probability: low (requires using …
> security(encoding/yaml): disable functions

- async/delay_test.ts
- async/pool_test.ts
- encoding/csv_test.ts
- testing/README.md
- testing/asserts.ts
- testing/asserts_test.ts
Returning the error is useful.
> feat(testing/asserts): Add assertThrows() overload to receive error

- node/events.ts
TypeScript v4.4 (which is used in Deno v1.14) now supports symbols as index signatures. This eliminates the need for some `@ts-ignore` comments in `node/events.ts`. This PR removes such unnecessary comments.
> chore(node/events): remove unnecessary @ts-ignore comments

- collections/max_with.ts
- collections/max_with_test.ts
- collections/min_with.ts
- collections/min_with_test.ts
In the case of a comparator that returns undefined as the maximum or minimum value, the value returned depends on the order of the array.
This is a pretty edge case, but I've fixed it.
```ts
const comparator = (a, b) => {
if (a === undefined) {
return 1;
}
if (b === undefined) {
return -1;
}
return 0;
};
// current implementation:
maxWith([undefined, 1, undefined], comparator) //=> undefined (correct)
maxWith([undefined, undefined, 1], comparator) //=> 1 (wrong)
```
> fix (collections/maxWith,minWith): improve handling of arrays containing undefined

- encoding/README.md
This PR adds `hex` module documentation to `encoding` README
> docs(encoding): add hex docs

- collections/README.md
Fix document because `===` can't compare non-primitive types.
Same as #1206.
> docs(collections): replace console.assert with assertEquals

- node/_tools/setup.ts
Closes #1298 
`compress` seems to have been kinda abandoned, so I just opted to replace it with `denoflate`, solving some ugly TypeScript errors in the process
> fix(node): Use denoflate to decompress Node test folder

- node/README.md
- node/stream/web.ts
this pull request adds partial support for the experimental `stream/web` API from Node.js which is basically re-exports browser APIs.
Some of the APIs aren't in Deno yet so I have added only the ones present in Deno.
Ref: https://nodejs.org/api/webstreams.html#webstreams_class_readablestreambyobreader
Closes https://github.com/alephjs/esm.sh/issues/163
> feat(std/node/stream): add partial support for `stream/web`

- .github/workflows/ci.yml
- README.md
We discussed this internally, and decided to try only run canary CI for a while.
The reasons of this change are:
- We had problems in some recent releases because canary CI wasn't passing at the time of release
- Merging with red status confuses people (and caused a mistake)
- The latest released Deno is compatible with the latest tag of std, and it doesn't need to compatible with std's main
The downside of this change is (probably) that we can't merge PRs in std when CLI canary accidentally broke something in std.
This is an experimental attempt. I think we'll revisit this after several releases.
related: #1279 #870 denoland/deno#9801
previous change: #1209
> docs: change CI rule

- crypto/mod.ts
The `await` here will do a duplicate microtask, return the promise directly can reduce it
> perf(crypto): reduce one mircotask

- node/url_test.ts
Ref: https://github.com/nodejs/node/blob/8d83c470291d05f22010662380633bbddf0e7dcb/test/parallel/test-url-pathtofileurl.js#L96-L139
> chore(node/url): Add tests for `fileURLToPath` and `pathToFileURL`

- collections/running_reduce_test.ts
Related: https://github.com/denoland/deno_std/pull/1311#issuecomment-927709291
>I'll close this PR soon and just add test case.
Add case that:
- `initialValue` is not `0` or `""`.
- array of objects
> test(collections/running_reduce) Add test case

- node/_tools/config.json
- node/_tools/setup.ts
If file names are not in the correct order, it will be difficult to see which tests have already been added.
> chore(node/tools/setup): Make sure filenames are in the correct order before setting up

- ws/README.md
I think the ws module has been deprecated in #1306. Clarify it in the documentation.
> chore: clarify in the documentation that the ws module is deprecated

- node/os.ts
- node/os_test.ts
This was lost when Dino.dir was removed. This implementation is in
typescript and should do the same thing as std::env::temp_dir was
doing in the previous implementation:
https://doc.rust-lang.org/std/env/fn.temp_dir.html
The previous implementation was in the pull request denoland/deno#4213
> feat(std/node): Add back os.tmpdir() implementation

- node/buffer.ts
- node/buffer_test.ts
Reads byteLength number of bytes from buf at the specified offset and interprets the result as an unsigned, little-endian integer supporting up to 48 bits of accuracy.
> feat(node): Support `Buffer.readUIntLE`

- node/_crypto/scrypt.ts
- node/_crypto/scrypt_test.ts
- node/crypto.ts
Implementation borrowed from https://github.com/crypto-browserify/scrypt
> feat(node/crypto): add `scrypt` and `scryptSync`

- node/README.md
- node/_tools/test.ts
As the number of tests in `config.json` increases, it becomes more difficult to remove untargeted tests when we want to run a specific test in a local environment. (We can't even comment it out in a json file.)
> chore(node/_tools/test): Add `--only` flag to run specific tests

- node/stream/web.ts
this PR adds more re-exports from global stream APIs to `stream/web`:
- `ReadableByteStreamController`
- `TransformStreamDefaultController`
- `ByteLengthQueuingStrategy`
- `CountQueuingStrategy`
- `TextEncoderStream`
- `TextDecoderStream`
works fine on deno 1.14.2
> feat(node/stream/web.ts): export more APIs

- node/_crypto/pbkdf2_test.ts
closes #1347 
This PR should speed up the pbkdf2 test cases.
While these higher iteration numbers are recommended in actual usages, I think these cases are just redundant in CI (I think what these cases cover are already enough covered by the other cases)
> chore: remove pbkdf2 test cases with large iterations number

- path/win32.ts
closes #1341
As pointed in #1341, "=C:" special variable is the feature of cmd.exe, not an OS feature. So we can't safely rely on that for path resolution. (Also Deno.env.get doesn't allow `=` character in env var name. So this code path doesn't work anyway)
ref: https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133
> fix(path): remove =c: env var usage

- node/_tools/suites/parallel/test-url-fileurltopath.js
- node/url.ts
- Use Class defined in node/_error.ts to throw exception
- Correct Logical OR to Bitwise OR
- Move Comment
> fix(node/url): Use Class defined in `node/_error.ts` to throw exception

- node/_crypto/randomFill.ts
- node/_crypto/randomFill_test.ts
- node/crypto.ts
Reference: https://nodejs.org/api/crypto.html#crypto_crypto_randomfillsync_buffer_offset_size
Adds and exports `randomFillSync` and `randomFill` function.
> feature(node/crypto): add randomFillSync an randomFill

- hash/README.md
- hash/mod.ts
We decided to deprecate std/hash in favor of std/crypto (ref: https://github.com/denoland/deno_std/pull/1025 ), but we didn't mention that in README.
This PR explicitly adds the deprecation notice in hash/README and also adds `@deprecated` tags in jsdocs.
> chore: deprecate std/hash

- bytes/equals.ts
- bytes/equals_bench.ts
- bytes/mod.ts
- bytes/test.ts
For large `Uint8Array`s, it's faster to make `Uint32Array`s from the underlying `ArrayBuffer`s and compare those instead of the original `Uint8Array`s. I've used the following benchmarking code and found the cutoff to be at around 1000 elements on my machine:
```ts
import {
bench,
runBenchmarks,
} from "https://deno.land/std@0.110.0/testing/bench.ts";
function equalsNaive(a: Uint8Array, b: Uint8Array): boolean {
if (a.length !== b.length) return false;
for (let i = 0; i < b.length; i++) {
if (a[i] !== b[i]) return false;
}
return true;
}
function equalsSimd(a: Uint8Array, b: Uint8Array): boolean {
if (a.length !== b.length) return false;
const len = a.length;
const compressable = Math.floor(len / 4);
const compressedA = new Uint32Array(a.buffer, 0, compressable);
const compressedB = new …
```
> feat(bytes): switch equals to simd for large byte arrays

- node/_tools/test.ts
This patch pipes the output from the subprocess tests to `console.log` after the test has finished. That way the test output is marked as output of Deno.test and can be ignored by passing `--quiet` instead of going directly to stdout
Before and after with `--quiet`
Aditionally, the output of a failed test will be passed to a `fail` call for easier debugging
Before and after
> fix(node/_tools): Better error and output logging

- node/_utils.ts
- node/process.ts
- node/process_test.ts
This PR changes the handling of not implemented events in process object. Currently it throws on notImplemented events but this PR changes it to just show the warnings about it.
This enables some of npm modules running in Deno compat mode (e.g. mocha)
> fix(node/process): warn on not implemented event instead of throw

- collections/deep_merge.ts
- collections/deep_merge_test.ts
On Deno, `Object.prototype.__proto__` has been removed, but not always on other platforms. As long as it is explicitly marked as browser compatible, it should be fixed.
> fix(collections): Prevent calling `Object.prototype.__proto__` on non-Deno platforms in collections/deep_merge.ts

- fs/expand_glob.ts
In my use case, this change makes `expandGlob` x1.9 faster.
> perf(fs): Parallelize `expandGlob`

- http/file_server_test.ts
This PR skips the type checking of file_server.ts in each test run (The type is already checked at the start of test file itself. There's no need of type checking iteratively). This reduces the test exec time. (It's reduced from 36s to 3s on my machine)
> test(http/file_server): skip type checking in each test case

- http/file_server.ts
`html` template literal tag in file_server is unnecessarily complex, but not useful at all. This PR removes it.
> refactor(http/file_server): remove html template literal tag

- http/file_server.ts
- http/file_server_test.ts
This PR refactors the default value and alias flag handling in http/file_server using `default` and `alias` options of `parse` function.
> refactor(http/file_server): use default and alias features of flag parser

- http/file_server.ts
- http/file_server_test.ts
This PR updates `http/file_server.ts`. Now the file_server cli doesn't need `--allow-read` permission flag when `--help` flag is passed. (`read` permission was used during resolving the target. Now we resolve it after handling `--help`)
> fix(http/file_server): don't require --allow-read for showing help message

- node/events.ts
This PR replaces `process.emit('warning', warning)` with `process.emitWarning(warning)`. (I had overlooked presence of `process.emitWarning`)
> chore(node/events): avoid directly emitting 'warning' event

- node/_utils.ts
- node/events.ts
- node/events_test.ts
This PR is part of a fix to #1511 (This issue is still not fully resolved yet).
> fix(node/events): make EventEmitter's public methods enumerable

- node/querystring.ts
- node/querystring_test.ts
- Change functions order(No logical change)
- Add docs
- Remove unnecessary `hexTable` export
- Clean up deno test
> docs(node/querystring): Add docs

- http/server.ts
- http/server_test.ts
This PR supersedes #1478
This PR updates the APIs in `http/server.ts`.
`serve` now has the following signature:
```ts
async function serve(
handler: Handler,
options: ServeInit = {},
): Promise<void>;
```
And `ServeInit` has `addr`, `signal` (for aborting), `tls` options. The addr defaults to ":8000", so the example given in #1478 like the below works:
```ts
import { serve } from "https://deno.land/std/http/server.ts";
serve(req => new Response("Hello world"));
```
(http server starting with the port 8000 by default may look strange, but this has prior examples such as python's http.server, Django, etc. ref: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers . Alternative default port might be 3000, 8008, 8080, etc)
This `serve` covers the use cases of `listenAndServe` and …
> BREAKING(http): update `serve` API

- node/_errors.ts
- node/assertion_error.ts
- node/process.ts
This call is not present in lib.dom.d.ts. As such, we should @ts-ignore
it.
Fixes #1523
> fix(node): @ts-ignore Error.captureStackTrace()

- archive/tar_test.ts
- collections/chunk.ts
- collections/unzip.ts
- collections/without_all_test.ts
- encoding/_yaml/dumper/dumper.ts
- encoding/_yaml/loader/loader.ts
- encoding/_yaml/type/pairs.ts
- fmt/printf.ts
- hash/_wasm/wasm.js
- io/util.ts
- testing/_diff.ts
- testing/bench_test.ts
- uuid/_common.ts
This PR replaces instances of `new Array(n)` with `Array.from({ length: n })`.
This has 2 main benefits:
1. **Performance:**
`new Array(n)` [**_always_** results in holey arrays](https://v8.dev/blog/elements-kinds#avoid-creating-holes).
This results in very bad deoptimizations from the V8 engine.
> Once the array is marked as holey, it remains holey forever — even if all its elements are present later!
This can have serious performance implications for end-users. (see `chunk` and `unzip` for the most worrying instances of this)
2. **Type-safety:**
`new Array()` returns `any[]` by default.
This results in unsafe code which can lead to runtime errors.
`Array.from` returns `unknown[]` by default, which ensures type-safety.
While making this PR I discovered one bug in …
> perf: use `Array.from` instead of `new Array`

- node/_tools/suites/parallel/test-util.js
- node/util.ts
[`types`](https://github.com/nodejs/node/blob/6e1629786fe16058e0f12bc1613fae7734bff9b0/lib/util.js#L367) is come from [internalBinding](https://github.com/nodejs/node/blob/6e1629786fe16058e0f12bc1613fae7734bff9b0/lib/internal/util/types.js#L58) but we actually don't touch V8 APIs directly in std/node so [simulating the behavior in typescript](https://github.com/denoland/deno_std/blob/e72289d02705b7ee75227c599f95c17ffe6aeb44/node/_util/_util_types.ts#L90).
> feat(node/util): Add `util.isDate`

- fs/walk.ts
- fs/walk_test.ts
> fix(fs/walk): dont throw when encountering a symlink to a file

- node/_tools/test.ts
This change should speed up CI runs.
> chore(node): don't typecheck require module when running tests

- node/_buffer.js
- Add space between definition
- export `Buffer` instead of using `Buffer2`
- That's how it works in node.
- https://github.com/nodejs/node/blob/f2170253b694c488f8ad2616dfc5c66b6a3c90a0/lib/buffer.js#L1244
> refactor(node/buffer): export `Buffer` instead of using `Buffer2`

- http/file_server.ts
`listenAndServe` and `listenAndServeTls` have been deprecated in v0.114.0. This PR migrates them to `serve` and `serveTls`, which are new APIs.
> chore(http/file_server): migrate to serve and serveTls

- node/_fs/_fs_rm.ts
- node/_fs/_fs_rm_test.ts
- node/fs.ts
- node/fs/_fs_rm_test.ts
- node/fs/promises.ts
this is a part of https://github.com/denoland/deno_std/pull/1564;
`fs.rmSync` need by https://github.com/nodejs/node/blob/master/test/common/tmpdir.js#L8
> feat(node/fs): implement `fs.rm` and `fs.rmSync`

- node/_tools/suites/parallel/test-util.js
- node/internal/errors.ts
- node/module_all.ts
Errors defined in [`nodejs/node/lib/internal/errors`](https://github.com/nodejs/node/blob/afe460ec9e30add944056760a01d1185c6aac276/lib/internal/errors.js#L390-L408) are implemented in [`node/_errors.ts`](https://github.com/denoland/deno_std/blob/main/node/_errors.ts) and work correctly, but can't import `internal/errors` in test file like `test-util.js`.
> chore(node): Implement `internal/errors`

- node/http.ts
- node/net.ts
Make patterns like `const server = http.createServer(go).listen()` work.
> fix(node): improve http.Server.listen() compat

- node/_next_tick.ts
- node/_stream/async_iterator.ts
- node/_stream/duplex.ts
- node/_stream/duplex_internal.ts
- node/_stream/end_of_stream.ts
- node/_stream/from.ts
- node/_stream/readable.ts
- node/_stream/readable_internal.ts
- node/_stream/writable.ts
- node/_stream/writable_internal.ts
- node/_util/_util_callbackify.ts
- node/child_process.ts
- node/process.ts
Towards #1482
Added a helper module so `nextTick` can be used across `std/node` instead of using
`queueMicrotask` ad hoc. Still need to provide a proper polyfill.
> node: add nextTick helper module

- fs/README.md
- fs/mod.ts
- wasi/snapshot_preview1_test.ts
Fixes https://github.com/denoland/deno_std/issues/1539
> Remove fs/mod.ts

- node/README.md
- node/module_all.ts
- node/wasi.ts
since [Node.js WASI](https://nodejs.org/api/wasi.html#wasiinitializeinstance) is 1:1 to Deno WASI API, we can just re-export `Context`
> feat(node): add wasi module

- node/http.ts
- node/http_test.ts
The goal is to get http.Server in good enough shape to run Node's
benchmarks. Not quite there yet but getting closer.
This commit adds a few regression tests but those are expected to
eventually be subsumed by Node's own test suite.
> fix(node/http): improve http.Server compatibility

- node/_tools/config.json
- node/_tools/suites/parallel/test-readline-csi.js
After landing #1588 these tests can be enabled as they pass as expected.
> chore(node): enable ignored readline tests

- README.md
No production code changed
This is a minor edit to documentation in order to fix a grammar issue.
> fix(docs): Added correct plural case for word "title"

- node/http.ts
Handle malformed (usually truncated) client request by swallowing the
exception and closing the connection. Node also emits a "clientError"
but we don't currently have the `net.Socket` object listeners for that
event expect.
Fixes #1620.
> fix(node/http): ignore server request parse errors

- fmt/printf.ts
- fmt/printf_test.ts
Currently `printf` behaves as seen in the following block.
```ts
import {printf} from "https://deno.land/std/fmt/printf.ts";
printf("%.3f",0.9999);
//it print 0.000
printf("%.1f\n",0.99);
//it print 0.0
printf("%.3f\n",1.9999);
//it print 1.000
```
The reason for this behavior is that `roundFractionToPrecision` ignores the carry.
so, I fixed it.
> fix(fmt): print with rounding taken into account

- node/_process/streams.ts
This change makes [`enquirer`](https://github.com/enquirer/enquirer) work in compat mode.
> fix(node): use async read for stdin

- node/internal/fs/utils.js
- node/internal/url.ts
- node/url.ts
[toPathIfFileURL](https://github.com/nodejs/node/blob/d81f328aa5b02397f7eac99389f28b951366c438/lib/internal/url.js#L1548) is not public API.
> refactor(node/url): Move `toPathIfFileURL` to internal

- node/_tools/suites/parallel/test-util-inspect.js
- node/internal/util/inspect.js
`validateObject` is added when https://github.com/denoland/deno_std/pull/1632 is merged.
> fix(node/util/inspect): Validate invalid options

- node/README.md
- node/_tools/test.ts
With this change the test results show the command to repeat the failed single test file of node.js compat testing.
This command is more efficient than `--only` feature of `node/_tools/test.ts` because of less overhead in the execution. So I now deleted `--only` feature of test runner to promote this method of running single test case.
cc @wafuwafu13
> chore(node): show the command to repeat single test

- node/internal/querystring.ts
- node/querystring.ts
This is needed in https://github.com/denoland/deno_std/pull/1667
> ref(node): Export encodeStr , hexTable and isHexTable

- http/server_test.ts
This PR fixes the error message expectations in https server tests. This should fix the CI failure in main
(The error is first observed in main 1 hour ago. It's probably caused by https://github.com/denoland/deno/pull/12488)
> test(http): fix error message of unknown issuer

- .github/workflows/ci.yml
- datetime/test_2021_12_31.ts
This PR adds ability to run test with the specific date time. This is necessary for writing test for #1676
> chore: add faketime testing

- encoding/toml.ts
- encoding/toml_test.ts
This PR contains two parts.
1. origin regexp couldn't match the key correctly, see https://github.com/denoland/deno_std/issues/1067#issuecomment-907740319
2. fixes wrong test https://github.com/denoland/deno_std/blob/bfe8b128164d295bad9eb9f73250ced55b07cf4b/encoding/toml_test.ts#L513-L542
> fix(toml): parse declaration correctly

- node/inspector.ts
- node/module_all.ts
This PR adds placeholder `inspector` module in std/node.
Some tools use `inspector` to check if there's active inspector automatically even when the user don't intend to use inspector (for example, ava does it https://github.com/avajs/ava/blob/c214512ddfd78530adf5f632974345396cc39e24/lib/cli.js#L121 ) This PR is useful for avoiding crashing the node compat mode in thoses cases.
> feat(node): add mock inspector module

- node/_utils.ts
- node/internal_binding/_node.ts
Now the CI is blocked by the reference error in `node/internal_binding/_node.ts` (cf: https://github.com/denoland/deno_std/runs/4466763309?check_suite_focus=true ), which is probably caused by https://github.com/denoland/deno/pull/13025
~~The issue seems only happening with swc. This PR works around it by using tsc for transpiling the problematic enum~~
This PR works around the issue by avoiding using enum reference in enum definition.
reference: transpiled result in playground https://www.typescriptlang.org/play?ssl=11&ssc=1&pln=11&pc=4#code/KYDwDg9gTgLgBMAdgVwLZwKKIMYQCYCWiA5gM5wDec1AUNQIIDKAwgJKsA0cA9N3AAzU4dOAFUAKgDEAHF15wAjEJEAhJhgBsAFjl8ATMuqjmjPbrgBmQ3BWsAcvQBKATXNbrACQwANcwFZrFVFJSQxHcw1A9W1RRwAZcwB2azj6cXslAF44d3l3bNsHFw4aAF9qIA
> ci: fix reference error in node ci

- node/module_all.ts
- node/zlib.ts
This PR adds mock implementation of `zlib` module in std/node.
Some module depeneds on `zlib`'s interfaces even without using its actual features. (e.g. This rollup plugin depends on zlib's interface even when its function is actually not used. ref: https://github.com/btd/rollup-plugin-visualizer/blob/a56a9061da9f8902ec1a7cfcbfef85d6e075b706/plugin/compress.ts ). This addition is useful for those situations.
> feat(node): add mock zlib module

- node/fs.ts
- node/internal/fs/utils.js
This PR exports `fs.Stats` class, which is a part of public Node.js API. https://nodejs.org/api/fs.html#class-fsstats
closes #1689
> feat(node): export fs.Stats class

- encoding/toml.ts
- encoding/toml_test.ts
now function `stringfy` will not align keys by default, and you could pass `{ keyAlignment : true }` to function `stringfy` as second parameter to align keys.
```ts
return stringfy(srcObj);
/*
key : value
keykey : value
keykeykey : value
*/
return stringfy(srcObj, { keyAlignment : true });
/*
key       : value
keykey    : value
keykeykey : value
*/
```
Close #1067
> feat(toml): Align keys by optional

- examples/colors_test.ts
- fmt/colors_test.ts
These tests can't pass with the canary. Skipped them for now.
ref: https://github.com/denoland/deno/pull/13031
> chore: skip fmt/colors test

- node/README.md
- node/_tools/test.ts
This PR adds a function to filter the Node.js test cases. You can only execute tests which include the given specific patterns:
```sh
deno test -A node/_tools/test.ts -- <pattern-to-match>
```
This should improve the productivity of node.js compat testing
> chore(node/_tools): enable node.js test filtering

- node/util.ts
This PR exposes `debuglog` method via util module. It is a part of public API, but wasn't exposed correctly https://nodejs.org/api/util.html#utildebuglogsection-callback
> feat(node): expose util.debuglog

- uuid/mod.ts
Follow up to https://github.com/denoland/deno_std/pull/1720
Side note: it seems like almost all code in this repo uses explicit return types, however, it's not mentioned in the [style guide](https://deno.land/manual@v1.17.0/contributing/style_guide). Should it be?
> style(uuid): add return type to `validate`

- .github/workflows/ci.yml
- node/https.ts
- node/https_test.ts
closes #1703 
This PR implements `https.request` using `fetch` API.
I first tried to follow the node.js implementation more closely, but it seems too complicated to follow (wasted almost 2 days on it...). I also heard feedbacks in the design meetings and more people seem preferring implementation by `fetch`. So I switched to this version.
If this PR looks good, I'll align `http.request` to this implementation as it seems flaky ref: #1738
> feat(node): add https.request

- node/process.ts
- node/process_test.ts
This PR adds `process.execPath` in std/node.
This resolves one of the issues in running npm in compat mode. ref: https://github.com/denoland/deno/issues/13187
> feat(node): add process.execPath

- node/process.ts
- node/process_test.ts
- node/testdata/process_exit2.ts
Fixes https://github.com/denoland/deno_std/issues/1752
Related to https://github.com/denoland/deno_std/pull/1628
> fix(node): don't emit exit twice

- node/child_process_test.ts
- node/internal/child_process.ts
This is useful for additional compatibility with Node.JS, which allows
numbers and booleans to be values to environment variables. In Deno, we
convert those values to strings to match the signature of Deno#run.
This should resolve #1725.
> fix(node/child_process): Allow number and boolean env vars.

- node/_tools/suites/parallel/test-util-isDeepStrictEqual.js
- node/internal/util/comparisons.ts
Fixes #662 the test suite passes, there is one issue however, i think that is we should probably be having this check of getOwnPropertySymbols and getOwnPropertyNames somewhere earlier as presently the location where this is being done (inside the isBoxedPrimitive) seems rather prone to error as the check is only for length. 
Is there any other way we can implement this check to ensure that the code catches a scenario wherein prototype modifications are done on an object in a way so that the length of `getOwnPropertySymbols` and `getOwnPropertyNames` is same in both boxed primitive as well as the modified prototype object.
> Implementation of deepStrictEqual

- crypto/mod.ts
This interface was previously not exposed making it invisible in deno
doc.
> chore(crypto): export interface for docs

- node/url.ts
When running programs such as `npm` we would see "strange" URLs such as:
```
https://***:undefined@registry.npmjs.org/qnullnullnullnullnullnull
```
These were produced as a series of `url.format()` that mistakenly injected nullish strings for auth/search/hash instead of NOPing
> fix(node/url): format auth/search/hash corruption

- node/http.ts
Partially unblocks `npm` by fixing `minipass-fetch` which depends on `req.on('response', ...)`
> fix(node/http): client emit response, trailers & abort

- node/internal_binding/tcp_wrap.ts
Correctly describe bind6 as connecting to an IPv6 address instead of IPv4.
> Change bind6 comment to IPv6

- node/timers.ts
- node/timers_test.ts
Deno's built-in timer functions throw "Illegal invocation" exceptions
unless they are called with this == globalThis or this == null.
> fix(node): work around |this| check in deno core

- node/internal_binding/tcp_wrap.ts
These methods have no directly observable side effects and should
therefore be safe to turn into no-ops. Doing so unblocks a number
of third-party modules.
Can be implemented once https://github.com/denoland/deno/pull/13103
lands.
> fix(node/net): setNoDelay and setKeepAlive no-ops

- encoding/README.md
- encoding/csv.ts
- encoding/csv_test.ts
Resolves #881
Took from a comment in the issue by @dsherret and removed the ability to pass a `parse` arg to the function which gave it the responsibility of parsing and, optionally, data transformation. Let me know wha you think!
> BREAKING(encoding/csv): add return type to csv's parse and remove a parse func from args

- fs/walk.ts
- fs/walk_test.ts
Don't error on special files like UNIX domain sockets. Filter them out
instead.
Fixes #1789.
<hr>
I opted to filter them out because you can't really do anything except unlink them but maybe they should be included instead? Produces entries that look like this though:
```
{
path: "/foo",
name: "bar.sock",
isFile: false,
isDirectory: false,
isSymlink: false,
}
```
Feedback appreciated.
> fix(fs/walk): filter special files

- node/_tools/test.ts
This PR sets `DENO_NODE_COMPAT_URL` env var to the local std root while node.js compat testing. So the contributors can simply run `deno test` without setting env vars.
> chore: set compat env var automatically on testing

- http/_mock_conn.ts
This PR updates the mock `Deno.Conn` object which is used in `http` testing. This follows the change of CLI canary https://github.com/denoland/deno/pull/13103
> chore: update mock Deno.Conn

- _deno_unstable.ts
- node/_fs/_fs_access.ts
`Deno.getUid()` is still an unstable API, so this PR adds it to `_deno_unstable.ts`
Related to #1819
> chore: Add `getUid` to `_deno_unstable.ts`

- collections/group_by.ts
This PR introduces the following type changes:
- **Fix**: the properties of the return type are now marked as **optional** because they may or may not exist. This aligns with both the runtime behavior of this function and the behavior of the corresponding [stage-3 proposal](https://github.com/tc39/proposal-array-grouping).
- Enhancement: the properties of the return type are now inferred from the return type of the selector.
```ts
const nums = [1, 2, 3, 4];
const result = groupBy(nums, n => n % 2 === 0 ? 'even' : 'odd');
console.log(result); // { odd: [1, 3] }
// before
result.even // number[]
result.odd // number[]
result.unknown // number[]
// after
result.even // number[] | undefined
result.odd // number[] | undefined
result.unknown /*
^^^^^^^
Property 'unknown' does not exist on type …
```
> fix(collections/group_by): improve type safety

- path/README.md
Isn't it supposed to be a TypeScript code block?
- Added TypeScipt syntax highlighting for the missed code block.
> docs(path/README): Fix missed syntax highlighting language in code block

- _deno_unstable.ts
- node/process.ts
This PR mocks `process.umask` with the hard coded default value. This avoids the bug of `Deno.umask` described in [this comment](https://github.com/denoland/deno_std/issues/1893#issuecomment-1032897779)
With this change, `yarn install` / `yarn add <mod>` commands finally work without errors!
closes #1893
closes https://github.com/denoland/deno/issues/13420
> chore: mock process.umask

- _deno_unstable.ts
- node/os.ts
`Deno.networkInterfaces` is still an unstable api.
Related: #1900
> chore: add `networkInterfaces` to `_deno_unstable.ts`

- io/buffer.ts
This gets rid of the error messages like the following when using `io/buffer.ts` under tsc directly via dnt: 
```
TS2376: A 'super' call must be the first statement in the constructor when a class contains initialized properties, parameter properties, or private identifiers.
```
While this is being fixed in future version of TypeScript, it is a limitation that is easy to work around and allows people to use the `std` lib via dnt without type errors.
> fix(io/buffer): super and initialized prop

- node/_module/cjs/cjs_declare_timers.js
- node/_tools/test.ts
- node/module.ts
- node/module_test.ts
Some npm modules have their own timer declarations (ref: https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/rest/RESTManager.js#L3 ), but those declarations conflicts with parameters of commonjs wrapper, and cause SyntaxError.
~~This PR adds the internal block inside the cjs wrapper and avoids the above error.~~ this doesn't work because now module can't control the strictness of the module. ("use strict" doesn't have effect anymore)
This PR adds another inner wrapper inside of the current one. The inner wrapper only provides the canonical commonjs items `exports`, `require`, `module`, `__filename`, `__dirname`, which prevents the conflicts of the declarations of timer functions.
closes #1901
> fix(node/module): fix commonjs wrapper

- node/_tools/config.json
- node/_tools/suites/common/index.js
- node/_tools/suites/parallel/test-util-types.js
- node/_tools/suites/parallel/test-zlib-random-byte-pipes.js
- node/internal/crypto/keys.ts
- node/internal/crypto/util.js
- node/internal/util/types.ts
This PR enables `hasCrypto` flag in compat testing module. This flag should be true in compat testing as we provide cryptographic features in `std/node`
> test(node): enable hasCrypto flag

- node/timers.ts
Unlike globalThis.setTimeout in browsers, the setTimeout in node only
accepts functions, not strings.
The existing code works fine when typechecking with
lib.deno.shared_globals.d.ts, which declares setTimeout callback
argument as "(...args: any[]) => void". It is only a problem when
using lib.dom.d.ts, which declares the callback as having type
"string | Function". With the lib.dom.d.ts declaration, typechecking
fails because there is no .bind in string.
> Don't use globalThis.setTimeout types in node/timers

- encoding/_yaml/error.ts
- encoding/csv_stringify.ts
- hash/sha1.ts
- hash/sha256.ts
- hash/sha512.ts
- io/buffer.ts
- log/handlers.ts
- log/handlers_test.ts
- log/logger_test.ts
- log/mod_test.ts
- log/test.ts
- node/assertion_error.ts
- node/dgram.ts
- node/http.ts
- node/https.ts
- node/internal/errors.ts
- node/internal/fs/streams.ts
- node/internal_binding/pipe_wrap.ts
- node/internal_binding/stream_wrap.ts
- node/internal_binding/tcp_wrap.ts
- node/net.ts
- node/process.ts
- strict-ts44.tsconfig.json
- testing/asserts.ts
This commit makes deno_std `noImplicitOverride`-compliant and enables the compiler option in `deno.json` so that further changes don't regress it. Closes https://github.com/denoland/deno_std/issues/1933
> chore: Enable "noImplicitOverride" compiler option and fix errors

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
*(This is based on [microsoft/vscode-dev-containers/containers/deno](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/deno))*
Adds a `.devcontainer` definition to support VS Code remote development environments (such as GitHub Codespace for example).
It comes with latest deno version installed, along with the vscode extension pre-configured
> build: add `.devcontainer`

- async/README.md
- async/abortable.ts
- async/abortable_test.ts
Hi. 
The `abortable` is a wrapper function that makes `Promise` and `AsyncIterable` cancelable.
For example, in the case of `Promise`, it looks like this
```typescript
import { abortable } from "https://deno.land/std/async/mod.ts";
import { delay } from "https://deno.land/std/async/mod.ts";
const p = delay(1000);
const c = new AbortController();
setTimeout(() => c.abort(), 100);
// Below throws `AbortedError` after 100 ms
await abortable(p, c.signal);
```
and for `AsyncIterable` as follows
```typescript
import { abortable } from "https://deno.land/std/async/mod.ts";
import { delay } from "https://deno.land/std/async/mod.ts";
const p = async function* () {
yield "Hello";
await delay(1000);
yield "World";
};
const c = new AbortController();
setTimeout(() => c.abort(), 100);
// Below throws …
```
> feat(async): Add `abortable` to async module.

- http/file_server.ts
- http/file_server_test.ts
This PR exposes `serveDir` function from `http/file_server.ts` module.
`serveDir` can be used like the below. This example serves the files under `path/to/static/files/dir` when the requested path starts with `/static`
```ts
import { serve } from "https://deno.land/std@$STD_VERSION/http/file_server.ts";
import { serveDir } from "https://deno.land/std@$STD_VERSION/http/file_server.ts";
serve((req) => {
const pathname = new URL(req.url).pathname;
if (pathname.startsWith("/static")) {
return serveDir(req, {
fsRoot: "path/to/static/files/dir",
});
}
// Do dynamic responses
});
```
closes #1905 
closes #898
> feat(http): expose serveDir function from file_server.ts

- node/_tls_wrap.ts
- node/tls_test.ts
This PR adds basic support of `tls.createServer` in `std/node`.
part of #1475
> feat(node/tls): basic support of tls.createServer

- archive/tar.ts
This fixes the lint error:
```
(no-deprecated-deno-api) `Deno.File` is deprecated and scheduled for removal in Deno 2.0
```
---
Note:
- `Deno.File` became `Deno.FsFile` in https://github.com/denoland/deno/pull/13660
- `no-deprecated-deno-api` was updated in https://github.com/denoland/deno_lint/pull/1015
- `deno_lint` was upgraded to `0.26.0` in https://github.com/denoland/deno/pull/13758
> chore(archive): fix lint error in tar.ts

- node/_crypto/crypto_browserify/README.md
- node/_crypto/crypto_browserify/randombytes.ts
- node/_crypto/crypto_browserify/randombytes_test.ts
part of #1962 
This ports [randombytes](https://www.npmjs.com/package/randombytes), a small utility on top of `crypto.getRandomValues`, to `std/node`.
> chore(node): add randombytes from crypto-browserify

- node/_crypto/crypto_browserify/evp_bytes_to_key.ts
- node/_crypto/crypto_browserify/evp_bytes_to_key_test.ts
This PR adds [evp_bytestokey](https://www.npmjs.com/package/evp_bytestokey) module to `std/node/_crypto`. This is one of the dependencies of [`public-encrypt`](https://www.npmjs.com/package/public-encrypt)
I only ported the last test cases from the project because other test cases depends on [C extension with openssl library](https://github.com/crypto-browserify/EVP_BytesToKey/blob/master/test/main.cc), and don't seem easily portable
part of #1962
> chore(node/crypto): add EVP_BytesToKey

- streams/delimiter.ts
- streams/delimiter_test.ts
Equivalent of `LineStream`, but `string` based.
In response to whatwg/encoding#283
> feat(streams): TextLineStream

- testing/asserts.ts
- testing/asserts_test.ts
The following currently passes, though it shouldn't:
```ts
assertObjectMatch({ foo: /abc*/ }, { foo: /abc+/ });   // different pattern
assertObjectMatch({ foo: /abc+/ }, { foo: /abc+/i });  // different flags
```
It's because `RegExp` are of type `"object"` so they enter in the `filter()` function.
For some reason, the regex source pattern isn't listed by both `Object.getOwnPropertyNames` and `Object.getOwnPropertySymbols` methods, which only returns `"lastIndex"` (which isn't' enough to differentiate between 2 regexs):
```ts
const r = /abc/i
console.log(typeof r, [...Object.getOwnPropertyNames(r), ...Object.getOwnPropertySymbols(r)])
// "object", Array [ "lastIndex" ]
```
This is a small patch which avoids regexs entering this condition and instead being treated like a primitive
> fix(testing): assertObjectMatch for RegExp/Map/Set

- fs/empty_dir_test.ts
- fs/exists_test.ts
The tests failed locally. Adding --no-prompt fixed them.
> test: add --no-prompt to deno run

- async/debounce_test.ts
- testing/asserts.ts
- testing/asserts_test.ts
In the same spirit as https://github.com/denoland/deno_std/pull/969, this PR retypes the signature for `assertStrictEquals` such that it can be used as a [type assertion function](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions). The nature of the runtime assertion is now reflected in the type system.
I also added a test with comments to demonstrate this change.
Please note that — because this has an effect on the type system — it is possible that new compiler errors will appear in code where they did not before (this is intended and desirable for type safety).
> feat(testing/asserts): use assertion signature for "assertStrictEquals"

- streams/buffer.ts
- streams/buffer_test.ts
Equivalent of `std/io/buffer.ts`'s `Buffer` but with streams
> feat: streams based `Buffer`

- node/integrationtest/test.ts
npm integration test is not passing since 4e8f0e7bb80300f4ad06483436d154e7fe10b5ab (std change doesn't seem relevant to the failure, probably broken by CLI canary change).
This PR skips `npm install` test on mac and linux to make CI green for main.
#1999 tracks this issue
> chore: skip npm integration test on Linux and Mac

- README.md
Follow up to https://github.com/denoland/dotland/pull/1900
> fix(docs): update outdated reference to `deno_website2`

- fmt/colors.ts
- fmt/colors_test.ts
Bringing two updates to `ANSI_PATTERN` used in fmt/colors:
- [Fix potential ReDoS](https://github.com/chalk/ansi-regex/commit/8d1d7cdb586269882c4bdc1b7325d0c58c8f76f9)
- [Match cursorSave and cursorRestore escape codes](https://github.com/chalk/ansi-regex/commit/02fa893d619d3da85411acc8fd4e2eea0e95a9d9)
Also added preliminary test for `stripColor`.
> feat(fmt): update `ANSI_PATTERN`

- node/integrationtest/test.ts
`npm@8.5.3` (published 3 days ago) doesn't seem working with node compat mode on mac and linux. This PR pins the npm version to `8.5.2`.
closes #1999
> chore(node): pin npm version to 8.5.2 in integration test

- node/http.ts
- node/integrationtest/test.ts
This PR fixes the call of `http.request` without `href` option.
`minipass-fetch@>2` calls `http.request` without `href` option ([this commit](https://github.com/npm/minipass-fetch/commit/f96f3b13e68f3851fd9fadb762c58f441a4c3f48) started it).
`npm` started depending on `minipass-fetch@2` indirectly at [this commit](https://github.com/npm/cli/commit/3c17b6965f0c5fffd5ac908388568a307466a73f), and that [broke](https://github.com/denoland/deno_std/runs/5417966994?check_suite_focus=true) the integration test of `npm install` in compat mode in CI
closes #2001
> fix(node): fix http.request for minipass-fetch 2.x

- async/mod.ts
We forgot to re-export `abortable` in `mod.ts` in #1939. This PR fixes it.
This change also fixes the example in `async/README.md`, which imports `abortable` from `mod.ts`.
closes #1958
> fix(async): re-export abortable in mod.ts

- async/README.md
- encoding/README.md
- node/integrationtest/test.ts
CLI canary started recognizing `javascript` and `typescript` as language tags for markdown code blocks at https://github.com/denoland/deno/pull/13785, and that caused some of new type errors in std's doc testing.
This PR fixes it.
> docs: fix doc testing errors

- node/process.ts
- node/process_test.ts
`process.on("SIGBREAK", handlers)` throws with invalid signal error (SIGBREAK is not a valid signal name for non-windows platforms, ref: https://github.com/denoland/deno/blob/245f69256b9e22f7759b887e82138ad3844a8cf4/runtime/ops/signal.rs).
This PR makes `process.on` ignore `SIGBREAK` binding on non-windows platforms.
Note: `SIGBREAK` is a signal for handling CTRL + BREAK on windows, and it's only meaningful for windows. ref: https://nodejs.org/api/process.html#event-message
part of #2010
> fix(node/process): ignore SIGBREAK binding on non windows

- node/module.ts
- node/upstream_modules.ts
- node/upstream_modules_test.ts
This PR adds the shim of [get-caller-file](https://npm.im/get-caller-file).
CallSite.prototype.getFileName returns `file://` scheme url in deno, but it returns absolute file path in Node.js. This PR fixes that difference by providing shim.
`get-caller-file` is depended by yargs. So this should improve the compatibility of many cli tools which depends on yargs.
closes #2026
> feat(node): shim get-caller-file

- node/_tools/test/common/index.js
- node/global.ts
- node/global_test.ts
This PR replaces `global` object in std/node with Proxy object which intercepts the access to timer functions and returns the Node.js versions of them.
This change enables running the code like the below:
```js
const { setInterval } = global;
...
setInterval(...).unref();
```
The actual example of the above structure is found in [here](https://github.com/mochajs/mocha/blob/b46db73fa0e58c92bde925eaa4054210b771b5a9/lib/nodejs/parallel-buffered-runner.js) in mocha code base.
Note: This change doesn't affects globalThis object. So actual global timers are still web compliant timers provided by Deno CLI.
---
part of https://github.com/denoland/deno/issues/12886
> fix(node): make global.<timerFunc> Node.js timers

- node/process.ts
- node/process_test.ts
This PR changes the behavior of binding to 'unimplemented' events on `process` object.
With this change, the events are still not handled, but the listeners are actually registered on `process` object and it increased/decreased the `listenerCount` of the each event.
This makes mocha's unit testing happy, and now we can pass `npx nps test.node.jsapi` test category in compat mode with this change.
part of #12886
> chore: warn on non supported event, but still register listener

- flags/mod.ts
Additionally the `ArgParsingOptions` interface has been renamed to
`ParseOptions`. This aligns with the precedent from TS's lib files where
function option bags are named after the function that they are an
options bag for (eg `Performance#mark` + `PerformanceMarkOptions`).
> chore: improve docs for flags/

- node/_fs/_fs_write.mjs
- node/_fs/_fs_write_test.ts
If `buffer.length` is larger than `length`, more date will be writed into file.
> fix(node/fs): Fix writing redundant data

- node/_tls_wrap.ts
We currently creates temporary cert files in `TlsServer.listen` to pass them to `Deno.listenTls` because `Deno.listenTls` didn't support string args for cert files at tha time. We added `cert` and `key` option in https://github.com/denoland/deno/pull/13740, and now we can simply use those options to specify certs with strings.
> refactor(node/tls): use in-memory options for cert files

- node/_fs/_fs_readlink.ts
- node/_fs/_fs_streams.ts
- node/_utils.ts
- node/cluster.ts
- node/dgram.ts
- node/domain.ts
- node/http2.ts
- node/https.ts
- node/inspector.ts
- node/internal/child_process.ts
- node/internal/http.ts
- node/internal_binding/handle_wrap.ts
- node/internal_binding/pipe_wrap.ts
- node/internal_binding/stream_wrap.ts
- node/internal_binding/tcp_wrap.ts
- node/internal_binding/util.ts
- node/net.ts
- node/repl.ts
- node/tls.ts
- node/v8.ts
- node/vm.ts
- node/worker_threads.ts
- node/zlib.ts
This PR makes the 1st arg (message) for `notImplemented` utility required.
If the message is omitted, the program only shows `notImplemented` and it doesn't give any information, and therefore that's inconvenient. This PR make the message required and improve the situation.
> chore(node): make the message for notImplemented required

- log/handlers.ts
- log/handlers_test.ts
When I create a log formatter which like `[{loggerName}][{levelName}] {msg}` and I expect to get a log looks like `[database][INFO] client connecting...` , but I get `[{loggerName}][{levelName}] client connecting...`. To solve this problem, I try to add a SPACE between `[{}]` and it worked, but in my opinion, we should allow removing the space between the log record fields.
> fix(log): Fix log formatter issue

- .github/workflows/version_bump.yml
So close. Maybe this will fix this.
```
Creating branch release_0_134.0...
Switched to a new branch 'release_0_134.0'
[release_0_134.0 9bfa4a14] 0.134.0
2 files changed, [10](https://github.com/denoland/deno_std/runs/5869850645?check_suite_focus=true#step:5:10) insertions(+), 1 deletion(-)
Pushing branch...
fatal: could not read Username for 'https://github.com': No such device or address
error: Uncaught (in promise) Error: Error executing git. Code: 128
throw new Error(
^
at runCommandWithOutput (https://raw.githubusercontent.com/denoland/automation/0.10.0/helpers.ts:47:[11](https://github.com/denoland/deno_std/runs/5869850645?check_suite_focus=true#step:5:11))
at async file:///home/runner/work/deno_std/deno_std/_tools/release/02_create_pr.ts:[19](https://github.com/denoland/deno_std/runs …
```
> chore(ci): fix version bump git push

- archive/tar.ts
- io/readers.ts
- io/readers_test.ts
- mime/multipart.ts
> fix(io/readers): use an array as a MultiReader constructor parameter to avoid Maximum call stack size exceeded

- node/global_test.ts
- node/internal/util/debuglog.ts
> fix(node): Make global.ts evaluate synchronously

- deno.json
- node/_fs/_fs_close.ts
- node/_fs/_fs_close_test.ts
- testing/asserts.ts
From denoland/deno#14072 `deno run` prints warning and that causes some CI errors in `node/child_process` testing. This PR fixes it.
> chore: update node:unit task to fix CI

- testing/_test_suite.ts
- testing/asserts.ts
- testing/bdd.ts
- testing/bdd_test.ts
The assertSnapshot function from https://github.com/denoland/deno_std/pull/2039 that is being worked on will need access to the `Deno.TestContext` for the test case it is used in. This updates `it` to take a function that will have the `Deno.TestContext` passed to it as its first and only argument. This will also enable making use of the test step api within an `it` function.
The `deno fmt` command also made me update the `assert.ts` file.
> feat(testing): add TestContext argument to it

- http/file_server.ts
- http/file_server_test.ts
- testing/asserts.ts
Towards #2107 
Major changes:
- use native readable streams optimization. `Deno.File#readable` instead of a wrapper stream. See https://github.com/denoland/deno/pull/14284
- use fnv-1a default etag hash function. Adds an option to allow using others.
- ~~faster hex function for out of other algorithms (like `sha-1`), using hex lookup table.~~
- disables logging by default when invoked independently. Replaces the `--quiet` flag with `--verbose`. Public API remains unchanged.
- ~~use simpler extname extraction to avoid scanning manually. (downsides?)~~
Benchmarks:
`main`:
```
Running 10s test @ http://localhost:4507/README.md
8 threads and 20 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.44ms  522.77us  26.73ms   97.55%
Req/Sec     1.40k   119.07     2.63k …
```
> perf(http): optimize file server

- .github/codecov.yml
Hi, Tom from Codecov here. I noticed that you were using Codecov but weren't actually getting any notifications on pull requests. I figured it would be useful to get some idea if code being changed is being tested, but also not blocking CI/merging. Let me know if this makes sense or if we can do something that would be helpful.
> chore(ci): add informational Codecov status checks

- node/_tools/test/common/index.js
This PR updates the setup of global var leak detection in node compat testing.
We added `reportError` global in https://github.com/denoland/deno/pull/13799. We need to mark this as known global now.
> test(node): update global var leak detection

- node/_crypto/randomInt.ts
- node/_crypto/randomInt_test.ts
Referencing #2099 - committed the `randomInt` fix and modified the `between` assertion within `randomInt_test.ts` to disallow maximum inclusion when checking generated value.
> Change crypto/randomInt (and associated test) to generate maximum exclusive instead of inclusive

- node/_crypto/crypto_browserify/randombytes.ts
- node/_crypto/randomBytes.ts
- node/_crypto/randomInt.ts
- node/crypto.ts
- testing/asserts.ts
close #2114
I think the cause of #2114 is that the global variable `crypto` in the repl references the Node's Crypto API instead of the Web Crypto API.
This PR will replace `crypto.xxx` with `globalThis.crypto.xxx`.
I'm not really sure if this change fixes #2114 (I don't know how to test it). Therefore, there is still no certainty that this approach is suitable.
> fix(node): Use Web Crypto API via globalThis

- wasi/snapshot_preview1.ts
According to the node.js docs,
we can use WASI class without arguments. I mean that the `ContextOptions` should be optional.
This is a problematic to load https://github.com/ruby/ruby.wasm .
See also: https://nodejs.org/api/wasi.html
> fix(wasi): ContextOptions is an optional argument

- http/server.ts
I would like to see `ServeTlsInit` being exported the way `ServeInit` already is.
> http: serve() should export the interface ServeTlsInit

- testing/_test_utils.ts
- testing/mock.ts
- testing/mock_test.ts
- testing/time_test.ts
This has a breaking change because the generic parameters have changed from `spy<Self, Args, Return>()` to `spy<Self, Prop>()`.
Only the types have been changed so there should be no runtime difference.
There's still a type error that I'm not sure how to resolve, which is why this is still a draft. Initially I thought it was [a bug in TypeScript](https://github.com/microsoft/TypeScript/issues/48805). But it seems like that's not the case.
Adding `// @ts-ignore` seems to work without breaking any other types, but I'd prefer to find a better way around this.
Fixes #2121
> feat(testing)!: Infer stub and spy return types from properties

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot_test.ts
Adds regression test for #2144 
Depends on [this PR in denoland/deno](https://github.com/denoland/deno/pull/14387).
> test(testing/snapshot): Add regression test for Deno.inspect compacting empty iterables

- archive/tar.ts
- async/mod.ts
- bytes/mod.ts
This will improve the index view of the documentation for these parts of std in doc.deno.land.
> docs: improve module JSDoc for archive, async, bytes

- testing/asserts.ts
- testing/asserts_test.ts
fixes #2171 
The `equal` function keeps track of encountered objects by adding them to `seen`. Encountered objects must be added to `seen` before the first recursive call to `compare` because otherwise the `compare` function will infinitely recurse when comparing circular objects.
> fix(testing): Compare circular objects

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
- testing/snapshot_test.ts
> fix(testing/snapshot): handle multiline strings

- node/dns.ts
After #2164, I get this error when I try to use the node/net module.
```shell
> deno run ./node/module_all.ts
Check file:///C:/Users/azusa/work/deno/deno_std/node/module_all.ts
error: TS2614 [ERROR]: Module '"file:///C:/Users/azusa/work/deno/deno_std/node/dns.ts"' has no exported member 'LookupOneOptions'. Did you mean to use 'import LookupOneOptions from "file:///C:/Users/azusa/work/deno/deno_std/node/dns.ts"' instead?
import type { LookupOneOptions } from "./dns.ts";
~~~~~~~~~~~~~~~~
at file:///C:/Users/azusa/work/deno/deno_std/node/net.ts:70:15
```
Fix this problem by exporting the interface that is no longer exported from node/dns after #2164 again.
> fix(node/dns): export more types

- node/module_test.ts
- node/worker_threads.ts
Fixes #2181. Uses a different method for detecting if the environment is in a node worker thread so that web workers don't count. That way it doesn't wait for a parent startup message that is never coming.
> fix(node/worker_threads): Don't wait for parent message in web worker

- bytes/equals.ts
These two methods are used on `bytes/equals_bench.ts` but are not exported, so it throws TypeScript and Runtime Errors, most notably 
```
error: Uncaught SyntaxError: The requested module './equals.ts' does not provide an export named 'equalsNaive'
import { equalsNaive, equalsSimd } from "./equals.ts";
```
I discover these errors while trying to port the remaining benchmarks to the new `Deno.bench` API, similar to #2173
> :bug: Export equalsSimd and equalsNaive

- node/_buffer.mjs
- node/_tools/test/parallel/test-buffer-write.js
As indicated by the [node source code](https://github.com/nodejs/node/blob/ce29d28/src/node_buffer.cc#L726), the `length`parameter is optional and defaults to the length of the `src`.
Closes https://github.com/denoland/deno_std/issues/2046
> fix(node/module): interpret length parameter as optional in blitBuffer

- node/timers.ts
- node/timers_test.ts
Fixes promisified timers. Without this fix. this code:
```
import { setTimeout } from 'https://deno.land/std@0.138.0/node/timers/promises.ts';
await setTimeout(2000);
```
Would result in:
```
error: Uncaught TypeError: Callback must be a function. Received 2000
throw new codes.ERR_INVALID_CALLBACK(callback);
```
I looked around for code on how to easily test this, but could not really find any good way.
> fix(node/timers): set custom promisify function

- testing/__snapshots__/snapshot_test.ts.snap
Probably caused by https://github.com/denoland/deno/pull/14495
Now some snapshot expectations need to be updated.
> test(testing/snapshot): update snapshot expections

- collections/deep_merge.ts
- collections/deep_merge_test.ts
This commit adds logic to `deepMerge()` to prevent infinite looping over cyclic data structures. The algorithm will now bail out before calling `mergeObjects()` if either object has already been processed.
Fixes: https://github.com/denoland/deno_std/issues/2134
> fix(collections): prevent cycles in deepMerge()

- http/server.ts
- http/server_test.ts
This PR adds `onListen` option to `serve` and `serveTls` functions. You can override the default logging bahavior of these functions.
closes #2186 
closes #2071 
Note: I didn't add `secure: boolean` option to params for `onListen` callback (suggested in https://github.com/denoland/deno_std/issues/2186#issuecomment-1125347398) as it should be obvious from the function you are using (i.e. `secure` is false when you use `serve`, and `secure` is true when `serveTls`.)
> feat(http): add onListen option to serve

- testing/asserts.ts
- testing/asserts_test.ts
- testing/mock_test.ts
Based on issue #1302 
`assertRejects` now throw when the given function does not return a promise.
> feat(assertRejects): fails on synchronous throw #1302

- encoding/csv.ts
- encoding/csv_test.ts
Hey, I was using the csv parse function with a poorly coded csv file and the error message wasn't too helpful with tracking what exactly was wrong. 
I added a couple more hints:
- The number of fields found for the headers row
- The number of fields of values row (expected to match the headers)
When this is useful:
- When the number of headers doesn't match one of the subsequent rows
> Improved error message for csv's parse function

- testing/asserts.ts
- testing/asserts_test.ts
This commit updates `assertStrictEquals()`, `assertAlmostEquals()`, and `assertNotStrictEquals()` to use `Object.is()` instead of the `===` operator. The reason is that `Object.is()` better matches user expectations of an assertion library in a couple edge cases. It also better aligns with the behavior of at least one other runtime's assertion library (Node.js).
Fixes: https://github.com/denoland/deno_std/issues/2151
> BREAKING(testing): use Object.is() for strict equality

- .github/workflows/ci.yml
This PR makes CI checks faster by using xl runners for lint and wasm jobs.
> ci: use xl runners for lint and wasm jobs

- permissions/test.ts
The error message for invalid permission name has been changed in https://github.com/denoland/deno/pull/14676, and now CI is failing in main.
This PR fixes it by updating the expectation of the error message.
> test(permissions): update error message expectation

- async/pool_test.ts
Removes an unnecessary `console.log` in `async/pool_test.ts` and replaces it with `assertEquals`.
> replace console.log with array and assertEquals

- node/internal_binding/constants.ts
- node/os.ts
- node/os_test.ts
This PR adds SIGBREAK to the OS signals, a prerequisite for https://github.com/denoland/deno/pull/14694.
> chore: add sigbreak to os constant

- flags/README.md
- flags/mod.ts
- flags/test.ts
> breaking(flags): add collect option

- archive/tar.ts
- async/mux_async_iterator.ts
- bytes/bytes_list.ts
- collections/binary_heap.ts
- hash/_sha3/sponge.ts
- hash/md5.ts
- hash/sha1.ts
- io/readers.ts
- io/writers.ts
- log/logger.ts
- mime/multipart.ts
- node/_fs/_fs_dir.ts
- node/http.ts
- node/internal/child_process.ts
- node/url.ts
- testing/asserts_test.ts
- testing/snapshot.ts
Replace TypeScript `private` variables and methods to JavaScript private identifiers. This PR doesn't include refactoring to private identifies where it's not possible to do so (e.g. properties in constructors).
Tackles https://github.com/denoland/deno_std/issues/1649.
> chore: replace TS `private` with private identifiers

- async/README.md
- async/tee.ts
Eliminate redundant function wrapping in documentation of async's tee method. Resolves https://github.com/denoland/deno_std/issues/2279
> docs(async): use top-level await in tee docs

- http/server_test.ts
- io/buffer_test.ts
- node/fs/_fs_writeFile_test.ts
- node/internal/crypto/_randomBytes_test.ts
- testing/asserts_test.ts
- testing/mock_test.ts
This PR fixes unhandled `assertRejects` calls in test cases.
> test: fix unhandled promises in test cases

- testing/README.md
- testing/asserts.ts
This PR updates the jsdocs of `assertThrows` and `assertRejects` to follow the recent changes in the behaviors of them.
> docs(testing): improve docs of assertThrows and assertRejects

- streams/delimiter.ts
- streams/delimiter_test.ts
Ref https://github.com/denoland/deno_std/pull/2267#issuecomment-1139443404
cc @jsejcksn
> fix: put TextLineStream CR handling behind option

- node/_tools/common.ts
- node/_tools/config.json
- node/_tools/test.ts
The test case `node/_tools/test/parallel/test-net-socket-close-after-end.js` looks very flaky in macOS recently.
This PR (temporarily) disables that test case only on darwin.
closes #2241
> chore(node): ignore test-net-socket-close-after-end.js on darwin

- async/pool_test.ts
Fixes a deprecation warning. Resolves https://github.com/denoland/deno_std/issues/2283
This is a follow-up of https://github.com/denoland/deno_std/pull/2284
@kt3k I've basically followed your suggestion there, with the slight modification that instead of sending `ERROR_WHILE_MAPPING_MESSAGE` as a parameter to `assertRejects`, I maintain the strict equality check. It looks like `assertRejects` checks for inclusion of the passed-in message, rather than strict equality.
> tests(async): use generic assertRejects in pool_test.ts

- node/async_hooks.ts
This fixes an issue where TypeScript correctly identifies symbol field initialization errors in TypeScript 4.7 but previously didn't.
Ref: denoland/deno#14242
> fix(node): type checking on AsyncResource

- media_types/README.md
- media_types/_util.ts
- media_types/_util_test.ts
- media_types/mod.ts
- media_types/test.ts
- media_types/vendor/LICENSE
- media_types/vendor/mime-db.v1.52.0.json
Once upon a time [deno.land/x/media_types](https://deno.land/x/media_types) was inside `std` but it was removed due to there being a debate about the API and I took over maintaining it.
The PR intends to reverse this and will result in a series of PRs brining some of the common APIs common to handling HTTP requests into the std library.
@lucacasonato this includes the GoLang `mime` package APIs as well as some parts of the `jshttp/mime-types` APIs that `deno.land/x/media_types` was based on.  It should provide an easy migration path for users of `deno.land/x/media_types` but also provide more logical APIs aligned to what is in GoLang.
Once this is landed, a subsequent PR should be created so the fileserver uses this instead of it partial mime db.  I will also refactor oak and my other …
> feat: add media_types

- http/file_server.ts
I accessed https://doc.deno.land/https://deno.land/std@0.141.0/http/file_server.ts and noticed that there was no description of how to specify the options.
- Export some interfaces according to the [style guide](https://deno.land/manual/contributing/style_guide#export-all-interfaces-that-are-used-as-parameters-to-an-exported-member). ("Export all interfaces that are used as parameters to an exported member")
- Add a description to JSDoc.
> chore(http/file_server.ts): export interface for serveDir/serveFile

- http/file_server.ts
- http/file_server_test.ts
This PR refactors http/file_server to use the media_types module from std.
It also removes some dead code that was not being referenced in the file.
> refactor(http): file_server uses std/media_types

- media_types/mod.ts
This works around an issue when you try to use `media_types` under Node.js via dnt.  Node.js doesn't have as good type inference as Deno does when using JSON imports, and causes some assignment issues.
> fix(media_types): work around type issues under Node.js

- node/README.md
- node/assert.ts
- node/internal/util/comparisons.ts
Those were skipped because they don't have test cases in `test-assert.js`.
I used the implementation of `isDeepEqual()` from [`./node/internal/utils/comparisons.ts`](https://github.com/denoland/deno_std/blob/main/node/internal/util/comparisons.ts), which I believe to be a direct copy of the code in Node.
These functions missing is what prevents [Recast](https://github.com/benjamn/recast) from working on Deno using esm.sh.
It's my first time contributing to the Node compat modules, so let me know if I missed anything 😊
> feat(node/assert): add deepEqual and notDeepEqual 

- streams/conversion.ts
- streams/conversion_test.ts
> Hi, just letting you know, that an empty `catch` handler doesn't catch anything. You have to pass an empty function at least.
_Originally posted by @thekondr in https://github.com/denoland/deno_std/pull/2227#discussion_r890269446_
Based on the comments above, use `promise.catch(()=>{})` instead of `promise.catch()` that does nothing, and ignore the error correctly.
> chore(stream/conversion.ts): handle errors in `toTransformStream` correctly

- http/server.ts
- http/server_test.ts
Provides valid `port` to `ServeInit.onListen`.  
Fixes default `Listening on http://hostname:0/` message.
> Pass resolved ephemeral port to onListen

- dotenv/mod.ts
- dotenv/mod_test.ts
- dotenv/testdata/.env.comments
support inline comment like:
```
FOO=bar # this is a comment
```
> fix(dotenv): support inline comment

- streams/conversion.ts
> `Deno.copy` will be removed in Deno 2.0.
There's also a reference of `Deno.copy` here:
https://github.com/denoland/deno_std/blob/e72e13db63328cf8a91c2e274f175229653f5637/examples/curl.ts#L6
Not sure how to handle that because of different context.
> chore(streams): remove deprecated `Deno.copy` from example

- README.md
Actually deno fmt --check does fail currently, some files seems to be deliberately manually formatted, should those be added as an exception to deno.json?
> docs(README): using deno fmt --check

- node/_process/streams.mjs
- node/process_test.ts
This commit adds `cursorTo()`, `moveCursor()`, `clearLine()`, and `clearScreenDown()` to the Node.js compat `stdout` and `stderr` streams.
Refs: https://github.com/denoland/deno_std/issues/2322 (this does not fix the issue, but should help unblock Vite in compat mode)
Refs: https://github.com/denoland/deno_std/issues/2055
> feat(node): add missing TTY methods to stdout,stderr

- bytes/equals.ts
- bytes/equals_bench.ts
> chore(bytes): rename `equalsSimd` to `equals32Bit`

- encoding/_yaml/loader/loader.ts
- encoding/front_matter.ts
- encoding/front_matter_test.ts
Closes https://github.com/denoland/deno_std/issues/2333
> encoding: add front matter module

- collections/mod.ts
This adds back collections/mod.ts that was removed in https://github.com/denoland/deno_std/pull/2321 , but adds it back with a warning. This will allow people to use collecitons/mod.ts in non-production scenarios for quick hacking and then convert their code to use the specific imports before deployment to make the module graph lean (see https://github.com/denoland/deno_std/pull/2321#issuecomment-1152423433 for more rationale about why we should have a mod.ts).
Overall, my preference would be to not even have a warning here and instead just document to not use it when publishing modules, but it was discussed during the design meeting that this would be a good compromise to try to get people away from using mod.ts when distributing or deploying modules, but still be able to use it in quick …
> refactor: add back collections/mod.ts with a warning

- _tools/release/02_create_pr.ts
- deno.json
- Uses `deno task` because that uses the current executable when running deno commands now
- Uses `deno task --cwd .` in order to move wasmbuild to a new task
> chore: updates for using deno 1.23

- http/file_server.ts
All other `Response` here use `Status` enum and `STATUS_TEXT`,
may as well do that for 206 and 200.
> fix(http/file_server): uniform status & statusText

- node/perf_hooks.ts
This reverts commit 2e180b039369a06d46adf506142b597c7ea28f35.
The commit is being reverted because the necessary changes were
made in https://github.com/denoland/deno/pull/14573.
> Revert "fix(node): omit EventTarget methods from performance (#2358)"

- node/perf_hooks.ts
- node/perf_hooks_test.ts
We removed the omission of EventTarget methods from typing in https://github.com/denoland/deno_std/pull/2360, but we forgot to shim these actual methods for `std/node`'s `performance` object and that now causes type error in CI. This PR fixes it.
ref:
- https://github.com/denoland/deno/pull/14573
- https://github.com/denoland/deno_std/pull/2358
> fix(node): make performance object event target

- wasi/snapshot_preview1.ts
- wasi/snapshot_preview1_test.ts
I have no idea where the official WASI spec lives, but according to the [Node documentation](https://nodejs.org/api/wasi.html#wasiinitializeinstance), `initialize()` invokes the exported `_initialize()` function on the Wasm module, if it exists. Currently, the function throws.
> Fix WASI initialize()

- encoding/json/_parse_test.ts
- encoding/json/_stringify_test.ts
`ConcatenatedJSONParseStream` internally uses `JSON.parse` and the test cases depend on the error message of the native `JSON.parse`.
Recently the error message for invalid json like `{foo: 1}` has been changed from `Unexpected token f` to `Expected property name or '}'` in the latest v8 update denoland/deno#14874. We need to update these expectations in these test cases.
> test(encoding/json): fix parse stream test expectation

- examples/chat/server_test.ts
Temporary change, ref https://github.com/denoland/deno/pull/14919#issuecomment-1161670859
> chore: Don't use Deno.spawn() in chat server test

- encoding/csv/stream.ts
- encoding/csv/stream_test.ts
- encoding/testdata/complex.csv
`CSVStream` had a problem where CRs in fields and consecutive trailing CRs were not handled properly. This PR fixes that problem.
The PR also adds some test cases.
> fix(encoding/csv/stream): properly handle CR characters

- encoding/json/_parse.ts
[`null` is a valid JSON type](https://datatracker.ietf.org/doc/html/rfc8259#section-3), but was not included in the union in the initial PR.
> fix(encoding/json): add `null` to JSONValue union

- node/fs.ts
`createReadStream()` was previously only available via the `default` export. This commit fixes that.
Fixes: https://github.com/denoland/deno_std/issues/2389
> fix(node): export createReadStream() from fs

- testing/asserts.ts
- testing/asserts_test.ts
This commit updates the equality checking logic of Sets to
break out of an inner loop when a match occurs. Prior to this
commit, it was possible to perform too many comparisons, which
incorrectly made a counter in the code go below zero.
Fixes: https://github.com/denoland/deno_std/issues/2295
> fix(testing): break out of Set equality check on match

- dotenv/mod.ts
- dotenv/mod_test.ts
- Closes #2366 
Note that this PR makes the `message` parameter for `MissingEnvVarsError` **required** (was optional) in order to maintain a reasonable param order while ensuring the `missing` param is required.  
If this is an issue it can be reverted, but I believe the `missing` param should remain required for consistency.
> feat(dotenv): include missing vars in MissingEnvVarsError

- testing/README.md
- testing/__snapshots__/snapshot_test.ts.snap
- testing/asserts.ts
- testing/snapshot.ts
- testing/snapshot_test.ts
> feat: add createAssertSnapshot

- node/_fs/_fs_exists.ts
- node/_fs/_fs_exists_test.ts
fs.exists has non-standard callback signature. We need to provide special implementation for promisify via the special property `Symbol.for("nodejs.util.promisify.custom")`
cf. https://github.com/nodejs/node/pull/13316
> fix(node/fs/exists): fix promisified exists

- http/README.md
- http/http_errors.ts
- http/http_errors_test.ts
- http/mod.ts
This provides HTTP error classes for each HTTP error status code plus some utility functions.  This allows more structured handling of HTTP errors.  It is part of oak commons being contributed back to std.
> feat(http): add HTTP errors

- encoding/front_matter.ts
This PR fixes the doc example of `encoding/front_matter` module.
Thanks @geoffreypetri for reporting this ref https://github.com/denoland/deno_std/pull/2335#discussion_r918047909
> docs(encoding/front_matter): fix example

- node/module.ts
- node/module_test.ts
This PR fixes the error message when the http(s) urls are given to `createRequire`.
This addresses the issue reported in https://github.com/denoland/deno_std/issues/955#issuecomment-1180179073
> fix(node/module): improve error message of createRequire

- io/writers.ts
- io/writers_test.ts
The PR fixes  an error I'm seeing in a real-world use case when I try to copy entries from https://deno.land/std@0.141.0/archive/README.md#untar into a `StringWriter`, like:
```ts
const sw = new StringWriter();
const res = await copy(entry, sw);
```
~~I'm not sure whose responsibility it is to keep the buffered chunks inside `StringWriter.#chunks` isolated from the inputs to `.write`.~~
Given:
https://github.com/denoland/deno_std/blob/255f3fa8b2c7bd666018178e6dd3bea5422f23a3/io/types.d.ts#L62
... it's the `StringWriter`'s responsibility to copy data out of `p` during `write(p)`, rather than maintaining references to `p`.
> fix(io) StringWriter retaining references after write

- http/http_errors.ts
- http/http_errors_test.ts
This PR closes https://github.com/denoland/deno_std/issues/2451 by adding an optional `headers` property. Through this option, error specific headers could be added to the error (response) data. For example, if JWT verification failed, the error creation could look like this:
```ts
const httpError = createHttpError(401, "Unauthorized", {
headers: new Headers({ "WWW-Authenticate": "Bearer" }),
});
console.log(httpError.headers); // Headers { "www-authenticate": "Bearer" }
```
> feat(http/http_errors): Add headers property

- node/http.ts
- node/http_test.ts
- node/https.ts
Node automatically sets the protocol in http and https defaults, which makes some node modules break if they do not set a protocol in the options.
Feel free to improve the code added as I'm not that familiar with how ts works.
> fix(node/http(s)): Set the url protocol by default

- collections/includes_value.ts
This is a tiny fix for a code example of `collections/include_value` function. Added closing triple backquotes for the code block.
> docs(collections): fix code example in `include_value` function

- node/_tools/config.json
> test: skip test-net-allow-half-open.js on darwin

- node/_fs/_fs_exists.ts
Fixes https://github.com/denoland/deno_std/issues/2494
`fs.existsSync` should never throw as per Node implementation
> fix(node): fs.existsSync never throws

- io/README.md
Having the `title` attribute in the code blocks, removes the syntax highlighting of that code block in the webpage. Either we should support attributes. But since it seems like the `title` attribute is used nowhere else in this repository READMEs, I removed those two.
> docs(io): remove title attribute

- crypto/README.md
- crypto/mod.ts
- crypto/test.ts
- crypto/timing_safe_equal.ts
- crypto/timing_safe_equal_test.ts
- node/internal_binding/_timingSafeEqual.ts
This adds `subtle.timingSafeEqual()` to `std/crypto` which is used to compare array buffers in a way that cannot be exploited in timing based attacks.
This is like to be added to WebCrypto at some point in the near future (see: https://github.com/w3c/webcrypto/issues/270) but until that point, we should have it in std. It is required #2303 which I am refactoring as part of the migration of oak commons to std.
It also refactors `node/crypto/timingSafeEqual` to use this instead of its own implementation (which is very close to this implementation, but supports Node.js's `Buffer` as well).
> feat(crypto): add subtle.timingSafeEqual()

- node/child_process.ts
Vite complains about missing API but never uses it :)
> node: add stub for child_process.execSync

- http/server.ts
- http/server_test.ts
Since [`certFile` and `keyFile` option in `Deno.listenTls` is deprecated and will be removed in Deno 2.0](https://github.com/denoland/deno/pull/13740), so I changed to use `cert` and `key` option directly in `serveTls` and changed `ServeTlsInit` interface a bit.
> feat(http): support cert, key options in serveTls

- encoding/csv.ts
- encoding/csv/_parser.ts
- encoding/csv_test.ts
- removes BufReader as input for `parse`
- makes `parse` sync and browser compatible
> feat(encoding/csv): sync parse

- node/internal/errors.ts
The function hideStackFrames had been moved to another file, didn't remove declared type
closes #2516
> fix:2516 remove new used declared 'GenericFunction'

- http/cookie.ts
- node/_utils.ts
- node/child_process.ts
- node/internal/errors.ts
- node/internal/idna.ts
Closes #2493. This was done by replacing `@param\s+\{.*\}` with `@param`. The same was done for `@return` and `@returns`.
Might be worth noting that keeping these directives type-free might have to be done via a new rule for `deno lint`. Otherwise, it has to be done manually like this.
> docs: removed types from jsdoc directives

- collections/binary_heap.ts
- collections/binary_heap_test.ts
There were 2 issues and I fixed both. I found them while investigating issue https://github.com/denoland/deno_std/issues/2522.
1. push was using the wrong algorithm for finding the parent index. It would end up comparing and swapping with the wrong index in some cases. The first test case below pins the correct behavior. The test case passes for the heap npm module too.
2. pop would swap with the wrong child if both were less than the parent value. It would always swap with the left instead of the one that is lowest.
Below are 2 quotes from the [Binary Heap Wikipedia page](https://en.wikipedia.org/wiki/Binary_heap).
Steps for insertion:
> 1. Add the element to the bottom level of the heap at the leftmost open space.
> 2. Compare the added element with its parent; if they are in the …
> fix(collections): Fix edge cases for BinaryHeap

- node/_fs/_fs_access.ts
- node/_fs/_fs_appendFile.ts
- node/_fs/_fs_chmod.ts
- node/_fs/_fs_chown.ts
- node/_fs/_fs_copy.ts
- node/_fs/_fs_link.ts
- node/_fs/_fs_lstat.ts
- node/_fs/_fs_mkdir.ts
- node/_fs/_fs_mkdtemp.ts
- node/_fs/_fs_open.ts
- node/_fs/_fs_readFile.ts
- node/_fs/_fs_readdir.ts
- node/_fs/_fs_readlink.ts
- node/_fs/_fs_realpath.ts
- node/_fs/_fs_rename.ts
- node/_fs/_fs_rm.ts
- node/_fs/_fs_rmdir.ts
- node/_fs/_fs_stat.ts
- node/_fs/_fs_symlink.ts
- node/_fs/_fs_truncate.ts
- node/_fs/_fs_unlink.ts
- node/_fs/_fs_utimes.ts
- node/_fs/_fs_watch.ts
- node/_fs/_fs_writeFile.ts
- node/fs.ts
- node/fs/_fs_writeFile_test.ts
This fixes #2510 by adding types to the `node/fs/promises.ts` exports.
1. Moved the `promisfy()` calls from `node/fs.ts` to the individual modules in the `_fs/` folder. (Some of the arguments types aren't exported from those files, this seemed like the right thing to do)
2. Manually typed the promisified functions via `as`
3. Fixed a type error in `node/fs/_fs_writeFile_test.ts` (created by the new types) by typecasting the `made-up-encoding` string to the TextEncodings type
> feat(node): add types to fs/promises

- crypto/README.md
- crypto/keystack.ts
- crypto/keystack_test.ts
- crypto/mod.ts
This adds a utility class which is a pre-cursor to being able to provide a cookie interface that can transparently sign and validate client cookies to prevent cookie tampering, which is a best practice we should be promoting.  It is currently part of `oak_commons` that I am contributing back to `std`.
> feat(crypto): add KeyStack for rotatable key data signing

- testing/README.md
- testing/asserts.ts
- testing/asserts_test.ts
For #2444. Deliberately kept simple as to not mess with the natural order of things (`typeof actual` and `unexpectedType`).
closes #2309
> feat(testing/asserts): assertNotInstanceOf

- node/_tools/test/parallel/test-util-types.js
- node/internal/util/types.ts
- node/internal/util/types_test.ts
Changed to use [get %TypedArray%.prototype [ @@toStringTag ]](https://tc39.es/ecma262/#sec-get-%typedarray%.prototype-@@tostringtag) for checking TypedArray.
> fix(node): Stricter checking of TypedArray

- http/README.md
- http/cookie_map.ts
- http/cookie_map_test.ts
- http/mod.ts
This PR adds `CookieMap` and `SecureCookieMap` to `std/http`. It is part of the ongoing effort to migrate parts of oak/oak_commons into `std`.
`CookieMap` provides a `Map` like interface to request and response cookies, while `SecureCookieMap` provides a similar interface, but accepts a key ring object for transparent verifying and signing cookies, helping ensure cookies cannot be tampered with client side.  These features have been present in oak for an extended period of time and are well liked and used.
Because of the async nature that built in encryption, `SecureCookieMap` methods operate asynchronously.  Because of this, when @kt3k and I paired on it, we agreed that having a sync `CookieMap` which didn't support key signing would be useful.
Also, @lucacasonato was concerned about the …
> feat(http): add CookieMap and SecureCookieMap

- _deno_unstable.ts
- async/README.md
- async/delay.ts
For #1730. Am I right in saying a test can't currently be done for this?
> feat(async/delay): add persistent option

- encoding/csv.ts
- encoding/csv_test.ts
> feat(encoding/csv): remove ColumnOptions

- testing/asserts.ts
For #2170. FYI `typeof Nan` is `number`, so `Nan` was omitted from the `Falsy` type.
> feat(testing): better assertFalse types

- encoding/json/_parse.ts
Improves type safety by adding `undefined` to the union of values of the string-indexed object type union member of `JSONValue`: now its values are effectively optional, which better represents that no object will have a not-undefined value at every possible key.
> fix(encoding/json): Improve safety of `JSONValue` object type

- encoding/jsonc.ts
As a continuation of #2565, I'd like to improve not only `encoding/json/_parse.ts` but also `encoding/jsonc.ts` types.
I should have suggested it when I commented on https://github.com/denoland/deno_std/pull/2565#issuecomment-1228053348, but I forgot.
> fix(encoding/jsonc): Improve safety of `JSONValue` object type in `jsonc.ts`

- node/http.ts
This stub makes Fastify work in Deno.
```js
import f from "npm:fastify";
const fastify = f({ logger: true })
// Declare a route
fastify.get('/', async (request, reply) => {
return { hello: 'world' }
})
// Run the server!
const start = async () => {
try {
await fastify.listen({ port: 3000 })
} catch (err) {
fastify.log.error(err)
process.exit(1)
}
}
start()
```
CC @mcollina
> feat(node): add Server.setTimeout() stub

- node/internal/streams/duplex.mjs
- node/internal/streams/writable.mjs
- fix #2566
I run `grep 'Promise.All' -nr .` in the repo and only found 3 typos. Let me know if I miss somewhere else.
> chore(node): change Promise.All to Promise.all

- node/_fs/_fs_access.ts
- node/_fs/_fs_access_test.ts
This PR fixes the permission handling of accessSync when the process uid is the owner of the given file.
> fix(node/fs): fix accessSync permission handling

- encoding/README.md
- encoding/csv/stream.ts
- encoding/csv/stream_test.ts
- encoding/json/_parse.ts
- encoding/json/_parse_test.ts
- encoding/json/_stringify.ts
- encoding/json/_stringify_test.ts
- textproto/mod.ts
- textproto/test.ts
We usually use camelCase and PascalCase for public API names, but there were some exceptions to this rule in std.
- `JSONParseStream`
- `ConcatenatedJSONParseStream`
- `JSONStringifyStream`
- `JSONValue` (type)
- `readMIMEHeader` method in `TextProtoReader` class
We discussed about these exceptions internally and decided to not allow these naming exceptions.
This PR replaces these ALL CAPS acronyms in API names with camelCased versions. (The old APIs are still aliased with `@deprecated` tags)
---
See also https://github.com/denoland/manual/pull/343
> BREAKING: replace ALL CAPS acronyms in public API names

- node/integrationtest/mysql2-example.js
- node/integrationtest/test.ts
This PR removes the usage of `--comapt` flag in `node/integrationtest`.
I updated `express` and `mysql2` module test to make those use `npm:` schema.
I removed `npm` and `yarn` cli tests as these tests can't be translated into `npm:` format easily, and also because we have our own dependency resolver in CLI, so the priority of running those tools should be very low now.
> chore(node): remove the usage of --compat in node/integrationtest

- flags/mod.ts
We made the handling of `--no-foo` type arguments optional in #2301.
`"--no-qux"` isn't equal to `"--qux=false"` by default anymore. This PR fixes the example of parse API doc following that change.
> docs(flags): fix parse doc example

- node/_readline.mjs
- node/readline_test.ts
`readline.Interface` constructor currently has a reference to global `process` object, but it doesn't work without `--compat` mode. This PR fixes it.
(Note: `deno run --unstable -A npm:prisma db pull` seems now blocked by this error)
> fix(node/readline): fix Interface constructor

- node/_process/streams.mjs
This PR fixes `BadResource` error while executing `DEBUG=* PRISMA_CLI_QUERY_ENGINE_TYPE=binary deno run --unstable -A npm:prisma db pull` command. (The root cause is https://github.com/denoland/deno/issues/15708 )
This PR stores `Deno.isatty?.(Deno.stdin.rid)` value at the start of program, instead of evaluating it each time. This works around the issue above.
> fix(node/process): fix BadResource issue of stdin.isTTY

- node/_process/process.ts
Uncovered this while attempting to run [wrangler](https://www.npmjs.com/package/wrangler) via
```console
$ deno run --unstable -A npm:wrangler
Wrangler requires at least node.js v16.13.0. You are using v16.11.1. Please update your version of node.js.
Consider using a Node.js version manager such as https://volta.sh/ or https://github.com/nvm-sh/nvm.
```
New versions derived from:
```console
$ docker run -it --rm node:16.17 --eval "console.log(process.versions)"
{
node: '16.17.0',
v8: '9.4.146.26-node.22',
uv: '1.43.0',
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.18.1',
modules: '93',
nghttp2: '1.47.0',
napi: '8',
llhttp: '6.0.7',
openssl: '1.1.1q+quic',
cldr: '41.0',
icu: '71.1',
tz: '2022a',
unicode: '14.0',
ngtcp2: '0.1.0-DEV',
nghttp3: '0.1.0-DEV'
}
```
> fix(node): bump node version to latest stable

- node/_process/streams.mjs
This reverts commit 336da79918798704e2b4dff4616de5d117cf4d63.
The root issue (https://github.com/denoland/deno/issues/15708) has been resolved by https://github.com/denoland/deno/pull/15747
> fix(node/process): revert workaround for stdin.isTTY (#2590)

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
This PR disables the `deploy-compat` check for PRs. `denoland/deployctl` only works for origin branches. The check currently doesn't work for PRs from forks.
> ci: check deploy-compat only with main

- test_import_map.json
[This line](https://github.com/denoland/deno_std/blob/d3b14b2aa06db78dd642ba816a6388e88d5008e2/test_import_map.json#L4) doesn't seem right. This PR removes it.
> remove: outdated std import

- .github/workflows/ci.yml
- README.md
If this test is still desired, we can work towards bringing it back. Otherwise, reasons for removing:
1. There aren't many markdown files in `std/node` anyway.
2. The step uses a `strict-ts44.tsconfig.json` config file, which doesn't exist.
3. The comment hasn't been actioned since late 2021 (#1590).
https://github.com/denoland/deno_std/blob/d3b14b2aa06db78dd642ba816a6388e88d5008e2/.github/workflows/ci.yml#L100-L102
> remove: `Doctest /node` step in CI

- node/tty_test.ts
`isatty(-1)` returns true when the test is run from the terminal (because of issue https://github.com/denoland/deno/issues/14398, `Deno.isatty(-1)` is currently equivalent of `Deno.isatty(0)`). This assertion blocks our release process, and this PR fixes it.
> chore(node/tty): temporarily disable invalid input tests

- node/process.ts
- node/process_test.ts
fixes #2640 
We currently only define getter of `execPath` in process, but pnpm writes to `process.execPath` for some reason and is broken there (https://github.com/pnpm/pnpm/blob/67d8b65d2e8da1df3725034b8c5b1fcf3af4ad81/packages/config/src/index.ts#L175). This PR makes it writable and fixes the issue for pnpm.
> fix(node/process): make execPath writable

- node/_process/process.ts
- node/process_test.ts
This PR reduces the required env permission range for `x in process.env` and `process.env.hasOwnProperty(x)`.
> fix(node/process): reduce required env permission range

- http/file_server.ts
- http/file_server_test.ts
This supercedes #2504
This PR makes `serveFile` return 404 response when the requested path is a directory.
Currently `serveFile` returns 200 response for directory paths and the response object throws when its body is read. This PR fixes this confusing behavior.
BTW if file_server is used as CLI tools, the path is checked if it's directory or not before passed to `serveFile`. So this change only affects users who use `serveFile` API directly.
> fix(http/file_server): serveFile returns 404 when the path is directory

- _tools/check_deprecation.ts
- deno.json
- replace jsdoc regex with [deno_doc](https://github.com/denoland/deno_doc) for more consistency.
> feat(tools/check_deprecation): use deno_doc for jsdoc parsing

- node/_fs/_fs_read.ts
- node/_fs/_fs_read_test.ts
The behavior of `position` option in `fs.read` and `fs.readSync` is different between Deno and Node.
This PR fixes the behavior of Deno to be the same as Node's.
If `position` is an integer, 
- Specifies the number of bytes to start reading counting from the ***beginning*** of the file
- The file position will be ***unchanged***
Ref: https://nodejs.org/api/fs.html#fsreadfd-buffer-offset-length-position-callback
If `position` is an integer, 
- Specifies the number of bytes to start reading counting from the ***current position*** of the file
- The file position will be ***updated***
```mjs
// import for Node
import fs from 'fs';
import { Buffer } from 'node:buffer';
// or
// import for Deno
import fs from "https://deno.land/std@0.156.0/node/fs.ts";
import { Buffer } from …
```
> fix(node/fs): position option of fs.read and fs.readSync works the same as Node

- _util/os.ts
- node/internal_binding/uv.ts
- node/os.ts
This adds enough support for node compat to run on FreeBSD (which [has Deno packaged](https://www.freshports.org/www/deno), despite not being an official platform).
> node: add FreeBSD support

- node/_process/process.ts
- node/process_test.ts
Currently `process.env` throws a TypeError when the env name has invalid chars or it's an empty string (because Deno.env.get throws with those inputs).
This PR prevents those behaviors and instead makes it return `undefined` with those invalid inputs.
closes #2665
> fix(node/process): does not throw with invalid env var names

- node/_tools/test/parallel/test-child-process-spawnsync-env.js
This commit updates test-child-process-spawnsync-env.js to match the test from Node.js with two exceptions noted in a TODO comment. These TODOs should be addressable once Deno <--> Node CLI argument mapping is implemented and there is a way to start Deno with require() available.
Refs: https://github.com/denoland/deno_std/issues/2674
> chore(node): update test to be more like node

- node/internal/child_process.ts
The command variable moved here was being defined unconditionally even though it is only used when the shell option is used. This commit moves the variable to be defined conditionally.
> chore(node): don't build command unless necessary

- node/internal_binding/handle_wrap.ts
- node/net.ts
- node/net_test.ts
When `net.connect` fails with an immediate error, `error` event happens before `close` event in node.js, but in `std/node` the events happen in the opposite order. This PR fixes it.
closes #2666
ref https://github.com/denoland/deno/issues/15824
> fix(node/net): fix socket events order

- collections/deep_merge.ts
- collections/deep_merge_test.ts
> fix(collections): deepMerge ignoring 'replace' options for nested properties

- node/_tools/config.json
This PR temporarily disables `test-dns.js` and `test-dns-resolveany.js` on windows as they fail too often on CI recently.
closes #2682
> chore(node): temporarily disable dns-related node comapt tests on windows

- node/process.ts
- node/process_test.ts
1. Is this the best way to conditionally define a method of a class? These methods don't exist on Windows platforms in Node.
2. How can `// @ts-ignore` be avoided in the tests?
3. [`test-process-uid-gid.js`](https://github.com/nodejs/node/blob/main/test/parallel/test-process-uid-gid.js) wasn't added because `process.setuid()`, `process.seteuid()`, `process.setgid()` and `process.setegid()` aren't and cannot currently be implemented, meaning the majority of that test would fail.
> feat(node/process): `process.getuid()` and `process.getgid()`

- deno.json
`lint:deprecations` was previously incorrectly `lint:depreactions` within the `lint` task.
> fix: `lint:deprecations` typo within `lint` task

- examples/catj.ts
- examples/gist.ts
- testing/chai_example.ts
- testing/fast_check_example.ts
- testing/sinon_example.ts
These pages were erroring out on loading due to the use of "ignored" language.
Lowlight was failing due to the use of "ignored" as language name, which is unsupported.
> fix: testing example pages failing to load

- node/_tools/setup.ts
Running `deno task node:setup` fails because `Buffer.from` was not a function. `Buffer` import was coming from the non-Node part of this library.
> fix(node): revert using `Buffer.from` in setup

- node/_process/process.ts
- node/process_test.ts
Should return `true` for success. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value
> fix(node/process): do not error assigning `false` to `process.env[VAR_NAME]`

- node/_process/streams.mjs
I'm unsure if the old line should be kept to ensure compatibility with Deno < 1.26
> fix(node/process): Deno 1.26 replaced Deno.setRaw with Deno.stdin.setRaw

- http/file_server.ts
- http/file_server_test.ts
- http/testdata/file#2.txt
Current implementation don't escape some reserved characters, which causing the browser to consider certain part is not the file path.
> fix(http/file_server): handles path with reserved char

- _tools/check_circular_deps.ts
- _tools/check_deprecation.ts
Also specifies a version for `deno_doc` in the deprecation check so avoid any compatibility issues in the future.
> chore: upgrade to `deno_graph@0.34.0` for circular dependency check

- node/_tools/test/parallel/test-webcrypto-sign-verify.js
Deno supports Ed25519 now, so update the WebCrypto test to include it.
Blocked on https://github.com/denoland/deno/pull/16099
> test(node): enable more webcrypto testing

- _tools/check_deprecation.ts
- fs/README.md
- fs/exists.ts
- log/handlers.ts
`exists` was deprecated because it causes a race condition when used before a file operation. However, it still has some legitimate uses cases, [even within `std`](https://github.com/denoland/deno_std/blob/1c2a47fe0fa1968e5a55fa340c910d525c2b657c/log/handlers.ts#L199-L204). The community has expressed more arguments here:
* #2594
* #2102
This PR:
1. Reverts the deprecation of `exists` and `existsSync`.
2. Advises against using `exists` before a file operation and clearly explains the reasoning.
3. Closes #2125.
4. Cleans up an illegitimate use of `exists` within the codebase.
5. Adds `URL` support for the argument.
A few legitimate use cases were also likely removed in #2546, as `Deno.lstat` is still used to check for the existence of files. It'd be a good idea to revisit these removals …
> chore(fs): document the deprecation of `exists` and `existsSync`

- http/file_server.ts
- http/file_server_test.ts
- http/testdata/subdir-with-index/index.html
This PR adds option to `serveDir` which controls whether it serves `index.html` as index of dir or not. Default is true.
closes #2709
> feat(http/file_server): add `showIndex` option to serveDir

- streams/conversion.ts
- streams/conversion_test.ts
`iterateReader` and `iterateReaderSync` use shared underlying buffer for its outputs. This causes the issue when the consumer of iterable is slow at handling these bytes. (Especially when used in `fetch` body, the request body can be corrupted in real world use cases. See https://github.com/denoland/deno/issues/14437 for details.)
closes https://github.com/denoland/deno/issues/14437
> fix(streams): don't use shared buffer for iterateReader outputs

- node/crypto_test.ts
- node/internal/crypto/hash.ts
This is supported in Node:
> - `'base64url'`: [base64url](https://tools.ietf.org/html/rfc4648#section-5) encoding as specified in [RFC 4648, Section 5](https://tools.ietf.org/html/rfc4648#section-5).
https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#buffers-and-character-encodings
> feat(node/crypto): add base64url encoding to hash.digest()

- node/child_process_test.ts
- node/internal/child_process.ts
Deno.spawnSync() returns getters for stdout and stderr which throw when 'inherit' is used. This commit updates Node's spawnSync() to handle this case.
Fixes: https://github.com/denoland/deno_std/issues/2742
> fix(node): handle inherited output in spawnSync()

- http/file_server.ts
- http/file_server_test.ts
The most of normalizeURL validations/path processing now seem useless because the basic validations are already done in CLI layer. This PR updates and simplifies it.
> refactor(http/file_server): simplify normalizeURL util

- collections/partition.ts
This allows for more accurate type inference when type guards are provided, like `Array.filter`.
```ts
declare const target: (string | number)[].
partition(target, (value: unknown): value is string => typeof value === "string") // [ string[], number[]]
```
Backward compatibility should not be a problem.
> feat(collections): improve types of `partition` module

- streams/conversion.ts
Amending https://github.com/denoland/deno_std/pull/2735
I read the awesome blog entry[^blog] by @kt3k, which describes how he found the difficult bug, and I recognized that his patch could be slightly better in memory allocation.
This PR uses `Uint8Array.prototype.slice()`, which returns a new Uint8Array with a new underlying ArrayBuffer.
Consider `bufSize: 1024 * 1024 * 1024 /* 1MiB */`. In the current code, `new Uint8Array(bufSize)` allocates 1MiB buffer, and initializes it with zero for each loop block. Instead, with this patch, a large buffer will be allocated before the loop, and `.slice` creates a Uint8Array with an underlying ArrayBuffer that allocates only the required size. It might not be a problem when `bufSize` is small but could consume unnecessary memory when `bufSize` is …
> chore(streams): memory optimizations by avoiding large buffer allocation in a loop

- .github/CODEOWNERS
- examples/chat/server_test.ts
- textproto/mod.ts
This PR deprecates `std/textproto` in 0.159.0 for removal in 0.160.0 and closes #2609.
Concerns:
1. Is the recommended alternative in the deprecation description valid?
2. Is the deprecation timeframe reasonable?
> chore: deprecate `std/textproto`

- node/_tls_wrap.ts
- node/tls_test.ts
This PR improves the compatibility of TLSSocket.
An npm module `http2-wrapper` (which has 5M weekly downloads) has the following line to extract `JSStreamSocket` from the internal property of TLSSocket.
```js
const JSStreamSocket = (new tls.TLSSocket(new stream.PassThrough()))._handle._parentWrap.constructor;
```
This PR still doesn't fully support this hack (because we don't have `JSStreamSocket` implementation at all), but at least this enables the above line passing (and as a result `deno run -A --unstable npm:web-ext --version` works with this fix and #2749 )
> fix(node/tls): set tlssocket._handle._parentWrap

- crypto/mod.ts
Being able to use these types would be great in some cases when working with `std/crypto`.
> feat(crypto): export algorithm types

- async/debounce.ts
- async/deferred.ts
- async/tee.ts
- bytes/mod.ts
- datetime/mod.ts
- encoding/varint/mod.ts
- flags/mod.ts
- fmt/colors.ts
- fs/expand_glob.ts
- fs/walk.ts
- io/files.ts
- io/types.d.ts
- node/module.ts
- node/path/posix.ts
- node/path/win32.ts
- path/posix.ts
- path/win32.ts
- permissions/mod.ts
- signal/README.md
- signal/mod.ts
- streams/buffer.ts
- streams/conversion.ts
- streams/delimiter.ts
- testing/asserts.ts
- testing/snapshot.ts
- uuid/mod.ts
- uuid/v4.ts
- uuid/v5.ts
Some documentation uses relative paths in import statements. It's nice to have this as an absolute path so people can copy and paste.
example: https://deno.land/std@0.159.0/streams/mod.ts?s=readAll
> docs: Using absolute paths in jsdoc import statements

- _util/download_file.ts
- archive/tar.ts
- http/file_server_test.ts
- io/buffer_test.ts
- log/handlers.ts
- node/_tools/setup.ts
- streams/conversion.ts
I think Deno CLI is trying to move away from using rid based filesystem functions. (https://github.com/denoland/deno/issues/12107, https://github.com/denoland/deno/issues/15796#issue-1364389627, https://github.com/denoland/deno/pull/15933#issuecomment-1250044922)
This PR removes the use of rid based functions from the standard library and replaces them with:
- `Deno.read(file.rid, buf)` -> `file.read(buf)`
- `Deno.write(file.rid, buf)` -> `file.write(buf)`
- `Deno.close(file.rid)` -> `file.close()`
(However, I didn't change `node` and `wasi` because they still seem to need rid-based functions.)
This is just a source code cleanup and does not change existing behavior.
> chore: Avoid using rid-based filesystem functions

- examples/cat.ts
- examples/curl.ts
- examples/xeval.ts
- examples/xeval_test.ts
towards https://github.com/denoland/deno_std/issues/1986
Switch the Deno stream used in the `example/` directory to a web stream.
And resolve the todo comment below.
> // TODO(ry) Re-enable streaming in this example.
// Originally we did: await Deno.copy(res.body, Deno.stdout);
// But maybe more JS-y would be: res.pipeTo(Deno.stdout);
> chore(examples): Converting Deno Streams to Web Streams

- node/child_process_test.ts
- node/internal/child_process.ts
This PR mocks `ChildProcess.prototype.disconnect` method.
Resolves https://github.com/denoland/deno/issues/16256
> fix(node/child_process): mock childProcess.disconnect method

- node/_tools/config.json
- node/child_process_test.ts
- node/internal/child_process.ts
depends on denoland/deno#16319
This PR adds support of `windowsVerbatimArguments` option in child_process APIs.
> fix(node/child_process): add support of windowsVerbatimArguments option

- node/_utils.ts
This PR modifies the warning message for unimplemented APIs, and makes it clear that the message is warning, not an error.
> chore: modify warning message for unimplemented APIs

- _tools/check_deprecation.ts
- _tools/check_licence.ts
- deno.json
This PR adds directories found in `.gitignore` to those lists of directories that should be ignored when performing:
1. License check
2. Deprecation check
3. Linting
4. Formatting
Note: `/hash/_wasm/target` in checks were ignored because it's looking as though `std/hash` will soon be removed anyway.
> chore: correct ignored files for checks, linting and formatting

- .gitignore
- fs/expand_glob.ts
- fs/expand_glob_test.ts
This is in relation to #2571. When passing globstar false, and passing the glob segment `**`, globstar false isn't being respected.
> fix(fs/expandGlob): globstar false does not take effect (#2571)

- node/net.ts
- node/net_test.ts
This PR delays the timing of 'close' event when `.close()` is called on net.Server. With the current implementation, 'close' event is emitted a bit too early and the port is not available yet. That causes the module `get-port` failing to return 'available' port. This PR uses `setTimeout` instead of `nextTick` for calling `_emitCloseNT` and the timing is delayed, and that makes `get-port` working.
closes #2788
related https://github.com/denoland/deno/issues/16282
> fix(node/net): modify close event timing

- .github/workflows/ci.yml
Used `GITHUB_OUTPUT` instead of `set-output` to manage output for each step of GitHub Actions
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Using `set-output` in GitHub Actions will result in a warning message and future deprecation.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> Fix(GitHub Actions)： use `GITHUB_OUTPUT` instead of deprecated `set-output` 

- uuid/_common.ts
This PR removes the internal utilities `stringToBytes` and `createBuffer`, which aren't used in the codebase.
> chore(uuid): cleanup unused internal functions

- http/file_server.ts
This PR removes the transform stream for a partial content response and instead just calls `file.seek()`.
> chore(http/file_server): remove transform stream for partial content response

- node/_fs/_fs_opendir.ts
- node/_tools/test/parallel/test-fs-opendir.js
> fix(node/fs): enable to check error thrown on invalid values of bufferSize

- http/file_server.ts
- http/file_server_test.ts
This PR removes duplicated hashing functionality in the file server and its testing code and instead uses code from `std/crypto`.
> refactor(http): use hashing functions from `std/crypto`

- streams/conversion.ts
This PR removes the note in the docs of `iterateReader`, which is no longer meaningful.
ref: https://github.com/denoland/deno_std/pull/2735
> docs(streams): remove obsolete note

- node/assertion_error.ts
I didn't save one of the files 🤦
> chore: add ts-ignores for Deno.consoleSize() API

- node/_fs/_fs_access.ts
- node/process.ts
- node/process_test.ts
These are being renamed to `Deno.uid()` and `Deno.gid()` in core.
Depends on https://github.com/denoland/deno/pull/16432
> chore: use renamed Deno.getUid() and Deno.getGid()

- node/_fs/_fs_access.ts
- node/process.ts
- node/process_test.ts
The API rename has been completed in the CLI repo.
> chore: drop Deno.getGid() and Deno.getUid()

- dotenv/mod.ts
- dotenv/mod_test.ts
- dotenv/testdata/.env.test
Empty strings in .env files crashed the parsing of them. Looks like it was just a falsey value that was not tested for.
Simple reproc (.env):
```
A=""
```
Related: #2798
> fix(dotenv): Empty string crashing parsing

- node/_fs/_fs_common.ts
- node/_fs/_fs_open.ts
- node/_fs/_fs_open_test.ts
Add support for [numeric flags](https://nodejs.org/api/fs.html#file-system-flags) for `fs.open()` and `fs.openSync()` and make argument handling a bit more aligned with [Node's implementation](https://github.com/nodejs/node/blob/main/lib/fs.js#L551).
Closes #2796: `npm:tmp` is failing because [it's using](https://github.com/raszi/node-tmp/blob/master/lib/tmp.js#L30) numeric flags for file opening which is not yet supported by our polyfill.
> feat(node/fs): add support for numeric flags in `fs.open()`

- flags/mod.ts
I noticed a broken link in the flags docs 🙂
> docs(flags): fix broken link to minimist
