- deno.json
> chore: update permissions for `lint:circular` task

- path/parse_test.ts
part of #3713 #4600
This improves the test coverage of `windows.parse()` function.
> test(path): improve `windows.parse()` test

- path/mod.ts
This change removes the `posix` and `win32` exports from the `@std/path` root module.
This change was made to keep the root module of `@std/path` reserved for importing APIs that automatically detect and work on the OS of the current machine. OS-specific APIs can be imported instead from `@std/path/posix/*` or `@std/path/windows/*`. This helps keep dependencies lean.
To migrate, import from `@std/path/posix/*` instead of `path.posix` for POSIX systems or `@std/path/windows/*` instead of `path.windows` for Windows systems.
For POSIX systems:
```diff
- import { posix } from "@std/path";
+ import { basename } from "@std/path/posix";
- posix.basename("/home/user/Documents/");
+ basename("/home/user/Documents/");
```
For Windows systems:
```diff
- import { windows } from "@std/path";
+ import …
```
> BREAKING(path): remove `path.posix` and `path.win32`

- path/windows/join.ts
I missed reverting this in #4946.
> chore(path): use `assertPath()` in `windows.join()`

- _tools/check_docs.ts
- url/basename.ts
- url/dirname.ts
- url/extname.ts
- url/join.ts
- url/mod.ts
- url/normalize.ts
> docs(url): complete documentation

- _tools/check_docs.ts
- ini/ini_map.ts
- ini/mod.ts
- ini/parse.ts
- ini/stringify.ts
> docs(ini): improve ini docs

- msgpack/decode_test.ts
part of #3713
This improves the test coverage of `decode` function of `@std/msgpack`
> test(msgpack): add `decode()` test cases

- msgpack/encode_test.ts
part of #3713
This improves the test coverage of `encode` of `@std/msgpack`.
> test(msgpack): add test cases for `encode()`

- _tools/check_docs.ts
- msgpack/decode.ts
- msgpack/encode.ts
- msgpack/mod.ts
> docs(msgpack): complete documentation

- async/debounce.ts
This reverts https://github.com/denoland/deno_std/pull/4283
By using `Array.fromAsync`, the call result of the debounced function is stored in memory i.e. it's leaked unnecessarily. We can avoid it by not using `Array.fromAsync`.
> docs(async): avoid memory leak in example

- async/tee.ts
towards #5001 
This PR marks `Tuple` and `TupleOf` types as @internal (We would remove them if TypeScript natively support something similar).
These 2 types are too general to be exported as part of `@std/async`. We shouldn't consider these as public APIs.
> chore(async): mark `Tuple` and `TupleOf` as `@internal`

- async/pool.ts
- async/pool_test.ts
part of #5001
We usually don't export error message string as string constant value. Also exporting this doesn't look useful. I suggest we should remove this export.
> BREAKING(async): stop exporting ERROR_WHILE_MAPPING_MESSAGE

- http/cookie.ts
- http/cookie_test.ts
> feat(http): support partitioned cookies

- streams/_test_common.ts
This PR removes a test util in `@std/streams` which is not used from anywhere.
> chore(streams): remove unused test util

- cli/parse_args.ts
- cli/parse_args_test.ts
This PR adds test cases of `parseArgs`. This also removes a dead line.
The test coverage of `parse_args.ts` improves from `97.65%` to `98.99%`
part of #3713
> test(cli): improve test coverage

- cli/spinner_test.ts
part of #3713 
This improves the line coverage of `cli/spinner.ts` from 62.79% to 95.35%
> test(cli): improve spinner test coverage

- ulid/_util.ts
- ulid/mod.ts
- ulid/test.ts
There's no reason why this value shouldn't be hardcoded. Also, includes a small cleanup of the functions.
> refactor(ulid): remove `len` argument from `encodeTime()` and `encodeRandom()`

- testing/_test_utils.ts
- testing/bdd.ts
- testing/snapshot.ts
As we don't use the access modifiers in the Standard Library.
> refactor(testing): remove use of `public` keyword

- _tools/check_circular_package_dependencies.ts
This functionality is no longer used and won't be needed after https://github.com/jsr-io/jsr/pull/528 is merged.
> chore: remove `--table` functionality from graph checker

- cli/spinner.ts
> chore(cli): make spinner unstable/experimental

- testing/time.ts
See https://github.com/denoland/deno_std/pull/5033#discussion_r1641593658
> refactor(testing): remove `FakeTime.start` setter

- streams/delimiter_stream.ts
- streams/delimiter_stream_test.ts
This PR improves the test suite of `DelimiterStream`. Now the test cases cover the lines except 'unreachable' lines.
part of #3713
> test(streams): improve `DelimiterStream` test cases

- json/_common.ts
- json/concatenated_json_parse_stream_test.ts
This PR improves the test cases of `json`. With this change, this change makes the line coverage of `std/json` 100%.
part of #3713
> test(json): improve json testing

- fs/_is_subdir.ts
- fs/_is_subdir_test.ts
> refactor(fs): resolve directories when checking whether they are the same in `isSubdir()`

- async/abortable.ts
`abortablePromise()` and `abortableAsyncIterable()` have been made private functions (no longer exported) in favor of [`abortable()`](https://jsr.io/@std/async/doc/~/abortable).
Under the hood, `abortable()` uses `abortablePromise()` if the first argument, `p`, is a promise, or `abortableAsyncIterable()` if `p` is an async iterable. This change was made to avoid confusion for users regarding which function to use; now, use `abortable()`.
To migrate, use `abortable()` instead of `abortablePromise()` or `abortableAsyncIterable()` in the same way.
For promises:
```diff
- import { abortablePromise } from "@std/async/abortable";
+ import { abortable } from "@std/async/abortable";
const request = fetch("https://example.com");
const c = new AbortController();
setTimeout(() => c.abort(), 100);
- …
```
> BREAKING(async): make `abortablePromise()` and `abortableAsyncIterable()` private

- fs/ensure_dir_test.ts
This PR adds a check for #3233
> test(fs): check `ensureDir()` is not racy

- fs/ensure_symlink.ts
- fs/ensure_symlink_test.ts
part of #3713
This improves the line coverage of ensureSymlink test.
> test(fs): improve `ensureSymlink()` test

- streams/early_zip_readable_streams.ts
- streams/early_zip_readable_streams_test.ts
Jumping from: https://github.com/denoland/deno_std/pull/5078#discussion_r1645446809
This pull request changes the structure of the readable stream to use a pull method instead of the start method, stopping it from the possibility of using excessive memory, possibly overflowing it if not consumed fast enough, or at all. This alternative also offers a way to cancel the provided reason streams from the returned stream.
This refactor did turn out to be slightly slower than the existing one in a benchmark.
> fix(streams): prevent `earlyZipReadableStreams()` from possibly using excessive memory

- fs/expand_glob.ts
- fs/expand_glob_test.ts
This PR improves the line coverage of `fs/expand_glob.ts`.
part of #3713
> refactor(fs): improve `expandGlob()` implementation and testing

- jsonc/parse.ts
- jsonc/parse_test.ts
This improves the test coverage of `jsonc` from 85.26% to 97.42% (missed lines are reduced from  46 to 8)
part of #3713
> test(jsonc): remove dead code and improve testing

- archive/tar.ts
- expect/_custom_equality_tester_test.ts
- expect/_extend_test.ts
- expect/_to_equal_test.ts
- expect/expect.ts
- io/_test_common.ts
- io/buf_reader.ts
- io/buf_reader_test.ts
- io/limited_reader.ts
- io/string_writer.ts
- log/_test_handler.ts
- log/logger_test.ts
- toml/_parser.ts
- yaml/_dumper/dumper_state.ts
- yaml/_error.ts
- yaml/_loader/loader_state.ts
- yaml/_mark.ts
- yaml/_state.ts
- yaml/schema.ts
- yaml/type.ts
Closes #5066
Fixes:
Removed public keyword
Added separate declaration and constructor assignment
Replaced private key with # keyword
> refactor(archive,expect,io,log,toml,yaml): remove `private` and `public` access modifiers

- json/_test_common.ts
- json/common.ts
- json/concatenated_json_parse_stream.ts
- json/concatenated_json_parse_stream_test.ts
- json/json_parse_stream.ts
- json/json_parse_stream_test.ts
- json/json_stringify_stream.ts
The `writableStrategy` and `readableStrategy` options have been removed from the constructors from `ConcatenatedJsonParseStream`, `JsonParseStream` and `JsonStringifyStream`.
These options were removed because they aren't used in most use cases. For this reason, none of the other `TransformStream` implementations in the Standard Library have these options.
Only those who use these options.
If you require the use of these options, please implement a custom class that uses them.
```
class CustomJsonStringifyStream extends TransformStream<unknown, string> {
constructor(
writableStrategy: QueuingStrategy<unknown>,
readableStrategy: QueuingStrategy<string>,
) {
super(
{
transform(chunk, controller) {
controller.enqueue(JSON.stringify(chunk));
},
},
writableStrategy,
readableStrategy,
);
}
} …
```
> BREAKING(json): remove `writableStrategy` and `readableStrategy` options

- _tools/check_docs.ts
- dotenv/mod.ts
- dotenv/parse.ts
- dotenv/stringify.ts
This PR improves `dotenv` docs.
Some examples need the setup of actual `.env` files. Such examples are tagged as `no-eval`
part of #3764
> docs(dotenv): improve `dotenv` docs

- media_types/content_type.ts
This PR removes a historical note in `contentType` docs, which now seems just confusing to the users.
> docs(media-types): remove outdated historical note

- media_types/all_extensions.ts
- media_types/all_extensions_test.ts
- media_types/deno.json
- media_types/extension.ts
- media_types/mod.ts
This PR renames `extensionsByType` to `allExtensions` to align the naming convention to `extension` which takes the same arguments.
`extensionsByType` has been renamed to `allExtensions`
`extension` and `extensionsByType` take the same arguments (the content type), but named in an inconsistent way. This change align the naming of the latter to the former.
```diff
-import { extensionsByType } from "@std/media-types";
+import { allExtensions } from "@std/media-types";
```
> BREAKING(media-types): rename `extensionsByType` to `allExtensions`

- http/mod.ts
> docs(http): remove outdated mention of `CookieMap`

- http/file_server.ts
- http/mod.ts
Currently we use `4507` as the default port number of http/file-server. This PR changes it to use the same default port as `Deno.serve` as suggested in https://github.com/denoland/deno_std/issues/4853#issuecomment-2132251185
closes #4853
> BREAKING(http): change the default port of file-server to the same default of `Deno.serve()`

- cli/spinner_test.ts
- cli/testdata/spinner_cases/stop.ts
> test(cli): improve `Spinner` test

- testing/time.ts
- testing/time_test.ts
`Date()` (call without `new`) isn't faked correctly with the current implementation. This PR fixes it.
> fix(testing): function call of `Date` constructor is not correctly faked

- yaml/parse.ts
- yaml/parse_test.ts
- yaml/schema/mod.ts
- yaml/stringify.ts
- yaml/stringify_test.ts
This PR adds handling of string input for `schema` option for `parse` and `stringify`. This prepares for #5117
(Note: I plan to remove Schema class input for `schema` option at 1.0.0, which prevents exposing internal details of schema implementation as public APIs.)
This PR also removes the references to private types `DumperStateOptions` `LoaderStateOptions` from public types. This prepares for #3764
> feat(yaml): support schema name for 'schema' option

- testing/time.ts
- testing/time_test.ts
Alternative to #5125. This PR disables multiple FakeTime creations.
context: https://github.com/denoland/deno_std/pull/5125#issuecomment-2187684400
> BREAKING(testing): disable multiple `FakeTime` creations

- http/cookie.ts
- http/cookie_test.ts
[`getCookies()`](https://jsr.io/@std/http/doc/cookie/~/getCookies) or [`setCookie()`](https://jsr.io/@std/http/doc/cookie/~/setCookie) now throw [`SyntaxError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError)s if they encounter invalid characters for their respective implementations. Previously, they threw a mix of [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)s and [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)s.
This change was made because `SyntaxError` is typically used in JavaScript to represent the encountering of invalid characters.
When error-handling either of these functions, compare against `SyntaxError`, rather than `Error` …
> BREAKING(http): improve thrown errors in `cookie` module

- _tools/check_docs.ts
- yaml/parse.ts
- yaml/schema/mod.ts
- yaml/stringify.ts
part of #3764 
This PR documents `parse` and `stringify` of `yaml` package. I skipped documenting other items (such as `Schema`, `Type`, etc) as they are planned to be excluded from public APIs #5117
> docs(yaml): improve `yaml` document

- http/user_agent.ts
- http/user_agent_test.ts
This PR removes some dead code and improves typings in `http/user_agent.ts`, and also adds test cases which exercise uncovered lines.
towards #3713
> refactor(http): remove dead code and improve `UserAgent` testing

- testing/mock.ts
- testing/mock_test.ts
This PR improves testing of `testing/mock.ts`, and also removes some dead code in it.
part of #3713
> refactor(testing): remove dead code and improve test of `testing/mock.ts`

- http/signed_cookie.ts
- http/signed_cookie_test.ts
`verifyCookie()` has been renamed to `verifySignedCookie()`.
This change was made to make it clear to users that this function only deals with signed cookies.
Use `verifySignedCookie()` instead of `verifyCookie()`.
```diff
- import { verifyCookie } from "@std/http/signed-cookie";
+ import { verifySignedCookie } from "@std/http/signed-cookie";
// ...
- await verifyCookie(signedCookie, key);
+ await verifySignedCookie(signedCookie, key);
// ...
```
Closes #5134
> BREAKING(http): rename `verifyCookie()` to `verifySignedCookie()`

- testing/bdd_test.ts
This PR improves test coverage of `testing/bdd.ts`.
part of #3713
> test(testing): improve bdd testing

- http/server_sent_event_stream.ts
- http/server_sent_event_stream_test.ts
This PR changes the error thrown in [`ServerSentEventStream`](https://jsr.io/@std/http/doc/server-sent-event-stream/~/ServerSentEventStream) from [`RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError) to [`SyntaxError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) if the `comment`, `event` or `id` properties of the chunk contained a newline.
This change was made as `SyntaxError` is more appropriate for invalid characters, than `RangeError`.
To migrate, when error-handling, compare against `SyntaxError` instead of `RangeError`.
```diff
import { ServerSentEventStream } from "@std/http/server-sent-event-stream";
const stream = ReadableStream
.from<ServerSentEventMessage>([{ event: "a\nb" }]) …
```
> refactor(http): change error thrown in `ServerSentEventStream` to `SyntaxError`

- fs/copy.ts
> docs(fs): add not supported docs for `CopyOptions.preserveTimestamps`

- testing/README.md
- testing/types.ts
This should bring the JSR score to 100%.
> docs(testing): add module docs

- testing/mock.ts
- testing/mock_test.ts
Currently thrown error from constructor is not captured by `spy`. This PR enables spying thrown errors from constructor.
> fix(testing): correctly throw in constructor with `spy()`

- csv/stringify.ts
- csv/stringify_test.ts
This PR improves `stringify` test cases. part of #3713
> test(csv): improve stringify testing

- csv/parse.ts
- csv/parse_test.ts
part of #3713 
This improves the test coverage of `csv/parse.ts`.
> refactor(csv): remove dead code and improve tests

- csv/csv_stringify_stream_test.ts
This PR improves the test of CsvStringifyStream. part of #3713
> test(csv): improve `CsvStringifyStream` test

- csv/_io.ts
- csv/csv_parse_stream.ts
- csv/csv_parse_stream_test.ts
part of #3713 
This PR removes some dead code in CsvParseStream and improves the testing of it.
> refactor(csv): remove dead code and improve `CsvParseStream` test

- csv/_io.ts
- csv/csv_stringify_stream.ts
- csv/parse.ts
- csv/stringify.ts
Looks like #5158 broke some test cases which are recently added, and now main CI is red.
This reverts #5158 to fix it.
> chore: Revert "refactor(csv): minor cleanups (#5158)"

- csv/csv_parse_stream.ts
- csv/parse.ts
`ReadOptions` are options for a private function `parseRecord`. It doesn't make sense for this type to be exposed as a public API.
towards #5159
> BREAKING(csv): make `ReadOptions` private

- yaml/_loader/loader.ts
- yaml/parse.ts
- yaml/parse_test.ts
> BREAKING(yaml): remove `iterator` argument from `parseAll()`

- yaml/stringify.ts
`DumpOptions` is the options for `stringify`. This should be named `StringifyOptions`
`DumpOptions` has been renamed to `StringifyOptions`
The current name isn't aligned to the naming convention of the option types because it's options for `stringify`. There's no public API called `dump`.
```diff
-import type { DumpOptions } from "@std/yaml`;
+import type { StringifyOptions as DumpOptions } from "@std/yaml`;
```
> BREAKING(yaml): rename `DumpOptions` to `StringifyOptions`

- yaml/parse_test.ts
This PR adds test cases of `parse` function.
This exercises the case of various escape sequences, invalid strings, yaml directives.
This improves line coverage of yaml package from 60.49% to 65.01%.
part of #3713
> test(yaml): improve `parse()` testing

- yaml/_loader/loader.ts
- yaml/parse_test.ts
[merge type](https://yaml.org/type/merge) (`<<`) handling seems broken (ref #4457). This PR fixes it and add test cases to check it.
> fix(yaml): fix merge (<<) type handling in `parse()`

- yaml/_loader/loader.ts
- yaml/_loader/loader_state.ts
This PR makes `tagMap` and `anchorMap` properties non-nullable. These 2 properties are assigned with `Object.create(null)` nearly the beginning of their usages, but not initialized in the constructor. That causes them nullable types, and makes the logic unnecessarily complex. This PR removes those complexities.
> refactor(yaml): simplify map initializations

- semver/mod.ts
The `SEMVER_SPEC_VERSION` constant has been removed from `@std/semver`.
This constant was removed as it provided no further value to the package. The single source of truth for this value can be found in the [documentation](https://jsr.io/@std/semver).
If needed, see the [documentation](https://jsr.io/@std/semver) to get the currently supported SemVer spec version, and define the constant.
```diff
- import { SEMVER_SPEC_VERSION } from "@std/semver";
+ const SEMVER_SPEC_VERSION = "2.0.0";
foo(SEMVER_SPEC_VERSION);
```
> BREAKING(semver): remove `SEMVER_SPEC_VERSION`

- yaml/_loader/loader.ts
- yaml/parse_test.ts
This PR adds test of parsing block scalars.
part of #3713
> test(yaml): add test for block scalars

- yaml/parse_test.ts
This PR adds misc test cases to exercises the edge cases of `parse`. The line coverage of `readDocument` becomes 100% with this change.
part of #3713
> test(yaml): add misc `parse()` test cases

- yaml/parse_test.ts
This PR adds test cases of anchor and alias handling of `parse`.
part of #3713
> test(yaml): test anchor and alias handling of `parse()`

- archive/tar_test.ts
According to this line https://github.com/denoland/deno_std/blob/9c543c9f36deb6b96bfe389034783400407f04e8/archive/tar_test.ts#L74, the byte length should be 163.
> test(archive): fix typo in `tar_test.ts`

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
- testing/snapshot_test.ts
> fix(testing): Throw error eagerly when insufficient permissions are granted to write to snapshot file in update mode

- expect/_extend_test.ts
- expect/test.ts
This PR adds test cases of:
- `expect().resolves`
- `expect().rejects`
- Throwing cases of custom matchers.
This improves the code coverage of `expect` about 2%.
part of #3713
> test(expect): improve `expect` test cases

- expect/_to_equal_test.ts
This PR adds tests of `expect` which exercise `iterableEquality` internal utility.
part of #3713
> test(expect): add test of `iterableEquality`

- expect/_to_be_close_to_test.ts
- expect/_to_contain_equal_test.ts
- expect/_to_have_been_called_test.ts
- expect/_to_have_been_last_called_with_test.ts
- expect/_to_have_property_test.ts
This PR adds the test cases to exercise various edge cases of matchers.
part of #3713
> test(expect): test edge cases of matchers

- expect/_matchers.ts
- expect/_to_have_been_nth_called_with_test.ts
This PR fixes the validation of `nth` argument of `toHaveBeenNthCalledWith` matcher.
> fix(expect): fix validation of nth param in `toHaveBeenNthCalledWith` matcher

- deno.json
- uuid/deno.json
> chore: release `uuid@1.0.0`

- yaml/stringify_test.ts
part of #3713 
This PR adds the test cases of `stringify` when the output is hex encoded strings.
> test(yaml): test `stringify()` case when string encoded into hex sequences

- yaml/parse_test.ts
- yaml/stringify_test.ts
part of #3713 
This PR add test cases for checking `!!timestamp` tag handling.
> test(yaml): test `!!timestamp` type handling

- yaml/parse_test.ts
This PR adds test cases which check the handling of `?` character in yaml.
part of #3713
> test(yaml): add test cases of handling ? mark in YAML

- yaml/_loader/loader.ts
- yaml/_loader/loader_state.ts
- yaml/parse.ts
The `ParseOptions.legacy` option has been removed.
Setting this option to true allowed documents adhering to versions <1.2 of the YAML specification. v1.2 of the YAML spec was published in 2009 (15 years ago). It's fair to say that most, if not, all, YAML use these days adheres to >=v1.2 of the spec, making this option redundant.
This option only affected those who have the option set to `true` and are adhering to YAML spec version <1.2. If you require this feature, use [`@std/yaml@0.224.3`](https://jsr.io/@std/yaml@0.224.3), as this is the last version containing this feature. Otherwise, we recommend updating your document to use the latest version of the YAML spec.
> BREAKING(yaml): remove `ParseOptions.legacy` option

- expect/_utils.ts
This PR removes the special handlings of [immutable-js](https://www.npmjs.com/package/immutable) objects in iterable equality check in `std/expect`. None of std packages has special handling for specific 3rd party library support except this one. This kind of special logic doesn't seem aligned to the concept of the standard library. So I suggest we should remove these handlings before the stabilization.
towards #5014
> BREAKING(expect): remove special handling of Immutable.js objects

- yaml/parse_test.ts
> test(yaml): add `parse()` test for duplicate keys

- yaml/parse_test.ts
- yaml/stringify_test.ts
part of #3713 
This PR adds the test cases which check the handling of `!!binary` type.
> test(yaml): check handling of binary type

- yaml/_loader/loader.ts
- removes `DirectiveHandler` type and makes directiveHandlers standalone functions
> refactor(yaml): remove `DirectiveHandler` type

- yaml/_loader/loader.ts
- replaces optional options with default object
> refactor(yaml): add default options object

- yaml/_loader/loader.ts
- moves code into a dedicated `sanitizeInput()` function
> refactor(yaml): add `sanitizeInput()` function

- yaml/parse_test.ts
- yaml/stringify_test.ts
part of #3713
This PR adds test cases to check parsing and serialization of booleans.
> test(yaml): test handling of boolean values

- yaml/parse_test.ts
part of #3713
This PR adds tests of handling of various !!int values in the yaml parser.
> test(yaml): add test of parsing !!int types

- yaml/_type.ts
- yaml/stringify.ts
- yaml/stringify_test.ts
This PR fixes the handling of style variaions for `!!int` type.
> fix(yaml): fix `!!int` style variation handling in `stringfiy`

- assert/assert_test.ts
Mainly so `@std/assert` reaches 100% coverage.
> test(assert): add "`assert()` throws if expr is falsy" test

- crypto/timing_safe_equal_test.ts
Brings coverage `@std/crypto` to 100%.
Towards #3713
> test(crypto): test `timingSafeEqual()` in handling `DataView`s

- yaml/_dumper.ts
- yaml/_loader.ts
- yaml/parse.ts
- yaml/stringify.ts
- moves `_loader/loader.ts` to `_loader.ts`
- moves `_dumper/dumper.ts` to `_dumper.ts`
> refactor(yaml): move loader and dumper files

- bytes/equals_test.ts
- cli/_run_length.ts
- collections/permutations.ts
- expect/_utils.ts
Fixes errors on `main` (see [here](https://github.com/denoland/deno_std/actions/runs/9785146367/job/27017549354)).
> fix(bytes,cli,collections,expect): add missing non-null assertions

- fmt/printf_test.ts
part of #3713 
This improves the test coverage of `fmt/printf.ts` from 94.58% to 96.93% (reduces 16 uncovered lines)
> test(fmt): add test cases for `printf()`

- yaml/_loader.ts
- yaml/parse.ts
This argument previously did nothing.
Towards #5195
> refactor(yaml): remove first argument from `ParseOptions.onWarning`

- yaml/_loader.ts
- yaml/parse.ts
- yaml/parse_test.ts
[`ParseOptions.json`](https://jsr.io/@std/yaml@0.224.3/doc/parse/~/ParseOptions.json) has been renamed `ParseOptions.allowDuplicateKeys`. This change only affects those that previously set `ParseOptions.json` to `true`. No changes in behavior have been made.
This name more clearly describes how the option affects the behavior of [`parse()`](https://jsr.io/@std/yaml/doc/~/parse).
To migrate, use the `allowDuplicateKeys` option instead of the `json` option for `parse()`.
```diff
import { parse } from "@std/yaml/parse";
const yamlString = `name: John Doe
age: 30
name: Jane Doe`;
- parse(yamlString, { json: true });
+ parse(yamlString, { allowDuplicateKeys: true });
```
Towards #5195
> BREAKING(yaml): rename `ParseOptions.json` to `ParseOptions.allowDuplicateKeys`

- yaml/_dumper.ts
- yaml/stringify.ts
The `ParseOptions.noArrayIndent` option has been renamed to `ParseOptions.arrayIndent`. As a result, the polarity of the option has been swapped. In other words, `true` behavior has been changed to `false` behavior, and visa-versa. This only affects users who currently use `ParseOptions.noArrayIndent`.
This change makes the option far easier to understand by avoiding a negative-tensed name.
Use `ParseOptions.arrayIndent` instead of `ParseOptions.noArrayIndent` and swap the polarity of the option.
```diff
import { parse } from "@std/yaml/parse";
const yamlString = `fruits:
- Apple
- Banana
- Cherry`;
- parse(yamlString, { noArrayIndent: false });
+ parse(yamlString, { arrayIndent: true });
```
Towards #5124
> BREAKING(yaml): rename `ParseOptions.noArrayIndent` to `ParseOptions.arrayIndent`

- yaml/_dumper.ts
- yaml/stringify.ts
The `ParseOptions.noCompatMode` option has been renamed to `ParseOptions.compatMode`. As a result, the polarity of the option has been swapped. In other words, `true` behavior has been changed to `false` behavior, and visa-versa. This only affects users who currently use `ParseOptions.noCompatMode`.
This change makes the option far easier to understand by avoiding a negative-tensed name.
Use `ParseOptions.compatMode` instead of `ParseOptions.noCompatMode` and swap the polarity of the option.
```diff
import { parse } from "@std/yaml/parse";
const yamlString = `fruits:
- Apple
- Banana
- Cherry`;
- parse(yamlString, { noCompatMode: false });
+ parse(yamlString, { compatMode: true });
```
Towards #5124
> BREAKING(yaml): rename `StringifyOptions.noCompatMode` to `StringifyOptions.compatMode`

- fmt/printf.ts
- fmt/printf_test.ts
Currently `e` formatting with rounding has a bug in some edge cases. For example `sprintf("%.3e", 0.000099999)` becomes `1.000e--04` (which has double minus sign). This PR fixes it.
> fix(fmt): fix the case when mantissa exceeds 10 by rounding and exponent is negative

- yaml/_dumper.ts
- yaml/stringify_test.ts
`noRefs` option stopped working at 1.0.0-rc.1. This PR fixes it.
One of if-condition in `inspectNode` util was reversed here: https://github.com/denoland/deno_std/pull/5239/files#diff-d51202515e2d50a21e0e272ef2ce1cce07793bc5a2a01a7ea1f9e4b3ccb0c429R808
> fix(yaml): fix `StringifyOptions.noRefs`

- assert/match.ts
- assert/not_match.ts
This PR improves the example of `assertMatch` API. (`RegExp(/foo/)` works, but it looks confusing to me)
> docs(assert): update `assertMatch` example

- assert/not_strict_equals.ts
This PR improves the example of `assertNotStrictEquals` doc.
> docs(assert): improve `assertNotStrictEquals` example

- csv/_io.ts
- csv/parse.ts
- replaces `runeCount()` with length of strings
> refactor(csv): remove `runeCount()` function

- yaml/_loader.ts
- renames `throwWarning()` to  `dispatchWarning()` as the function does not throw an error
> refactor(yaml): rename `throwWarning()` to `dispatchWarning()`

- yaml/_dumper.ts
- yaml/_loader.ts
- yaml/_mark.ts
- yaml/_utils.ts
- replaces repeat helper function with built in `String.prototype.repeat()`
> refactor(yaml): remove repeat helper function

- csv/_io.ts
- csv/_shared.ts
- csv/parse.ts
- csv/parse_test.ts
- reverts https://github.com/denoland/deno_std/pull/5298#issuecomment-2208355438
- adds test
> test(csv): add grapheme length test

- assert/object_match.ts
This PR improves the docs of `assertObjectMatch`.
> docs(assert): improve `assertObjectMatch` docs

- yaml/_dumper.ts
- replaces `duplicatesIndexes` array with Set of objects
- reduces nesting and adds early returns
> refactor(yaml): cleanup `inspectNode()`

- expect/_types.ts
Makes it possible to use `resolves.not` without hinting error (else you need to use `not.resolves` to ditch out this warning but it feels more awkard)
> fix(expect): make `.not` aware of whether is it is in async context

- yaml/_dumper.ts
- yaml/_type.ts
- yaml/_type/int.ts
- yaml/stringify_test.ts
This PR removes the style aliases of `!!int` type in `stringify` API.
No users should be affected by this change.
closes #5272
> BREAKING(yaml): remove style aliases of `!!int` type

- path/_common/glob_to_reg_exp.ts
- path/glob_to_regexp.ts
- path/posix/glob_to_regexp.ts
- path/windows/glob_to_regexp.ts
The `GlobToRegExpOptions` interface has been replaced with `GlobOptions`, which is identical in behavior. This change only affects users who explicitly import `GlobToRegExpOptions`.
This change was made because `GlobToRegExpOptions` is identical to `GlobOptions`, and `GlobOptions` is already used in `normalizeGlob()`, `joinGlobs()`, and `expandGlob()` in `@std/fs`. This removal means a decrease in the API surface of `@std/path` without impeding functionality.
To migrate, use `GlobOptions` instead of `GlobToRegExpOptions`. This is only needed if you already explicitly import `GlobToRegExpOptions`.
```diff
- import type { GlobToRegExpOptions } from "@std/path/glob-to-regexp";
+ import type { GlobOptions } from "@std/path/glob-to-regexp";
- const options: GlobToRegExpOptions = {
+ const …
```
> BREAKING(path): remove `GlobToRegExpOptions`

- path/_common/format.ts
- path/deno.json
- path/format.ts
- path/mod.ts
- path/parse.ts
- path/parse_format_test.ts
- path/posix/format.ts
- path/posix/mod.ts
- path/posix/parse.ts
- path/types.ts
- path/windows/format.ts
- path/windows/mod.ts
- path/windows/parse.ts
`FormatInputPathObject` has been removed in favor of `Partial<ParsedPath>`, which is identical in behavior. This also introduces `@std/path/types`, where `ParsedPath` can be accessed.
This interface was removed because it's the same as `Partial<ParsedPath>`. By just using `Partial<ParsedPath>`, we can reduce the API surface area of `@std/path` without affecting behavior.
To migrate, use `Partial<ParsedPath>` instead of `FormatInputPathObject`. This only affects users that explictly use `FormatInputPathObject`.
```diff
- import { FormatInputPathObject } from "@std/path";
+ import { ParsedPath } from "@std/path/types";
- const parsedPath: FormatInputPathObject = {
+ const parsedPath: Partial<ParsedPath> = {
base: "file.txt",
ext: ".txt",
name: "file"
}
// ...
```
Towards …
> BREAKING(path): remove `FormatInputPathObject`

- deno.json
These are necessary to make deduplication happen in depending packages/apps.
`assert@1.0.0` is not published yet.
`uuid` is not depended from other std packages.
So I think these 2 non-range specifiers didn't actually have effect of preventing deduplication.
> chore: fix workspace dependency specifiers

- yaml/_dumper.ts
- yaml/stringify.ts
- yaml/stringify_test.ts
The `ParseOptions.noRefs` option has been renamed to `ParseOptions.useAnchors`. As a result, the polarity of the option has been swapped. In other words, `true` behavior has been changed to `false` behavior, and visa-versa. This only affects users who currently use `ParseOptions.noRefs`.
This change makes the option far easier to understand by avoiding a negative-tensed name.
Use `ParseOptions.useAnchors` instead of `ParseOptions.noRefs` and swap the polarity of the option.
```diff
import { parse } from "@std/yaml/parse";
const yamlString = `fruits:
- Apple
- Banana
- Cherry`;
- parse(yamlString, { noRefs: false });
+ parse(yamlString, { useAnchors: true });
```
Closes #5124
> BREAKING(yaml): rename `StringifyOptions.noRefs` to `StringifyOptions.useAnchors`

- front_matter/any.ts
- front_matter/json.ts
- front_matter/toml.ts
- front_matter/yaml.ts
Currently in `std/front-matter` package `extract` functions are typed as `Extractor` variable, and therefore it doesn't show type information of `@params`, `@returns`, etc.
This PR changes them to functions and improves the docs.
BEFORE
AFTER
This PR also exports `Extract` type (which is return type of `extract`) from each language file. This resolves #5323
> fix(front-matter): improve `extract` types

- yaml/_dumper.ts
- yaml/_loader.ts
- yaml/_type/omap.ts
- yaml/_type/pairs.ts
- yaml/_utils.ts
- moves `getObjectTypeString()` to `_utils.ts` as it can be shared.
> refactor(yaml): move `getObjectTypeString()`

- front_matter/_create_extractor.ts
- front_matter/_types.ts
- front_matter/any.ts
- front_matter/json.ts
- front_matter/toml.ts
- front_matter/types.ts
- front_matter/yaml.ts
We updated `extract` function types in #5325, and `Extractor` type became unused from any public APIs.
This PR makes `Extractor` type private.
> BREAKING(front-matter): make `Extractor` helper type private

- yaml/_dumper.ts
- yaml/_dumper_test.ts
- renames `dropEndingNewline()` to `trimTrailingNewline()`
- uses `.at(-1)`
- adds tests
> refactor(yaml): simplify and rename `dropEndingNewline()`

- fs/walk.ts
- fs/walk_test.ts
Previously, `walk[Sync]()` would return files and folders ending with strings, as defined in the `exts` option. E.g. It'd return the `asserts` folder when setting `exts: ["ts"]`. This is unexpected behaviour, as one would not expect folders to be turned when setting file extensions.
This change adds the leading period, `.`, to any extensions defined in `exts`, if missing, as there doesn't appear to be any good reason to require the user to have this leading period.
> fix(fs): accept `exts` without leading period in `walk[Sync]()`

- toml/_parser.ts
- toml/parse_test.ts
- replaces Utils object with functions
> refactor(toml): remove Utils object

- yaml/stringify_test.ts
This PR adds test cases which exercise block scalar output of `stringify`
part of #3713
> test(yaml): test block scalar output of stringify

- yaml/stringify_test.ts
This PR adds test cases yaml.stringify, which exercise 'folded style' of string value, and flow sequence styles of lists and mappings.
This change improves the line coverage of `yaml/_dumper.ts` from 70.56% to 85.41%
> test(yaml): add test cases of stringify

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot.ts
- testing/snapshot_test.ts
> fix(testing): escape CR in snapshot files

- testing/_test_suite.ts
- testing/bdd.ts
- testing/bdd_test.ts
Partially addresses #5034 
This changes uses `() => void | undefined` type for describe body type instead of `() => void`, which causes type error if the user assigned async functions to it.
This will prevents the confusion like https://github.com/denoland/deno/issues/22991
> fix(testing): cause type error for async function as describe body

- yaml/parse_test.ts
part of #3713 
This PR add test cases that exercises the parsing of single quoted strings.
This improves the coverage of `yaml/_loader.ts` from 82.51% to 84.76%.
> test(yaml): test parsing of single quoted scalars

- http/cookie.ts
- http/cookie_test.ts
> fix(http): allow deleting cookie with `secure`, `httpOnly` and `partitioned` attributes

- yaml/_dumper.ts
- replaces `iskey` with `isKey`
> refactor(yaml): camelcase `iskey`

- fmt/colors.ts
`stripColor` has been replaced by `stripAnsiColor` in `@std/fmt`. No changes in behavior have been made.
This change was made because `stripAnsiColor` more accurately describes the purpose of this function.
To migrate, use `stripAnsiColor` instead of `stripColor`.
```diff
- import { stripColor, red } from "@std/fmt/colors";
+ import { stripAnsiCode, red } from "@std/fmt/colors";
- console.log(stripColor(red("Hello, world!")));
+ console.log(stripAnsiCode(red("Hello, world!")));
```
> BREAKING(fmt): remove `stripColor`

- front_matter/_create_extractor.ts
- front_matter/_formats.ts
- front_matter/test.ts
- replaces `RECOGNIZE_REGEXP_MAP` and `EXTRACT_REGEXP_MAP` objects with maps
> refactor(front-matter): replace regexp objects with maps

- csv/stringify.ts
- csv/stringify_stream_test.ts
- csv/stringify_test.ts
`StringifyError ` has been removed in favor of [`TypeError `](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) as the error thrown in [`stringify()`](https://jsr.io/@std/csv/doc/~/stringify).
This change aligns `stringify()` with [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in its exceptions. The benefit of doing this is that a standard error class is used that fits the use case without having an extraneous custom error class.
To migrate, compare against `TypeError` instead of `StringifyError`, when error-handling `stringify()`.
```diff
- import { stringify, TOMLParseError } from "@std/csv/stringify";
+ import { stringify } from "@std/csv/stringify";
try { …
```
> BREAKING(csv): throw `TypeError` in `stringify()` instead of `StringifyError`

- streams/to_text.ts
- streams/to_text_test.ts
toText() should return complete UTF-8 string.
> fix(streams): toText() incorrect with multibyte strings in different chunks

- testing/_test_suite.ts
- testing/bdd_test.ts
closes #5034
This PR updates the behavior of `describe` in `testing/bdd`. Now `describe` throws if an async function is passed to it.
> fix(testing): throw error when async func is passed to describe

- testing/__snapshots__/snapshot_test.ts.snap
- testing/snapshot_test.ts
This PR fixes the flakiness of `assertSnapshot() - different directory` test case.
In the test case, 2 snapshot updates happen, but the order of them seems racy now.
This change masks the count of these 2 updates, instead checks them independently.
> test(testing): fix flakiness of snapshot test

- yaml/_dumper.ts
- replaces boolean params with options object for more clarity.
- removes default values
> refactor(yaml): add writeNode options

- yaml/_dumper.ts
Note: We might want to re-introduce param passing for type security again at a later point, since this shifts the problem to the class property `dump`, which type is `any` atm.
> refactor(yaml): remove passing `this.dump` as method param

- collections/_utils.ts
- collections/sample.ts
- inlines `randomInteger()` as it is not used elsewhere.
> refactor(collections): inline `randomInteger` utility function

- data_structures/binary_heap.ts
- data_structures/binary_search_tree.ts
This commit fixes the documentation in `data-structures` so all broken `@link` nodes are correctly linked.
> docs(data-structures): get all `@link` nodes working

- async/debounce.ts
`debounce` does not work in node.js because setTimeout returning type difference.
This PR uses `Number()` to convert from Node.js `Timeout` to number by `toPrimitive()`.
```
npx jsr add @std/async
```
package.json
```json
{
"dependencies": {
"@std/async": "npm:@jsr/std__async@^1.0.0-rc.3"
},
"type": "module"
}
```
index.js
```js
import { debounce } from "@std/async/debounce";
const d = debounce(() => {
console.log("test");
}, 200);
d();
d();
```
```
$ node index.js
test
test
```
```
$ node index.js
test
```
> fix(async): improve debounce node.js compatibility

- text/closest_string.ts
- text/compare_similarity.ts
- text/word_similarity_sort.ts
This commit refines the document in the `text` module. Namely,
- Move the note about word distance calculation possibly to change in the future to more visible place
- Fix the wrong doc comments (e.g. `possibleWords` description on `closestString`)
- Change `possibleWords` type from `string[]` to `ReadonlyArray<string>` to communicate to readers that the passed array won't be mutated
- Use `toSorted` instead of `sort` to ensure immutability
> docs(text): refine documents in text module

- deno.json
There was a mistake in `lint` task definition in #5380 (`lint:docs` is executed twice). This PR fixes it.
> chore: check import map in lint task

- jsonc/parse.ts
Options were removed in 255b7994ee20e8318016009693f0be00ab55416d
> docs(jsonc): remove docs for removed `options` parameter

- expect/_extend_test.ts
- expect/expect.ts
Looking at how you need to use `expect.extend`, the return type `ExtendMatchResult` is expected but it is not exported publicly:
https://github.com/denoland/deno_std/blob/81943c34c7ba662ee44446d4fa49790e7138ee23/expect/_extend_test.ts#L7-L11
Workaround is to use `any` but it's not ideal
```ts
declare module "@std/expect" {
interface Expected {
toMatchDescriptor: (key: PropertyKey, expected:PropertyDescriptor) => any;
}
}
```
```diff
-    toMatchDescriptor: (key: PropertyKey, expected:PropertyDescriptor) => any;
+    toMatchDescriptor: (key: PropertyKey, expected:PropertyDescriptor) => ReturnType<Matcher>;
> fix(expect): improve `expect` type to make it work better with `expect.extend`

- yaml/_schema.ts
- yaml/_type.ts
All `Type` objects already have this property defined. Users don't have control over this value.
Towards #5340
> refactor(yaml): make `Type.kind` required

- yaml/_loader.ts
- yaml/parse.ts
- yaml/parse_test.ts
[`parse()`](https://jsr.io/@std/yaml@1.0.0-rc.3/doc/~/parse) now throws [`SyntaxError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) instead of `YamlError`. No changes in behavior have been made.
This change was made to align `@std/yaml` with other `parse()` functions in the Standard Library, such as in `@std/csv` and `@std/toml`, and [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse), which all throw `SyntaxError`. This will also result in a slightly smaller API surface and allows the user to more easily differentiate between `parse()` and `stringify()` errors (`stringify()` will soon throw `TypeError`).
To migrate, compare against `SyntaxError` instead of `YamlError` when …
> BREAKING(yaml): replace `YamlError` with `SyntaxError` in `parse()`

- cli/parse_args.ts
Addresses https://github.com/denoland/std/pull/5212#pullrequestreview-2181458294
> docs(cli): documentation tweaks

- yaml/_type.ts
This property isn't used anywhere.
> refactor(yaml): remove `Type.loadKind` property

- yaml/_type.ts
- yaml/_type/float.ts
- yaml/_type/int.ts
Adds type guards and makes the purpose of the method clearer.
> refactor(yaml): improve `Type.predicate` behavior

- yaml/_dumper.ts
- yaml/_loader.ts
- yaml/_schema.ts
- yaml/_type.ts
- yaml/_type/binary.ts
- yaml/_type/bool.ts
- yaml/_type/float.ts
- yaml/_type/int.ts
- yaml/_type/map.ts
- yaml/_type/merge.ts
- yaml/_type/nil.ts
- yaml/_type/omap.ts
- yaml/_type/pairs.ts
- yaml/_type/regexp.ts
- yaml/_type/seq.ts
- yaml/_type/set.ts
- yaml/_type/str.ts
- yaml/_type/timestamp.ts
- yaml/_type/undefined.ts
I'm mostly certain this is the right approach.
Supercedes #5453
> refactor(yaml): add `KindType` generic type argument to `Type`

- yaml/_dumper.ts
- yaml/_type.ts
- yaml/_type/timestamp.ts
This PR removes instanceOf field of `Type` type, which is only used by `timestamp` type and can be easily replaced by `object instanceof Date` check.
This simplifies the `detectType` logic in `yaml/_dumper.ts`
> refactor(yaml): remove `instanceOf` field of `Type`

- .github/FAQ.md
Answers the following questions:
1. Why is the Standard Library versioned differently to the Deno runtime?
2. Which versions of Deno is the Standard Library guaranteed to work with?
Closes #4732
> chore: answer versioning questions in FAQ

- semver/increment.ts
- semver/increment_test.ts
- semver/mod.ts
The `prerelease` and `buildmetadata` arguments for [`increment()`](https://jsr.io/@std/semver/doc/increment/~/increment) into a new optional `IncrementOptions` interface.
This change was made to ensure the symbol adheres to the [Deno Style Guide](https://docs.deno.com/runtime/manual/references/contributing/style_guide/#exported-functions%3A-max-2-args%2C-put-the-rest-into-an-options-object.) which states that optional arguments should go into an options object.
To migrate, use the options argument, instead of the positional arguments in `increment()`.
```diff
import { increment, parse } from "./semver/mod.ts";
- increment(parse("1.2.3"), "prerelease", "alpha", "0");
+ increment(parse("1.2.3"), "prerelease", { prerelease: "alpha", build: "0" });
```
Closes #4420
> BREAKING(semver): replace `prerelease` and `buildmetadata` arguments with options object

- media_types/_db.ts
- media_types/type_by_extension_test.ts
> fix(media-types): return `video/mp4` for `.mp4` extension

- dotenv/mod.ts
- dotenv/mod_test.ts
The `examplePath` option for `load[Sync]()` from `@std/dotenv` has been removed. The `allowEmptyValues` option and `MissingEnvVarsError` have also been removed, as the basis for their existence was dependent on the `examplePath` option.
See details in #5449.
To migrate, if environment variables need to be validated, do so in-code instead of using the `examplePath` option.
```env
FOO=bar
```
```diff
import "@std/dotenv/load";
+ if (!Deno.env.has("QUX") {
+   // ...
+ }
```
Closes #5449
> BREAKING(dotenv): remove `examplePath` option from `load[Sync]()`

- http/signed_cookie.ts
> docs(http): improve unstable API notices

- cli/spinner.ts
> docs(cli): improve unstable API notices

- _tools/check_docs.ts
These aren't needed as JSR doesn't have a dedicated page for class constructors. Also, VSCode merges the documentation for classes and their constructors. In other words, class examples are shown, even if there are no constructor examples, when one hovers over a class.
I'll remove the redundant examples in follow-up PRs.
> chore: remove requirement for `@example`s in constructors

- cli/parse_args.ts
- cli/prompt_secret.ts
- cli/spinner.ts
This ensures that the argument is displayed as `options` instead of [`unnamed 1`](https://jsr.io/@std/cli@1.0.0-rc.5/doc/~/parseArgs) in documentation.
> docs(cli): fix options arguments display

- fs/expand_glob.ts
- fs/move.ts
- fs/walk.ts
This ensures that the argument is displayed as `options` instead of `unnamed 1` in documentation.
> docs(fs): fix options argument display

- io/to_readable_stream.ts
- io/to_writable_stream.ts
This ensures that the argument is displayed as `options` instead of `unnamed 1` in documentation.
> docs(http): fix options argument display

- json/stringify_stream.ts
This ensures that the argument is displayed as `options` instead of `unnamed 1` in documentation.
> docs(json): fix options argument display

- yaml/parse_test.ts
This PR adds the check of `merge` of list of mapping. (Reduces 8 missed lines in `yaml/_loader.ts` coverage report)
> test(yaml): add check of merge of list of mapping

- assert/object_match.ts
- assert/object_match_test.ts
Separated from #5408
Fix: #3771
When filtering two objects, the `fn()` function returns an empty object if they don't have the same keys or symbols. This PR adds the logic so that it returns the entries of the first object in this case. (also rename `fn` to 	`filterObject`)
> fix(assert): `assertObjectMatch` doesn't print whole object

- testing/_time.ts
- testing/time.ts
- testing/time_test.ts
[`async/deadline` v1.0.0](https://github.com/denoland/std/blob/release-2024.07.19/async/deadline.ts) uses `AbortSignal.timeout`, so `FakeTime` cannot be used for it.
Fixes #5499.
> fix(testing): FakeTime fakes `AbortSignal.timeout`

- expect/mod.ts
> docs(expect): link to matcher docs

- assert/object_match.ts
- assert/object_match_test.ts
Separated from #5408
Fix: #3472
Currently, when filtering arrays, `assertObjectMatch()` uses `filterObject({ ...value }, { ...subset })` which converts arrays into objects. This PR adds `filterArray()` function to handle arrays.
> fix(assert): fix `assertObjectMatch()` prints arrays as objects

- assert/assertion_error.ts
> chore(assert): remove redundant constructor example

- async/retry.ts
> chore(async): remove redundant constructor example

- .github/CONTRIBUTING.md
> chore: document design decision to only use `@std/assert` within testing code

- streams/to_json.ts
- streams/to_json_test.ts
- streams/to_text.ts
- streams/to_text_test.ts
Includes documentation clarifications and test cleanups. See discussion in #5079.
> fix(streams): strictly define `toJson()` and `toText()` input

- yaml/stringify_test.ts
This PR adds test cases which check the behavior of `stringify` when `skipInvalid: true` specified
> test(yaml): check stringify behavior when skipInvalid specified

- yaml/parse_test.ts
This PR adds test cases which check that `parse` throws with reserved characters '@' and '`'.
This improves the line coverage of `yaml/_loader.ts`, reducing 17 missed lines.
> test(yaml): check the use of reserved characters

- yaml/_schema.ts
- yaml/parse.ts
- yaml/stringify.ts
By adding a `SchemaType` type.
Closes #5443
> docs(yaml): document different schemas

- yaml/_type/float.ts
According to the spec, it seems that the float type shouldn't contain a `:` (see https://yaml.org/spec/1.2.2/#10214-floating-point).
> refactor(yaml): cleanup dead code in float `Type` implementation

- yaml/stringify_test.ts
This PR adds test cases that check the behavior of `sortKeys` option of `stringify`.
> test(yaml): test sortKeys option behavior

- path/posix/mod.ts
- path/windows/mod.ts
This is clearer and more accurate.
> docs(path): cleanup `@std/path/posix` and `@std/path/windows` module documentation

- fs/move.ts
- fs/move_test.ts
Previously, [`@std/fs/move`](https://jsr.io/@std/fs/doc/move/~/) threw `SubdirectoryMoveError`. Now, it throws [`Deno.errors.NotSupported`](https://docs.deno.com/api/deno/~/Deno.errors.NotSupported).
This change was made to reduce the API surface area by using an appropriate error class that's already built into the Deno runtime.
To migrate, compare against `Deno.error.NotSupported` instead of `SubdirectoryMoveError` when error-handling `move()` or `moveSync()`.
```diff
- import { move, SubdirectoryMoveError } from "@std/fs/move";
+ import { move } from "@std/fs/move";
try {
await move("./path/to/folder/subdir", "./path/to/folder");
} catch (error) {
- if (error instanceof SubdirectoryMoveError) {
+ if (error instanceof Deno.errors.NotSupported) {
// ...
}
}
```
Towards #5476
> BREAKING(fs): throw `Deno.errors.NotSupported` instead of `SubdirectoryMoveError` in `move[Sync]()`

- testing/mock.ts
- testing/mock_test.ts
Improves casing and punctuation.
> refactor(testing): improve error messages in `mock` module

- cli/spinner_test.ts
- cli/testdata/spinner_cases/change_message.ts
- cli/testdata/spinner_cases/custom_color_black.ts
- cli/testdata/spinner_cases/custom_color_blue.ts
- cli/testdata/spinner_cases/custom_color_cyan.ts
- cli/testdata/spinner_cases/custom_color_gray.ts
- cli/testdata/spinner_cases/custom_color_green.ts
- cli/testdata/spinner_cases/custom_color_magenta.ts
- cli/testdata/spinner_cases/custom_color_red.ts
- cli/testdata/spinner_cases/custom_color_white.ts
- cli/testdata/spinner_cases/custom_color_yellow.ts
- cli/testdata/spinner_cases/custom_interval_10.ts
- cli/testdata/spinner_cases/custom_interval_750.ts
- cli/testdata/spinner_cases/custom_message.ts
- cli/testdata/spinner_cases/custom_spinner.ts
- cli/testdata/spinner_cases/set_color.ts
- cli/testdata/spinner_cases/start.ts
Currently most spinner test scripts end the execution with errors (because `setTimeout(spinner.stop, num)` throws instead of correctly stopping the spinner).
This PR fixes them by correctly stopping the spinners.
(This probably fixes https://github.com/denoland/std/issues/5541 )
> test(cli): stop spinner without error

- expect/_types.ts
- expect/expect.ts
> docs(expect): add examples of matcher usages

- .github/workflows/workspace_publish.yml
We need to manually dispatch `workspace_publish` workflow to retry it with latest stable CLI.
ref: https://github.com/denoland/std/issues/5555
> chore: allow manual dispatch of workspace_publish

- fs/walk.ts
Related: #5557 
Even though a walk function originally returns relative paths, it gave examples of absolute paths, so I misunderstood.
This PR fixes it.
> docs(fs): fix incorrect examples for walk

- semver/greater_than_range_test.ts
- semver/less_than_range_test.ts
- semver/parse_range.ts
> fix(semver): correctly remove spaces between operators and versions in `parseRange()`

- semver/increment.ts
- semver/increment_test.ts
- semver/parse.ts
Provides more context to the error.
> refactor(semver): throw `TypeError` if release is invalid in `increment()`

- assert/assertion_error.ts
- assert/assertion_error_test.ts
Ref:
- https://github.com/denoland/std/issues/5476#issuecomment-2254261250
> feat(assert): add `options` parameter to `AssertionError` constructor

- ini/mod.ts
- ini/parse.ts
- ini/stringify.ts
It previously contained information that was extraneous for module documentation.
> docs(ini): cleanup module documentation

- testing/mock.ts
- testing/mock_test.ts
> refactor(testing): improve error messages in `mock` module (part 2)

- semver/_constants.ts
- semver/is_range.ts
- semver/max_satisfying_test.ts
- semver/min_satisfying_test.ts
- semver/parse_range.ts
- semver/parse_range_test.ts
- semver/satisfies_test.ts
> fix(semver): throw on invalid input in `parseRange()`

- ini/stringify.ts
- ini/stringify_test.ts
This PR removes `commentChar`, `assignment`, and `deduplicate` options from `stringfiy` options.
- `deduplicate` is no longer relevant as we dropped the support of `IniMap`, which was only meaningful with `IniMap`
- `commentChar` is no longer relevant as stringify doesn't support comments in output.
- Dropped `assignment` option as `=` seems the only common character for assignment in `INI`.
This PR also make `FormattingOptions` private as it's no longer reasonable to keep it public.
related #5562
> BREAKING(ini): reduce options for `stringify`, make `FormattingOptions` type private

- http/etag.ts
- http/etag_test.ts
Not completely sure this is a breaking change, but this PR improves the return type of `eTag` function. Now it returns `Promise<string>` if the input is `string` or `Uint8Array`.
related #5217
> fix(http): better `eTag` return type for `string` and `Uint8Array` inputs

- http/etag.ts
We changed the `eTag` function in #5571 and this symbol is not referenced from any public API.
`ETagSource` type has been removed
It's not used from public APIs.
```diff
- import { type ETagSource } from "@std/http/etag";
+ import { type FileInfo } from "@std/http/etag";
+ type ETagSource = string | Uint8Array | FileInfo;
```
> BREAKING(http): remove `ETagSource`

- Releases.md
#5110 was missed in the release note in the previous release #5554 because [the upgrade tool](https://github.com/denoland/bump-workspaces) didn't understand `text/unstable` scope yet. (Now it's addressed in https://github.com/denoland/bump-workspaces/pull/30 )
This PR fixes the release note.
> chore: update Releases.md

- io/copy.ts
- io/copy_test.ts
- deduplicate logic by importing `writeAll`
- add JSDoc description of returned value
- add test step for returned value
> refactor(io): use `writeAll()` within `copy()`

- semver/try_parse.ts
The argument of `tryParse` becomes `string` instead of `string | undefined`.
`canParse` and `parse` only accepts `string`. This change aligns `tryParse` to these similar APis.
```diff
-tryParse(version);
+typeof version === "string" ? tryParse(version) : undefined;
```
> BREAKING(semver): do not accept undefined input in `tryParse`

- semver/can_parse.ts
This addressed the concern raised in https://github.com/denoland/std/pull/5220#pullrequestreview-2208098580
> fix(semver): do not throw in `canParse`

- semver/_constants.ts
- semver/format.ts
- semver/format_range.ts
- semver/format_test.ts
- semver/is_semver.ts
- semver/is_semver_test.ts
`format` currently handles NaN semvers (`{ major: NaN, minor: NaN, patch: NaN }`) or Infinity semvers (such as `{ major: Infinity, minor: Infinity, patch: Infinity }`) in a special way.
This change stops those special handlings.
The infinity SemVers or NaN SemVers don't represent valid semantic versions, and they are not part of the semver spec. It's not reasonable to handle them in a special way, but rather we should consider them invalid versions.
Do not use these non-standard semvers as sentinel values. Instead use comparison functions such as `compare`, `greaterThan`, `lessThan`, `greaterThanRange`, `lessThanRange`, etc for checking semver conditions.
> BREAKING(semver): remove the handling of non-standard SemVers in format function

- semver/compare.ts
This PR clarifies the description of `compare` docs. The expression `s0 === s1` is misleading as the equality of semvers can't be checked with `===` operator.
> docs(semver): clarify compare docs

- testing/snapshot.ts
This PR adds the mentioning of the default serializer of snapshot testing.
related #5218
> docs(testing): mention default serializer

- fmt/duration.ts
This PR renames `PrettyDurationOptions` to `FormatOptions`.
The option object types are named with the convention of `FooOptions` where `Foo` is the function name which the option is used for. This PR aligns the option object type for `format` function to this convention.
```diff
-import type { PrettyDurationOptions } from "@std/fmt/duration";
+import type { FormatOptions as PrettyDurationOptions } from "@std/fmt/duration";
```
> BREAKING(fmt): rename `PrettyDurationOptions` to `FormatOptions`

- cli/parse_args.ts
- moves regexps outside function and makes them constants.
- adds named capturing group to `VALUE_REGEXP` instead of testing and splitting value afterwards.
- reduces code block with the same regexp check.
> refactor(cli): make regexps constants

- async/abortable_test.ts
Fixes https://github.com/denoland/std/actions/runs/10189680039/job/28188160624
> test(async): fix `abortable.AsyncIterable() calls return before throwing` test

- csv/parse.ts
This PR clarifies `parse` description.
Addresses the comment at https://github.com/denoland/std/pull/5219#issuecomment-2262035310
> docs(csv): clarify `parse` document

- csv/parse_stream.ts
- csv/parse_stream_test.ts
Although the constructor of `CsvParseStream` accepts `fieldsPerRecord` option (see https://jsr.io/@std/csv@1.0.0-rc.5/doc/~/CsvParseStreamOptions) that ensures that every record has the specified (or inferred from the first row) number of fields, this option has no effect at all in the current implementation.
To fix this issue, this patch implements the `fieldsPerRecord` logic in `CsvParseStream` together with sufficient amount of test cases.
> feat(csv): support `fieldsPerRecord` in `CsvParseStream`

- cli/parse_args.ts
- replaces `for in` loop with `for of` loop by using `Object.entries()`.
> refactor(cli): use `for of` instead of `for in` loop

- cli/parse_args.ts
- replaces `broken` boolean and just continues the loop directly by adding loop label.
> refactor(cli): remove `broken` variable in favour of loop label

- async/pool_test.ts
It seems that these tests didn't need to be so slow.
On M2 laptop:
- Before: ~8s
- After: ~0.7s
> test(async): improve test speed of `async/pool_test.ts`

- csv/parse_stream.ts
addressed the comment at https://github.com/denoland/std/pull/5219#issuecomment-2263388027
> docs(csv): clarify `CsvParseStream` description

- csv/_io.ts
- csv/mod.ts
- csv/parse.ts
- csv/parse_stream.ts
- csv/parse_stream_test.ts
- csv/parse_test.ts
This commit adds more examples to `parse` function and `CsvParseStream` class to cover all the provided options.
Also fixes a few other things:
- Replace stale description `ParseError` with the correct `SyntaxError`.
- Fix the default value of `comment` property. The old comment says the default value is `#`, but this was wrong.
- Get negative value in `fieldsPerRecord` option working in `parse` as documented
> docs(csv): more examples for `parse` and `CsvParseStream`

- csv/_io.ts
- csv/parse.ts
- csv/parse_stream.ts
- csv/parse_stream_test.ts
- csv/parse_test.ts
As we discussed in https://github.com/denoland/std/pull/5605#discussion_r1701028684, it seems like we never get `undefined` as a parse result of fields. If there is a mismatch in the number of fields across rows, the parse just throws an error.
To better reflect this in typing, this commit removes `undefined` from the record value type.
> fix(csv): remove `undefined` from possible value type of parse result

- .github/workflows/workspace_publish.yml
Publishing is now blocked by the change of hostname handling on onListen handler of `Deno.serve`. This PR tries to fix it by upgrading Deno CLI to canary.
> chore: fix workspace publish workflow

- cli/parse_args.ts
Addresses https://github.com/denoland/std/pull/5607#discussion_r1701383077
The following tests pass:
```ts
import { assertEquals } from "@std/assert";
Deno.test("isNumber should return true for valid numbers", () => {
assertEquals(isNumber("123"), true);
assertEquals(isNumber("-456"), true);
assertEquals(isNumber("0"), true);
assertEquals(isNumber("3.14"), true);
assertEquals(isNumber("-2.5"), true);
assertEquals(isNumber("1e3"), true);
assertEquals(isNumber("-5e-2"), true);
assertEquals(isNumber("0x10"), true);
});
Deno.test("isNumber should return false for invalid numbers", () => {
assertEquals(isNumber("abc"), false);
assertEquals(isNumber("123abc"), false);
assertEquals(isNumber("12.34.56"), false);
assertEquals(isNumber("1e"), false);
assertEquals(isNumber("e3"), false); …
```
> refactor(cli): minor cleanups

- csv/parse_stream_test.ts
- streams/mod.ts
- streams/text_line_stream_test.ts
Due to https://github.com/denoland/deno/pull/24623
> fix(csv,streams): use string arrays in `ReadableStream.from()` in docs and tests

- archive/untar.ts
These properties are not documented or tested anywhere. It seems they were included in the public API by mistake.
> fix(archive): make `block` and `reader` properties in `Untar` private

- archive/tar.ts
This property is not documented or tested anywhere. It seems it was included in the public API by mistake.
> fix(archive): make `data` property private in `Tar`

- http/file_server.ts
- http/file_server_test.ts
Previously, the `file-server` module handled all requests with non-`GET` and non-`HEAD` methods the same as `GET` and `HEAD` methods, when they shouldn't have. Now, such methods cause a HTTP 405 status to be served.
> fix(http): handle wrong request method correctly

- http/route.ts
- http/route_test.ts
This makes the parameter compatible with `deno serve`, which was the original intention of `route()`.
> fix(http/unstable): make `info` parameter optional

- uuid/_common.ts
The implementation is based on [npm:uuid `stringify()`](https://github.com/uuidjs/uuid/blob/main/src/stringify.ts).
<details>
<summary>Benchmark result and code</summary>
```
cpu: Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
runtime: deno 1.45.5 (x86_64-pc-windows-msvc)
file:///D:/coding/project/javascript/deno/console/mod.ts
benchmark      time (avg)        iter/s             (min … max)       p75       p99      p995
--------------------------------------------------------------- -----------------------------
group 10 uuids
old            36.98 µs/iter      27,042.4       (32 µs … 1.01 ms) 33.2 µs 100.6 µs 159.3 µs
new              528 ns/iter   1,893,939.4     (400 ns … 909.7 µs) 500 ns 1 µs 1.1 µs
summary
new
70.04x faster than old
group 100 uuids
old           367.56 µs/iter       2,720.7 …
```
> perf(uuid): make `bytesToUuid()` up to 100x faster

- datetime/format.ts
- datetime/format_test.ts
**Changes**
This PR changes the `utc` boolean option to `timeZone` with explicit `"UTC"` value option.
**Reasoning**
This makes the option extendable if needed and aligns the api to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString#using_options
> BREAKING(datetime): replace `utc` with `timeZone` option

- cache/memoize_test.ts
Fixes https://github.com/denoland/std/issues/5663
> fix(cache/unstable): fix flaky `memoize()` test with `FakeTime`

- uuid/_common.ts
<details>
<summary>Code</summary>
```ts
function uuidToBytes_new(uuid: string): Uint8Array {
const bytes = new Uint8Array(16);
let i = 0;
for (const str of uuid.split("-")) {
const hex = parseInt(str, 16);
switch (str.length) {
case 4: {
bytes[i++] = (hex >>> 8) & 0xff;
bytes[i++] = hex & 0xff;
break;
}
case 8: {
bytes[i++] = (hex >>> 24) & 0xff;
bytes[i++] = (hex >>> 16) & 0xff;
bytes[i++] = (hex >>> 8) & 0xff;
bytes[i++] = hex & 0xff;
break;
}
case 12: {
bytes[i++] = (hex / 0x10000000000) & 0xff;
bytes[i++] = (hex / 0x100000000) & 0xff;
bytes[i++] = (hex >>> 24) & 0xff;
bytes[i++] = (hex >>> 16) & 0xff;
bytes[i++] = (hex >>> 8) & 0xff;
bytes[i++] = hex & 0xff;
break;
}
}
}
return bytes;
}
function uuidToBytes_old(uuid: string): Uint8Array {
const bytes = uuid
.replaceAll("-", "") …
```
> perf(uuid): make `uuidToBytes()` up to 2.5x faster

- encoding/base32_test.ts
These are clearer and use official test vectors.
> test(encoding): cleanup base32 tests

- yaml/_dumper_state.ts
**Changes**
This PR removes the `result` property of the `DumperState`.
**Reasoning**
It is not used anywhere.
> refactor(yaml): remove `result` property

- .github/CONTRIBUTING.md
- _tools/check_docs.ts
- testing/types.ts
This commit adds support for `expect-error` directive in code snippets evaluator, which allows example snippets to have ones that are expected to fail either at compile time or runtime.
This is inspired by Rust where we can add doc tests that are supposed to panic, or to fail to compile, e.g.
```rust
/// ```should_panic
/// assert!(false);
/// ```
///
/// ```compile_fail
/// let x = 5;
/// x += 2;
/// ```
```
> chore: support `expect-error` directive in code snippets evaluator

- yaml/_loader_state.ts
**Changes**
This PR makes the `version` property in `DumperState` required.
**Reasoning**
The version is checked against `null`, so `undefined` should not be possible.
> refactor(yaml): Make `version` property required

- yaml/_loader_state.ts
**Changes**
This PR removes the `schema` property in `DumperState`.
**Reasoning**
`schema` is only used in the constructor to extract values which are stored in properties themselves.
> refactor(yaml): remove `schema` property

- testing/types.ts
- testing/types_test.ts
`IsExact` has many false positives.
- Add test cases for array or tuple types. These work correctly in the original `IsExact` implementation before this PR, but give false positives in [the alternative implementation](https://github.com/type-challenges/type-challenges/blob/e77262dba62e9254451f661cb4fe5517ffd1d933/utils/index.d.ts#L7-L9), so I am added it.
- Add test cases for function or class, and fix false positive.
- This fix resulted in the following false negative.
- Add test cases for intersection, and fix false negative. In other words, I fixed the problem that "correct equality may still be stricter than some expect."
https://github.com/denoland/std/issues/3196#issuecomment-1430099273
It was closed by arguments against including utility types.
However, `IsExact` already exists in …
> fix(testing): fix false positive in `IsExact`

- yaml/_schema.ts
**Changes**
This PR redefines the `include` property in `Schema` as a single optional `Schema`.
**Reasoning**
Every used Schema only has one included `Schema`.
> refactor(yaml): redefine `include` as optional `Schema`

- yaml/_loader_state.ts
**Changes**
This PR changes the type of `tagMap` and `anchorMap` to `Map`
**Reasoning**
The current implementation uses must use `Object.create(null)` to set the value.
This seems like legacy code that can be achieved with `Map`.
> refactor(yaml): use `Map` for `tagMap` and `anchorMap`

- yaml/_loader_state.ts
**Changes**
This PR sets the type of `overridableKeys` to `Set<string>`
**Reasoning**
The current implementation seems to be legacy code.
> refactor(yaml): use `Set` for `overridableKeys`

- assert/object_match.ts
As title describes, add an example in usage of `assertObjectMatch` to show that the `expected` object can be a subset of the `actual` object but the inverse will result in an assertion failure.
Discussed in #5682
> docs(assert): Add additional example in assertObjectMatch docs

- yaml/_dumper_state.ts
- yaml/stringify.ts
**Changes**
This PR moves the `stringify()` logic inside the `DumperState`.
**Reasoning**
This allows the reduction of `any` types. Other methods can be made private in a future PR.
> refactor(yaml): add `stringify()` method to `DumperState`

- .github/ISSUE_TEMPLATE/feature_request.md
This change has been made by `deno fmt` canary. We need to land this to make the main CI green.
> chore: fix formatting of markdown file

- yaml/stringify_test.ts
**Changes**
This PR adds a test for the edge case when `state.writeNode()` returns false in `stringify()`
> test(yaml): add edge case test for `stringify`

- semver/can_parse.ts
- semver/compare.ts
- semver/difference.ts
- semver/equals.ts
- semver/format.ts
- semver/greater_or_equal.ts
- semver/greater_than.ts
- semver/greater_than_range.ts
- semver/increment.ts
- semver/less_or_equal.ts
- semver/less_than.ts
- semver/less_than_range.ts
- semver/not_equals.ts
- semver/parse.ts
- semver/parse_range.ts
- semver/range_intersects.ts
- semver/satisfies.ts
- semver/try_parse.ts
- semver/try_parse_range.ts
**Changes**
This PR unifies names of public functions.
- `value` if the `argument` is a string to be parsed
- `version` if the argument is a `SemVer`
- `versionN...` if multiple arguments are `SemVer`s
- `Range` if the argument is a `Range`
**Reasoning**
The docs are automatically created and use the jsdoc param names.
It makes the docs more esthetically pleasing and easier to understand.
> refactor(semver): unify param names

- async/deadline.ts
- async/mod.ts
The latest stable Deno (1.45) uses TypeScript 5.5.
> chore(async): add browser-compat declarations

- yaml/_dumper_state.ts
**Changes**
This PR renames `DumperState` methods fro `write*()` to `stringify*()`
**Reasoning**
https://github.com/denoland/std/pull/5683 removed the `dump` property. All these functions now turn passed data into a string and return it.
> refactor(yaml): rename `DumperState` methods

- yaml/_dumper_state.ts
**Changes**
This PR removes the callback of `chooseScalarType()` and passes `implicitTypes` instead.
**Reasoning**
This allows to the inline the code of the utility function `testImplicitResolving()`, which is clearer to read and understand.
> refactor(yaml): replace `chooseScalarType()` callback with `implicitTypes ` argument

- cli/parse_args.ts
- http/etag.ts
- ini/_ini_map.ts
- internal/diff_str.ts
- media_types/parse_media_type.ts
**Changes**
This replaces comparisons done with `trim()` with `RegExp.test()`
**Reasoning**
`trim()` creates a new string which is only used for the comparison and thus not memory efficient.
> perf(cli,http,ini,internal,media-types): replace `trim()` comparisons with regexps

- webgpu/texture_with_data.ts
Aligns the error messages in the `webgpu` folder to match the style guide.
> refactor(webgpu): align additional error messages

- path/dirname.ts
- path/dirname_test.ts
- path/posix/dirname.ts
- path/windows/dirname.ts
part of #5537
This PR adds `dirname(url: URL): string` overload to dirname function.
If a user have a file URL string or object, currently they need to convert it to a path string first to perform path operation on it:
```ts
import { dirname, fromFileUrl } from "@std/path";
dirname(fromFileUrl(new URL(import.meta.url)));
```
This change makes it simpler by automatically interpret the file URL as path
```ts
import { dirname } from "@std/path";
dirname(new URL(import.meta.url));
```
> feat(path/unstable): support `URL` input in `dirname()`

- dotenv/mod.ts
- dotenv/parse.ts
- dotenv/parse_test.ts
Currently `parse` of `dotenv` silently ignores the invalid key entries in `.env` file. This PR adds the warning like `Ignored the key "1INVALID" as it is not a valid identifier: The key need to match the pattern /^[a-zA-Z_][a-zA-Z0-9_]*$/.` when `.env` file has invalid key entry.
closes #5619
> fix(dotenv): show warning when there is invalid key in `.env` file

- front_matter/yaml.ts
- front_matter/yaml_test.ts
This adds an `options` argument to `front_matter/yaml/extract` to pass options to the underlying YAML parser, such as schema selection, pursuant to #5677.
Closes #5677
> feat(front-matter/unstable): add pass-through `ParseOptions` argument for YAML parser

- yaml/_dumper_state.ts
- yaml/_loader_state.ts
- yaml/_type.ts
- yaml/_utils.ts
**Changes**
This PR replaces the `ArrayObject` type with `Record<string, unknown>`
**Reasoning**
`ArrayObject` is a generic `Record` type which doesn't need to be generic where it is used.
> refactor(yaml): remove `ArrayObject`

- .github/CONTRIBUTING.md
Update the CONTRIBUTING.md to indicate that error messages should describe the desired state if possible.
> docs: errors messages may describe desired state

- .github/CONTRIBUTING.md
Error messages should not include a period, as it will result in multiple sentences. Colons are the preferred punctuation but other punctuation may make sense in some cases.
> docs: specifically disallow periods in error messages

- internal/diff.ts
- internal/diff_test.ts
Aligns the error messages in the `internal` folder to match the style guide.
> refactor(internal): align additional error messages

- cli/_tools/generate_data.ts
- cli/prompt_secret.ts
Aligns the error messages in the `cli` folder to match the style guide.
> refactor(cli): align additional error messages

- async/pool.ts
- async/pool_test.ts
- async/retry.ts
- async/retry_test.ts
Aligns the error messages in the `async` folder to match the style guide.
> refactor(async): align the error messages to the style guide

- log/base_handler.ts
- log/console_handler.ts
- log/file_handler.ts
Ref: https://github.com/denoland/std/pull/5702
**Changes**
This PR makes the `BaseHandler` and `log()` method abstract.
It removes the obsolete `override` for `log()` in `FileHandler` and `ConsoleHandler`.
> refactor(log): make `BaseHandler` abstract

- front_matter/_formats.ts
**Changes**
This PR removes the os specific check for `\r?` before `\n`.
**Reasoning**
This is the only occurrence where a os check is done. Even the `recognize()` function in the same module doesn't do it:
https://github.com/denoland/std/blob/99200dcd9039eea515f3f850b2f13cf7be585d03/front_matter/_shared.ts#L36
> fix(front-matter): remove os specific newline

- yaml/_loader_state.ts
> refactor(yaml): inline `readBlockSequence()`

- yaml/_dumper_state.ts
**Changes**
This PR replaces the usage of an array with a `Set`.
**Reasoning**
The array is only used to check existing data.
> refactor(yaml): use `Set` in `inspectNode()`

- yaml/_loader_state.ts
> refactor(yaml): inline `readLineBreak()`

- semver/_shared.ts
- semver/increment.ts
- semver/parse.ts
- semver/parse_range.ts
- semver/parse_range_test.ts
Aligns the error messages in the `semver` folder to match the style guide.
> refactor(semver): align additional error messages

- jsonc/parse.ts
- jsonc/parse_test.ts
Aligns the error messages in the `jsonc` folder to match the style guide.
> refactor(jsonc): align additional error messages

- media_types/parse_media_type.ts
- media_types/parse_media_type_test.ts
Aligns the error messages in the `media_types` folder to match the style guide.
> refactor(media-types): align additional error messages

- log/levels.ts
- log/rotating_file_handler.ts
- log/rotating_file_handler_test.ts
Aligns the error messages in the `log` folder to match the style guide.
> refactor(log): align additional error messages

- yaml/_loader_state.ts
> refactor(yaml): inline `writeFoldedLines()`

- yaml/_loader_state.ts
> refactor(yaml): inline `readPlainScalar()`

- .github/CONTRIBUTING.md
The assertion package uses a period at the end of the error message. While this doesn't conform to the standard error message format, it would be a breaking change to adjust this now. This change-set adds a note to the CONTRIBUTING.md file to explain this exception.
> docs: add a note about error message format exception

- fs/copy.ts
- fs/copy_test.ts
- fs/ensure_dir.ts
- fs/ensure_dir_test.ts
- fs/ensure_file.ts
- fs/ensure_file_test.ts
- fs/exists.ts
- fs/exists_test.ts
Aligns the error messages in the `fs` folder to match the style guide.
> refactor(fs): align additional error messages

- uuid/common.ts
- uuid/v1.ts
- uuid/v1_test.ts
- uuid/v3.ts
- uuid/v3_test.ts
- uuid/v5.ts
- uuid/v5_test.ts
Aligns the error messages in the `uuid` folder to match the style guide.
> refactor(uuid): align additional error messages

- uuid/common_test.ts
This PR improves the test of `version` function of `@std/uuid` package
> test(uuid): assert error message of `version()`

- testing/_test_suite.ts
- testing/bdd.ts
- testing/bdd_test.ts
- testing/mock.ts
- testing/mock_test.ts
- testing/time.ts
- testing/time_test.ts
Aligns the error messages in the `testing` folder to match the style guide. Only errors thrown during test setup are updated, errors thrown during test execution are not updated.
> refactor(testing): align additional error messages

- expect/_equal.ts
- expect/expect.ts
- expect/test.ts
Aligns the error messages in the `expect` folder to match the style guide. Only errors thrown during test setup are updated, errors thrown from matchers during execution are not updated.
> refactor(expect): align additional error messages

- path/extname.ts
- path/extname_test.ts
- path/posix/extname.ts
- path/windows/extname.ts
> feat(path/unstable): support `URL` in `extname()`

- yaml/_dumper_state.ts
**Changes**
This PR removes `isArray()` in combination with `isObject()`, because array is an object.
> refactor(yaml): use `isObject()`

- .github/workflows/version_bump.yml
This PR specifies import map path in version_bump workflow using https://github.com/denoland/bump-workspaces/pull/31
This is now necessary as we use custom (non-`deno.json`) import map path.
> chore: specify import map path in version_bump workflow

- cache/ttl_cache.ts
- cache/ttl_cache_test.ts
Ref:
- https://github.com/denoland/std/pull/5662#pullrequestreview-2261065977
/cc @iuioiua In response to [your comment](https://github.com/denoland/std/pull/5662#issuecomment-2311270279) — feel free to refactor as you see fit
> docs(cache): document valid range information for TTL values

- msgpack/encode.ts
- msgpack/encode_test.ts
Towards https://github.com/denoland/std/issues/5831
> fix(msgpack): accept readonly input data in `encode()`

- expect/_matchers.ts
- expect/_to_contain_equal_test.ts
- expect/_to_have_been_last_called_with_test.ts
- expect/_to_have_been_nth_called_with_test.ts
Aligns the error messages in the matchers in `expect` folder to match the style guide.
> refactor(expect): align error messages in the matchers

- yaml/_loader_state.ts
> refactor(yaml): inline `readDoubleQuotedScalar()`

- yaml/_dumper_state.ts
- yaml/stringify_test.ts
**Changes**
This PR changes the error message in `stringifyNode()`.
**Reasoning**
The error will not throw if the value is an object. so `object` should be dropped from the message.
For the same reason, `typeof` should suffice.
> refactor(yaml): change error message in `stringifyNode()`

- async/deadline.ts
Towards https://github.com/denoland/std/issues/5679
> docs(async): add note about `deadline()` `DOMException` name of `TimeoutError`

- yaml/_type/pairs.ts
**Changes**
This PR simplifies the pair `construct()` function and adds correct types.
> refactor(yaml): simplify pair `construct()` function

- yaml/_type/omap.ts
**Changes**
Simplifies the resolve algorithm.
> refactor(yaml): simplify omap `resolve()`

- yaml/_loader_state.ts
> refactor(yaml): inline `readAnchorProperty()`

- assert/rejects.ts
- datetime/_date_time_formatter.ts
- fmt/printf.ts
- io/buf_reader.ts
- io/buf_reader_test.ts
- io/buffer.ts
- streams/buffer.ts
…nstead of `throw`
To ensure consistency across the codebase, this commit refactors the codebase to use `throw new Error` instead of `throw` for throwing errors.
https://github.com/denoland/std/issues/5854
> refactor(assert,datetime,fmt,io,streams): consistently `throw new Error()` instead of `throw Error()`

- yaml/_loader_state.ts
> refactor(yaml): inline `readAlias()`

- http/negotiation.ts
Currently the http negotiation methods are arbitrarily restrictive on what objects can be passed to the methods. It requires a Fetch API request object, when in fact it only requires a very specific type in the code.  Setting overly restrictive types reduces compatibility and should be avoided.
Prior to 1.0 of std/http this was a case, but was changed for some reason causing downstream regressions in dependent code. Please consider expressing minimally restrictive types that actually reflect what the code is dependent upon.
> fix(http): less restrictive arguments for `accepts*()` functions

- dotenv/stringify.ts
- dotenv/stringify_test.ts
Currently, stringify has a bug to parse JSON string.
Here is an example:
```ts
input { FOO: "{'key': 'value'}" }
input_stringify FOO='{\'key\': \'value\'}'
parsed_input { FOO: "{\\" }
```
After fix
```ts
input { FOO: "{'key': 'value'}" }
input_stringify FOO="{'key': 'value'}"
parsed_input { FOO: "{'key': 'value'}" }
```
Codebase to test
```ts
const input = { FOO: "{'key': 'value'}" };
const input_stringify = dotenv.stringify(input);
const parsed_input = dotenv.parse(input_stringify);
console.log("input", input);
console.log("input_stringify", input_stringify);
console.log("parsed_input", parsed_input);
```
> fix(dotenv): handle single-quotes in values in `stringify()`

- yaml/_dumper_state.ts
**Changes**
This PR moves `duplicate` and `duplicateIndex` code inside `isObject()` block, to avoid double check.
**Note** One line `(tag !== null && tag !== "?")` is not covered. Seems like tag is always null if the value is an object.
> refactor(yaml): move `duplicate` and `duplicateIndex`

- cache/memoize_test.ts
Fixes this: https://github.com/denoland/std/actions/runs/10625661936/job/29455981411?pr=5626
```
ERRORS 
memoize() is performant for expensive fibonacci function => ./cache/memoize_test.ts:65:6
error: AssertionError: Expected actual: "1724984137590" to be close to "1724984137573": delta "17" is greater than "10".
throw new AssertionError(
^
at assertAlmostEquals (file:///D:/a/std/std/assert/almost_equals.ts:51:9)
at file:///D:/a/std/std/cache/memoize_test.ts:73:3
FAILURES 
```
> fix(cache/unstable): fix flaky fibonacci test

- path/join.ts
- path/join_test.ts
- path/posix/join.ts
- path/windows/join.ts
part of #5537
This PR adds support of URL as the first parameter of `join`
> feat(path/unstable): support `URL` in first arg of `join()`

- io/buf_reader.ts
- io/read_int.ts
- io/read_long.ts
- io/read_short.ts
> fix(io): don't use `Deno.Buffer` in examples

- yaml/_dumper_state.ts
- yaml/stringify_test.ts
**Changes**
This PR adds test for invalid represent type value.
It also changes the function code to throw early.
> test(yaml): add invalid `represent` type test

- yaml/_dumper_state.ts
- yaml/stringify_test.ts
**Changes**
This PR fixes the `sortKey` error message with template string and adds a test.
⚠️ **Note**
Instead of throwing an error, we might want to remove this type check completely, because it should be covered by typescript.
```ts
if (typeof this.sortKeys === "function") {
objectKeyList.sort(this.sortKeys);
} else if (this.sortKeys) {
objectKeyList.sort();
}
```
WDYT?
> fix(yaml): fix `sortKey` error message

- async/retry.ts
- async/retry_test.ts
- csv/_io.ts
- csv/parse_stream.ts
- csv/parse_stream_test.ts
- fmt/duration.ts
- fmt/duration_test.ts
Related https://github.com/denoland/std/pull/5892#discussion_r1741451494
When using spread syntax or `Object.assign`, if a property with `undefined` is passed, overrides it.
```js
const options = { foo: undefined };
const spreaded = { foo: 1, ...options };
// => { foo: undefined }
const assigned = Object.assign({ foo: 1 }, options);
// => { foo: undefined }
```
This PR solves that problem by delaying the assignment of default values.
> fix(async,csv,fmt): assign default value when `undefined` is passed

- yaml/_type/bool.ts
- yaml/stringify_test.ts
Closing https://github.com/denoland/std/issues/5857
**Note**
This PR also adds and restructures tests for boolean values and instances for more clarity.
> fix(yaml): handle Boolean instances

- yaml/_dumper_state.ts
**Changes**
This PR switches the blocks so `Array.isArray()` test is positive not negative.
> refactor(yaml): switch array test

- yaml/_dumper_state.ts
- yaml/stringify_test.ts
Ref: https://github.com/denoland/std/issues/5857
**Note**
It seems weird to handle special treat strings in `stringifyNode()`. Maybe there is a way to move the evaluation inside `Type.predicate` like other types in a future PR.
> fix(yaml): handle string instances

- path/basename.ts
- path/basename_test.ts
- path/posix/basename.ts
- path/windows/basename.ts
> feat(path/unstable): support `URL` as 1st arg of `basename()`

- path/normalize.ts
- path/normalize_test.ts
- path/posix/normalize.ts
- path/windows/normalize.ts
This PR support file URL as 1st arg of `normalize` function.
related #5537
> feat(path/unstable): support file `URL` arg in `normalize()`

- path/basename.ts
- path/dirname.ts
- path/extname.ts
- path/posix/basename.ts
- path/posix/dirname.ts
- path/posix/extname.ts
- path/posix/join.ts
- path/windows/basename.ts
- path/windows/dirname.ts
- path/windows/extname.ts
- path/windows/join.ts
This PR changes the (unstable) 2nd overloads of `basename`, `dirname`, and `extname` to accept `string | URL` type. Now the 2nd overloads show how the APIs look like when they are stabilized . This also reduces the internal use of `any` types.
related: #5537
> fix(path/unstable): support `string | URL` in the 2nd overload of `basename`, `dirname`, and `extname`

- url/basename.ts
- url/dirname.ts
- url/extname.ts
- url/join.ts
- url/normalize.ts
Now these `path` APIs directly support file URL input, and deprecation notes can be simplified.
> docs(url): update deprecation docs

- data_structures/bidirectional_map.ts
- data_structures/bidirectional_map_test.ts
- data_structures/deno.json
- data_structures/mod.ts
Adds `BidirectionalMap` class to data structures. An extension of `Map` that supports two-way lookups between keys and values. All methods of `Map` are supported.
Automatically updates entries when a key or value already exists, ensuring no duplicates 
for either.
Closes #5736
> feat(data-structures/unstable): `@std/data-structures/bidirectional-map`

- http/file_server.ts
This PR shows hostname as `localhost` on windows when the server listens at `0.0.0.0`.
This substitution of the hostname used to be done by CLI, but we stopped doing that when `onListen` handler is set in https://github.com/denoland/deno/pull/24777
> fix(http): show hostname as 'localhost' for 0.0.0.0 on windows

- http/file_server.ts
This PR inlines `serveFallback` util in file_server.
This PR also removes the handling of `URIError`. This error can't happen now because `url` is taken from `request.url` which should be always a valid url.
This prepares for the implementation of #5875
> refactor(http): inline `serveFallback()` util

- assert/equal.ts
Realized it's no longer necessary due to using the `symmetricDifference` extra-fast-path for sets.
> refactor(assert): remove unnecessary `getValFromKeyedCollection()`

- assert/equal.ts
- assert/equal_test.ts
Split from https://github.com/denoland/std/pull/5913. As with that PR, I haven't yet made any corresponding changes for `expect`.
Fixes (?) https://github.com/denoland/std/issues/5912 (not 100% sure it will be fixed for every possible edge case though)
> fix(assert): value-equal complex keys

- assert/equals.ts
- assert/strict_equals.ts
- expect/_build_message.ts
This PR changes import specifiers for `@std/internal` more specific to avoid unnecessary dependencies included after #5901 landed.
#5901 introduces a new `@std/internal` API which are not necessary for these APIs.
> refactor(assert,expect): import internal APIs from more specific paths

- http/file_server.ts
Before (invalid):
```sh
http://::1:8000
```
After:
```sh
http://[::1]:8000
```
> fix(http): invalid ipv6 hostname printed to console

- io/types.ts
After an offline chat with Bartek, we'll be removing `Deno.Seeker[Sync]`, which should've been a part of https://github.com/denoland/deno/issues/9795.
> feat(io): add `Seeker[Sync]` interfaces

- _tools/check_mod_exports.ts
- assert/deno.json
- assert/mod.ts
- assert/unstable_never.ts
- assert/unstable_never_test.ts
part of #5920
This PR moves `assertNever` under the export path `assert/unstable-never`
> refactor(assert): move unstable `assertNever` under `@std/assert/unstable-never`

- expect/_equal.ts
- expect/_equal_test.ts
Same as https://github.com/denoland/std/pull/5914/ but for `expect`
> fix(expect): value-equal complex keys in `expect.equal()`

- net/get_network_address.ts
hi
dont know why but on my machine I have a loopback IP starting with `10.`
which is wrongly found as my local IP when using `getNetworkAddress()` 
loopback link usually don't have any physical interface so we can safely skip empty mac address `00:00:00:00:00:00`
Fixes #5933
> fix(net): skip empty mac address for `getNetworkAddress()`

- internal/_is_deno_2.ts
I'd previously forgot about `Deno.version`.
> chore: cleanup `IS_DENO_2` constant

- archive/untar.ts
- io/read_range.ts
- io/read_range_test.ts
Once a new version of `std` is published, unblocks https://github.com/denoland/deno/pull/25551.
> refactor(archive,io): use `Seeker[Sync]` from `@std/io/types`

- _tools/check_docs.ts
- data_structures/deno.json
- data_structures/mod.ts
- data_structures/unstable_bidirectional_map.ts
- data_structures/unstable_bidirectional_map_test.ts
> BREAKING(data-structures/unstable): move `bidirectional-map` module to `unstable-bidirectional-map`

- _tools/check_docs.ts
- html/deno.json
- html/mod.ts
- html/unstable_is_valid_custom_element_name.ts
- html/unstable_is_valid_custom_element_name_test.ts
> BREAKING(html/unstable): move `is-valid-custom-element-name` module to `unstable-is-valid-custom-element-name`

- _tools/check_docs.ts
- streams/deno.json
- streams/mod.ts
- streams/unstable_to_lines.ts
- streams/unstable_to_lines_test.ts
> BREAKING(streams/unstable): move `to-lines` module to `unstable-to-lines`

- _tools/check_docs.ts
- http/file_server.ts
- net/deno.json
- net/mod.ts
- net/unstable_get_network_address.ts
- net/unstable_get_network_address_test.ts
> BREAKING(net/unstable): move `get-network-address` module to `unstable-get-network-address`

- _tools/check_docs.ts
- text/deno.json
- text/mod.ts
- text/unstable_to_constant_case.ts
- text/unstable_to_constant_case_test.ts
> BREAKING(text/unstable): move `to-constant-case` module to `unstable-to-constant-case`

- _tools/check_docs.ts
- path/deno.json
- path/dirname.ts
- path/dirname_test.ts
- path/posix/dirname.ts
- path/posix/unstable_dirname.ts
- path/unstable_dirname.ts
- path/windows/dirname.ts
- path/windows/unstable_dirname.ts
part of #5920 
This PR moves the 2nd overload of `dirname` functions to `./unstable-dirname`.
Unstable versions of `dirname` functions are only available from `unstable-dirname`, `posix/unstable-dirname`, or `windows/unstable-dirname`.
If this looks fine, I'll work on the rest of items in `@std/path`
> BREAKING(path/unstable): move unstable overload of `dirname` to `unstable-dirname`

- _tools/check_docs.ts
- encoding/deno.json
- encoding/mod.ts
- encoding/unstable_base32_stream.ts
- encoding/unstable_base32_stream_test.ts
> BREAKING(encoding/unstable): move `base32-stream` module to `unstable-base32-stream`

- path/basename.ts
- path/basename_test.ts
- path/deno.json
- path/posix/basename.ts
- path/posix/unstable_basename.ts
- path/unstable_basename.ts
- path/windows/basename.ts
- path/windows/unstable_basename.ts
part of #5920 
This PR moves the unstable overload of `basename` to `unstable-basename`
> BREAKING(path/unstable): move unstable overload of `basename` to `unstable-basename`

- _tools/check_docs.ts
- encoding/deno.json
- encoding/mod.ts
- encoding/unstable_hex_stream.ts
- encoding/unstable_hex_stream_test.ts
> BREAKING(encoding/unstable): move `hex-stream` module to `unstable-hex-stream`

- net/unstable_get_network_address_test.ts
This PR adds a test fixture to exercise the fix #5941
> test(net): add test of `getNetworkAddress()`

- collections/pick.ts
- collections/pick_test.ts
> fix(collections): ensure `pick` doesn't generate missing properties as `undefined`

- _tools/check_docs.ts
- path/deno.json
- path/join.ts
- path/join_test.ts
- path/posix/join.ts
- path/posix/unstable_join.ts
- path/unstable_join.ts
- path/windows/join.ts
- path/windows/unstable_join.ts
part of #5920 
This PR moves the unstable overload of `join` function to `unstable-join` module.
> BREAKING(path/unstable): move unstable overload of `join` to `unstable-join`

- _tools/check_docs.ts
- front_matter/deno.json
- front_matter/unstable_yaml.ts
- front_matter/yaml_test.ts
part of #5920 
This PR moves the unstable overload of yaml's `extract` function to `unstable-yaml`.
> BREAKING(front-matter/unstable): move unstable overload of yaml `extract` to `unstable-yaml`

- _tools/check_docs.ts
- path/deno.json
- path/normalize_test.ts
- path/posix/normalize.ts
- path/posix/unstable_normalize.ts
- path/unstable_normalize.ts
- path/windows/normalize.ts
- path/windows/unstable_normalize.ts
part of #5920 
This PR moves unstable overload of `normalize` function to `unstable-normalize`.
> BREAKING(path/unstable): move unstable overload of `normalize` to `unstable-normalize`

- import_map.json
- tar/deno.json
We recently moved `@std/streams/fixed-chunk-stream` to `@std/streams/unstable-fixed-chunk-stream` in #5951. However, we forgot to update `@std/tar` accordingly. So now, `UntarStream` is unusable on the latest release. This PR fixes that. I'm sure there are other packages with the same issue.
> fix(tar): update to `0.1.1`

- archive/mod.ts
- archive/tar.ts
- log/mod.ts
- testing/__snapshots__/snapshot_test.ts.snap
- testing/bdd_test.ts
- testing/snapshot.ts
- testing/snapshot_test.ts
* Use the American spelling of colors in docs for consistency with module and option names
* Replace a few incorrect usages of it's
> docs(archive,log,testing): correct typos

- fs/exists.ts
`--allow-sys` is required as [`Deno.uid()`](https://docs.deno.com/api/deno/~/Deno.uid) and [`Deno.gid()`](https://docs.deno.com/api/deno/~/Deno.gid) are called when `options.isReadable = true`, which both require `--allow-sys` permissions.
Closes #5977
> docs(fs): clarify permissions requirements for `exists[Sync]()`

- archive/_common.ts
- archive/mod.ts
- archive/tar.ts
- archive/untar.ts
This package is being superceded by `@std/tar`.
Towards #5986
> deprecation(archive/unstable): deprecate `@std/archive`

- io/read_lines.ts
> deprecation(io/unstable): deprecate `readLines()`

- io/copy_n.ts
> deprecation(io/unstable): deprecate `copyN()`

- io/read_string_delim.ts
> deprecation(io/unstable): deprecate `readStringDelim()`

- assert/instance_of.ts
- assert/instance_of_test.ts
- assert/is_error.ts
- assert/is_error_test.ts
- assert/not_instance_of.ts
- assert/not_instance_of_test.ts
- assert/rejects.ts
- assert/rejects_test.ts
- assert/throws.ts
- assert/throws_test.ts
Makes this work:
```ts
import { assertInstanceOf } from "jsr:@std/assert/instance-of";
assertInstanceOf([].values(), Iterator);
```
> fix(assert): accept abstract classes

- io/slice_long_to_bytes.ts
This will be removed without replacement.
Towards #5989
> deprecation(io/unstable): deprecate `sliceLongToBytes()`

- http/unstable_route.ts
- http/unstable_route_test.ts
This is an approach for https://github.com/denoland/std/issues/5993#issuecomment-2355224277.
It allows the `method` option to accept a `string | string[]` value type. It's more convenient for some similar handlers.
Here are some examples:
```ts
const route: Route[] = [
{
method: ["GET", "HEAD"],
pattern: new URLPattern({ pathname: '/status' }),
handler: (req: Request) => new Response(req.method === 'HEAD' ? null : 'ok'),
},
]
```
```ts
const route: Route[] = [
{
method: ["POST", "UPDATE", "DELETE", ...somethingElse],
pattern: new URLPattern({ pathname: '/users/:id' }),
handler: (req: Request) => {
prepareSomething();
switch (req.method) {
case "POST":
createUser();
break;
case "UPDATE":
updateUser();
break;
case "DELETE":
deleteUser();
break;
default:
runSomethingElse();
break;
}
const …
```
> feat(http/unstable): add support for multiple request methods on route

- io/read_short.ts
This will be removed without replacement.
Towards #5989
> deprecation(io/unstable): deprecate `readShort()`

- io/read_int.ts
This will be removed without replacement.
Towards #5989.
> deprecation(io/unstable): deprecate `readInt()`

- io/read_range.ts
> deprecation(io/unstable): deprecate `readRange()`

- io/read_long.ts
This will be removed without replacement.
Towards #5989
> deprecation(io/unstable): deprecate `readLong()`

- archive/_common.ts
- archive/mod.ts
- archive/tar.ts
- archive/untar.ts
This is based on the next version of `@std/archive` being 0.225.4.
> docs(archive): update `@std/archive` deprecation notices

- text/levenshtein_distance.ts
- text/levenshtein_distance_test.ts
Fixes https://github.com/denoland/std/issues/6013
> fix(text): handle code points > U+FFFF in `levenshteinDistance`

- http/_negotiation/encoding.ts
- http/cookie.ts
- http/cookie_test.ts
- http/negotiation_test.ts
Towards https://github.com/denoland/std/issues/6016
Doesn't include a fix for the various `text` functions as it's less obvious there what the correct fix should be (e.g. should a configurable `locale` option be added?)
> fix(http): use non-locale-sensitive string methods for comparison

- http/file_server.ts
Because `Deno.permissions.querySync` is not a defined function in the deploy environment.
Conditionally call `Deno.permissions.querySync` and nullish coalesce to “granted” for network access.
> fix(http): make `file-server` work on Deno Deploy

- io/read_delim.ts
> deprecation(io/unstable): deprecate `readDelim()`

- io/multi_reader.ts
> deprecation(io/unstable): deprecate `MultiReader`

- io/string_writer.ts
> deprecation(io/unstable): deprecate `StringWriter`

- io/buf_reader.ts
> deprecation(io/unstable): deprecate `BufReader`

- http/mod.ts
- http/unstable_route.ts
This adds an example of the multiple request methods on route definition.
> docs(http/unstable): add example for multiple request methods on route

- Releases.md
This line was manually modified during [the release](https://github.com/denoland/std/pull/6043), and this heading level should have been `H4` instead of `H3`
> chore: fix heading level in Releases.md

- _tools/check_docs.ts
- log/base_handler.ts
- log/base_handler_test.ts
- log/levels.ts
- log/logger.ts
> docs(log): document `BaseHandler`

- log/debug.ts
This PR fixes the error that has occurred since https://github.com/denoland/std/commit/827fe95620fda2e3426189f80e754fac67e09898.
> docs(log): correct the examples of `debug()`

- log/console_handler.ts
There doesn't appear to be a reason for this to be a method on the `ConsoleHandler` class. This move avoids the need to document it as a method.
> fix(log): remove leaky `ConsoleHandler.prototype.applyColors()`

- expect/expect.ts
> fix(expect): register extended matchers after native matchers

- _tools/check_docs.ts
- log/get_logger.ts
- log/logger.ts
> docs(log): document `getLogger()` and `Logger`

- collections/_utils_test.ts
Add testing to the uncovered `filterInPlace` util function. Brings collections to 100% coverage
> test(collections): add tests for `filterInPlace()` util

- collections/deno.json
- collections/unstable_take_last_while.ts
- collections/unstable_take_last_while_test.ts
Create a backwards compatible unstable version of `takeLastWhile()` that accepts an iterable instead of arrays.
The array version is significantly more performant, so adding a special case for when the iterable is an array.
#5470
> feat(collections/unstable): support `Iterable` argument in `takeLastWhile()`

- cbor/encode_cbor_sequence.ts
The relative import from `"../bytes/concat.ts"` does not work when publishing to JSR
> fix(cbor): fix module specifier in import

- json/parse_stream.ts
Found a small typo with checking if a string is blank.
> refactor(json): fix typo

- path/posix/basename.ts
- path/posix/dirname.ts
- path/posix/extname.ts
- path/posix/join.ts
- path/posix/mod.ts
- path/posix/normalize.ts
I'm not sure if this was intentional, but the documentation added regarding URL manipulation with the `@std/path/posix` module in #5371 was inadvertently removed in #5900 and #5904.
It seems like the methods that accept a URL object are still in unstable and the [current docs](https://jsr.io/@std/url) for `@std/url` link to the `@std/path/posix` module, so I think it might be a good idea to re-add these examples.
> docs(path): re-add URL examples to `@std/path/posix` examples

- cbor/text_encoder_stream_test.ts
Closes: https://github.com/denoland/std/issues/6102
The expected result was filtering out empty strings provided in the input text, while `CborTextEncoderStream` doesn't remove them. The test appeared flaky because of the randomness of the test. In the event the first random chose zero (which is a 1 in 24 chance), an empty string would be one of the chunks. An empty string is encoded as byte 96. 
Lowering the size of the strings had no effect on the flakiness of the tests, but I am assuming that's why they were lowered in the first place.
> test(cbor): empty string being excluded from expected result

- cbor/decode_cbor_test.ts
Fixes: https://github.com/denoland/std/actions/runs/11310597614/job/31455830417#step:4:1
Due to the way JavaScript numbers work, numbers past `2 ** 53` lose precision. Weirdly though sometimes when converting them to BigInts they may gain more precision than they originally had.
> fix(cbor): number precision error in decoding test

- tar/mod.ts
- tar/untar_stream.ts
This pull request fixes a highly probable bug in the JSDocs example where if the directory already exists, it throws an error, or if the directory's directory doesn't exist, it throws an error.
> docs(tar): fix example in creating directories

- http/user_agent.ts
I believe two of the literal types for `Device.type` have typos. The `const` values being returned are correct, but attempting a comparison like `device.type === 'tablet'` currently errors.
```ts
error: TS2367 [ERROR]: This comparison appears to be unintentional because the types '"console" | "mobile" | "table" | "smartv" | "wearable" | "embedded" | undefined' and '"tablet"' have no overlap.
export const isTablet = (device: Device) => device.type === 'tablet'
~~~~~~~~~~~~~~~~~~~~~~~~
```
`"table"` should be `"table[t]"` and `"smartv"` should be `"smart[t]v"`.
This PR fixes the two typos, and adjusts the sort order to match the order of [the `const`'s above](https://github.com/denoland/std/pull/6129/files#diff-9b1df331f9b4a9ec031bf0b92f1fa21a2fa39f771e3c0f89c5ec9bffa619d517L22-L27) to make …
> fix(http): fix tablet and smarttv in Device.type literal types

- async/deno.json
- async/unstable_throttle.ts
- async/unstable_throttle_test.ts
> feat(async/unstable): add `throttle()` function

- fmt/bytes_test.ts
In some locales there is no group separator in parts which cause error during tests.
```ts
const parts = new Intl.NumberFormat().formatToParts(1000.1);
console.log(parts);
const group = parts.find(({ type }) => type === "group")!.value;
```
```
[
{ type: "integer", value: "1000" },
{ type: "decimal", value: "," },   
{ type: "fraction", value: "1" }   
]
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
const group = parts.find(({ type }) => type === "group")!.value;
```
Change to 10000.1 fix this issue.
```typescript
const parts = new Intl.NumberFormat().formatToParts(10000.1);
console.log(parts);
const group = parts.find(({ type }) => type === "group")!.value;
```
```ts
[
{ type: "integer", value: "10" },
{ type: "group", value: " " },
{ type: …
```
> test(fmt): handle missing group separator for 1000.1 in some locales

- fs/copy.ts
- fs/ensure_symlink.ts
- fs/eol.ts
- fs/expand_glob.ts
> refactor(fs): uncaught FS errors in web

- expect/_array_containing_test.ts
- expect/_asymmetric_matchers.ts
- expect/_object_containing_test.ts
- expect/_string_containing_test.ts
- expect/_string_matching_test.ts
- expect/expect.ts
- expect/mod.ts
Part of https://github.com/denoland/std/issues/3964, support:
* expect.not.arrayContaining 
* expect.not.objectContaining 
* expect.not.stringContaining
* expect.not.stringMatching
> fix(expect): support expect.not.{arrayContaining,objectContaning,stringContaining,stringMatching}

- _tools/check_docs.ts
- streams/early_zip_readable_streams.ts
- streams/zip_readable_streams.ts
Currently, rest arguments are not being asserted when `lint:docs` is run. This PR fixes the issue and adds missing `@param`   field to docs.
> docs(streams): rest arguments not being asserted in docs

- async/unstable_throttle.ts
> test(async): fix flakiness of throttle example

- _tools/check_docs.ts
- path/posix/join_globs.ts
- path/posix/normalize_glob.ts
- path/windows/join_globs.ts
- path/windows/normalize_glob.ts
Implements #5439
This implementation doesn't go well with unnamed parameters (see the other changes in `path/*`). IMO, this is ok. As named parameters and Jsdoc param names go hand in hand, especially considering these are public APIs. Also, immediately on implementation, this helped me uncover some unused fields in the same functions. I'm curious on your opinions on this.
> refactor(path): always name the parameters (add param definition check in doc linter)

- bytes/ends_with_test.ts
- bytes/equals_test.ts
- bytes/starts_with_test.ts
Current tests are kinda confusing and unclear what's being tested. It could help resolve confusion like https://github.com/denoland/std/issues/6146 if there was a specific test case (`` startsWith() ... `true` where `source` starts with `prefix` ``) that could be pointed to as failing upon the proposed change.
> test(bytes): document the cases being tested for equals/startsWith/endsWith

- media_types/vendor/db.ts
This change updates media_types by running `deno run media_types/vendor/update.ts`
This helps adding new mimetypes (I was specially looking for jxl image mimetype)
> feat(media-types): update media-types from latest mime-db

- _tools/check_docs.ts
- log/file_handler.ts
Documents `FileHandler` for #3764
> docs(log): document FileHandler

- expect/_serializer.ts
- expect/_serializer_test.ts
- expect/_types.ts
- expect/expect.ts
- expect/mod.ts
Part of #3964, support `expect.addSnapshotSerializer` api.
> fix(expect): support `expect.addSnapshotSerializer`

- ini/_ini_map.ts
- ini/mod.ts
- ini/parse_test.ts
- ini/stringify_test.ts
> BREAKING(ini): parse understands booleans, undefined, null and numbers

- _tools/check_docs.ts
- log/logger.ts
Gets us closer to #3764 
The file was already very well documented, it was just missing a few things
> docs(log): improve logger.ts docs

- bytes/index_of_needle_test.ts
- bytes/last_index_of_needle_test.ts
> test(bytes): fix typo in test description

- http/file_server.ts
- http/file_server_test.ts
Currently file server serves dot files even when `showDotfiles=false` specified. This PR changes it to not serve dot files when `showDotfiles=false`.
> fix(http): do not serve dot files when `showDotfiles=false`

- http/etag_test.ts
- http/file_server_test.ts
`FileInfo` type has been updated in this commit ( https://github.com/denoland/deno/commit/7becd83a3828b35331d0fcb82c64146e520f154b ), and now this test fixture needs to be updated
> chore: update FileInfo fixture

- log/file_handler.ts
`std/log/file-handler` examples generate `logs.txt` and it makes the repository modified state. That leads to the publishing failure https://github.com/denoland/std/actions/runs/11815536146/job/32916891866
This PR fixes the situation by ignoring examples in doc testing.
> chore(log): do not exec file handler examples in CI

- .github/workflows/ci.yml
This PR updates the CI workflow to check `publish --dry-run` after test runs.
This prevents the case like 2024.11.13 release ( https://github.com/denoland/std/actions/runs/11815536146/job/32916891866 ), which failed because the git repository state became dirty after the test run and CI didn't detect it
> chore: check publish --dry-run after testing

- assert/equals.ts
This PR improves the documentation for the `assertEquals` function by addressing how to compare `Blob` objects.
Fixes #6202
> docs(assert): add note and example for Blob comparison

- cli/deno.json
`promptSelect()` has been added in #6190, but it does not seem to be exported. This PR exports it.
> feat(cli/unstable): export `/unstable-prompt-select`

- text/_util.ts
- text/_util_test.ts
- text/to_camel_case.ts
- text/to_kebab_case.ts
- text/to_snake_case.ts
- text/unstable_to_constant_case.ts
> fix(text): use locale-independent letter case methods (#6016)

- dotenv/parse.ts
- dotenv/parse_test.ts
- dotenv/testdata/.env.test
Current env parser do not support `.env` files with `\r\n` line break.
fixes #6170
> fix(dotenv): handle multiline variables on Windows

- cli/unstable_prompt_select.ts
- cli/unstable_prompt_select_test.ts
This PR moves the cursor to the selected line instead of always staying at the bottom.
> fix(cli/unstable): hide cursor while showing the selection with `promptSelect()`

- expect/_matchers.ts
- expect/_to_match_object_test.ts
Matcher `toMatchObject` throws the same error message when it called with `.not` and without `.not`.
Without `.not`:
```ts
it("toMatchObject without not", () => {
expect({ foo: 0 }).toMatchObject({ foo: 1 });
});
```
Error:
```
error: AssertionError: Expected {
foo: 0,
} to NOT match {
foo: 1,
}
```
With `.not`:
```ts
it("toMatchObject with not", () => {
expect({ foo: 0 }).not.toMatchObject({ foo: 0 });
});
```
Error:
```
error: AssertionError: Expected {
foo: 0,
} to NOT match {
foo: 0,
}
```
Fixes #6224
> fix(expect): fix error messages for `toMatchObject`

- http/mod.ts
- http/unstable_route.ts
- http/unstable_route_test.ts
Closes  #5884
Not sure if it qualifies for "breaking change" since the API is still unstable, but it does break apps relying on current implementation `route()`
As explained in the linked issue, since `params: URLPatternResult` is way more likely to be used than `info: Deno.ServeHandlerInfo` in non-default handlers, it makes sense to switch them for improved DX
> BREAKING(http/unstable): switch `params` and `info` args in `Handler` in `route()` for more conveniency

- testing/_test_suite.ts
- testing/bdd_test.ts
In the current implementation, code inside a `describe` block is executed in every case, even when `describe.ignore` or `describe.skip` is used. This behavior is reflected in the following example and is currently tested as expected behavior:
Code:
```ts
describe.ignore("should ignore", () => {
assert(false);
});
```
Error:
```sh
Uncaught error from ./main.ts FAILED
ERRORS 
./main.ts (uncaught error)
error: (in promise) AssertionError
throw new AssertionError(msg);
^
```
This happens because the describe block is treated as a list of steps rather than as a single step itself. In my implementation, all code inside a describe.ignore block is ignored.
Fixes #6233
> fix(testing): stop code execution in `describe.ignore`

- regexp/escape.ts
- regexp/escape_test.ts
This PR updates `escape` of `@std/regexp`. Now `escape` escapes the leading digit as recommended in #3656. This behavior is aligned with regexp-escape proposal ( https://github.com/tc39/proposal-regex-escaping, polyfill: https://npm.im/regexp.escape )
closes #3656
> fix(regexp): escape leading digit

- .github/workflows/ci.yml
This PR add the CI step, which upload the html coverage report to Deploy on every push to main branch and host them using `jsr:@std/http/file-server`.
The builtin html coverage report of std test will be visible at https://std-coverage.deno.dev/ after the successful upload.
closes #5982
> chore: upload code coverage report to Deploy

- .github/workflows/ci.yml
Currently `deployctl` action seems failing because of permission error. https://github.com/denoland/std/actions/runs/12268957111/job/34231703522
This PR should fix it.
Note: `contents: write` permission is already given at top-level.
> chore: fix gha permission for deployctl action

- cbor/_common_decode.ts
- cbor/_common_encode.ts
- cbor/decode_cbor.ts
- cbor/decode_cbor_sequence.ts
- cbor/decode_cbor_test.ts
- cbor/encode_cbor.ts
- cbor/encode_cbor_sequence.ts
- cbor/encode_cbor_test.ts
- cbor/types.ts
Closes: https://github.com/denoland/std/issues/6249
These changes adds support for accepting a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instance in `encodeCbor` and returning it again from `decodeCbor`. It achieves this via the [259 tag number](https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml) ([Spec](https://github.com/shanewholloway/js-cbor-codec/blob/master/docs/CBOR-259-spec--explicit-maps.md)). 
While the code is mostly the same for encoding and decoding Objects, it differs in the need for limiting keys to only strings. It also guarantees that the order isn't at risk of being changed due to encoding/decoding.
This pull request does not add support for accepting Map instances via the streaming methods of this library. The …
> feat(cbor): add encoding/decoding for `new Map()` instance

- _tools/node_test_runner/run_test.mjs
- fs/_map_error.ts
- fs/_to_file_info.ts
- fs/_utils.ts
- fs/deno.json
- fs/unstable_errors.d.ts
- fs/unstable_errors.js
- fs/unstable_stat.ts
- fs/unstable_stat_test.ts
- fs/unstable_types.ts
This PR adds `stat` API, which mostly mirrors `Deno.stat`, to `@std/fs`.
towards #6255
> feat(fs/unstable): add `fs.stat`

- cli/unstable_prompt_select.ts
- cli/unstable_prompt_select_test.ts
ref https://github.com/denoland/std/pull/6257
> fix(cli/unstable): `promptSelect()` add `isTerminal()` check

- cli/parse_args.ts
This PR removes all `parseArgs()` console logs and adds a constant declaration instead. This is how it is done in other examples and also prevents logs when calling `deno task test`.
> docs(cli): remove `parseArgs()` console logs from examples

- log/logger.ts
Hello.
This pull request fixes the assertion in the `LogRecord` class test to correctly check the level name. The original assertion was checking `loggerName`, but I believe it should verify `levelName` instead.
> docs(log): fix level name assertion in LogRecord example

- data_structures/binary_search_tree.ts
- data_structures/binary_search_tree_test.ts
Previously, when cloning an existing BinarySearchTree using the static from method, the new tree’s #size field was not updated, leading to a mismatch between the reported size and the actual number of nodes. This commit addresses the issue by directly assigning the original tree’s #size to the new instance after copying all nodes.
Additional tests have been added to verify that size remains accurate and consistent following the cloning process.
> fix(data-structures): ensure size consistency in BinarySearchTree.from

- expect/_array_containing_test.ts
- expect/_asymmetric_matchers.ts
This pr is to fix https://github.com/denoland/std/issues/6243.
> fix(expect): Fix `expect.arrayContaining` bug

- fs/unstable_stat.ts
The code example in the stat function imports the `stat` function but uses `Deno.stat` instead of `stat`.
> fix(fs): use `stat` function in `stat` example

- expect/_types.ts
I was looking for a more pedestrian matcher, that would assert a number being [within](https://jest-extended.jestcommunity.dev/docs/matchers/Number#tobewithinstart-end) a range, or ±X of the expected value. Clarified `toBeCloseTo` as useful for avoiding floating point precision errors instead.
> docs(expect): clarify the tolerance in `toBeCloseTo`

- fs/empty_dir_test.ts
- fs/ensure_dir_test.ts
- fs/ensure_file_test.ts
- fs/ensure_link_test.ts
- fs/ensure_symlink_test.ts
- fs/move_test.ts
- fs/testdata/empty_dir.ts
- fs/testdata/empty_dir_sync.ts
- fs/walk_test.ts
This pull request addresses the issue of files and directories being created and written into the source tree while testing functions in the `fs` package. Creation of temporary directories were incorporated into the existing tests where applicable.    
Fixes #5358 .
> test(fs): do not write files in source tree during test

- fmt/duration.ts
- fmt/duration_test.ts
> fix(fmt): add correct pluralization to fmt/duration when using style: full

- datetime/format.ts
Fixes a trivial oversight in the docs that was missed in 4ec7dd4be99049e6721d4bf41b5a4d3ded7770b2 (#5647)
> docs(datetime): remove outdated mention of `utc` option

- data_structures/_binary_search_tree_internals.ts
- data_structures/binary_search_tree.ts
- data_structures/red_black_tree.ts
- data_structures/red_black_tree_test.ts
Previously, when cloning an existing RedBlackTree using the static from method, the new tree’s #size field was not updated, leading to a mismatch between the reported size and the actual number of nodes. This commit addresses the issue by directly assigning the original tree’s #size to the new instance after copying all nodes.
Additional tests have been added to verify that size remains accurate and consistent following the cloning process.
> fix(data-structures): ensure size consistency in RedBlackTree.from

- cli/parse_args.ts
This PR adds the example usages of `parseArgs`
closes #6261
> docs(cli): add examples of parseArgs

- .gitignore
- _tools/check_docs.ts
- _tools/check_licence.ts
- log/file_handler.ts
This PR re-enables doc tests that were disabled in #6183. To avoid publication failures, logs for testing are written to `./_tmp`, which is ignored by `.gitignore`. This PR also removes duplicate examples.
> test(log): re-enable doc tests for `FileHandler`

- expect/mod.ts
The jest function is `toMatchSnapshot`, not `toMatchSnapShot`.
> docs(expect): correct minor typo

- expect/expect.ts
- text/unstable_slugify.ts
Per #5728, we want to review the usage of `no-eval`.
These examples pass with `no-eval` removed, so we might as well remove them.
```
$ deno task test text/unstable_slugify.ts                                                                                                                                                                                                                                                                          
Task test deno test --unstable-http --unstable-webgpu --doc --allow-all --parallel --coverage --trace-leaks --clean "text/unstable_slugify.ts"
Check file:///home/fin/src/std/text/unstable_slugify.ts
Check file:///home/fin/src/std/text/unstable_slugify.ts$25-31.ts
Check file:///home/fin/src/std/text/unstable_slugify.ts$37-43.ts
Check …
```
> docs(expect,text): remove no-eval directives that appear to be unneccessary

- .github/workflows/ci.yml
- _tools/node_test_runner/deno_compat_hooks.mjs
- _tools/node_test_runner/package.json
- collections/max_with.ts
- collections/min_with.ts
- deno.json
This PR starts using native type strip feature of Node.js to run tests in Node, and it fixes the CI on main.
This PR also does some clean ups.
- You can now directly execute `deno task test:node` without running `npm install` in `_tools/node_test_runner` dir beforehand.
> chore: use native type stripping of Node.js in node testing

- csv/unstable_stringify_test.ts
To increase test coverage.
Related to: https://github.com/denoland/std/issues/3713
> test(csv): unstable stringify tests

- .github/workflows/ci.yml
- assert/object_match.ts
- assert/object_match_test.ts
- deno.json
> fix(assert): handle `__proto__` correctly in `assertObjectMatch`

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_chmod.ts
- fs/unstable_chmod_test.ts
This PR adds the `chmod` and `chmodSync` APIs to `@std/fs`, which are functions intended to mirror `Deno.chmod` and `Deno.chmodSync`, respectively.
Towards #6255.
> feat(fs/unstable): add chmod and chmodSync

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_symlink.ts
- fs/unstable_symlink_test.ts
- fs/unstable_types.ts
This PR adds the `symlink` and `symlinkSync` APIs to `@std/fs`, which are functions intended to mirror `Deno.symlink` and `Deno.symlinkSync`, respectively.  The PR also adds the associated `SymlinkOptions` type.
Towards #6255.
> feat(fs/unstable): add symlink and symlinkSync

- async/delay_test.ts
- async/deno.json
- async/unstable_wait_for.ts
- async/unstable_wait_for_test.ts
Submitting PR to contribute `waitFor` function (see #6213). Fixed small type in delay tests as well.
> feat(async/unstable): add `waitFor` function to wait for condition to be true (#6213)

- async/unstable_wait_for.ts
- async/unstable_wait_for_test.ts
- io/read_all.ts
- io/read_all_test.ts
This PR fixes `readAllSync` when the source stream outputs data slowly.
The bug was introduced in #4128 when we rewrite it without using `Buffer` class.
closes #6346
> fix(io): fix readAllSync for the case when read source is slow

- expect/expect.ts
Hi, I was reading the documentation for `expect.objectContaining` and noticed a mistake in the example.
The first expectation is incorrect because the expected value for the key bar does not match the actual value. I've updated the example to reflect the correct behavior.
> docs(expect): fix typo on objectContaining example

- expect/_to_be_close_to_test.ts
This PR adds the test case to check the fix #6291
> test(expect): check error message of `.toBeCloseTo()`

- cli/unstable_spinner.ts
- cli/unstable_spinner_test.ts
Related to #5495
Adds support to the `@std/cli/unstable_spinner` to write to `stderr` instead of the default `stdout`.
The current Spinner is unusable when piping to another command (e.g. `deno_cli | less` for paging). and will cause garbled data to the pipe/console. Using `stderr` is the standard approach for informational text since by default it is not passed along to the piped commands stdin.
NOTE: I personally would be happy to make this the default. I'm curious if folks would be open to this considering it's currently unstable.
An alternative could be to check if the terminal is interactive or not and change the default based on this.
> feat(cli/unstable): support stderr on spinner

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_real_path.ts
- fs/unstable_real_path_test.ts
This PR adds the `realPath`and `realPathSync` APIs to `@std/fs`, which are functions intended to mirror `Deno.realPath` and `Deno.realPathSync`, respectively.
Towards #6255.
> feat(fs/unstable): add realPath and realPathSync

- fmt/printf.ts
- fmt/printf_test.ts
`printf` is not working well with `colors` package.
```bash
➜  ent-std git:(master) ✗ cat test.ts  
import { printf } from "jsr:@std/fmt/printf";
import {underline} from "jsr:@std/fmt/colors";
printf("a: %7s|\n", underline("foo"))
printf("b: %7s|\n", underline("foo bar"))
➜  ent-std git:(master) ✗ deno run -A test.ts
a: foo|
b: foo bar|
```
Add `stripAnsiCode` in `Printf.fmtString` maybe solve this problem.
```bash
➜  std git:(feat/make_printf_working_with_colors) ✗ cat test.ts  
import {printf} from "./fmt/printf.ts";
import {underline} from "./fmt/colors.ts";
printf("a: %7s|\n", underline("foo"))
printf("b: %7s|\n", underline("foo bar"))
➜  std git:(feat/make_printf_working_with_colors) ✗ deno run -A test.ts
a:     foo|
b: foo bar|
```
> fix(fmt): make printf working with colors.

- log/mod.ts
The description on JSR could be updated as well, to mention considering Open Telemetry per #6124.
> docs(log): mention potential deprecation of @std/log

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_link.ts
- fs/unstable_link_test.ts
This PR adds the `link` and `linkSync` APIs to `@std/fs`, which are functions intended to mirror `Deno.link` and `Deno.linkSync`, respectively.
Towards #6255.
> feat(fs/unstable): add link and linkSync

- crypto/crypto.ts
This just clarifies the documentation.
> docs(crypto): clarify doc comment

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_read_link.ts
- fs/unstable_read_link_test.ts
This PR adds the `readLink` and `readLinkSync` APIs to `@std/fs`, which are functions intended to mirror `Deno.readLink` and `Deno.readLinkSync`, respectively.
Towards #6255.
> feat(fs/unstable): add readLink and readLinkSync

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_rename.ts
- fs/unstable_rename_test.ts
This PR adds the `rename` API to `@std/fs`, which is intended to mirror `Deno.rename` function.
Towards #6255.
> feat(fs/unstable): add rename

- front_matter/any.ts
- front_matter/toml.ts
This PR replaces `parser` calls with `extract()` calls.
It also adds a missing type in `front_matter/toml.ts`
> refactor(front-matter): call `extract()` functions in `any.ts`

- _tools/node_test_runner/run_test.mjs
- fs/_utils.ts
- fs/deno.json
- fs/unstable_make_temp_dir.ts
- fs/unstable_make_temp_dir_test.ts
- fs/unstable_types.ts
This PR adds the `makeTempDir` and `makeTempDirSync` APIs to the `@std/fs` package which intends to mirror the `Deno.makeTempDir` and `Deno.makeTempDirSync` functions. The PR also adds the `MakeTempOptions` type and helper functions `getNodeOs` and `getNodePath` in the `_utils.ts` file in preparation for use in future implementations of `@std/fs` APIs: `makeTempFile` and `makeTempFileSync`.
To achieve cross-runtime compatibility with Node.js and satisfy the Deno FS API requirement, the `makeTempDir` and `makeTempDirSync` APIs with `MakeTempOptions` extends functionality for creating temporary directories in Node.js. By adding an optional interface to augment the naming of temporary directory paths, these APIs exist as an alternative to Node-specific APIs that pass a prefix path string …
> feat(fs/unstable): add makeTempDir and makeTempDirSync

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_read_file.ts
- fs/unstable_read_file_test.ts
- fs/unstable_types.ts
This PR adds the `readFile` and `readFileSync` APIs to the `@std/fs` package which intends to mirror `Deno.readFile` and `Deno.readFileSync` functions. The PR also adds the `ReadFileOptions` type in preparation for adding the
`readTextFile` API to the `@std/fs` package.
A question on the documentation of `Deno.readFile` and `Deno.readFileSync`: Is the documentation slightly out of date? Specifically, this line:
> "Reading a directory returns an empty data array."
When attempting to do this on my local machine (MacOS), invoking functions `Deno.readFile` and `Deno.readFileSync` rejected/threw with an `Error` and an error code of `EISDIR` (os errno 21). This is true on Deno v1.46.0, v2.x, and
the latest Node.js AFAIK. For the purposes of the PR, I've assumed this is the intended behavior and …
> feat(fs/unstable): add readFile and readFileSync

- .github/typos.toml
CI started failing at typo in `jsonc/testdata/test262/JSON/parse/15.12.1.1-g2-3.js`. https://github.com/denoland/std/actions/runs/13319999611/job/37206312707
The file is test fixture, and we can skip checking typo in there
> chore: ignore jsonc/testdata from typo check

- fs/unstable_rename.ts
- fs/unstable_rename_test.ts
This PR adds the `renameSync` API to `@std/fs` which is intended to mirror the `Deno.renameSync` function.
Towards #6255.
> feat(fs/unstable): add renameSync

- front_matter/any.ts
It looks like `deno publish` is not happy with these imports. See https://github.com/denoland/std/actions/runs/13324576250/job/37215539410
This PR replaces paths to relative ones to fix the publish pipeline.
> refactor(front-matter): use relative path for importing module in the same package

- cli/unstable_progress_bar.ts
This pull request fixes the simple issue of the interval having the wrong delay of 200ms instead of 1000ms.
> fix(cli): update interval in ProgressBar

- async/unstable_wait_for_test.ts
ref: https://github.com/denoland/std/actions/runs/13358554953/job/37304692671?pr=6412
This PR increases the duration of `waitFor()` to add more leeway.
> fix(async/unstable): fix flaky `waitFor()` test

- async/pool_test.ts
ref: https://github.com/denoland/std/issues/6287
This PR increases `setTimeout` intervals and therefore adds more leeway to checks.
> test(async): fix flaky `pooledMap()` test

- _tools/check_docs.ts
- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_truncate.ts
- fs/unstable_truncate_test.ts
This PR adds `truncate` and `truncateSync` APIs to the `@std/fs` package which are intended to mirror `Deno.truncate` and `Deno.truncateSync` functions.
Towards #6255.
> feat(fs/unstable): add truncate and truncateSync

- fmt/printf.ts
`@std/fmt/printf` module docs are currently absent: https://jsr.io/@std/fmt/doc/printf
It seems that the reason is that the `@module` JSDoc section happens to be after an import. So, I move the import below and it fixes the issue (checked locally with `deno doc`).
Anyway, I think `deno doc` should probably consider this case in some way - either force to put the module doc as the first item in the module, or to allow putting the module doc anywhere in the module.
> docs(fmt): fix `printf` module doc absense

- cli/unstable_spinner.ts
- cli/unstable_spinner_test.ts
This PR adds test for multiple `start()` and `stop()` calls.
In addition, it removes the `#active` property and replaces it with `this.#intervalId === null` check. This should work identically.
> refactor(cli/unstable): clean up `start` end `stop` methods of `Spinner`, add test cases for multiple start/stop calls

- uuid/v1.ts
- uuid/v1_test.ts
Currently if the user specifies `rng` option, `generate` returns a broken string like `0b4e9750-ef65-11ef-8000-01undefinedundefinedundefinedundefinedundefined` because `rng` is not called as a function. This PR fixes it.
> fix(uuid): handle `rng` correctly in uuid v1

- _tools/check_docs.ts
- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_mkdir.ts
- fs/unstable_mkdir_test.ts
This PR adds `mkdir` and `mkdirSync` APIs to the `@std/fs` package which are intended to mirror `Deno.mkdir` and `Deno.mkdirSync` functions.
Towards #6255.
> feat(fs/unstable): add mkdir and mkdirSync

- text/_test_util.ts
- text/_test_util_test.ts
- text/deno.json
- text/unstable_reverse.ts
- text/unstable_reverse_bench.ts
- text/unstable_reverse_test.ts
Adds Unicode-aware string reverse function from https://github.com/mathiasbynens/esrever. Unicode handling can be disabled for extra performance.
Compared to `input.split().reverse().join()`:
- 1.69x faster (with Unicode handling)
- 2.91x faster (without Unicode handling)
<details><summary>Benchmark</summary>
```
scarf@fedora ~/r/d/deno_std (feat/text-unstable/reverse)> deno bench text/unstable_reverse_bench.ts
Check file:///run/media/home/scarf/repo/deno/deno_std/text/unstable_reverse_bench.ts
CPU | AMD Ryzen 5 5600G with Radeon Graphics
Runtime | Deno 2.1.10+56f67b5 (x86_64-unknown-linux-gnu)
file:///run/media/home/scarf/repo/deno/deno_std/text/unstable_reverse_bench.ts
benchmark              time/iter (avg)        iter/s      (min … max)           p75      p99     p995 …
```
> feat(text/unstable): add `reverse` function

- tar/tar_stream.ts
- tar/tar_stream_test.ts
- tar/untar_stream.ts
- tar/untar_stream_test.ts
Closes: https://github.com/denoland/std/pull/6376
This pull request makes the changes discussed in the other linked pull request.
It changes mode, uid, and gid to accept and decode numbers in the octal format `0o775` instead of decimal format `775`. It also changes slightly the decoding segment of these three to be more compatible with other tar specs.
> BREAKING(tar/unstable): fix handling of mode, uid, and gid

- fs/unstable_rename_test.ts
closes #6447
The difference of behavior of `Deno.rename` on unix and windows seems to have disappeared by this change https://github.com/denoland/deno/pull/28236
This PR runs the same test cases on all platforms, and ignores the cases on windows with Deno <= 2.2.2
> test(fs/unstable): remove windows specific paths and fix ci

- _tools/check_docs.ts
- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_utime.ts
- fs/unstable_utime_test.ts
This PR is part of the #6255 and adds the `utime` and `utimeSync` to the API
> feat(fs/unstable): add utime and utimeSync

- _tools/check_docs.ts
- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_write_text_file.ts
- fs/unstable_write_text_file_test.ts
This PR adds `writeTextFile` and `writeTextFileSync` APIs to `@std/fs` package. These functions mirror the `Deno.writeTextFile` and `Deno.writeTextFileSync` APIs.
Also, the `unstable_write_file.ts` is added to the doc checker in this PR.
Towards #6255.
> feat(fs/unstable): add writeTextFile and writeTextFileSync

- async/pool_test.ts
closes https://github.com/denoland/std/issues/6287
> test(async): use FakeTime in pooledMap testing

- async/unstable_wait_for_test.ts
closes https://github.com/denoland/std/issues/6361
> test(async): fix flaky waitFor test

- encoding/base64.ts
- encoding/base64url.ts
- encoding/base64url_test.ts
Closes: https://github.com/denoland/std/issues/5944
This pull request brings the performance added in https://github.com/denoland/std/pull/6457 to the stable base64 and base64url functions, but in a non-breaking manner. The only difference a user would find is a difference in error message if providing an invalid encoded string.
> perf(encoding): improve base64 encode/decode performance

- encoding/_common64.ts
- encoding/unstable_base32_test.ts
- encoding/unstable_base64_test.ts
This pull request fixes a simple bug where when decoding base64 the functions wouldn't throw when encountering an invalid byte between 128 - 256. Since the `rAlphabet` varaible only goes up to 128, any bytes not matching this range would return undefined and then later be interpreted as a 0 byte when it was meant to throw an error.
> fix(encoding): decoding base64 with invalid bytes >= 128

- _tools/check_docs.ts
- _tools/node_test_runner/run_test.mjs
- fs/_utils.ts
- fs/deno.json
- fs/unstable_make_temp_file.ts
- fs/unstable_make_temp_file_test.ts
This PR adds the `makeTempFile` and `makeTempFileSync` APIs to the `@std/fs` package which are intended to mirror `Deno.makeTempFile` and `Deno.makeTempFileSync` APIs.  This PR also adds `randomId` as a utility function to help generate 6-digit hexadecimal file names when using these APIs under a Node.js runtime.
Towards #6255.
> feat(fs/unstable): add makeTempFile and makeTempFileSync

- cli/unstable_progress_bar.ts
In preparation for https://github.com/denoland/std/pull/6430
> refactor(cli/unstable): replace `ProgressBar` `#options` property with actual properties

- internal/diff_str.ts
- internal/diff_str_test.ts
- Fixes #6326
- Fixes `a\\tb` vs `a\tb`: previously these would be detected as `!==` and cause `assertEquals` to reject, but `diff_str` found no difference
- Combines escaped spaces: `"  "` (double space) is currently treated as one token. This change makes `"\t\f"` also be treated as one token instead of four
- Adds one test and updates another because the space-combining was previously untested
> fix(assert,expect,internal,testing): improve handling of escaped chars in diff_str

- encoding/_common16.ts
- encoding/_common32.ts
- encoding/_common64.ts
- encoding/base32_test.ts
- encoding/base64url_test.ts
- encoding/hex_test.ts
- encoding/unstable_base32.ts
- encoding/unstable_base32_test.ts
- encoding/unstable_base64.ts
- encoding/unstable_base64_test.ts
- encoding/unstable_hex.ts
- encoding/unstable_hex_test.ts
Jumping from this conversation: https://github.com/denoland/std/pull/6499#discussion_r2006977391
This pull request updates the error message when the input has an invalid length to properly decode
> refactor(encoding): align error messages

- front_matter/_formats.ts
- front_matter/any_test.ts
This PR fixes a bug where trying recognize a format throws if the data starts with bom.
> fix(front-matter): handle BOM when recognizing format

- ini/_ini_map.ts
Seems like this is not needed as `IniMap.prototype.#formatting` properties are not dynamically used.
> refactor(ini): remove `IniMap.prototype.#cleanFormatting()`

- ini/_ini_map.ts
- ini/stringify_test.ts
This PR fixes the section check where a object values like `Date` would pass the check.
> fix(ini): replace `isRecord()` with `isPlainObject()`

- datetime/_date_time_formatter.ts
- datetime/_date_time_formatter_test.ts
- datetime/parse_test.ts
Previously, larger tests meant these appeared to be covered, but there was no testing of the deep specifications for each part type. Covering the cases revealed a bug with `fractionalSecond`, and the fix is included in this PR.
I also made `formatToParts` require exactly 2 digits when parsing `yy` and exactly 4 digits when parsing `yyyy` instead of 1-2 or 1-4 respectively. The spec requires `yy` to represent exactly 2 digits, but `yyyy` technically represents 4+ digits. In neither case are fewer digits allowed. I think it's unlikely anyone will be trying to parse years with 5+ digits, and parsing `yyyyMMdd` would require a more sophisticated approach if we allowed 5+, so I think only allowing 4 is best.
> fix(datetime): fix formatting of `fractionalSecond`, fix parsing of `yy` and `yyyy`, test each part type in dateTimeFormatter.format

- semver/_constants.ts
- semver/is_range_test.ts
- semver/is_semver_test.ts
Seems like this constant is only used in tests.
> chore(semver): remove `MIN` constant

- deno.json
These changes improve lint rules by ensuring that future JSR lint rules, which should apply to this codebase, are enforced. It also removes the need to explicitly include the `verbatim-module-syntax` rule.
> chore: improve lint rules

- expect/_build_message.ts
- expect/_matchers.ts
- expect/_to_match_object_test.ts
- internal/format_test.ts
closes #6225
Does not change the behavior of `expect.toMatchObject`, only the error message.
The behaviors of `expect.toMatchObject` and `assertMatchObject` are slightly different, so one of the tests from the latter does not work. I duplicated the rest of the diff-based tests.
Also makes `buildNotEqualErrorMessage` accept the `formatter` option with a default of `format` which aligns it with `buildEqualErrorMessage`. For both, makes `options` optional.
> fix(expect): include diff when `expect.toMatchObject` throws

- _tools/check_docs.ts
This is no longer needed since `deno test --doc` now evaluates code snippets in JSDocs.
> chore: rename `assertSnippetsWorks` to `assertHasSnippets`

- toml/_parser.ts
This reduces the usage of slice() and might have a positive impact on performance.
> refactor(toml): add `Scanner` `startsWith()` method

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_chown.ts
- fs/unstable_chown_test.ts
This PR adds `chown` and `chownSync` APIs to `@std/fs` package which are intended to mirror the `Deno.chown` and `Deno.chownSync` functions.
Towards #6255.
> feat(fs/unstable): add chown and chownSync

- encoding/_common16.ts
- encoding/_common32.ts
- encoding/_common64.ts
This pull request fixed the docs for calcSizeBase64, 32 and hex as they are incorrectly still mentioning the Raw instead of Into name.
> docs(encoding): fixed for calcSize functions

- toml/_parser.ts
- toml/parse_test.ts
This PR adds `skipWhitespaces()`  in order to declutter `nextUntilChar()`.
> refactor(toml): add `Scanner` `skipWhitespaces()` method

- path/mod.ts
This PR adds many more examples to `path`'s front-page `mod.ts`.
Each example uses `assertEquals` to ensure correctness and testability.
> docs(path): add many more examples to `mod.ts`

- encoding/mod.ts
This PR adds many more examples to `encoding`'s front-page `mod.ts`.
Each example uses `assertEquals` to ensure correctness and testability.
> docs(encoding): add many more examples to `mod.ts`

- csv/mod.ts
This PR adds many more examples to `csv`'s front-page `mod.ts`.
Each example uses `assertEquals` to ensure correctness and testability.
> docs(csv): add many more examples to `mod.ts`

- ini/parse.ts
- ini/parse_test.ts
This PR fixes a bug where the value `value="` was trimmed. This was due to `startsWith()` and `endsWith()` both being true with a value of `"`.
> fix(ini): fix quoted value bug

- toml/_parser.ts
- toml/parse_test.ts
The current toml implementation throws when trying to parse an empty string.
(Probably) all toml npm implementations allow empty strings and return an empty object, so we should probably too.
```ts
import toml from "npm:toml";
assertEquals(toml.parse(""), {});
import tomljs from "npm:toml-js";
assertEquals(tomljs.parse(""), {});
import * as s from "npm:smol-toml";
assertEquals(s.parse(""), {});
import * as i from "npm:@iarna/toml";
assertEquals(i.parse(""), {});
import * as c from "npm:confbox";
assertEquals(c.parseTOML(""), {});
```
> fix(toml): fix empty string handling

- toml/_parser.ts
Pretty sure this check is meant for `record`, not `body`.
> refactor(toml): fix object check in 'merge' util

- cli/unstable_spinner.ts
> docs(cli/unstable): fix Spinner example typo

- yaml/_loader_state.ts
This PR removes the `throwError()` and throws errors directly. This makes the code easier to read.
> refactor(yaml): remove `throwError()` method

- data_structures/unstable_bidirectional_map.ts
- data_structures/unstable_bidirectional_map_test.ts
Fixes https://github.com/denoland/std/issues/6597
> feat(data-structures/unstable): BidirectionalMap constructor accept iterables of key-value pairs

- _tools/node_test_runner/run_test.mjs
- fs/deno.json
- fs/unstable_create.ts
- fs/unstable_create_test.ts
This PR adds the `create` and `createSync` APIs to the `@std/fs` package which are intended to mimic the `Deno.create` and `Deno.createSync` functions.
Towards #6255.
> feat(fs/unstable): add create and createSync

- yaml/_loader_state.ts
It seems this doesn't really affect performance but is more readable.
> refactor(yaml): declare-on-use variables

- toml/_parser.ts
- toml/parse_test.ts
This PR fixes https://github.com/denoland/std/issues/6604
Refs https://toml.io/en/v1.0.0#integer, https://github.com/toml-lang/toml/issues/517
> fix(toml): fix handling of leading and trailing underscores in number literals

- fmt/printf_test.ts
This PR replaces `spy()` call with `stub()` call in order to avoid test cli output pollution.
> test(fmt): reduce unnecessary output during test run

- encoding/_common32.ts
- encoding/_common64.ts
- encoding/unstable_base32.ts
- encoding/unstable_base32_stream.ts
- encoding/unstable_base32_stream_test.ts
- encoding/unstable_base32_test.ts
- encoding/unstable_base64.ts
- encoding/unstable_base64_stream.ts
- encoding/unstable_base64_stream_test.ts
- encoding/unstable_base64_test.ts
Closes: https://github.com/denoland/std/issues/6601
Looking at the documentation for the proposal on MDN, it has an `omitPadding` option. Testing it out on Firefox, it seems to always add padding, even for base64url. Would it be better to also implement this option here or stick with current behaviour of always adding padding for base64 and always omitting padding for base64url? 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64
> BREAKING(encoding/unstable): base64/32 functions to match proposal-arraybuffer-base64 API

- _tools/check_browser_compat.ts
These changes reduces the execution time of this script by ~70% (60s) and removes the `--check` option, which feels redundant given we can just make the appropriate changes.
> chore: improve `_tools/check_browser_compat.ts` performance

- _tools/check_docs.ts
These refactors partially prepare the `lint:docs` script for use outside of the Standard Library, as discussed offline with Yoshiya a while ago. There are more improvements to come in upcoming PR(s). Other simplifications and cleanups were made, and the script now executes ~40% (1.3s) faster.
> chore: improve `lint:docs` script

- _tools/check_mod_exports.ts
- _tools/utils.ts
There are very few edge cases where this will return a false positive. So I think this is more than sufficient.
> chore: simplify and move `isTestFile()`

- .github/workflows/ci.yml
- .gitignore
- deno.json
If it's listed in the `.gitignore` file, Deno automatically exlucdes it from linting, formatting, publishing, etc.
> chore: cleanup `exclude` in root `deno.json`

- http/status.ts
This example seems flaky in doc testing because of dependency to the actual example.com host. (See https://github.com/denoland/std/actions/runs/14436676442/job/40478863407?pr=6573 )
I think we should ignore this in doc testing
> chore(http): do not request to example.com in doc testing

- http/file_server.ts
- http/file_server_test.ts
Fixes #6609
`Deno.serve()` already sets the `Date` header on responses. So simply removing these lines should fix this.
> fix(http): don't set the Date header in file_server.ts responses (use the default Date header value)

- async/abortable.ts
- async/abortable_test.ts
In `abortable`:
- If the signal is aborted with delay and the promise is rejected, an uncaught error does not occur. This is OK.
- If the signal is already aborted and the promise is rejected, an uncaught error occurs.
Uncaught errors should not occur in either case.
Also, I changed the tests to use `delay` instead of `clearTimeout` to detect leaks.
> fix(async): `abortable` should prevent uncaught error when promise is rejected

- dotenv/mod.ts
- dotenv/mod_test.ts
This PR fixes https://github.com/denoland/std/issues/6620, by adding `URL` as a valid type to the `envPath` parameter in the `LoadOptions` interface.
> feat(dotenv): add URL as envPath type

- .github/workflows/ci.yml
- .gitignore
- _tools/node_test_runner/.gitignore
- _tools/node_test_runner/run_test.mjs
- _tools/node_test_runner/tsconfig_for_bun.json
- collections/invert_test.ts
- deno.json
- fs/_node_fs_file_test.ts
- fs/unstable_chown_test.ts
- fs/unstable_read_file_test.ts
- fs/unstable_read_text_file_test.ts
- fs/unstable_remove_test.ts
- fs/unstable_truncate_test.ts
- fs/unstable_write_file_test.ts
- fs/unstable_write_text_file_test.ts
This PR starts running node compatible test cases in Bun in CI. This makes it easier to accept PRs like https://github.com/denoland/std/pull/6630 which says the change improves the bun compatibility.
In JSR pages, we already mark some of std packages compatible with Bun. So I believe this addition is reasonable
> chore: run some test cases in bun in CI

- .github/workflows/ci.yml
This is a minor change. This PR changes `matrix.node` to `matrix.bun` to prevent the use of unintended versions of Bun in the future.
https://github.com/denoland/std/blob/6a00d6cd34ca70b3a38932e313151a80531c5d2b/.github/workflows/ci.yml#L105-L126
> ci: use correct Bun version

- bytes/concat.ts
- bytes/concat_test.ts
`concat` currently only allows mutable arrays whereas it doesn't mutate its input.
This PR expands the signature to read-only arrays.
Doesn't refer to any open issue.
> fix(bytes): allow to concat() readonly arrays of bytes arrays

- expect/_assertions_test.ts
- internal/assertion_state.ts
- internal/assertion_state_test.ts
- testing/_test_suite.ts
- testing/bdd.ts
fixes #6518
fixes #6540
- ~~Renamed AssertionState to AssertionCounter~~
- ~~Moved AssertionCounter from `std/internal` to `std/expect`: It's really more of an `expect` feature than an `internal` feature~~
- ~~This means that `std/testing` now depends on `std/expect`~~
- ~~Removed `AssertionCounter.#state.assertionTriggered` to avoid desynchronizing from `assertionTriggeredCount`~~
- ~~Collected the validation error behavior in `AssertionCounter` rather than duplicating it in `testing`~~
- Ensured `AssertionState` is reset after validation: fixes #6540
- Added a cleanup step when `globalThis` is `unload`ed to ensure all `AssertionState`s are properly validated and reset: fixes #6518
> fix(expect,testing,internal): throw if `expect.hasAssertion` and `expect.assertions` are not checked

- fmt/README.md
- fmt/printf.ts
closes https://github.com/denoland/std/issues/6647
> docs(fmt): clarify runtime compatiblity

- datetime/difference.ts
This makes the code easier to read and also caches the result of `calculateMonthsDifference()` when either `quarters` or `years` is calculated first.
> refactor(datetime): simplify month difference

- text/unstable_dedent.ts
- text/unstable_dedent_test.ts
> fix(text/unstable): make dedent match reference for multiline substitutions

- README.md
Looks cooler and suits better, given the Deno logo is now green.
> chore: change badge color

- .github/workflows/ci.yml
- .github/workflows/version_bump.yml
- .github/workflows/workspace_publish.yml
It's possible that caching may not be the best idea for some of these cases, but I think it's worth just trying and seeing.
> chore: enable dependency caching between GA workflow runs

- cli/unstable_progress_bar.ts
This PR adds a `print()` call when the progress bar is initialized (`setInterval()` only starts printing after the delay) and removes the `print()` call when it is stopped.
> refactor(cli/unstable): print initial `ProgressBar`

- fs/unstable_rename_test.ts
We need to temporarily ignore the case `rename() rejects with Error when an existing directory is renamed with an existing regular file path`. This seems to have started failing in canary today, probably affected by https://github.com/denoland/deno/commit/cb23193f74b2cf34cf06111f9ebbf0599d5ec24d
> chore(fs/unstable): ignore some rename and renameSync tests on windows

- cli/unstable_progress_bar.ts
- cli/unstable_progress_bar_test.ts
This handles some edge cases (`value > max`, `value < 0`, `max < 0`) which threw `.repeat(negativeNumber)` errors.
> fix(cli/unstable): clamp `ratio`

- yaml/deno.json
`yaml/unstable_stringify.ts` was added in #6666. This PR exports it to make it available to users.
> feat(yaml/unstable): export `unstable_stringify.ts`

- cli/unstable_spinner.ts
- cli/unstable_spinner_test.ts
This PR adds a `updateFrame()` call when `start()` is called. This fixes an initial empty console mostly notable when the interval option was set as a big number.
> fix(cli/unstable): `Spinner` print on `start()`

- streams/buffer.ts
- streams/buffer_test.ts
This error type is more fitting for the given error messages. This change is non-breaking as `RangeError` extends `Error`.
> refactor(streams): throw `RangeError` within `Buffer` methods

- http/file_server.ts
This PR updates the formatting of html template in file_server.
This change has been caused by the upstream change of `deno fmt` in https://github.com/denoland/deno/pull/29616
> chore: update html formatting in file_server

- http/user_agent.ts
> fix(http): respect colors and other `Deno.inspect` options when logging `UserAgent`s

- collections/map_values_test.ts
The current test doesn't test anything, as it would pass even if the input was subject to mutation, because `5 ?? "nothing"` and `true ?? "nothing"` evaluate to `5` and `true` respectively.
Technically (in common with built-ins like `Array#map`) the input can still be mutated if the callback itself causes mutation, but changing that behavior would require `structuredClone` or similar, which incurs a performance cost and isn't always lossless. It's almost certainly better to leave that responsibility to userland code.
> test(collections): fix mapValues mutation test so it actually tests mutation

- async/delay.ts
- async/delay_test.ts
Bug was introduced in https://github.com/denoland/std/pull/6775, as `setArbitraryLengthTimeout` returns `{ valueOf(): number }` rather than a primitive `number`, and `Deno.unrefTimer` throws if its argument isn't a `number`.
Previous type checking missed it due to already using a `// @ts-ignore` for the offending line, and the test also missed it due to stubbing `Deno.unrefTimer` with a no-op.
> fix(async): pass numeric value of `delay` timer to `unrefTimer` when `persistent=false`

- async/delay.ts
In Node.js, setTimeout returns a NodeJS.Timeout. When using tsc in a frontend project, this can cause type errors.
code: https://github.com/iugo/deno-std-in-node/tree/async-timeout-type-error
> fix(async): convert setTimeout return values to Number (fixing type error when used with Node.js)

- html/deno.json
- html/unstable_escape_css.ts
- html/unstable_escape_css_test.ts
- html/unstable_escape_js.ts
- html/unstable_escape_js_test.ts
Resolves https://github.com/denoland/std/issues/6748
> feat(html/unstable): add escapeJs and escapeCss functions

- async/unstable_wait_for.ts
- async/unstable_wait_for_test.ts
`waitFor` accepts async predicate in type definition, however if `predicate` returns a Promise, it's considered true and always resolves at the first call. This PR fixes it by handling returned promise correctly.
> fix(async/unstable): fix handling of async predicate in waitFor

- semver/_shared.ts
- semver/increment.ts
- semver/increment_test.ts
If a user specifies a prerelease value in the form of `{identifer}.{number}` then both the identifier and the number will be used to set the prerelease metadata.
---
- Fixes https://github.com/denoland/std/issues/6824
> fix(semver): allow users to set prerelease number during increment
